#lang racket

;; BOUNDARY: integration

;; test-sync-version-historical.rkt — Tests for version-guard.rkt historical-line? guard
;;
;; W1 sub-issue #3325: 7 positive patterns + 2 negative cases
;; W2 sub-issue #3357: Now requires from shared version-guard.rkt

(require rackunit
         racket/file
         racket/port
         racket/runtime-path
         (only-in "../scripts/version-guard.rkt" historical-line?))

(define-runtime-path q-root "..")

;; ---------------------------------------------------------------------------
;; 7 positive pattern tests
;; ---------------------------------------------------------------------------

(test-case "P1: README Status bold entries protected"
  (check-true (historical-line? "**v0.28.22** — Context Loop Prevention Wiring")))

(test-case "P2: 'in vX.Y.Z' protected"
  (check-true (historical-line? "- `AUTH` (narrowed in v0.28.22 to match only `AUTH`)"))
  (check-true (historical-line? "Fixed in v0.28.21 during audit remediation")))

(test-case "P3: Wave labels '(vX.Y.Z W0)' protected"
  (check-true (historical-line? "# Analysis (v0.28.22 W1)"))
  (check-true (historical-line? "Changes from (v0.28.24 W0) are minimal")))

(test-case "P4: 'As of vX.Y.Z' protected"
  (check-true (historical-line? "As of v0.28.22, `open-session` registers tools.")))

(test-case "P5: Parenthetical EOL '(vX.Y.Z)' protected"
  (check-true (historical-line? "## Contract-Validated Events (v0.28.22)"))
  (check-true (historical-line? "See migration guide (v0.28.21)")))

(test-case "P6: Temporal references protected"
  (check-true (historical-line? "This feature was introduced v0.28.22 for safety."))
  (check-true (historical-line? "Deprecated since v0.28.22."))
  (check-true (historical-line? "Added v0.28.23 to prevent false positives."))
  (check-true (historical-line? "Removed v0.28.20 due to performance regression.")))

(test-case "P7: Section headers with version protected"
  (check-true (historical-line? "## Migration Guide (v0.28.22)"))
  (check-true (historical-line? "# Exn:fail Migration Analysis (v0.28.22 W1)")))

;; ---------------------------------------------------------------------------
;; 2 negative cases — these SHOULD be updated by sync-version
;; ---------------------------------------------------------------------------

(test-case "N1: HTML comment with version NOT protected"
  (check-false (historical-line? "<!-- verified-against v0.28.22 -->")))

(test-case "N2: Plain version reference NOT protected"
  (check-false (historical-line? "Generated by q v0.28.22"))
  (check-false (historical-line? "Version 0.28.22 release notes")))

(test-case "sync-version --all skips docs/reports historical reports"
  (define root (make-temporary-file "sync-version-reports-~a" 'directory))
  (define script-path (build-path q-root "scripts" "sync-version.rkt"))
  (dynamic-wind
   void
   (lambda ()
     (make-directory* (build-path root "util"))
     (make-directory* (build-path root "docs" "reports"))
     (call-with-output-file
      (build-path root "util" "version.rkt")
      (lambda (out)
        (display "#lang racket/base\n(provide q-version)\n(define q-version \"9.9.9\")\n" out)))
     (call-with-output-file (build-path root "info.rkt")
                            (lambda (out) (display "#lang info\n(define version \"0.0.1\")\n" out)))
     (call-with-output-file
      (build-path root "README.md")
      (lambda (out)
        (display
         "# q\n<!-- DO NOT EDIT: Status section is historical. Use sync-version.rkt for version bumps. -->\nq version 0.0.1\n"
         out)))
     (call-with-output-file (build-path root "docs" "live.md")
                            (lambda (out) (display "Generated by q 0.0.1\n" out)))
     (call-with-output-file (build-path root "docs" "reports" "baseline.md")
                            (lambda (out)
                              (display "| Version | 0.57.6 |\n| command | q version 0.57.6 |\n" out)))
     (define-values (proc _stdout stdin _stderr)
       (parameterize ([current-directory root])
         (subprocess #f #f #f (find-executable-path "racket") script-path "--write" "--all")))
     (close-output-port stdin)
     (subprocess-wait proc)
     (check-equal? (subprocess-status proc)
                   0
                   "sync-version --write --all completes after applying fixes")
     (check-true (string-contains? (file->string (build-path root "docs" "live.md")) "9.9.9"))
     (check-true (string-contains? (file->string (build-path root "docs" "reports" "baseline.md"))
                                   "0.57.6")
                 "historical report version must not be rewritten by --all"))
   (lambda () (delete-directory/files root))))
