((openai
  (base-url . "https://api.openai.com/v1")
  (default-model . "gpt-4o-mini")
  (auth-type . api-key)
  (factory . openai-compatible)
  (models . (("gpt-4o" (name . "GPT-4o") (context-window . 128000) (capabilities . (chat vision tools streaming)))
             ("gpt-4o-mini" (name . "GPT-4o mini") (context-window . 128000) (capabilities . (chat vision tools streaming))))))
 (anthropic
  (base-url . "https://api.anthropic.com/v1")
  (default-model . "claude-3-5-sonnet-latest")
  (auth-type . api-key)
  (factory . anthropic)
  (models . (("claude-3-5-sonnet-latest" (name . "Claude 3.5 Sonnet") (context-window . 200000) (capabilities . (chat vision tools streaming)))
             ("claude-3-5-haiku-latest" (name . "Claude 3.5 Haiku") (context-window . 200000) (capabilities . (chat streaming))))))
 (gemini
  (base-url . "https://generativelanguage.googleapis.com/v1beta")
  (default-model . "gemini-2.5-pro")
  (auth-type . api-key)
  (factory . gemini)
  (models . (("gemini-2.5-pro" (name . "Gemini 2.5 Pro") (context-window . 1048576) (capabilities . (chat vision tools streaming)))
             ("gemini-2.5-flash" (name . "Gemini 2.5 Flash") (context-window . 1048576) (capabilities . (chat vision tools streaming))))))
 (azure
  (base-url . "https://example.openai.azure.com")
  (default-model . "gpt-4o-mini")
  (auth-type . api-key)
  (factory . azure-openai)
  (models . (("gpt-4o-mini" (name . "Azure GPT-4o mini") (context-window . 128000) (capabilities . (chat vision tools streaming))))))
 (openrouter
  (base-url . "https://openrouter.ai/api/v1")
  (default-model . "openai/gpt-4o-mini")
  (auth-type . api-key)
  (factory . openrouter)
  (models . (("openai/gpt-4o-mini" (name . "OpenAI GPT-4o mini via OpenRouter") (context-window . 128000) (capabilities . (chat vision tools streaming)))
             ("anthropic/claude-3.5-sonnet" (name . "Claude 3.5 Sonnet via OpenRouter") (context-window . 200000) (capabilities . (chat vision tools streaming)))))))
