#hasheq(
  (content-digest . "fb4b433265356da0a12cc695c052386d9ccdebe14686b1f214b71b58cec20237")
  (milestone . 896)
  (plan-id . "fb67e0429ed155a4b4e3f31afe3ef3ca7748ee891c06247b11e5e2a86cfebd75")
  (report . "Every review round recorded in the rounds list completed, and every one returned CHANGES-REQUESTED. Every finding was reproduced against the tree before any fix was written, and every one is fixed with its own evidence: the W2 gate repair carries a red-first capture showing the previously masked failure now reaches the gate, the prose corrections are diffs against the artifacts they cite, and the round-3 substantiation findings are re-measurements rather than restatements - the sweep was genuinely re-run and the checksums genuinely re-verified in full. The round and finding counts are deliberately absent from this field and from every note in this record: they are stated once, in the verdict, derived from the findings this record contains. Four rounds of fixing them each produced a field that was stale at the commit carrying it, because the fix and the recording of the round it referred to landed together. The pattern across the rounds is consistent, and it is the substance of this wave rather than its history: each round found the same class of defect one step further along, in the claim that pointed at the evidence rather than in the evidence itself. The reason is structural rather than bad luck - a committed artifact names the tree it ran on, so every artifact-only commit moves the ground under the sentence that cites it. Round 4 is the informative one for what this wave was: it found no new defect in the W7 content at all, and its findings were entirely in the evidence, three of them the same trap it had been used to catch - a detector that mistakes a green summary line for a failure, a stale enumeration, and a caveat that contradicts the artifact it introduces. Its composition is enumerated in its own entry rather than summarised here. R4-F7, surfaced in the seconds before that review hit its quota, is the clearest statement of the wave's shape: the sweep had been run with the wrong instrument entirely, so two of its greens were vacuous - the same trap caught at successively lower levels, until the level reached was the instrument itself. Round 5 reviewed at b9a0ac1ad and found the validation record carrying eight duplicated top-level keys, under which the values the gate reads were a stale block naming a superseded head. The reviewer believed the record was unparseable; it was instead silently stale, which is worse - it read cleanly and would have failed the gate. Running the gate the way CI does then surfaced defects the reviewer, having no shell, could not see. Round 6 showed the same thing one level up: the fixes for the stale-field class were themselves stale by construction, each written in the same commit that recorded the round it described. Round 7 then showed it one level up again, which is that removing those numbers from the two fields the gate reads stopped the gate from seeing the drift without stopping it, and left counts in this record's prose that had already gone false by the next review. The shape has now repeated at every level this wave has touched: a check that passes is not a check that ran, a record that reads is not a record that is accepted, a field that has been rebound is not a field that has been described, and a number removed where a machine reads is not a number removed from the record. A further round is outstanding. That sentence is deliberately phrased without a round number, for the same reason the counts are gone: the previous revisions of it each named a specific round and were therefore stale at the commit that carried them. A claim that cannot fall behind is worth more than one that reads precisely and is wrong. No value in this record is invented, and this record does not assert approval. Round 9 then found the same shape one level up again, and named its cause: rebinding updated the binding fields but not the prose naming the same head, so every rebind created a fresh class of self-contradiction, and four consecutive rounds each found defects introduced by the previous round's remediation. The rebind procedure is now hardened to report a superseded head still named as a live claim. What converges is the content: every measurement that could be re-derived checked out, including both enumerations once measured against the right endpoint. The remaining surface is the process, not the evidence. Round 9 was the first round run with a shell, and that is its real result: the digest, record-commit, verify, the gate, all three manifests, provenance and lint were executed rather than simulated, and every numeric claim was re-derived and held. Its four findings are prose-integrity - three in this record, one in a test comment - and none touches binding, digest, checksum, provenance or measurement. The first is corruption this record's own round-8 remediation did, caught nowhere, which is the convergence pattern at its plainest: the edit that fixed a field broke a neighbouring one, and the machine checks were all green throughout because none of them reads prose. What that says about this wave is already said above and is not restated here. The remaining surface is prose and process, not evidence.")
  (reviewed-sha . "98e582e019277046290f67a6207d8555d5442041")
  (reviewer . "independent read-only VERIFY subagents (reviewer role), 14 rounds completed and recorded here. Rounds 9, 10, 13, 14 executed their checks. Rounds 1, 2, 3, 4, 5, 6, 7, 8, 11, 12 had no shell in the session and reported that themselves. Round 14 executed but ran off the mandated route, so it is advisory. Both lists are computed from the rounds themselves so neither can fall a round behind.")
  (rounds . (
    #hasheq(
      (findings . (
        #hasheq(
          (id . "R1-F1")
          (resolution . "FIXED. The W2 checks are now a test-suite run through run-tests whose returned failure count drives (exit 1), so failed-result? sees a non-zero exit. The W2 overlap review and SHA256SUMS are pinned to the frozen v1.00.29 campaign; the W0 ownership matrix stays derived so the checks double as a live drift check (both matrices have identical overlap scope: 34 platform/fast, 46 security/fast). Red-first proof at raw/red-first-worker-security-w2.txt: with the W2 path pointed at a nonexistent directory the file now exits 1 and the runner reports FAILED, where the identical broken state before the fix reported PASSED (33/33, exit 0).")
          (severity . "blocking")
          (summary . "tests/test-worker-security.rkt derived its W2 overlap artifact paths from q-version (naming artifacts/tier-ownership/v1.00.31-w2, which does not exist) and could not fail the gate, so the regression was invisible")
        )
        #hasheq(
          (id . "R1-F2")
          (resolution . "FIXED. CHANGELOG and the release report name the matrix's actual values and say why they moved (the bake's own derivation sweep changed two of the nine digest-bound inputs, so the matrix was regenerated by its canonical generator).")
          (severity . "blocking")
          (summary . "W6 PERMANENT prose bound the verdict to the superseded rehearsal identity (head fc1a6fa36, inputs digest a1b99fe2) while the committed matrix records 50bdf7334 / fb224a6f")
        )
        #hasheq(
          (id . "R1-F3")
          (resolution . "FIXED. Both passages now state six of seven gates pass and that readiness is deferred, not passed, with the reason (branch-gated; its .gate-evidence records must name the release commit and version).")
          (severity . "blocking")
          (summary . "The changelog claimed every release-preflight gate passes locally and listed readiness among them, while release-preflight.json records readiness as deferred-by-design")
        )
        #hasheq(
          (id . "R1-F4")
          (resolution . "PARTIALLY FIXED in round 1, completed in round 3. The checksum step was corrected to run from the repo root and a single capture retained per gate; head coherence is stated precisely rather than claimed. Round 3 judged the form correct but the substantiation incomplete, which became R3-F4.")
          (severity . "blocking")
          (summary . "W7 evidence was not coherently bound: the preflight named the first bake commit, the preflight JSON a later commit, and the verify chain an intermediate one, and that chain recorded a failed checksum run caused by executing sha256sum -c from inside the artifact directory")
        )
      ))
      (reviewed-sha . "55abf0271f61ae4797881c64d3948834cc5c1d7e")
      (round . 1)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (findings . (
        #hasheq(
          (id . "R2-F1")
          (resolution . "FIXED. The entry now records both re-stamps and names the current committed values as authoritative.")
          (severity . "blocking")
          (summary . "w4-recovery.json still described the W6 matrix as re-stamped to fc1a6fa36 with byte-identical inputs, contradicting the regeneration this bake performed")
        )
        #hasheq(
          (id . "R2-F2")
          (resolution . "PARTIALLY FIXED in round 2, completed in round 3. The report was corrected to the then-current preflight head, but round 3 found the same class of defect one step further along: the preflight was later re-run at b0f19d6bd while the report and the validation record still said 58d302db. Both now name b0f19d6bd, the head the retained capture names.")
          (severity . "blocking")
          (summary . "The release report quoted the first bake commit fcfa9ab3 and 84 changed .rkt files while the retained preflight capture recorded a later commit and 93")
        )
        #hasheq(
          (id . "R2-F3")
          (resolution . "FIXED. The 1511 value is consistent across the report, the preflight JSON, the validation record and the chain capture.")
          (severity . "blocking")
          (summary . "The report quoted 1510 test files scanned for the version-expectation lint; the real count is 1511")
        )
        #hasheq(
          (id . "R2-F4")
          (resolution . "FIXED. The claim is replaced by the precise account: each capture names the tree it ran against; the commits between the suite chain (e9af72fee) and the content head change only docs/reports prose and this directory's own JSON and raw captures, which no test reads; and git diff --name-only e9af72fee..86002515f confirms no source or test file changed after the chain ran, so the chain's numbers describe the merge candidate's code.")
          (severity . "blocking")
          (summary . "release-preflight.json claimed the three captures were 'all bound to the same content head', which was false - a committed artifact cannot contain the SHA of the commit that carries it")
        )
      ))
      (reviewed-sha . "21b753a26595be03db432f8a046efd0a97a6876a")
      (round . 2)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (findings . (
        #hasheq(
          (id . "R3-F1")
          (resolution . "FIXED. Both now name b0f19d6bd.")
          (severity . "blocking")
          (summary . "The release report and the validation record still attributed the preflight to 58d302db while the retained preflight artifacts (release-preflight.json and raw/preflight-locally-runnable.txt) both record b0f19d6bd. The previous fix had chased the moving commit one step and stopped short.")
        )
        #hasheq(
          (id . "R3-F2")
          (resolution . "FIXED. The sweep was re-run at the final head - 19 files, 0 failures, 0 errors - and the new capture states in its own header what it supersedes and why. The reviewer also observed that raco test exits 0 even when a case fails, so the per-file rackunit counts rather than the exit code are the signal; that is recorded in the preflight JSON, and it is the same failure mode that hid the worker-security W2 regression.")
          (severity . "blocking")
          (summary . "release-preflight.json claimed 0 failures, 0 errors citing raw/version-derivation-tests.log, but that capture was taken mid-repair and records test-wave-integrity-adversarial.rkt red (1/8) while the W6 matrix was still pinned to the pre-regeneration identity. The claim was true and the evidence under it was not.")
        )
        #hasheq(
          (id . "R3-F3")
          (resolution . "FIXED. Head, counts and elapsed time now match the capture they cite; the fast-suite duration (20m51s to 20m53s) was corrected in the same pass, and a raw-captures block now names which file substantiates which number.")
          (severity . "moderate")
          (summary . "The validation record quoted a full regression at 1935c2c90 with 20548 of 20549 tests and 29m40s while citing raw/verify-chain.txt, which records e9af72fee with 20553 of 20554 and 29m36s - an earlier run's numbers under a later run's filename.")
        )
        #hasheq(
          (id . "R3-F4")
          (resolution . "FIXED. The full unfiltered per-manifest output is retained in the chain capture: 6/6 W6, 9/9 W7, 1/1 tier-ownership, 16/16 entries, run from the repository root. It is retained there rather than in a sidecar log because the artifact-provenance linter requires every file under the wave artifact directory to be bound by SHA256SUMS. The single unavoidable self-reference is stated in the log, the report and the preflight JSON: the manifest entry for the log covers the log including the checksum section, so the log cannot verify its own entry.")
          (severity . "moderate")
          (summary . "The chain's checksum section showed three OK lines for manifests holding sixteen entries, so its all-OK summary was unsubstantiated by its own excerpt.")
        )
        #hasheq(
          (id . "R3-NB")
          (resolution . "Accepted as accurate. The 1510 in the red-first capture is labelled rather than edited, because rewriting a red-first capture to match a later run would destroy the red/green pair it exists to record. The reviewer independently confirmed sound: the runner base-dir tests (non-vacuous, each building a decoy q/ fixture, and now counted by the runner), all eight frozen-path pins and both authoring-identity pins with truthful comments, the readiness-deferred wording, the W6 PERMANENT and W4 DELIVERED bounding, the absence of any PR-check substitution, and the playwright-sidecar environmental claim (@requires browser at the file, ci profile skips it, identical failure on main).")
          (severity . "non-blocking")
          (summary . "Round 3's non-blocking observations: the superseded red-first capture's 1510 count, a confusing runner taxonomy label in the W2 red-first record, and prose drift in one suite duration.")
        )
        #hasheq(
          (id . "R3-TOOL")
          (resolution . "Recorded so the round's scope is not overstated. Its findings were all verified independently against the tree before any fix was written, and all four were real.")
          (severity . "process")
          (summary . "Round 3 ran without an exec tool in the child process, so it could not recompute the content digest, run git diff, verify checksums or execute tests, and marked those unverified.")
        )
      ))
      (reviewed-sha . "9ff617f2c73f7207fd6fd73077b16dcfd3996823 (chain head e9af72fee)")
      (round . 3)
      (rounds-prior-fix-check . "Six of the eight prior findings confirmed GENUINELY FIXED: R1-F1 (the W2 checks now run through run-tests whose failure count drives the exit; the frozen v1.00.29 artifacts verified on disk and self-identifying; the red-first capture consistent at 33-before/38-after with exactly the three artifact-reading cases failing), R1-F2 (the strict-runner assertion now requires both the strict variable and a run-tests.rkt invocation, checked against ci.yml's fast, platform and security windows; a lane dropping strictness cannot satisfy it), R1-F3 (no stale fc1a6fa36/a1b99fe2 identity survives in the release surface - the remaining mentions are legitimate history), R2-F1 (w4-recovery.json records both re-stamps and matches the committed matrix field-for-field), R2-F3 (1511 everywhere in the release surface), and R1-F4's checksum path. R1-F4 was accepted as fixed in form but left substantiation incomplete, which became R3-F4. R2-F2 was judged NOT FIXED and became R3-F1.")
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (additional-finding . #hasheq(
        (attribution . "Found by the round-5 reviewer in the seconds before it hit its quota; the reviewer died before it could write this up, so the finding was reconstructed from its output and then verified directly against the tree by running the sweep both ways. Recorded against round 4 because round 5 never completed.")
        (id . "R4-F7")
        (resolution . "FIXED by re-measurement with the correct instrument. The sweep now runs racket scripts/run-tests.rkt per file - the runner whose exit code reporting.rkt actually gates on - and reports 376 tests, 376 passed, 0 failed, 0 timeouts, every file exit 0, and 0 files with no test count. The capture carries the runner's own Tests:/Files: lines and each exit code, so a vacuous green is detectable rather than assumed absent, and its header records the full instrument history including that a fourth false alarm came from the capture script's own detector grepping for raco test's summary shape instead of the runner's. This is the same trap as R1-F1 and R4-F1, caught a third time and finally at the level of the instrument itself.")
        (severity . "blocking")
        (summary . "The wrong instrument. The 19-file sweep that substantiates release-preflight.json's 0-failures claim was run with bare raco test, which is wrong twice over: it exits 0 even when a case fails, and for a file whose entry point is module+ main rather than module+ test it executes nothing and still exits 0. Two of the 19 files are shaped that way - test-deterministic-clock.rkt (10 cases) and test-wave-delivery-integrity-register.rkt (10 cases) - so their greens were vacuous: a pass that ran zero tests. The capture recorded zero lines of output for exactly those two files, which is what finally exposed it.")
      ))
      (findings . (
        #hasheq(
          (id . "R4-F1")
          (resolution . "FIXED, by re-measurement rather than by editing the capture. This is the raco-test-exits-0 trap reproduced one level down, in the very tool written to catch it. Re-run with a detector that requires a non-zero failure or error count: 0 of 19, agreeing with the per-file counts above the footer. The re-run also disclosed a second bug of its own - EXIT= was reading echo's status rather than raco's - so the exit code is now captured from the command directly. The capture names both superseded captures and why each is superseded.")
          (severity . "blocking")
          (summary . "The 19-file sweep capture's footer said 11 of 19 files with a reported failure while every per-file section above it read 0 failures and 0 errors. The detector matched rackunit's green 0 failure(s) summary line. The capture is SHA256SUMS-bound and is cited by the report, the preflight JSON and the validation record as the substantiation of 0 failures, 0 errors, so on its face it contradicted the claim it was cited for.")
        )
        #hasheq(
          (id . "R4-F2")
          (resolution . "FIXED. The block now quotes the actual diff: twelve paths, none under tests/, scripts/, util/, extensions/, ci/ or .github/, which is the claim that matters - no source or test file changed after the chain ran.")
          (severity . "moderate")
          (summary . "The validation record's head-coherence block quoted a git diff enumeration of the e9af72fee delta that predated the sweep capture and therefore omitted a file that had changed. The log's own header names a head and a timestamp later than the chain, which is proof enough that the enumeration was stale.")
        )
        #hasheq(
          (id . "R4-F3")
          (resolution . "FIXED. The line is repointed at the checksum section that does exist, and the live re-check script was repointed at /tmp so it cannot reintroduce an unbound file into the wave artifact directory.")
          (severity . "moderate")
          (summary . "The chain's summary line still pointed at raw/checksums-final.txt, the sidecar design abandoned because the artifact-provenance linter requires every wave artifact to be bound by SHA256SUMS. The named file was never committed.")
        )
        #hasheq(
          (id . "R4-F4")
          (resolution . "FIXED. The challenge was upheld: the caveat described a mechanism that was not the one in play. The actual order is write the section, bind the manifest over the finalized log, then re-run the verification, so the line is true of the committed bytes. Reworded in the log, the report and the preflight JSON, and sha256sum -c confirmed 16/16 at this commit. The reviewer's inability to hash the file - it had no exec tool - is why the question needed settling by running the command rather than by reading it.")
          (severity . "moderate")
          (summary . "The self-reference caveat said the log could not contain the verification of its own entry, while the retained output immediately below contains exactly the verify-chain.txt: OK line - the caveat contradicted the artifact it introduced.")
        )
        #hasheq(
          (id . "R4-F5")
          (resolution . "ACCEPTED AS NON-BLOCKING, deliberately not fixed. It is a warning-level convention and the file is classified and counted correctly by the runner - the fast suite is 1209 = W4's 1208 plus this file, and its four cases are green in the sweep capture. Touching a test file after the chain ran would invalidate the head-coherence claim that no test file changed since e9af72fee, so fixing a cosmetic tag would have cost the coherence guarantee that every other finding in this wave was about. Recorded as a follow-up instead of traded against that guarantee.")
          (severity . "minor")
          (summary . "tests/test-runner-base-dir-resolution.rkt carries no @suite/@speed metadata, which the schema treats as required. The runner's own accounting records metadata-completeness=explicit:0/heuristic:0/missing:1 for the file, so the gap is measured rather than inferred. It is the only new test file deviating from the convention. Neither of lint-all's two warnings is about this file; they are arch and release-readiness, both pre-existing and non-blocking.")
        )
        #hasheq(
          (id . "R4-F6")
          (resolution . "FIXED, and then superseded in substance by R4-F7. The report no longer describes the file set in prose at all: it now states the sweep's real totals (376 tests across the 19 files) measured through the project runner, which is the thing the sentence was trying to establish.")
          (severity . "minor")
          (summary . "The release report's set arithmetic named a second new runner test that is not among the 19 files in the sweep.")
        )
        #hasheq(
          (id . "R4-HYG")
          (resolution . "FIXED. The chain log is untracked, .chainlogs/ is now in .gitignore with the reason recorded, and nul is untracked. Both were removed from the index only; no file was deleted from the working tree, and the pre-existing root script w1-apply-covers.py was left in place as out of scope for this wave.")
          (severity . "moderate")
          (summary . "Artifact hygiene, found while verifying the findings above: .chainlogs/w7-version-derive-tests.log was tracked, which this campaign forbids outright, and the repository root carried a stray file named nul containing the shell error /bin/sh: 1: where: not found - accidental redirection output, tracked since v1.00.04.")
        )
        #hasheq(
          (id . "R4-NB")
          (resolution . "Accepted and recorded as a follow-up for the next wave. The W2 suite that R1-F1 was about is airtight, so the finding does not reopen it; the main suite is a pre-existing property the validation record already classifies as follow-up work.")
          (severity . "non-blocking")
          (summary . "Round 4 also noted that the worker-security main suite (33 cases) still discards the value of its own (run-tests suite) call, so a main-suite failure cannot reach the exit code. It judged the W2 suite - the R1-F1 subject - airtight and the gap out of W7 scope.")
        )
        #hasheq(
          (id . "R4-TOOL")
          (resolution . "Recorded so the round's scope is not overstated. Every finding was independently verified against the tree, and the one that hinged on execution, R4-F4, was settled by running sha256sum -c rather than by reading. The reviewer judged the twelve prior fixes from file contents alone and was correct on all twelve.")
          (severity . "process")
          (summary . "Round 4 ran without an exec tool, so the content digest, record-commit, verify, all three checksum manifests, every git diff claim and all test executions were unverified by the reviewer and marked as such.")
        )
      ))
      (reviewed-sha . "2428611c392f0feec595c3e881beb88536ca52c6 (the content head when round 4 ran; the commit recording it, 697135ca, rebinds the trio to this head)")
      (round . 4)
      (rounds-prior-fix-check . "All twelve prior findings confirmed GENUINELY FIXED. R3-F2 was accepted as substantively fixed but its replacement capture introduced a new defect, which became R4-F1. R3-F4 was accepted as fixed in substance with its self-reference caveat upheld, which became R4-F4. R3-F1 was confirmed fixed, with the reviewer judging the residual gap between b0f19d6bd and the content head to be the unavoidable an-artifact-names-the-tree-it-ran-on consequence rather than the same defect, but noting the validation record's enumeration of that gap was incomplete, which became R4-F2.")
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (findings . (
        #hasheq(
          (id . "R5-F1")
          (resolution . "FIXED. The stale block is gone: 27 top-level pairs, 27 unique keys, zero duplicates, rebuilt through Racket's own writer so neither duplicates nor malformed structure can survive. implementation-sha now equals the evidence record's, so the gate's cross-record comparison passes. Verified by running the real gate the way CI runs it: eight structural rejections before the fix, two after, and the two remaining are the legitimate pending-review blocks. Four further defects surfaced by running that gate are recorded as R5-F1b through R5-F1e.")
          (severity . "blocking")
          (summary . "The validation record carried eight duplicated top-level keys, and the values the wave gate consumes were a stale trailing block naming content head 86002515 instead of b9a0ac1ad. The reviewer's stated mechanism - that Racket's reader rejects duplicate keys, leaving the record unparseable - is incorrect, and the true mechanism is worse. Racket does not reject duplicate keys in a #hasheq literal: it silently keeps the last. So the record read cleanly, reported 25 unique keys, and passed every structural check, while the gate compared the stale implementation-sha against the evidence record's and would have failed. The reviewer correctly identified the blocking consequence and the stale head; only the mechanism, and therefore the fix, differ.")
        )
        #hasheq(
          (id . "R5-F1b")
          (resolution . "FIXED. implementation-sha is 3a3d3297fe5172c26303a159a67a187e4639a459, matching the evidence record and the head-coherence text in the same datum.")
          (severity . "blocking")
          (summary . "implementation-sha named 86002515f9de49d4abd83d83fd279656ab7c15e7, a superseded content head, while the same record's head-coherence text and the other two records named b9a0ac1ad. The gate requires validation's implementation-sha to equal the evidence record's, so this alone would have been rejected - pointing at a field whose stale value was itself an artifact of the duplicate-key shadowing.")
        )
        #hasheq(
          (id . "R5-F1c")
          (resolution . "FIXED, both with measurements taken at this head rather than quoted. format-compile: raco make and raco fmt canonicality (the same test scripts/pre-commit.rkt performs) over all 29 changed .rkt files between base 50bdf7334 and this head - 29 compiled, 29 canonical, 0 not-canonical, 0 fmt-error. fast: promoted to the top level from suites.fast, with its provenance noted. The nested copy is retained so the record still shows where the number came from.")
          (severity . "blocking")
          (summary . "The record had no top-level format-compile field and no top-level fast field, both required by the gate's validation-required-fields and both then validated for a passed result. The fast measurement existed but only nested under suites, which the gate does not consult - so the record carried a true number in a place no gate would ever read it.")
        )
        #hasheq(
          (id . "R5-F1d")
          (resolution . "FIXED without flattening away the meaning. The first item is genuinely deferred by design and is now classified deferred-noncritical; the other four are noncritical. Each keeps its original descriptive classification in a new label field, so nothing descriptive is lost and the gate sees the vocabulary it requires.")
          (severity . "blocking")
          (summary . "The five remaining-items used descriptive classifications - deferred-by-design, environmental-not-a-regression, follow-up-not-blocking, verdict-bounded, outstanding-coordinator-owned - none of which valid-noncritical-remaining-item? accepts. That predicate admits exactly noncritical and deferred-noncritical. The items were truthful and each carried a nonempty owner and rationale; only the vocabulary was wrong, so the gate rejected the whole list.")
        )
        #hasheq(
          (id . "R5-F1e")
          (resolution . "FIXED; recorded here as the provenance of R5-F1b through R5-F1d, which were found by running the gate rather than by reading the record. The lesson is this wave's recurring one, one level up again: a check that passes is not a check that ran. The record satisfied every read-based inspection available to a reviewer without a shell, and was simultaneously rejected by the project's own gate. A reviewer without exec can confirm a record is well-formed; it cannot confirm a record is accepted.")
          (severity . "blocking")
          (summary . "The round-5 reviewer had no exec tool, so five of the eight gate rejections were invisible to it. Running the gate the way CI does surfaced them: the missing format-compile and fast fields, the implementation-sha mismatch, and the remaining-items vocabulary. Each is a real defect that would have failed CI's evidence gate on the merge candidate.")
        )
        #hasheq(
          (id . "R5-F2")
          (resolution . "FIXED. Round 4's reviewed-sha is 2428611c392f0feec595c3e881beb88536ca52c6, with a note that this is the head when it ran. Worth stating plainly: this was the head-attribution defect class reintroduced while remediating that same class, by rebinding the trio and letting the head field follow the new binding instead of the review that actually happened.")
          (severity . "moderate")
          (summary . "Round 4's reviewed-sha had been rewritten to b9a0ac1ad7771306cda061a3ca4e9a4d3ee29278, a commit created at 01:31:48 local, thirty-nine minutes after the 00:52:24 commit that recorded round 4. The head round 4 reviewed was 2428611c3. Rounds 1 through 3 each keep their true head; round 4 was the only one that did not.")
        )
        #hasheq(
          (id . "R5-F3")
          (resolution . "FIXED. Both say nineteen, matching the round-4 tally of 4 + 4 + 4 + 7 and the record's own verdict line.")
          (severity . "minor")
          (summary . "Two sentences still said eighteen findings where the record enumerates nineteen: the report field and round 5's note. Both undercount the set round 5 was instructed to confirm.")
        )
        #hasheq(
          (id . "R5-F4")
          (resolution . "FIXED. The claim now states the real scope: the twelve paths, enumerated, with the reason no test reads any of them.")
          (severity . "minor")
          (summary . "release-preflight.json describes the post-preflight commits as changing only docs/reports/*.md prose and this directory's own JSON captures. The wave's current enumeration lists twelve paths including .gitignore, a deleted chain log, SHA256SUMS, raw .txt and .log captures and the three .rktd records - and the *.md glob does not match .rktd at all. A stale enumeration of exactly the kind fixed as R4-F2, surviving in a checksum-bound artifact.")
        )
        #hasheq(
          (id . "R5-F5")
          (resolution . "FIXED. The raw index now lists all six bound raw captures.")
          (severity . "minor")
          (summary . "The same JSON's raw index lists five files but omits raw/red-first-worker-security-w2.txt, which its own independent-review text cites and which SHA256SUMS binds. An incomplete enumeration in a bound artifact - the standard R4-F2 enforced.")
        )
      ))
      (note . "Round 5 ran to completion and returned CHANGES-REQUESTED. Every finding it raised is enumerated in the findings list below, each reproduced against the tree before being fixed. It reviewed at b9a0ac1ad, the content head current when it ran. The reviewer had no exec tool and worked from the worktree's git metadata and the retained artifacts; everything checkable by reading, it checked, and the substantive test evidence - the 376-test sweep, the playwright failure's honest description, the head-coherence claim, and the R4-F5 trade-off - survived its attack. It judged the R4-F5 deferral legitimate rather than an evasion: the missing metadata is measured, the file's four tests are green, and editing a test file after the chain would have destroyed the no-test-file-changed guarantee the rest of the record depends on. Its one blocking finding was correct in substance and wrong in mechanism, and the correction mattered: the validation record was not unparseable but silently stale, a harder failure to notice and a more dangerous one to ship.")
      (reviewed-sha . "b9a0ac1ad7771306cda061a3ca4e9a4d3ee29278")
      (reviewer . "zai-coding-plan/glm-5.3-flash (independent, read-only)")
      (round . 5)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (findings . (
        #hasheq(
          (id . "R6-F1")
          (resolution . "FIXED. Round 5's reviewed-sha is b9a0ac1ad7771306cda061a3ca4e9a4d3ee29278, the head it actually ran at. R5-F2's subject is restored to b9a0ac1ad with the interval corrected from forty minutes to the thirty-nine minutes the reflogs give. The lesson is recorded rather than quietly fixed: rebinding a record and letting a head field follow the new binding, instead of the event the field describes, is now a named failure mode of this wave.")
          (severity . "moderate")
          (summary . "A regression introduced by the round-5 remediation itself: the bulk head substitution rewrote text inside findings that are historical descriptions. R5-F2's subject, the SHA wrongly written into round 4's reviewed-sha, became the current head while its timestamps still described the old one, and round 5's own reviewed-sha was rewritten to a commit created hours after round 5 ran. Two commits apart this is the head-attribution class this record exists to police, reintroduced by the act of rebinding - the third occurrence in this wave, after R1-F4 and R2-F4.")
        )
        #hasheq(
          (id . "R6-F2")
          (resolution . "FIXED against the measured delta. git diff --name-only b0f19d6bd..9841fed8 is ELEVEN paths, and the field now enumerates exactly those eleven. This is the R5-F4 class reintroduced by the R5-F4 fix - the third round running that a corrected enumeration was itself wrong.")
          (severity . "moderate")
          (summary . "The preflight JSON's chain enumeration said twelve paths and then named fourteen, and three of the files it named do not appear in that range at all because they predate the preflight head, while the deleted .chainlogs/w7-version-derive-tests.log does. Count and enumeration could not both be true, from the committed text alone.")
        )
        #hasheq(
          (id . "R6-F3")
          (resolution . "FIXED by producing the captures rather than softening the claim. format-compile was re-measured at this head and retained as raw/format-compile-canonicality.txt: raco make and raco fmt canonicality over all 29 changed .rkt files, 29 compiled, 29 canonical, 0 not-canonical, 0 fmt-error, one line per file. focused-tests was re-measured through the project runner and retained as raw/focused-release-tests.txt: 8 files, 164 tests, 164 passed, 0 failed, every RUNNER-EXIT 0, the W7-touched four contributing 55 and the release-surface four the other 109. Both are bound in SHA256SUMS and indexed in the preflight JSON. A capture script written during this fix repeated the wave's signature error, taking the exit status after a pipe instead of from the command, which is why the capture records RUNNER-EXIT taken directly.")
          (severity . "minor")
          (summary . "The validation notes claimed every number in the record was retained as a raw capture, which was not true: the format-compile figures and both focused-tests figures had no capture behind them at all. The numbers were genuine but the unconditional claim overstated them.")
        )
        #hasheq(
          (id . "R6-F4")
          (resolution . "FIXED. The notes now state five completed rounds, thirty-three findings, a seventh outstanding, and give round 4's composition accurately, including the tooling note and the two hygiene findings the F-numbered count omits.")
          (severity . "minor")
          (summary . "The validation notes still described four completed review rounds, a fifth outstanding and nineteen findings, at a head where five rounds had completed with thirty-three findings. It also described round 4 as having six findings while the breakdown it gave sums to five.")
        )
        #hasheq(
          (id . "R6-F5")
          (resolution . "FIXED. The status now says five rounds and thirty-three findings. Its second half, that the wave is not merge-authorized while no APPROVED verdict exists, remains true and is unchanged.")
          (severity . "minor")
          (summary . "The evidence record's status still said four CHANGES-REQUESTED rounds with nineteen findings fixed, contradicting the review record it points at.")
        )
        #hasheq(
          (id . "R6-F6")
          (resolution . "FIXED. The report says round 6 is pending and the timestamp now includes the round-5 entry with its reviewer.")
          (severity . "minor")
          (summary . "The review record's report field said Round 5 is pending and its timestamp key listed only r1 through r4, both contradicting the rounds list in the same record.")
        )
        #hasheq(
          (id . "R6-F7")
          (resolution . "FIXED. The field now distinguishes the failed first attempt, which produced no verdict, from the round 5 that subsequently ran to completion on zai-coding-plan/glm-5.3-flash.")
          (severity . "minor")
          (summary . "The tooling-notes field said round 5 could not run because every route was quota-exhausted, contradicting the completed round-5 entry in the same record. The sentence was true of the first attempt when written and was never updated after that round completed on a different route.")
        )
      ))
      (note . "Round 6 ran to completion and returned CHANGES-REQUESTED with seven findings, all reproduced against the tree and all fixed. Its distinctive property is that five of the seven were stale summary fields in the evidence records themselves, and two of those five were regressions introduced by the round-5 remediation: the bulk head substitution rewrote historical subjects, and a corrected enumeration was itself wrong. Every substantive piece of test evidence survived again - the 376-test sweep, the eleven-path delta, the honest description of the Playwright failure, and the remaining-items labels that preserve meaning alongside the gate vocabulary. The reviewer judged the format-compile and fast fields honestly labelled rather than dressed up, and judged the remaining-items fix as preserving meaning rather than flattening it. Its one substantive complaint was that two numbers in the validation record had no retained capture, which was correct, and is fixed by producing them.")
      (reviewed-sha . "9841fed8f2e24bb343e54d310ff836044a903602")
      (reviewer . "zai-coding-plan/glm-5.3-flash (independent, read-only)")
      (round . 6)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (findings . (
        #hasheq(
          (id . "R7-F1")
          (resolution . "FIXED by removing the round number rather than updating it. The sentence now says a further round is outstanding, and states why it is phrased that way: the previous two revisions each named a specific round and were stale at the commit carrying them, because the fix and the recording of the round it referenced landed together. A pending-round claim that cannot fall behind is worth more than one that reads precisely and is wrong.")
          (severity . "minor")
          (summary . "The review record's report field said Round 6 is pending, in the same commit whose rounds list contained a completed round-6 entry and whose verdict said round 7 PENDING. R6-F6 had flagged the identical sentence one round earlier when it said Round 5 is pending; the fix moved the stale claim forward one round instead of eliminating it.")
        )
        #hasheq(
          (id . "R7-F2")
          (resolution . "FIXED structurally rather than by editing the number. The status no longer restates a round or finding count at all: it states that the wave is verified through every round recorded in the review record, that all returned CHANGES-REQUESTED with every finding reproduced before being fixed, and that the counts live in the review record where they are derived from the findings it contains. Nothing here can fall behind.")
          (severity . "minor")
          (summary . "The evidence record's status said five CHANGES-REQUESTED rounds with thirty-three findings fixed, at a commit where the review record it points at read six rounds and forty findings. R6-F5 had established this exact class and the fix set the value one round behind by construction.")
        )
        #hasheq(
          (id . "R7-F3")
          (resolution . "FIXED the same way as R7-F2. The leading count is gone; the field states that every recorded round completed and returned CHANGES-REQUESTED, and points at the review record for the derived counts.")
          (severity . "minor")
          (summary . "The validation record's notes opened by claiming five completed rounds and thirty-three findings, contradicted two sentences later in the same field by its own round-6 and seventh-round sentences and by the verdict's six and forty.")
        )
        #hasheq(
          (id . "R7-F4")
          (resolution . "FIXED and re-measured. The totals are now 6/6 W6, 11/11 W7, 1/1 tier-ownership, 18/18 in total, in the release report and in the preflight JSON, each noting that the earlier figures are superseded and why the manifest grew. Verified by running sha256sum -c from the repository root against all three manifests: 11 + 6 + 1 = 18 OK. The bound historical capture raw/verify-chain.txt still says nine of nine and is left alone: it records what was true when it ran.")
          (severity . "moderate")
          (summary . "Stale manifest totals. The W7 manifest grew from nine to eleven entries when the round-6 remediation added the two captures, so the release report and the preflight JSON still claimed 9/9 W7 and 16/16 in total, false at the commit carrying them and inconsistent with the same JSON's own eight-entry raw index.")
        )
        #hasheq(
          (id . "R7-F5")
          (resolution . "FIXED by measuring the range that matters rather than the one that existed when the field was written. git diff --name-only b0f19d6bd..3a3d3297f is THIRTEEN paths, and the field now enumerates exactly those thirteen. The three earlier wrong revisions are named in the field, because the pattern is the finding: a prose enumeration of a git delta, restated by hand at a head it does not describe.")
          (severity . "moderate")
          (summary . "The chain enumeration retained a stale present-tense twelve paths and corrected only to the pre-remediation endpoint 9841fed8f, so no stated count matched the range the merge candidate actually spans. This is the third consecutive round in which a corrected enumeration was itself stale at the head carrying it.")
        )
        #hasheq(
          (id . "R7-F6")
          (resolution . "FIXED against the measured delta: git diff --name-only e9af72fee..3a3d3297f is fourteen paths, and the field now says fourteen. Same class as R7-F5 - an enumeration not maintained when the captures were added.")
          (severity . "moderate")
          (summary . "The validation record's head-coherence said the delta from the chain head lists twelve paths; the two round-6 captures make it fourteen at the named endpoint.")
        )
        #hasheq(
          (id . "R7-F7")
          (resolution . "FIXED by naming the head the captures actually ran at, in the format-compile details and in both raw-captures entries, and by noting that no .rkt file changed since so the result describes this head's code while the capture keeps its own. The notes sentence now says each capture names the head it ran on rather than claiming a re-measurement at the binding head. This is the campaign's own rule, restated after being broken: a committed artifact cannot contain the SHA of the commit that carries it, and a later re-binding is not a re-measurement.")
          (severity . "moderate")
          (summary . "The two new captures name head 9841fed8f, but the record claimed they were measured at this head, 3a3d3297f, in four separate places. No .rkt file changed between the two heads so the numbers hold, but the record's own convention, stated in its head-coherence field and applied correctly to the suite chain, is that each capture names the tree it ran on and is never upgraded to the binding head. R3-F3 was rated moderate for exactly this shape.")
        )
      ))
      (note . "Round 7 ran to completion and returned CHANGES-REQUESTED with seven findings, all reproduced against the tree and all fixed. Its value is that it caught the REMEDIATION rather than the work: five of its seven findings were stale summary fields in these records, and it showed the round-5 and round-6 fixes for exactly that class were stale by construction - each was written in the same commit that recorded the round it referred to, so each was a round behind the moment it landed. R6-F4, R6-F5 and R6-F6 each reproduced the defect they were filed against, one round later, which is the strongest evidence yet that the defect is the hand-written number and not the number. The fix is therefore to stop restating the count: the evidence status and the validation notes now name this record as the authority and say nothing that can fall behind, and this verdict's counts are derived from the findings it contains. The remaining two findings were real measurement errors - the manifest totals were not updated when the captures grew the manifest, and the chain and head-coherence enumerations were not updated when the same captures were added - and both are now measured against the ranges the merge candidate actually spans. R7-F7 caught the record claiming the new captures were measured at the binding head when they name an earlier one, which is this campaign's own rule, restated after being broken.")
      (reviewed-sha . "3a3d3297fe5172c26303a159a67a187e4639a459")
      (reviewer . "zai-coding-plan/glm-5.3-flash (independent, read-only)")
      (round . 7)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (findings . (
        #hasheq(
          (id . "R8-F1")
          (resolution . "FIXED. head-coherence now names 4891dd2a and its range is measured to that head. Re-measured: git diff --name-only e9af72fee..4891dd2a is fourteen paths, the count the field already claimed, so only the endpoint was wrong, not the tally.")
          (severity . "blocking")
          (summary . "The validation record's head-coherence opened \"The content head is 3a3d3297f...\" while the same datum's implementation-sha said 4891dd2a, so the record contradicted itself inside a single value. The same field's diff range e9af72fee..3a3d3297f was likewise measured to a superseded endpoint, and its closing sentence claimed the trio sits on top of the named head when it sits on top of 4891dd2a. This is the R5-F1b shape inverted, and it survived two rebinds past the point where 4891dd2a became nameable.")
        )
        #hasheq(
          (id . "R8-F2")
          (resolution . "FIXED. The notes name 4891dd2a, and the self-correction sentence no longer claims to have happened at the head the field previously named - it now says when the correction actually happened: during the round-7 pass, re-anchored at the round-9 pass.")
          (severity . "blocking")
          (summary . "The validation record's notes opened \"This record is written at the W7 content head 3a3d3297f\" and described itself as \"corrected at this head\", while the round-7 pass that actually edited it landed in 4891dd2a. A field edited at one head while asserting it was written at another is the R7-F1 class, and this field was the one the round-7 pass had just rewritten.")
        )
        #hasheq(
          (id . "R8-F3")
          (resolution . "FIXED by re-measuring to the endpoint the merge candidate actually spans. git diff --name-only b0f19d6bd..4891dd2a is thirteen paths, the same set the field enumerates, so the path list was already correct and only the named endpoint was not.")
          (severity . "moderate")
          (summary . "The preflight JSON's chain field measured its enumeration to b0f19d6bd..3a3d3297f and then claimed the count was \"measured against the range the merge candidate actually spans\", which was false in the very commit that wrote it - the merge candidate spans to 4891dd2a. R7-F5 had introduced the claim, and it was already stale when written.")
        )
        #hasheq(
          (id . "R8-F4")
          (resolution . "FIXED. The authorization head is 4891dd2a, so following it literally now produces a binding the gate accepts. This was the sharpest instance of the wave's own thesis: the record bound one head and described another, and a field that has been rebound is not a field that has been described.")
          (severity . "moderate")
          (summary . "The evidence record's merge-authorization head read 3a3d3297f while instructing that the APPROVED review be bound at that exact head - a head the gate itself rejects, since it requires reviewed-sha to equal implementation-sha (4891dd2a). An operator following the authorization literally would have bound the review at a head that could not pass. Its source field also dated the directive to a session before 3a3d3297f existed.")
        )
        #hasheq(
          (id . "R8-PROC")
          (resolution . "FIXED procedurally. A rebind now checks the finished records for any superseded head still named as a live claim, and reports it, so the next rebind fails loudly instead of silently. The check is scoped by key rather than by text: the review record's per-round reviewed-sha legitimately names historical heads, and a global substitution would reintroduce R6-F1 for the fifth time. A second procedural error is recorded because it nearly became a third: a chained string-replace in this remediation corrupted a field into a doubled SHA, caught only by re-reading the record. Set the key through the hash, not through text position - which is what the review record's own per-round heads have required since R6-F1.")
          (severity . "moderate")
          (summary . "Procedural: all four findings share one cause, and it is a gap in the REBIND PROCEDURE rather than in any record. Rebinding updated the binding fields (implementation-sha, content-digest) but not the prose naming the same head, so every rebind this wave created a new class of self-contradiction. Rounds 6, 7, 8 and 9 each found defects introduced by the previous round's remediation, which is a convergence failure worth naming rather than treating as unlucky.")
        )
      ))
      (note . "Round 8 ran to completion and returned CHANGES-REQUESTED. All of its substantive findings were one class, and the class is procedural rather than textual: the records bound head 4891dd2a while four present-tense sentences still described 3a3d3297f as the content head. That is not four separate oversights - it is a gap in the rebind procedure, which updated the binding fields and not the prose naming the same head, so every rebind this wave created a fresh class of self-contradiction. The sharpest instance was the evidence record's merge authorization, which instructed that an APPROVED review be bound at a head the gate itself rejects; an operator following it literally would have produced a binding that could not pass. Rounds 6, 7 and 8 each found defects introduced by the previous round's remediation. That is a convergence failure and is recorded as one. What converges is the content: every measurement round 8 could re-derive checked out - the capture totals, the manifest counts, the suite numbers, the reflog timestamps, the gate's structure, and both enumerations, which held at thirteen and fourteen once measured against the right endpoint. The rebind procedure is now hardened to report any superseded head still named as a live claim, so the next rebind fails loudly rather than silently.")
      (reviewed-sha . "4891dd2a52007053e9af7eea0b508bc0e548fcb0")
      (reviewer . "zai-coding-plan/glm-5.3-flash (independent, read-only)")
      (round . 8)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (findings . (
        #hasheq(
          (id . "W7-R9-F1")
          (resolution . "FIXED. The note is rebuilt as a single string with its subject at the head, and is asserted to open with \"Round 8\" rather than left to be read.")
          (severity . "moderate")
          (summary . "The round-8 note was text-mangled by the remediation that created it: it opened \" ran to completion and returned CHANGES-REQUESTED.\" with its subject missing, and ended \"...fails loudly rather than silently.Round 8\" with the subject stranded at the tail, glued without a space. The record's own R8-PROC had already noted that a string-replace corrupted a field on that pass; the doubled SHA was caught and this was not. Every other round's note opens \"Round N ran to completion...\".")
        )
        #hasheq(
          (id . "W7-R9-F2")
          (resolution . "FIXED. The round-8 and round-9 review times are appended to the enumeration, and the enumeration is derived from the rounds list rather than restated by hand. Round 8's own review captured no completion time, so its entry is the date of the commit that recorded it, ec372103 at 2026-09-26T06:49:10Z; stating that in the resolution is the honest form, because a reconstructed time presented as an observed one is the same defect as a count that drifted. A first attempt at this fix derived the reviewer and timestamp fields from the rounds list as it stood BEFORE round 9 was appended, which produced an enumeration missing r8 and a reviewer count describing round 9 as in flight after it had completed - the exact defect F2 names, reintroduced by the fix for it. Both are now derived after the rounds list is final.")
          (severity . "minor")
          (summary . "The top-level timestamp enumerated r1 through r7 while the rounds list recorded eight rounds and the verdict said \"rounds 1-8\", so round 8's review time appeared nowhere in the record. Round 6's W6-F6 had already fixed exactly this class of timestamp divergence in the W6 record, and the same record's own standard was not applied to round 8.")
        )
        #hasheq(
          (id . "W7-R9-F3")
          (resolution . "FIXED. The count is derived from the rounds list at write time, so it cannot fall behind again. The timestamp and reviewer keys are now written from the same derivation that produced the rounds.")
          (severity . "minor")
          (summary . "The top-level reviewer key read \"..., 5 rounds solicited\". That count was last updated at the round-4 recording and matched nothing derivable at this head: eight rounds were completed and a ninth in flight. It is a hand-maintained count of another field, which is the same defect this wave exists to police.")
        )
        #hasheq(
          (id . "W7-R9-F4")
          (resolution . "FIXED. Reworded to name the three files that actually pin frozen artifacts. The change is comment-only and that is measured, not asserted: the file re-runs through the project runner at 75/75 with exit 0, captured in raw/milestone-gate-recheck.txt. Whether the tier-ownership matrix binds this file's hash was checked BEFORE editing - it records test PATHS and a digest of the families list, not per-file hashes, so a comment change leaves it valid. This is the one round-9 finding that changes the tree under tests/, so both path enumerations and the no-source-change claim are re-derived rather than left standing; they move from 13/14 to 15/16 and the claim is restated precisely.")
          (severity . "minor")
          (summary . "tests/test-milestone-gate.rkt:627 read \"Unlike the frozen v1.00.29 artifacts elsewhere in this file, the tier-ownership matrix is a CURRENT-TREE drift check\". A grep for 1.00.29 in that file returned exactly one hit - the comment itself. The comparison pointed at nothing, and the files that do pin frozen artifacts are the shard-plan, ci-cohort-report and worker-security tests, each pinning a v1.00.29 path. A false comparison in a comment is a small thing, and leaving it in a tree whose thesis is that a claim pointing at evidence differs from a claim resting in it is worse.")
        )
      ))
      (note . "Round 9 ran to completion with a shell available and was the first round whose checks were executed rather than simulated. That difference is the substantive result of this round: the digest, record-commit, verify, the wave gate, all three manifests, provenance and lint were run, and every numeric claim in the three records was independently re-derived. All five checks executed green, and the gate reported exactly the two expected rejections with no third hiding behind them - confirmed by reading the gate source, which appends to reasons without short-circuiting. Every measurement held: both path enumerations matched the actual path SETS and not merely the counts, the suite numbers matched raw/verify-chain.txt, the capture file lists matched git, and the affected sweep still read 376/376 with every runner exit 0. Round 9 also swept all fourteen superseded heads across the three records and confirmed every occurrence is either a per-round reviewed-sha by design, a historical finding, or a capture attribution naming the tree it ran on - no live field names a superseded head. Its four findings are prose-integrity, in the review record's own fields and in one test comment, and none touches binding, digest, checksum, provenance or measurement. The first is damage this record's own remediation did three commits earlier, which is the convergence pattern stated again: a text-position edit to a record that repeats the same value corrupted a field, the doubling was caught, and the mangled note was not. Round 10 is pending.")
      (reviewed-sha . "b83d16f39ec1481612ca011a2572b2f3a541ae45")
      (reviewer . "zai-coding-plan/glm-5.3-flash (independent, read-only, exec enabled)")
      (round . 9)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (findings . (
        #hasheq(
          (id . "W7-R10-F1")
          (resolution . "FIXED by re-measurement, not by adjustment. All three surfaces now state the measured 6/6 W6, 12/12 W7, 1/1 tier-ownership and 19/19 overall. The deeper point is that the retained chain capture cannot show those numbers: raw/verify-chain.txt records 9/9 and 16/16 because the W7 manifest held nine entries when the chain ran, and re-running the 29-minute chain was not justified for a manifest that grew by adding captures. So the fix states the current totals as measured now and labels the retained output a historical snapshot of its own run, in all three surfaces, instead of silently quoting 16/16 as current or restating a capture that says otherwise. The validation record's capture count is corrected from eight to nine.")
          (severity . "moderate")
          (summary . "Stale manifest totals across three live release surfaces. The W7 manifest holds twelve entries and the three manifests verify 19/19 at this commit, but the release report, the preflight JSON and the validation record still carried the figures that were true when the round-7 remediation last re-measured them: 11/11 W7 and 18/18 overall, and in the validation record 9/9 W7, 16/16 and eight captures. The manifest grew twice after that re-measurement - two captures at round 6 and the milestone-gate recheck at round 9 - and no live surface was re-measured with it.")
        )
        #hasheq(
          (id . "W7-R10-F2")
          (resolution . "FIXED at the source. The per-round findings arrays are the data and the aggregate is derived prose, so the nine-round total was corrected from 56 to 55 rather than a finding being invented to reach 56, and this round's two findings bring the derived total to 57. The record now also says where the off-by-one came from: the round-8 aggregate was hand-maintained, and the correction is made by summing the arrays, which is the only derivation that cannot drift. Asserted on the parsed record, not on the text.")
          (severity . "moderate")
          (summary . "The verdict aggregate was wrong, and had been wrong since round 8. It read all 56 findings; the nine per-round findings arrays sum to 55. Rounds 1 through 8 sum to 51, not the 52 the record had been carrying, so the error was inherited rather than introduced by round 9 - the 56 came from adding four to a total that was already one high.")
        )
      ))
      (note . "Round 10 ran to completion with a shell and, like round 9, executed all five checks rather than simulating them: the digest matched, record-commit returned pure, verify returned digest-ok, the gate reported exactly the two expected rejections with reject! confirmed to append rather than short-circuit, all three manifests verified (12/12, 6/6, 1/1), provenance passed with 950 notes, and lint-all reported 23 passed and the same 2 pre-existing warnings. Every numeric claim was re-derived independently and the round swept the superseded heads and the duplicate-key risk again; those held. Two findings, and both are the defect class this wave has produced most often: a live surface carrying a count that was true when last measured and was not re-measured when the data beneath it grew. Neither touches binding, digest, provenance or measurement, and the finding count fell from six to two, which is the first evidence of convergence in the review process rather than in the content - the content converged several rounds ago, and it is the prose and its aggregates that have not. The more interesting finding is the first, because its fix was not a number. The retained chain capture records 9/9 and 16/16 and cannot record anything else without re-running a 29-minute suite, so the honest repair is to state the current totals as measured now and to label the capture as a historical snapshot of its own run, rather than to quote it as current or to restate it into agreement. Both were available and both would have been false. Round 11 is pending.")
      (reviewed-sha . "b83d16f39ec1481612ca011a2572b2f3a541ae45")
      (reviewer . "zai-coding-plan/glm-5.3-flash (independent, read-only, exec enabled)")
      (round . 10)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (execution . "PARTIAL - all seven mandated execution checks NOT-RUN and reported as such; static analysis substituted and labelled; one of two findings real, one refuted")
      (findings . (
        #hasheq(
          (id . "W7-R11-F1")
          (resolution . "FIXED by re-measurement, and the fix is not a number correction. The count survived because 28f39f30d happens to sit on the b0f19d6bd..content segment, and that range is also sixteen paths, so a sentence that mixed three ranges and mislabelled one of them produced an arithmetically true figure. That is the most dangerous shape a record defect can take: it survives review by being true while being evidentially false, and four revisions of this field had each restated something wrong at the head carrying it. The field now measures each range separately - chain head to preflight commit is 5, preflight commit to content head is 18, chain head to content head is 19 - and names both stable anchors instead of reaching the chain head by pointing at the capture, which is how the two ranges came to be confused in the first place. It deliberately does not name the content head: the artifact is bound by SHA256SUMS, its digest feeds the evidence binding, and committing it moves any head it names, so it points at the evidence record's implementation-sha and merge-authorization.head as the authority instead. Both generators are bound in the manifest following the W6 precedent, so the correction is reproducible rather than asserted; the second is idempotent and keyed on shapes rather than digits, because restating the counts writes a generator into the manifest and moves the counts again.")
          (severity . "moderate")
          (status . "FIXED")
          (summary . "The preflight chain field conflated three commits as one. It claimed the sixteen-path enumeration was the delta between the commit named inside verify-chain.txt and this artifact's own commit field, and it named 28f39f30d as that endpoint. Both halves are false and wrong in the same direction: verify-chain.txt names only e9af72fee and cannot name the commit that carries it, b0f19d6bd is a DESCENDANT of that head rather than an ancestor, and the delta between them is 5 paths, not 16. The endpoint 28f39f30d was a third commit again - an intermediate on the way, the round-9 remediation.")
        )
        #hasheq(
          (id . "W7-R11-F2")
          (resolution . "NOT FIXED, because the finding is false, and acting on it would have corrupted a correct record. The W7 manifest holds 12 entries because it binds 9 files under raw/ and 3 that are not captures: release-preflight.json, w4-recovery.json and the release report. '(9 captures)' counts the captures and is correct; the reviewer counted 8 raw files, missed one, compared the capture count against the entry count, and concluded a correct figure was stale. The error is instructive rather than trivial: two different units - entries and captures - were read as one, which is a counting error of exactly the kind this wave has been about. Had the finding been acted on, '(9 captures)' would have become '(12 captures)' and been wrong twice over. The field was instead restated to the unambiguous form - entry counts with the raw count given alongside - so the ambiguity is gone without the figure being changed. Rejected findings are recorded here rather than dropped, because a review that only keeps what it got right teaches nothing about which checks are load-bearing.")
          (root-cause . "Two units read as one. The manifest binds twelve entries; nine of them are captures under raw/ and three are not. The reviewer counted eight raw files, then compared that capture count against the entry count. The field was never stale - the comparison was, and a unit error is the same class of thing this wave exists to police, which is why it is recorded here rather than merely dismissed.")
          (severity . "moderate")
          (status . "REFUTED - not a defect")
          (summary . "The round reported that the validation record's checksums field presents '(9 captures) ... all verify' in the present tense while the W7 manifest holds twelve entries, and called the 9 a superseded figure presented as current.")
        )
      ))
      (not-run . ("gsd-evidence-bind.rkt digest / record-commit / verify (the binding)" "git diff on the record commit (record-commit purity)" "gsd-wave-gate.rkt (the gate; static analysis of its preconditions substituted)" "sha256sum -c on all three manifests (the checksums; manifest contents verified instead)" "verify-artifact-provenance.rkt and lint-all.rkt" "git diff --name-only enumerations (the path counts)" "the review record's interior: round count, per-round findings sum, the historical " "reviewed-sha values, and any duplicate top-level key beyond character 500 - the file is " "one 62.2 KB line, the read tool refuses lines over 50 KB, and grep shows only the first " "500 characters, with no second copy in the tree"))
      (note . "Round 11 returned CHANGES-REQUESTED with two findings, and it is a different kind of round from the ten before it: the reviewer had no shell, said so plainly, and returned a NOT-RUN register naming all seven mandated checks it could not execute. That register is the most valuable part of the round. It refused to reason about whether the binding, gate and checksum commands would pass, it noticed that the review record is a single 62 KB line its tools cannot read past 500 characters, and it declined to substitute an in-tree claim for a measurement it had not made. What it could check from raw text, it checked, and one of the two findings it raised is real. The real one, F1, is the best example yet of this wave's central theme, and it is worth stating precisely because the defect was invisible to arithmetic. The field named three commits as one and produced the right number anyway, so it would have passed any check that counts paths. The evidence-only-record discipline, the stale-live-claim sweep and the gate would all have passed it. Only reading the sentence and asking which commit each range runs between found it, and the sentence it was found in had already survived four revisions. The second finding, F2, is refuted: the manifest's 12 entries are 9 captures plus 3 non-captures, the reviewer counted 8 raw files and compared captures to entries, and acting on it would have made a correct record wrong. Both facts are recorded. The finding count is 58 accepted out of 59 raised, and the distinction is the point: a review process that cannot reject its own findings is not converging, it is accumulating. The convergence evidence is that the real finding was a prose defect in an artifact rather than a defect in a binding, a digest, a measurement or the content, and that the fix is a re-measurement with the generators bound so it is reproducible. The standing problem is unchanged and is now structural rather than incidental: the mandated review route has lost its exec four rounds running, and every check that has to be executed - the binding, the gate, the checksums, the provenance, the lint - is therefore unverified by the reviewer at exactly the point where it matters most. Eleven rounds of reading have found real defects, and reading is not what is failing. Round 12 is pending and must have a shell.")
      (reviewed-sha . "856f485098c3ccd3cf9e9e6d856e747bf5d241a6")
      (reviewer . "zai-coding-plan/glm-5.3-flash (independent, read-only; NO exec - self-reported)")
      (round . 11)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (execution . "BLOCKED - all seven mandated execution checks refused by the session; marked BLOCKED rather than inferred; gate preconditions analysed statically and labelled as not a run")
      (findings . (
        #hasheq(
          (id . "W7-R12-F1")
          (resolution . "NOT FIXED in the tree, because it is not in the tree. This is the sole reason the wave is not merge-authorized, and it is not a wave-content defect: the binding, the gate, the checksums, the provenance and the lint have all been run by the implementer and pass, and the round that matters is the one that certifies them independently. Two mitigations are in place. The reviewer's static analysis of the gate's preconditions is recorded as corroboration, clearly labelled as not a run, and it found no third rejection. And the record now carries the NOT-RUN register as a first-class list, so a round that cannot execute says exactly which checks it skipped rather than leaving the omission to be inferred from a verdict.")
          (root-cause . "The mandated review route is not receiving a shell. Two attempts this round and one the round before granted an exec allowlist, and the reviewer reported no exec tool in the session in all three cases. Rounds 9 and 10 did execute their checks, so the capability existed and has since been lost on the route rather than absent from the harness.")
          (severity . "blocking")
          (status . "OPEN - infrastructure, not wave content")
          (summary . "All seven mandated execution checks BLOCKED: the evidence binding, the record-commit purity diff, the gate run, sha256sum -c on all three manifests, artifact provenance, lint-all, and the git path enumerations. The reviewer refused to issue APPROVED over checks it had not run and returned CHANGES-REQUESTED on that ground alone, which is the first time a round in this wave has declined to approve for want of evidence rather than for a defect it had found.")
        )
        #hasheq(
          (id . "W7-R12-F2")
          (resolution . "FIXED, and it is the most consequential change this wave has made to its own instruments. All three records are now laid out over 36, 473 and 111 lines with a longest line of 5773 characters, so the whole of each is openable and the tally is independently checkable: 4+4+6+9+9+7+7+5+4+2+2 = 59 across eleven rounds, one marked REFUTED, giving the 58 accepted the verdict claims. Every per-round reviewed-sha is readable, including the legitimate duplicate shared by rounds 9 and 10. Only layout changed - no value moved, the content digest is byte-identical, and the gate still reports exactly the two honest rejections. Two dead ends are recorded in the commit rather than hidden: racket/pretty's pretty-print emitted a leading quote so the result no longer read back as a hash, and equal? is unusable on these records because they mix one immutable top-level hash with 71 mutable nested ones and equal? is #f for a mutable and an immutable hash of identical contents. The check used instead is mutability-independent structural equality plus layout idempotence.")
          (root-cause . "The records were written as a single datum on one line, so a reviewer whose read tool caps lines at 50 KB could not open the 71 KB review record at all, and grep showed only the first 500 characters of any match. The record was therefore unreviewable in the one place where review is the point.")
          (severity . "moderate")
          (status . "FIXED")
          (summary . "docs/reports/gsd-wave-reviews/v1.00.31-w7.rktd is a single 71 KB line, exceeding the session read tool's 50 KB per-line cap, and grep displays only the first 500 characters of a match. The rounds array, every per-round findings array, the verdict and the historical reviewed-sha values were consequently unverifiable. The round demonstrated the cost rather than asserting it: asked to check that the aggregate was 58 accepted and 1 refuted, it reported that the word 'refuted' and the id W7-R11-F2 were ABSENT from a record that contains both, because its probes could only see the first 500 characters.")
        )
      ))
      (not-run . ("gsd-evidence-bind.rkt digest / record-commit / verify (the binding)" "git diff on the record commit (record-commit purity)" "gsd-wave-gate.rkt (the gate; static precondition analysis substituted, labelled)" "sha256sum -c on all three manifests (contents counted, digests not computed)" "verify-artifact-provenance.rkt and lint-all.rkt" "git diff --name-only enumerations (the 18 / 19 / 5 path counts)" "the review record's interior - the finding aggregate, the historical reviewed-sha values, and the duplicate-key scan - because the file was one 71 KB line, the read tool refuses lines over 50 KB, and grep showed only the first 500 characters"))
      (note . "Round 12 is the round that explains the other eleven. It found no defect in the wave content, invented none, and returned CHANGES-REQUESTED anyway - on the ground that it could not execute the checks it was commissioned to run. It was granted an exec allowlist, found none in its session, marked all seven mandated checks BLOCKED rather than reasoning about whether they would pass, and declined to issue an approval it could not stand behind. That is the correct behaviour and it is worth being explicit about what it means for this wave: after twelve rounds, the obstacle to merge is not the content and not the prose, both of which have converged, and not the instruments, all of which pass when the implementer runs them. It is that the one party whose job is independent certification has not been able to run anything for four consecutive rounds. The round's second finding is the one that should worry a future session most, because it was nearly an approval by omission. The review record had grown to a single 71 KB line that the reviewer's read tool refuses and grep truncates to 500 characters, so the finding arrays it was asked to sum were invisible. Its probes over the first 500 characters returned results consistent with the claims and proved nothing - it reported the word 'refuted' and the id W7-R11-F2 as absent from a record containing both. Had the round been less careful it would have certified an aggregate it never saw, and the wave would have merged on that. The records are now openable end to end, which is the precondition for every future round being worth anything. The pattern across all twelve rounds is that the defects have moved steadily upward: first instrument failures that permitted vacuous greens, then evidence and binding errors, then prose that no gate reads, then a derived aggregate mislabelled while arithmetically true, and now the instruments' own readability. Each layer had to be fixed before the next became visible, and the current layer is the one that makes the others auditable. That is progress, and it is not the same as being close. Round 13 is pending and must have a shell.")
      (reviewed-sha . "98e582e019277046290f67a6207d8555d5442041")
      (reviewer . "zai-coding-plan/glm-5.3-flash (independent, read-only; exec allowlist granted and NOT present)")
      (round . 12)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (execution . "COMPLETE - every mandated check executed; digest matched, record-commit pure, verify digest-ok, gate exactly two rejections, 21/21 checksums, provenance 950 notes, lint 23 passed / 2 pre-existing warnings")
      (findings . (
        #hasheq(
          (id . "W7-R13-F1")
          (resolution . "FIXED at the writer, not in the text. All four figures are now computed from the per-round findings arrays when the verdict is built, and an assertion requires them to partition the total - which is the property nothing was checking, and the reason the error survived while every other figure in the record was correct. The verdict also now states its counting convention outright, because 61 is the array total and R4-F7 is a real finding recorded outside round 4's array, so a reader comparing the total against the wave's finding history would otherwise be misled by a number that was never wrong.")
          (root-cause . "A derived aggregate retyped by hand. The verdict's three figures did not partition: 58 accepted + 1 refuted + 1 open = 60 against 61 findings in the arrays. The 58 was correct for the eleven-round state and was left in place when round 12 added one accepted and one open finding. This is the same defect the record was corrected for once already - a hand-maintained total wrong by one for four rounds - reintroduced by the author of that correction, because the rule lived in prose rather than in the thing that writes the field. A rule not enforced by the writer is not a rule.")
          (severity . "moderate")
          (status . "FIXED")
          (summary . "The top-level verdict read '61 findings raised, 58 accepted after one was refuted, 1 still open'. Round 13 executed the checks and derived the dispositions from the arrays itself: 61 total, 1 refuted, 1 open, therefore 59 accepted. 58 + 1 + 1 = 60, not 61. The figure is one stale generation behind.")
        )
        #hasheq(
          (id . "W7-R13-F2")
          (resolution . "REMOVED, not annotated. Annotating a duplicate leaves two copies of a paragraph in a record whose whole argument is that each claim should be stated once and should not fall behind, and one of the two would still be the stale copy. The fix script locates the second copy, asserts its distinctive tail already appears earlier in the field - so it is provably the duplicate and not a distinct passage - and only then removes it. The field drops from 5760 to 5127 characters and 'This review is the eighth' now occurs zero times.")
          (root-cause . "A remediation that appended instead of replaced, leaving a byte-identical copy of a paragraph behind. The duplicate is also four generations stale, opening 'This review is the eighth' in a record at twelve rounds.")
          (severity . "moderate")
          (status . "FIXED")
          (summary . "The report field contains one paragraph twice, verbatim. Round 13 saw the stale deixis and classified it as covered by the record's own design statement rather than as a defect. Verifying it showed the second occurrence is a byte-identical duplicate of the preceding paragraph, from 4317 to 4950 of the field - 633 characters - so it is a residue of a remediation that appended rather than replaced, not merely a number that fell behind.")
        )
      ))
      (not-run . ("the fast test suite - not in this round's mandate; lint-all's tests check and " "the bound fast-suite capture cover it"))
      (note . "Round 13 had a shell, and that changes what this wave can say. Twelve rounds have returned CHANGES-REQUESTED, and rounds 1-8, 11 and 12 did so for two different reasons: rounds 1-8 found real defects, and rounds 11 and 12 found none they could certify because they could not execute anything. Round 13 executed all eight mandated checks and all ten re-derivations, pasted the real output for each, and every one held: the digest, record-commit purity, the verify, the gate reporting exactly the two honest rejections and no third, all twenty-one checksums across three manifests, provenance, lint at 23 passed and the same two pre-existing warnings, all three path enumerations at 5, 18 and 19, zero duplicate top-level keys in any record, the live-versus-historical classification, count hygiene on both live surfaces, the chain-field repair against its own measurements, the gate's preconditions, and the record layouts. The four-round outage in W7-R12-F1 is resolved and is recorded as resolved. It found two defects, both in this record, and neither touches binding, digest, checksum, provenance, measurement or the W7 content. The first is its own accepted-count being stale by one, and the reason is the most uncomfortable finding of the wave: the aggregate had already been corrected once for being hand-maintained, the correction made it derived, and the very next round typed the figure back into a format string. A rule enforced only in prose does not survive its own author. The fix moves the arithmetic into the writer and adds the assertion that was missing - that the three dispositions must partition the total - which is the property that would have caught it and which nothing was checking. The second is a duplicated paragraph I found while verifying the first, which round 13 had classified as context rather than a defect; it is a byte-identical copy left by a remediation that appended instead of replacing. It is removed rather than annotated. What the wave has established across thirteen rounds is that the W7 content is sound by every check that can be run, and that the remaining surface is the record describing itself. That is a real convergence, and it is narrower than it looks: the last four findings were all in prose, and prose is exactly what no gate in this repository reads, so a wave can be made of them indefinitely. The difference now is that a round with a shell can see them, which four rounds ago it could not. Round 14 is pending.")
      (reviewed-sha . "98e582e019277046290f67a6207d8555d5442041")
      (reviewer . "zai-coding-plan/glm-5.3-flash (independent, read-only; EXEC PRESENT - all eight mandated checks and all ten re-derivations executed with real output, ending the four-round outage recorded as W7-R12-F1)")
      (round . 13)
      (verdict . "CHANGES-REQUESTED")
    )
    #hasheq(
      (execution . "PARTIAL - eight of nine mandated gates executed. digest matched; record-commit pure; verify digest-ok; gate reported exactly the two expected rejections and no third; W7 checksums 14/14; W0 checksums 1/1; provenance ok; lint 23 passed / 2 pre-existing warnings. The ninth, the W6 checksum, could not be executed as mandated because the instruction named a manifest that does not exist - see W7-R14-F1. The reviewer located the real W6 manifest and verified 6/6 itself.")
      (findings . (
        #hasheq(
          (id . "W7-R14-F1")
          (resolution . "Corrected in the round 15 instruction, and the corrected path is verified to exist and to pass 6/6 from the repository root before being handed to a reviewer. Recorded against the instruction rather than dropped, because a mandated check that cannot be executed is a missing gate and this wave has twice been damaged by exactly that: W7-R12-F1 and the bare-raco-test sweep that exited 0 without running anything.")
          (root-cause . "A wrong path in the review instruction I wrote, not a defect in any artifact. There is exactly one tier-ownership manifest in the tree, artifacts/tier-ownership/v1.00.31-w0/SHA256SUMS; the W6 manifest is under wave-delivery-integrity. No file in the repository is wrong.")
          (severity . "low")
          (status . "FIXED AT SOURCE - in the review instruction, not in the tree")
          (summary . "The mandated checksum command for W6 named artifacts/tier-ownership/v1.00.31-w6/SHA256SUMS, which does not exist. sha256sum exits 1 with 'Datei oder Verzeichnis nicht gefunden', so a mandated check could not be executed as written. The reviewer reported it rather than silently substituting the manifest it found, which is the correct behaviour and is why it surfaced at all.")
        )
        #hasheq(
          (found-by . "NOT raised by the round 14 reviewer. Found by me while writing the classifier that computes this record's disposition counts, immediately after round 14 returned. It is recorded here because it was found while adjudicating round 14, not attributed to a review that did not raise it.")
          (id . "W7-R14-F2")
          (resolution . "The 57 findings are NOT backfilled with a status, because assigning 57 dispositions from prose at volume is the very move this wave exists to stop: it would manufacture exactly the record the verdict was pretending to have. Instead the classifier loses its default branch, so a finding with no status is unclassified and is counted as such, and the verdict now states the real shape of the data: the total, how many findings carry an explicit status, and how many carry none. The partition assertion is gone, because there is no partition to assert over unrecorded dispositions. Rounds 11 onward do record a status on every finding, so the record is well-formed going forward and the deficit is historical, confined to rounds 1-10, and permanent as history.")
          (root-cause . "A classifier with a default branch, used as a measurement instrument. The missing value and the meaningful value were both 'accepted', so the error was invisible to every check: the count was self-consistent, the partition assertion passed, and a reviewer reading the verdict would see four numbers that added up. This is the same failure as W7-R13-F1 one level deeper. F1 was a derived total that went stale by one generation; this is a derived category that never existed in the data. The wave had spent four rounds hardening the arithmetic of a number whose categories were being invented as it was written.")
          (severity . "high")
          (status . "FIXED - the unsupported claim is withdrawn, not backfilled")
          (summary . "The verdict asserts a four-way disposition partition over all 63 findings - '61 accepted, 1 refuted, 1 still open' - but only 6 of the 63 carry a status at all. Rounds 1 through 10 wrote findings with exactly the keys id, resolution, severity and summary, and no status, so 57 findings have no recorded disposition. The word 'accepted' for those 57 was supplied by the classifier's default branch at write time. The verdict was reporting an inference as though it were a recorded fact, and round 13's assertion that the dispositions partition the total was checking that inference against itself.")
        )
        #hasheq(
          (found-by . "NOT raised by the round 14 reviewer. Found by me while running the script that writes this entry, before it wrote anything.")
          (id . "W7-R14-F3")
          (resolution . "Separators are whitespace, and the idempotence assertion stays and is now load-bearing rather than decorative. The first version of the script also had one paren short in the verdict's hash-set, and the balance guard caught it before the file was written. Three defects in one remediation tool, none of them visible to the artefact they were repairing.")
          (root-cause . "The emitter was written from memory of a hash syntax that is not Racket's, and the failure mode is the dangerous one: a reader that rejects bad input would have surfaced this immediately, but ',' is valid Racket with different meaning, so the corruption passed every check that only asked whether the text parsed. It was caught solely by the assertion that re-emitting a rendered record is a structural no-op - an assertion I nearly dropped as ceremonial when porting the emitter, and which is the only reason the record was not written corrupt.")
          (severity . "high")
          (status . "FIXED - in the remediation tool, before it could write the record")
          (summary . "The hand-rolled record emitter written for this round separated hash-pair clauses and list elements with a comma. Racket's reader does not accept a comma as a separator there: it reads ',' as UNQUOTE. So the emitter produced text that looked like a hash and parsed as something else, and it did so silently - no error, no warning, a datum of the right shape and the wrong contents. The two renderings differed by 4278 characters.")
        )
      ))
      (not-run . ("sha256sum -c artifacts/tier-ownership/v1.00.31-w6/SHA256SUMS - not run as mandated: no such file. The reviewer substituted the correct W6 manifest and reported 6/6 OK." "the fast test suite - not in this round's mandate; lint-all's tests check and " "the bound fast-suite capture cover it"))
      (note . "Round 14 executed nearly everything, found almost nothing in the content, and returned one finding aimed at the review process rather than the tree. Adjudicating it turned up the deepest defect in the wave, and the two are related in a way worth stating. The reviewer's finding was that a path in my instruction did not exist, so a mandated check could not run. Mine is that a category in my verdict did not exist either, so a mandated assertion - that the dispositions partition the total - was passing while measuring nothing. In both cases a value that should have come from the data was supplied by me at write time, and in both cases the error was invisible to the arithmetic because I was the one supplying the number the arithmetic was checked against. An instrument that shares an author with the thing it measures will agree with it. On the content: fourteen rounds have now run, and the last three found nothing in the W7 content, in the binding, the digest, the checksums, the provenance or the measurement. Every remaining defect is in the record describing itself, and the record is prose, and no gate in this repository reads prose - which means a wave can be made of these indefinitely. Round 13 was the first round with a shell and it found four; round 14 had one and found one, and the one it found was in the harness. That is progress, and it is progress in the review rather than in the product, which is the honest shape of this wave at fourteen rounds. Two process notes. This round ran on gpt-5.5, not the mandated zai-coding-plan/glm-5.3-flash, because I launched it without the model override and the child inherited the session default. It is recorded as advisory and does not count toward approval, whatever it says; the route constraint is one of the few things holding this process independent, and I weakened it by omission rather than by decision, which is worse than the reverse. And the reviewer's provenance figure of 952 notes appeared to contradict this record's live claim of 951 for w6 and 950 for w7; I took that for a stale live claim of the class this wave exists to police, and I was one reproduction away from recording a fifteenth false finding. Both figures are correct: 952 is the default whole-repository invocation, 950 is --current-wave v1.00.31-w7, 951 is --current-wave v1.00.31-w6. They measure different things and neither is stale. The rule that saved it is the one this wave has been paying for the hard way - reproduce a finding before it becomes a finding - and the corollary is that the same rule applies to the tools I write: my own classifier is an instrument, and it needed the same scrutiny as the reviewer's shell. Round 15 is pending and must run on the mandated route.")
      (reviewed-sha . "98e582e019277046290f67a6207d8555d5442041")
      (reviewer . "gpt-5.5 (independent, read-only; EXEC PRESENT - eight of the nine mandated gates executed with real pasted output, and every re-derivation ran). NOT the mandated independent route: this round was launched without the model override and ran on the session default. The route constraint names zai-coding-plan/glm-5.3-flash, so this round is recorded for completeness and advisory value and does NOT count as the round that can authorize approval. Its finding stands regardless of model, because it is a checkable fact about a path rather than a judgement.")
      (round . 14)
      (verdict . "CHANGES-REQUESTED")
    )
  ))
  (schema-version . 2)
  (scope . "W7 blocked-wave repair, bake and v1.00.31 release, reviewed read-only against the frozen W7 wave doc in the campaign plan snapshot. Rounds 1-4 covered the runner base-dir fix and its regression tests, the three classes of version-coincidence defect, the W2 gate-integrity repair and its red-first proof, the W6 rehearsal matrix regeneration and head re-stamp, the W4 local-capture correction, the release honesty of the CHANGELOG entry and the release report, and the coherence and substantiation of the W7 evidence captures. Each round was a fresh read-only reviewer at the then-current head; no finding was accepted without being reproduced against the tree first.")
  (timestamp . "2026-09-25T17:10:00Z (r1) / 2026-09-25T17:35:00Z (r2) / 2026-09-25T20:20:00Z (r3) / 2026-09-25T22:30:00Z (r4) / 2026-09-26T02:05:00Z (r5, zai-coding-plan/glm-5.3-flash) / 2026-09-26T04:20:00Z (r6, zai-coding-plan/glm-5.3-flash) / 2026-09-26T05:35:00Z (r7, zai-coding-plan/glm-5.3-flash) / 2026-09-26T06:49:10Z (r8, zai-coding-plan/glm-5.3-flash) / 2026-09-26T12:17:17Z (r9, zai-coding-plan/glm-5.3-flash, exec enabled) / 2026-09-26T13:15:00Z (r10, zai-coding-plan/glm-5.3-flash, exec enabled) / 2026-09-26T22:40:00Z (r11, zai-coding-plan/glm-5.3-flash, no exec - NOT-RUN register returned) / 2026-09-27T01:40:00Z (r12, zai-coding-plan/glm-5.3-flash, exec allowlist granted but not present - all seven checks BLOCKED) / 2026-09-27T02:15:00Z (r13, zai-coding-plan/glm-5.3-flash, EXEC PRESENT - all mandated checks executed, outage resolved) / 2026-09-27T02:50:00Z (r14, gpt-5.5, EXEC PRESENT - eight of nine mandated gates executed; NOT the mandated route, so advisory and not counted toward approval)")
  (tooling-notes . "Round 3 was obtained on a later attempt after three provider failures: a usage-limit error on the reviewer role's default model, an OpenRouter credit limit (402) on an alternative, and an OpenRouter monthly key limit (403) on a third. Round 5 was first attempted on the routes that had served rounds 3 and 4 and could not finish: all four configured providers were quota-exhausted, the last returning a five-hour usage limit partway through. That attempt produced no verdict and is recorded as such. Round 5 was subsequently run to completion through zai-coding-plan/glm-5.3-flash and returned CHANGES-REQUESTED, with every finding it raised fixed, as was round 6. The earlier wording here said round 5 could not run without qualification, which stopped being true when that round completed; the failed attempt and the completed round are now distinguished rather than conflated. No verdict was invented in place of any of these failures. The pattern across all of them is the same and is worth stating plainly: a review that cannot run is a missing gate, never an implicit approval, and the evidence record says so in its status field.")
  (verdict . "CHANGES-REQUESTED (rounds 1-14; 66 findings raised across the per-round findings arrays. 9 of them carry an explicit machine-readable status - 7 FIXED, 1 REFUTED, 1 OPEN - and the remaining 57 carry no status at all: rounds 1-10 wrote findings with only id, resolution, severity and summary, so for those the record asserts NO disposition and the number is not an inference presented as a fact. The old verdict counted all 66 as 'accepted'; that was a classifier default, not a recorded value, and it is withdrawn rather than backfilled - see W7-R14-F2. Every finding from round 11 onward does carry a status, so the record is well-formed going forward. Round 15 PENDING - NOT APPROVED, and this record must not be read as approval. The total is over the per-round findings arrays, the record's declared basis; R4-F7 is a real finding recorded separately in round 4 and is not in those arrays, so this total is the array total and not the wave's finding count. Round 14 ran on gpt-5.5 rather than the mandated independent route and is advisory; approval requires a round on the mandated route.")
)
