;; Wave review: v1.00.27 W4 — L0/L1/L2 local feedback telemetry with p90 evidence
;; Record-only companion to gsd-wave-evidence/v1.00.27-w4.rktd
;; and gsd-wave-validation/v1.00.27-w4.rktd.
(
(wave . "v1.00.27-w4")
(reviewed-sha . "633ed9fde5fed1cd1dbd6ac0acbf17cdd876a266")
(scope . "scripts/run-tests/overhead.rkt, tests/test-run-tests-overhead-diagnostics.rkt, artifacts/tier-ownership/v1.00.27-w4/local-p90.json, artifacts/tier-ownership/v1.00.27-w4/SHA256SUMS, artifacts/tier-ownership/v1.00.27-w4/slo-evidence-record.md")
(findings
  (review-methodology . "the wave adds read-only telemetry over the three local feedback loops (L0 single test file, L1 area via the direct unit impact set, L2 full unit-fast tier) plus a governance validator; the review recomputed every derived number independently: the p90 per loop was recomputed by linear interpolation at rank 0.9*(n-1) from the raw per-sample elapsed-ms values in local-p90.json, the SLO verdicts were recomputed from the embedded targets, and the checksums were re-verified with sha256sum -c — no hand-written verdict or derived number survives")
  (validator-gates . "--check fails the record for any missing required field (per-loop sample count, machine context, method, per-area grouped/subprocess mode), any nonzero exit-code sample, any sample-count below the required 20, or any mismatch between stored and recomputed p90/verdict values; the validator was exercised against mutated records during development (missing machine-context field, a failed-exit sample) and rejects each case")
  (slo-discipline . "L0 (p90 1883 ms ≤ 5 s) and L1 (p90 4428 ms ≤ 30 s) confirm §8 unchanged; L2 measured p90 234910 ms exceeds the 120 s target and is adjusted to ≤240 s exclusively through the governed evidence record slo-evidence-record.md (sample set, method, reason, owner, review) committed in the same PR; the §8 L0/L1 targets are untouched and no code path reinterprets the fast-gate report's p50/p95 method")
  (sample-integrity . "local-p90.json holds 20 real samples per loop on the current tree, warm and cold start (L2: 1 cold, 19 warm; every L2 sample a fresh racket scripts/run-tests.rkt process), grouped mode per area per W3's governed configuration, machine context recorded per loop; the one L2 warm sample that exited 1 on an in-tier test failure was replaced by a fresh identical-protocol all-pass run rather than silently dropped or edited, and --check independently rejects failed-exit samples so the final set is verifiable from the record alone")
  (mutation-safety . "the telemetry is observation-only: no execute-* check, isolation root, STRICT_TEST_RUNNER contract, blocking gate, or grouped/subprocess decision path was modified; grouped/subprocess decisions still come solely from W3's governed configuration, and the new tests cover the validator's failure modes without touching runner behavior")
  (test-evidence . "focused suites green at reviewed-sha: test-run-tests-overhead-diagnostics 15 success(es) 0 failure(s) 0 error(s) (10 diagnostics + 5 new local-telemetry governance checks), overhead.rkt --check exit 0 with recomputed p90s and verdicts, sha256sum -c clean on both pinned artifacts"))
(concerns . "L2's adjusted ≤240 s ceiling leaves only ~5 s of headroom above the measured 234.9 s p90; the governed record notes that any unit-fast growth re-triggers the review, and the validator recomputes verdicts on every --check so a future breach is surfaced mechanically, not by memory")
(verdict . "approved-for-merge"))
