#hasheq((schema-version . 2)
        (milestone . 895)
        (wave . "W2")
        (issue . 9688)
        (review . "self-review pre-submit")
        (status . "submitted")
        (branch . "campaign/v1.00.30-w2")
        (checks . #hash(("tests/test-ci-eager-compilation.rkt" . "pass")
                        ("tests/test-ci-workflow-diagnostics.rkt" . "pass")
                        ("tests/test-prepared-env-report.rkt" . "pass")
                        ("scripts/check-deps.rkt" . "pass")
                        ("scripts/run-tests.rkt --suite fast" . "pass")
                        ("scripts/metrics.rkt --lint" . "pass")))
        (invariants . #hash(("bug-0065-retained" . #t)
                            ("single-eager-boundary" . #t)
                            ("no-per-file-fallback" . #t)
                            ("future-mtime-purge" . #t)
                            ("membership-unchanged" . #t)))
        (containment-not-recovery . "R1 PASS is containment ONLY; residual pre-W4 233-292s job walls reported in EAGER-COMPILE-CONTAINMENT-v1.00.30.md")
        (note . "independent APPROVED review and cohort gates are coordinator-owned and pending"))
