;; Wave review: v1.00.28 W4 — Production grouped-execution eligibility and parity evidence
;; Record-only companion to gsd-wave-evidence/v1.00.28-w4.rktd
;; and gsd-wave-validation/v1.00.28-w4.rktd.
(
(wave . "v1.00.28-w4")
(reviewed-sha . "d6b6dde6b88dd9db51b292c87806b290e60395de")
(scope . "scripts/run-tests/grouped-eligibility.rkt, tests/test-grouped-eligibility.rkt, tests/test-runner-work-queue.rkt, tests/metadata/classification, artifacts/test-runtime/v1.00.28-w4/parity-matrix.json, artifacts/test-runtime/v1.00.28-w4/group-safe-report.json, artifacts/test-runtime/v1.00.28-w4/SHA256SUMS, docs/reports/GROUPED-PRODUCTION-CHARACTERIZATION-v1.00.28.md")
(findings
  (review-methodology . "the wave adds a private eligibility-decision layer (classification reader, parity-matrix predicates, fail-closed decide-eligibility, group-safe share math) plus a production characterization; the review independently re-derived every decision number: the 25 parity cells in parity-matrix.json were re-checked for completeness (exactly the five modes isolated/grouped/grouped-repeat/grouped-random/grouped-concurrent per GROUP-SAFE file), passing/uniform-counts/order-independent/repeated-stable/no-leaks invariants, group-safe-report.json percentages were recomputed from the classification mass column (5/14 files = 35.71%, 3032/118106 ms = 2.57%), and SHA256SUMS was re-verified with sha256sum -c — every stored derived number reproduces")
  (fail-closed-discipline . "decide-eligibility precedence rollback-switch → unclassified-file → classified-isolated → parity-missing → parity-failed → grouped was traced through the implementation and its contract tests: any unclassified file, any classified-ISOLATED family, any missing or failing parity cell, or the rollback switch yields subprocess; the default execution mode of the runner is untouched (subprocess) and the 5 parity-complete files are NOT activated in this wave, so zero production behavior changes without a later governed activation step carrying inventory-unchanged proof")
  (classification-honesty . "the 9 ISOLATED rows carry per-file reasons (4 zero-parsed-output files that cannot prove parity, 1 declared sandboxed-home mutation, 3 declared process/fs mutations in slow integration, 1 runner-gate structural form) rather than optimistic defaults; the report states the decision-relevant work-mass number (2.57%) is small because ISOLATED slow-integration families dominate cohort mass — the wave does not oversell grouped adoption")
  (mutation-safety . "no execute-* check, isolation root, worker-security contract, scheduler variable, or existing gate semantics modified; grouped-eligibility.rkt is a new leaf module consumed only by the new contract suite and the W4 sidecar; tests/test-runner-work-queue.rkt gains fail-closed/rollback cases without changing existing runner behavior")
  (test-evidence . "focused suites green at reviewed-sha: test-grouped-eligibility 11 success(es) 0 failure(s) 0 error(s), test-runner-work-queue exit 0 incl. the new fail-closed default and rollback-switch cases, test-milestone-gate exit 0 (attempt-1 drift fixed at ca94104c by regenerating the v1.00.27-w0 ownership matrix to include the new test file), sha256sum -c clean on both pinned artifacts"))
(concerns . "the parity matrix stands in measured isolated wall clock for the W0 census median_ms (noted in group-safe-report.json); the 4 zero-parsed-output ISOLATED files remain uncharacterized until they gain a real (module+ test) discovery point — they stay subprocess fail-closed, which is the correct direction; cohort is 14 files, so percentages will move as later cohorts are classified")
(verdict . "approved-for-merge"))
