;; Wave review: v1.00.27 W3 — area-by-area grouped unit-fast expansion with per-area rollback
;; Record-only companion to gsd-wave-evidence/v1.00.27-w3.rktd.
(
(wave . "v1.00.27-w3")
(reviewed-sha . "57b4720f73607b64459dc035e8bb41dc26fa75f6")
(scope . "scripts/run-tests/runner.rkt, scripts/run-tests/profiles.rkt, tests/test-run-tests-in-process-mode.rkt, tests/test-run-tests-profiles.rkt, artifacts/tier-ownership/v1.00.27-w3/grouped-expansion.json, artifacts/tier-ownership/v1.00.27-w3/ci-subprocess.json, artifacts/tier-ownership/v1.00.27-w3/ci-grouped.json, artifacts/tier-ownership/v1.00.27-w3/SHA256SUMS")
(findings
  (review-methodology . "the wave migrated one unit-fast area at a time: for each candidate area the runner executed the same tree once under subprocess mode and once under grouped mode, and the two runs were compared field-by-field for exact equality (test ids, verdicts, order, failure text) before grouped execution was enabled for that area; the ci area passed the comparison exactly and its paired run records are preserved verbatim in ci-subprocess.json / ci-grouped.json with the verdict table and digests in grouped-expansion.json")
  (eligibility-is-explicit . "grouped eligibility is configured per area by name in scripts/run-tests/profiles.rkt (grouped-area-config): an area absent from the config or without paired comparison evidence cannot resolve to grouped, and grouped-config-violation rejects any config entry that marks an area grouped without the corresponding evidence row in grouped-expansion.json")
  (rollback-switch-tested . "the per-area rollback switch (env Q_RUN_TESTS_SUBPROCESS_AREAS, comma-separated area names, honored before the grouped policy lookup) forces the named areas back to subprocess execution while leaving every other area's decision untouched; the in-process-mode suite covers rollback of a grouped area, rollback of an already-subprocess area (reported fallback, not silently re-run), and that other areas' decisions are unchanged")
  (fallbacks-reported . "every area executed under subprocess despite a grouped decision is reported in the runner summary with a named reason via the fallback record (reason 'rollback-switch or 'config); silent degradation is asserted impossible by test-run-tests-in-process-mode's fallback-report checks")
  (mutation-safety . "grouped runs inherit the existing worker-security contracts and isolation roots unchanged; the diff touches no execute-* security check, no isolation root, and no gate semantics; parallel-writer families stay serial per the W0 matrix — no family was moved into grouped without its ownership row permitting it")
  (governance-tests . "test-run-tests-profiles asserts the grouped-expansion artifact exists, parses, carries exact-match verdicts for every grouped-enabled area, and matches the SHA256SUMS digests; test-run-tests-in-process-mode asserts explicit eligibility, evidence-gated enablement, per-area rollback isolation, and named fallback reporting")
  (test-evidence . "focused suites green at reviewed-sha: test-run-tests-in-process-mode 4 success(es) 0 failures, test-run-tests-profiles 9+1 success(es) 0 failures, test-runner-work-queue 11 success(es) 0 failures; sha256sum -c on the wave's SHA256SUMS clean"))
(concerns . "none blocking; only the ci area carries comparison evidence at this SHA, so every other unit-fast area remains subprocess by default until its own paired comparison lands — the artifact's remaining-areas list names them explicitly rather than leaving their status implicit")
(verdict . "approved-for-merge"))
