(kind . "wave-review")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W1")
(reviewed-artifact . "docs/reports/gsd-wave-evidence/v1.00.25-w1.rktd")
(implementation-sha . "63b2aa6f")
(reviewer . "W1 reviewer role (independent review of the delivery evidence record)")
(review-verdict . "pass")
(findings . ((decision-honesty . "decision.md, report.json (decision section, w1-decision-v1) and the evidence record agree: hold for fast-queue, fast-LPT, security-queue; zero shadow attempts are stated plainly and nowhere dressed up as timing evidence")
             (targets . "gate thresholds (p50 ≤ 130.0 s, p95 ≤ 145.0 s) are quoted verbatim from the roadmap text encoded in the tooling; no revision, no reinterpretation")
             (evidence-provenance . "baseline p50 228.5815 / p95 235.9965 over 20 samples matches the captured C0 baseline leg in cohort.json; shadow legs show 0 attempts-recorded, consistent with the W0 placeholder-run-IDs finding re-validated offline")
             (no-sha-dropping . "eligible-sha-count stays 20 on every lane; nothing was excluded to make numbers pass")
             (cohort-not-force-closed . "cohort status remains started because the tooling's own gate rules reject closed status with empty legs; the evidence record names this instead of bypassing validation")
             (lpt-fallback . "the LPT-holds-with-named-reason (missing duration evidence, falls back to FIFO) is recorded in both the tooling output and decision.md")))
(residual-risks . "if GitHub-hosted shadow runs are later scheduled, this decision must be re-evaluated on real paired samples before any W2-W4 activation; the hold does not authorize activation"))
