(kind . "wave-review")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W6")
(reviewed-artifact . "docs/reports/gsd-wave-evidence/v1.00.25-w6.rktd")
(implementation-sha . "56d3f689bfd9e2ea0bbdba6a9557021b5541b2e5")
(branch . "main")
(review-verdict . approve)
(review-confidence . medium)
(findings . ((gate-honesty . "the gate verdict (fail, target unachieved) is directly recomputable from the 20 samples in artifacts/ci-baseline/v1.00.25-c2/report.json: p50 253.5 s and p95 276.0 s against the never-revised roadmap target of p50 <= 115 s / p95 <= 135 s; the record does not soften the miss and names the next lever (shard-count/parallelism tuning of the fast suite) for a separate reviewed decision")
             (mode-distinction . "tests/test-ci-cohort-report.rkt pins the cohort mode vocabulary (post-promotion | paired-shadow) in both cohort.json and report.json, so every reported number names which mode produced it; the C2 record declares paired-shadow #f, promoted defaults, and required-lane provenance, distinguishing it from the C1 paired-shadow cohort")
             (out-of-sample-claim . "the cohort window (2026-09-04 .. 2026-09-06, first eligible SHA 5739881dc53a, run 33867684782) starts after the W2-W4 activations were stable and all 20 SHAs are new relative to C1, so the out-of-sample claim is supported by the recorded run ids")
             (reliability-pins . "the schema requires per-SHA reliability counters (attempts/successes/failures/cancelled/reruns) to be kept without dropping SHAs and requires named reasons for exclusions (8 recorded), so failed, cancelled, and rerun attempts cannot silently vanish from the record")
             (reserved-decision . "the record correctly leaves the next lever unexercised: a timing miss alone implies no queue rollback, and target values are not revised anywhere in the wave artifacts")))
(concerns . ((margin . "the miss is large (p50 more than 2x the target), which suggests the fast-suite critical path is dominated by the slowest test shard; the named lever should be evaluated with fresh cohort measurements in a later reviewed decision rather than assumed")))
(record-only . "this review adds no code and touches no digest input")
