;; Wave review: v1.00.28 W3 — fast-tier architecture review, split business logic from boundary contracts
;; Record-only companion to gsd-wave-evidence/v1.00.28-w3.rktd.
(
(wave . "v1.00.28-w3")
(reviewed-sha . "8de5440ed3ff754e89da032f3e78c0f8edf77647")
(scope . "tests/test-cwd-independence.rkt, tests/test-agent-session-basic.rkt, tests/test-golden-flows.rkt, tests/test-gsd-delivery-verifier.rkt, tests/tier-ownership-matrix.json, artifacts/tier-ownership/v1.00.28-w3/fast-integration-review.json, artifacts/tier-ownership/v1.00.28-w3/inventory-reconciliation.json, artifacts/tier-ownership/v1.00.28-w3/SHA256SUMS")
(findings
  (review-methodology . "the wave enumerated the full @speed fast + @boundary integration inventory from the W0 census (254 rows), ranked it by work mass, and classified every row against the five review questions (business behavior, real boundary, fake adapter, minimal real contract, destination lane); the four §6 candidate families were then split in place: business behavior now runs on deterministic/injectable layers, and only the minimal real-boundary contract cases touch the real resource")
  (classification-is-total . "fast-integration-review.json carries rows = 254 with rows_selected = 254 and a classification object per row covering the five review questions plus owning gates; no row is left unclassified or unnamed (owner-area distribution: core 176, runtime 41, extensions 29, workflows 3, four singleton areas)")
  (splits-keep-the-boundary-real . "each candidate file still executes its real-boundary contract under the required fast gate: test-cwd-independence keeps one real executable/CWD probe canary; test-agent-session-basic keeps filesystem create/resume/recreate on a real store root; test-golden-flows keeps one small real golden path; test-gsd-delivery-verifier keeps the minimum real-Git contract set; the deterministic-fake sides cover the business behavior without touching the real resource")
  (retier-rule-honored . "retiering-is-not-deletion: all 254 rows are retained with destination unchanged because no cheaper faithful adapter is identified before W1 instrumented per-test cost evidence exists; a cross-tier move without destination-gate signoff would violate the hard rule, so the review verdict names the blocker instead of dropping coverage")
  (reconciliation-exact . "inventory-reconciliation.json shows before == after per behavior ID with moves = 0, drops = 0, and 4 in-place reviews; the regenerated ownership matrix (972 rows) matches reality — the drift check is green because no @speed/@boundary metadata changed")
  (governance-tests . "test-milestone-gate.rkt fails closed when a behavior leaves fast without a destination test or without a named required gate, so any future retier landing without its owner is red in CI")
  (test-evidence . "focused suites green at reviewed-sha: test-cwd-independence exit 0, test-agent-session-basic 19 success(es) 0 failures, test-golden-flows exit 0, test-gsd-delivery-verifier 24 success(es) 0 failures, test-milestone-gate exit 0; sha256sum -c on the wave's SHA256SUMS clean"))
(concerns . "none blocking; the retained verdict is explicitly evidence-pending: once W1 lands instrumented per-test cost data, the same 254-row review must be re-run with real cost numbers before any row is retiered — the artifact's per-row classification field records this dependency rather than hiding it")
(verdict . "approved-for-merge"))
