;; Wave review: v1.00.28 W2 — Fixture amplification reduction with pristine-copy experiment
;; Record-only companion to gsd-wave-evidence/v1.00.28-w2.rktd
;; and gsd-wave-validation/v1.00.28-w2.rktd.
(
(wave . "v1.00.28-w2")
(reviewed-sha . "8c003200dc39fe275a2a0dd93862cb03c8f4e958")
(scope . "tests/helpers/pristine-git-fixture.rkt, tests/test-pristine-git-fixture.rkt, tests/test-gsd-delivery-verifier.rkt, tests/test-gsd-campaign-repository.rkt, tests/test-gsd-wave-worktree.rkt, artifacts/test-runtime/v1.00.28-w2/{fixture-census,git-fixture-experiment,stress-evidence}.json + SHA256SUMS, docs/reports/TEST-FIXTURE-AMPLIFICATION-v1.00.28.md, docs/reports/gsd-wave-{evidence,reviews,validation}/v1.00.28-w2.rktd")
(findings
  (review-methodology . "the wave is an experiment-plus-hold wave, so the review checked the three things such a wave must get right: (1) the experiment's internal validity — both arms run through the same shared constructor with the identical sample definition (construct + git rev-parse --verify HEAD first-use assert + cleanup), 2 uncounted warmups and 14 successful samples per arm, interleaved, wall-clocked, and every quoted median in TEST-FIXTURE-AMPLIFICATION-v1.00.28.md traces to git-fixture-experiment.json; (2) the honesty of the activation decision — the gate table's median-improvement row fails in the wrong direction (pristine-copy 143.95 ms vs clone 38.77 ms construct, ~3.7x slower), and the wave correctly does NOT activate: the constructor default stays the legacy clone strategy and the report states the hold rather than quietly keeping the new code path warm; (3) the safety suite's coverage of the risk that motivated the experiment — hardlinks, objects/info/alternates, shared object store, shared mutable refs, inherited hooks, repo-local identity, baseline-immutability under scenario deltas, and concurrent create/destroy are all asserted red-first and pass at 7/7")
  (hold-language . "the report says plainly that the hypothesis is refuted on this machine; it does not spin the 3.7x slowdown as a partial win, does not activate conditionally, and does not leave the default ambiguous — the one-edit rollback (constructor strategy parameter back to clone) is itself contract-tested by the legacy-contract test in the safety suite")
  (amplification-report . "the census numbers in the report match fixture-census.json per family (delivery-verifier 21 repositories with dv-base rebuilt 19x, wave-worktree 4, campaign-repository 0 git / 33 planning trees, new safety suite 14/15); the report declares the branch/commit counters null with the instrumented-counter reason instead of estimating them")
  (evidence-integrity . "sha256sum -c artifacts/test-runtime/v1.00.28-w2/SHA256SUMS verifies all three JSON artifacts from the q root at the reviewed SHA, in the exact path form the wave's Verify command uses (this attempt fixed the manifest from artifact-relative to q-root-relative paths after the prior attempt left it in a form the verify command could not consume)")
  (no-behavior-change . "the three consuming suites report the same counts as before the wave (25/25, 33/33, 10/10) and no production code changed; the whole wave is test-side plus artifacts and reports, so the hold cannot regress runtime behavior")
  (scratch-hygiene . "the prior attempt's tmp/ probes (probe-pristine.rkt and six more) tripped the pre-commit format lint; they were deleted per the BUG-0026 scratch-file contract and lint-format reports 0 errors over 2386 files at the reviewed SHA"))
(concerns . "the 3.7x pristine-copy penalty is a measurement on this machine's filesystem and must not be cited as a universal constant — a future re-run on a different checkout/CI filesystem may justify re-opening the gate, but that requires fresh ≥10-sample evidence, not this report; the pristine baseline stays in the tree as the safety suite's backing store even though the strategy is not the default, which is a deliberate, documented cost; branch/commit-per-construction census counts remain uninstrumented (null), so amplification is quantified at repository granularity only")
(verdict . "approved-for-merge"))
