;; Wave review: v1.00.28 W1 — Real-time wait elimination across unit-fast and fast
;; Record-only companion to gsd-wave-evidence/v1.00.28-w1.rktd
;; and gsd-wave-validation/v1.00.28-w1.rktd.
(
(wave . "v1.00.28-w1")
(reviewed-sha . "8b6f3b20ba4bc8b72bef8905032f987f80055ca1")
(scope . "tests/helpers/deterministic-clock.rkt, tests/test-deterministic-clock.rkt, tests/test-agent-session-basic.rkt, tests/test-auto-retry.rkt, tests/test-retry-iteration.rkt, artifacts/test-runtime/v1.00.28-w1/{wait-audit.json,benchmarks/,SHA256SUMS}, docs/reports/TEST-WAIT-AUDIT-v1.00.28.md, docs/reports/gsd-wave-{evidence,reviews,validation}/v1.00.28-w1.rktd, plus removal of two stray tracked browser-audit test files and three stray benchmark JSONs left by an older campaign")
(findings
  (audit-completeness . "the audit covers all 29 occurrences across 15 files triaged by the W0 census (static-wait-scan.json) plus targeted greps for sleep/sync-timeout/alarm-evt/thread-wait/subprocess-wait/current-seconds/current-milliseconds/retry/backoff/poll/timeout/wait; every occurrence carries a class (A/B/C/D), a named disposition, and an evidence link to remediation commits or to the retained-line justification; the 5 raw sleeps in files left over from the older browser-audit campaign are recorded as purged-residue rows (files deleted on this branch), not silently dropped")
  (class-A-remediation . "the three unit-fast class-A families (test-agent-session-basic R1, test-auto-retry R2, test-retry-iteration R3) now assert requested logical delays, retry counts, ordering, and timeout transitions through the injectable deterministic clock/sleeper seam (tests/helpers/deterministic-clock.rkt) with zero wall-clock waits; the seam has its own self-test suite (tests/test-deterministic-clock.rkt) whose single retained real sleep (R4) is a class-D canary with a named behavioral reason: it proves the helper actually sleeps real time when asked, guarding against a silently-passing no-op sleeper")
  (retained-canaries . "every retained real-clock test has a named behavioral reason recorded in the audit row (unit-fast: only the R4 helper canary; fast: suite-level canaries with reasons in the report); no unjustified real sleep remains in unit-fast")
  (classes-B-C . "no class B (asynchronous synchronization) or class C (process settle) occurrences exist in unit-fast/fast per the census; the audit rows record the negative finding with the grep evidence rather than assuming it")
  (benchmark-evidence . "both remediated families have >=10-sample before/after manifests (test-auto-retry, test-retry-iteration) captured with identical methodology; the purged-residue wave3 family has an explicitly INCOMPARABLE before/after pair because its before state was a purged foreign-campaign file, and no speedup is claimed from it; all six manifests plus the audit JSON and the report are checksummed in artifacts/test-runtime/v1.00.28-w1/SHA256SUMS (sha256sum -c verifies 8/8 OK at the reviewed SHA)")
  (lint-gate . "the wave's red/guard check is implemented as test cases inside tests/test-deterministic-clock.rkt, which run in the default suite forever: wait-audit.json must parse and be self-consistent, every test file carrying a raw sleep must have an audit row with a class and a named disposition, every retained occurrence must carry a named behavioral reason, the summary's unjustified-unit-fast-sleeps count must be zero, the three remediated families must carry zero raw sleeps (a new raw sleep turns the test red), and remediated families must have benchmark manifests")
  (scope-discipline . "no production module was modified (R5 production seams are consumed via fakes); the only non-test code change is the new lint script and its workflow hook"))
(concerns . "the wave3 residue manifests are INCOMPARABLE by design (purged foreign-campaign file, no retained before evidence) — reviewers of the PR must not read the after-only numbers as a speedup; the audit JSON must be re-checksummed if any audit row changes after this point")
(verdict . "approved-for-merge"))
