((wave . "v1.00.29-w10")
 (ticket . "campaign v1.00.29 W10 (milestone #894): rebalance, final cohort, and bake")
 (review-type . "IMPLEMENTER SELF-REVIEW (honest); this wave had no independent review round — findings below are the self-review's own objections and their dispositions")
 (reviewed-shas
   .
   "campaign/v1.00.29-w10 @ bb93281c (implementation) + wave C trio checkpoint; branch point 30713cad (post-W9 origin/main); wave diffs = scripts/run-tests/{shard-plan,cli,runner}.rkt, tests/{test-run-tests-shard-plan,test-run-tests-arg-validation,test-ci-cohort-report}.rkt, tests/fixtures/shard-plan-cohort-seed.json, artifacts/ci-baseline/v1.00.29-final/* (6 files), docs/reports/PROOF-GRAPH-FINAL-v1.00.29.md, docs/reports/gsd-wave-*/v1.00.29-w10.rktd, README.md (metrics)")
 (self-review-findings
   (F1 . "SCOPE: W10's file list does not include cli.rkt/runner.rkt, but the deliverable demands 'a local measurement via a --measure mode'. Disposition: the measure mode is the only honest way to produce per-file durations for the model without CI; implemented as an ADDITIVE third --shard-plan mode (report/active semantics untouched), never wired into required CI, exit-0 measurement pass. The wave contract's 'keep existing subcommands backward compatible' is preserved (validated by the untouched arg-validation pins + new cases).")
   (F2 . "AMBIGUOUS CONTRACT TERM: 'no file predicted to straddle a shard boundary twice' has no prior mechanical definition in the repo. Disposition: operationalized in shard-plan.rkt with a FROZEN definition (weight > mean = straddles once, informational; weight > 2× mean = straddles twice, violation) and shipped inside the artifact's checks_definitions so the definition travels with the evidence. The starvation bound (1.35× mean) is taken verbatim from the wave contract.")
   (F3 . "'THE three retained CI wall times in the cohort seed' is ambiguous (the seed has 24). Disposition: pre-registered the mechanical rule 'three latest pre-W4 merged PRs by merged_at' (9667/9668/9666 → 928/817/832s, mean 859s) because pre-W4 walls are the wall the fast-suite shard plan actually influences; post-W4 walls additionally contain the prepared-env lane and are reported separately (never averaged into the anchor).")
   (F4 . "'LATEST retained v1.00.28-final cohort evidence' has no per-file durations in ci-baseline (only per-SHA walls). Disposition: identified artifacts/test-runtime/v1.00.28-w7/fast-runtime-census.json (q.census.fast-runtime/1, post-remediation census feeding the v1.00.28-final decision) as the latest retained per-file duration evidence; extended load-duration-snapshot ADDITIVELY to map median_ms → duration_seconds; 1180/1186 files covered, 7 substitutions recorded at the p95 default — nothing invented.")
   (F5 . "OBJECTION — is the 1180-record v1.00.28 census still representative of the v1.00.29 inventory? Disposition: partly not (1186 current files, 7 missing covered by the conservative default; inventory deltas disclosed in decision.md §4). The regeneration is therefore a calibrated PREDICTION, not a measurement of the current tree; this is exactly why the rebalance decision keeps 3 shards and does not activate the re-assignment inside the measured cohort window.")
   (F6 . "OBJECTION — test-suite regression introduced mid-wave: tests/test-ci-cohort-report.rkt failed 6 checks (C3 rows flipping to 'unverified') on the wave branch while passing on the base. Disposition: root-caused BEFORE any coercion — the failing fixture (fc-full-guards) built a hasheq with STRING keys, so guard lookups resolve only when cross-module string literals happen to be the same object; base's fresh single-pass compile shared the literals, the wave branch's incremental layout did not. Fixed by making the fixture `hash` (equal?-based, content-addressed) with an explanatory comment; 143/143 green after. The latent fragility lives in the fixture (test-side), not the production gate; noted for future hardening of hash-ref-tolerant callers.")
   (F7 . "OBJECTION — the measured starvation check flags a VIOLATION on degenerate inputs (3 files / 3 shards → worst shard 1.96× mean). Disposition: correct behavior, kept: the check is mechanical and the degenerate case is a real starvation shape; documented via the measure-mode demo output rather than special-cased away.")
   (F8 . "VERDICT DISCIPLINE: §7.2 PR CI rows fail badly and the W4 topology increase is the dominant cause. Disposition: reported as progress-not-achieved with attribution (TOPOLOGY DISCLOSURE in decision.md + PROOF-GRAPH-FINAL + this trio); no target revised; the single draft verdict is PARTIAL — SAFE REDUCTION DELIVERED, consistent with bundle §13 because all 14 safety-gate rows hold (row 12's v1.00.29-window ratio explicitly pending-coordinator-fill with carried 100% baseline and test-verified fail-closed mismatch behavior) and measurable safe reductions were delivered.")
   (F9 . "OPERATIONAL NOTE (execution environment, not code): the sandbox cannot chdir into the worktree and caps invocations at ten minutes, so canonical commands ran through an untracked job-local runner with the worktree as cwd (same pattern as W9's record), and the frozen fast gate ran through the runner's own sharding (--shard-total 8 × --shard-index 0..7, CI's mechanism). Two mid-wave operational mistakes (a stray duplicate background run; a log truncation) were made and cleaned up; they affected NO committed artifact and NO measurement quoted here — the final chain was re-run clean on the final head after the cleanup."))
 (disposition-of-findings
   .
   "F1-F5,F8,F9: documented as stated (no code change needed beyond what shipped). F6: fixed in bb93281c with the hasheq→hash fixture change. F7: kept. None of the findings blocks the deliverables; no finding was silenced."))
