;; Wave review: v1.00.27 W6 — Series bake and v1.00.27 release
;; Record-only companion to gsd-wave-evidence/v1.00.27-w6.rktd
;; and gsd-wave-validation/v1.00.27-w6.rktd.
(
(wave . "v1.00.27-w6")
(reviewed-sha . "e453da533e1f72aec5eb47d2e0b866361a29e1d7")
(scope . "util/version.rkt, CHANGELOG.md, README.md, docs/reports/SERIES-COMPLETION-v1.00.23-v1.00.27.md, artifacts/ci-baseline/v1.00.27-c3/SHA256SUMS, docs/reports/gsd-wave-{evidence,reviews,validation}/v1.00.27-w6.rktd, plus test-side version-dynamic sync (12 test/fixture files) so no current-version test expectation hardcodes the frozen release string")
(findings
  (review-methodology . "the wave is a release/bake wave, so the review checked the three things release waves must get right: (1) release language never exceeds the C3 artifacts — every claim sentence in CHANGELOG.md and the series record was traced to either a checksummed C3 artifact or a linked evidence report; (2) the single-source-of-truth version propagation is complete — q-version '1.00.27' in util/version.rkt is the only literal, and grep found the remaining '1.00.27' strings only in historical comments, in runner-side paths to the actually-committed v1.00.27-w* artifact directories, and in the frozen v1.00.27 tag/release references, all of which are correct as literals; (3) the series record is complete per roadmap §11 — five milestones each with tag + merge SHA, queue/LPT/CI-topology states with one-command rollback commands, re-tiering evidence, removed-overlap equivalence evidence, and the final verdict")
  (claim-language . "the 2x claim is NOT published and must not be: C3's tool-computed verdict missed six of seven fixed §8 rows (fast p50 267.5 s / p95 285.95 s vs 115/135 s targets; PR CI p50 1043.5 s / p95 1175.65 s vs 588/735 s; security-runner p50 685.5 s and workflows-runner p50 695.5 s vs 700 s), so both the CHANGELOG and the series record state 'target not achieved' per missed row with the observed numbers and link the preserved, checksummed C3 evidence; the one achieved row (prepared-env verified restores 100.0% ≥ 95%) is reported with its artifact link; this matches the wave's release-language rule mechanically")
  (record-first . "the series-completion record was checkpointed (9dfce821) before the release entry (933263bf), satisfying the wave's 'write the series-completion record first' ordering; the record binds C3 by digest (SHA256SUMS) rather than by trust")
  (version-dynamic-sync . "the review verified the W0-established discipline end-to-end: test-side current-version expectations now read (q-version) from util/version.rkt (12 files synced at e453da53), so the frozen 1.00.27 string survives only where it names real frozen artifacts/tags; ; version consistency is covered by metrics --lint and release-dry-run (6/6), both green")
  (metrics-sync . "README's metrics table was re-synced after the test-side edits changed the test-line total (264260 → 264294) and metrics --lint reports all 5 static metrics matching; release-notes lint PASSes at the reviewed SHA")
  (sha-integrity . "cd artifacts/ci-baseline/v1.00.27-c3 && sha256sum -c SHA256SUMS verifies all five pinned C3 artifacts at the reviewed SHA, so the published verdict and every number quoted in the release language are digest-bound"))
(concerns . "the release publishes an honestly-not-achieved final claim, which is the correct outcome for a fixed-target series but means the six latency rows remain open future work; the release must not be edited at publish time to soften or upgrade the per-row language — the coordinator-owned tag/release flow should reuse the reviewed CHANGELOG verbatim")
(verdict . "approved-for-merge"))
