(kind . "wave-review")
(schema-version . 2)
(campaign . "v1.00.26")
(wave . "W6")
(reviewed-artifact . "docs/reports/gsd-wave-evidence/v1.00.26-w6.rktd")
(implementation-sha . "aa7ec8e2fbdf99b5af67af314078935f93ac089f")
(branch . "campaign/v1.00.26-w6")
(review-verdict . approve)
(review-confidence . high)
(review
  (decision-honesty . "the cohort records a negative result against the wave's own target: pr-elapsed p50 = 935 s against a 588 s target and p95 = 957.5 s against a 735 s target on all 20 unique merged PR SHAs, with targets unrevised and the verdict written as target-unachieved plus a named next lever — the roadmap rule is applied exactly as written and no green-washing path was taken")
  (gate-scope . "the gate measures first required-check start to last required-check completion (mergeable-PR wall time), not queue wait alone, per the TDD clause; queue telemetry stays a separate visible field so the queue contribution is auditable without double-counting it into the gate")
  (cohort-integrity . "exactly 20 unique PR head SHAs are required by the tooling contract and present in cohort.json; duplicates and re-runs are recorded rather than dropped; exclusion-count is 0 and failure/cancellation counts live in the manifest, so no silent truncation or cherry-picking could have flattered the result — and the result is a miss anyway, which is the strongest honesty signal available")
  (tdd-shape . "the pr-elapsed pins were written failing-first before the mode existed and then went green; the percentiles use linear interpolation as pinned; the report --check regenerates and compares byte-stable statistics")
  (artifact-binding . "SHA256SUMS binds cohort.json, report.json, report.md, and decision.md byte-for-byte and verifies OK standalone; the evidence record is bound to the non-artifact content digest over the two changed source files at implementation-sha, reproducing with the recorded command")
  (scope-discipline . "the wave touches only the two declared tooling surfaces plus record-only artifacts; no workflow or lane behavior changed on main-ancestry paths, so the topology that produced the cohort is exactly the integrated W1-W5 state")
  (attempt-history . "one continuous attempt is recorded honestly with no provider stops and no rework"))
(concerns
  (single-window-confound . "all 20 PRs accumulated inside one calendar window under the integrated topology; the observed miss is real for this window but the next lever (warm-cache at first-check start) should be re-measured with cohorts spread across days before any v1.00.27 target is set from these numbers")
  (post-merge-steps-open . "the squash-merge to protected main and post-merge gate confirmation are intentionally outside this record's claims; they are coordinator-owned and must land while the wave issue is still open"))
(record-only . "this review adds no code and touches no digest input")
