#hasheq(
 (schema-version . 1)
 (status . frozen)
 (authority . ".planning/Racket-Wartbarkeits-und-Architekturanalyse-q-Coding-Agent.md")
 (baseline-sha . "274de500e86666b54c10bacda09e99d006bd5501")
 (freeze-candidate-sha . "d18c6898ded4086aa534316d167de184fdb6ec5a")
 (w4-candidate-sha . "93045f4d1e6c9396ec94312c7bbc93958c41847a")
 (series-wave-count . 32)
 (follow-up-wave-count . 27)
 (amendment-required? . #t)
 (scope-stop? . #t)
 (findings .
  (#hasheq((id . MA-01) (status . closed) (owner . "Architecture governance")
           (target-waves . ("v0.99.87/W0" "v0.99.87/W4"))
           (evidence . ("docs/reports/ARCHITECTURE-BASELINE-v0.99.87.md" "ca84d20a"))
           (closure-proof . "Deterministic raw/Markdown baseline, metric reconciliation, independent review, and v0.99.87 release record")
           (release . "v0.99.87"))
   #hasheq((id . MA-02) (status . partial) (owner . "Extensions boundary")
           (target-waves . ("v0.99.87/W1" "v0.99.88/W2" "v0.99.88/W3" "v0.99.88/W4"))
           (evidence . ("docs/architecture/dependency-policy.rktd" "tests/test-extension-exception-fitness.rkt" "7b62932a"))
           (closure-proof . "Each dated exception receives a pair-precise remove-or-waive decision; no stale, expired, or blanket exception")
           (release . "v0.99.88"))
   #hasheq((id . MA-03) (status . partial) (owner . "Extensions / runtime provider service")
           (target-waves . ("v0.99.88/W0" "v0.99.88/W1" "v0.99.88/W2"))
           (evidence . ("docs/reports/ARCHITECTURE-BASELINE-v0.99.87.md" "docs/architecture/dependency-policy.rktd"))
           (closure-proof . "Neutral registry service injected; Runtime import and exception removed; dynamic-load and differential tests pass")
           (release . "v0.99.88"))
   #hasheq((id . MA-04) (status . open) (owner . "Extensions package lifecycle")
           (target-waves . ("v0.99.88/W3"))
           (evidence . ("docs/architecture/dependency-policy.rktd" "7b62932a"))
           (closure-proof . "Package lifecycle capability/adapter removes coupling or a narrow evidence-backed waiver is approved with package/security gates")
           (release . "v0.99.88"))
   #hasheq((id . MA-05) (status . open) (owner . "TUI / Extensions bridges")
           (target-waves . ("v0.99.88/W4"))
           (evidence . ("docs/architecture/dependency-policy.rktd" "tests/test-extension-exception-fitness.rkt"))
           (closure-proof . "Each of dialog-api, ui-surface, and widget-lifecycle is removed or receives an evidence-backed permanent pair waiver")
           (release . "v0.99.88"))
   #hasheq((id . MA-06) (status . partial) (owner . "GSD domain architecture")
           (target-waves . ("v0.99.89/W0-W4" "v0.99.90/W0-W5"))
           (evidence . ("docs/reports/GSD-RESPONSIBILITY-EFFECT-INVENTORY-v0.99.87.md" "extensions/gsd/responsibility-inventory.rkt" "3bf783c2"))
           (closure-proof . "Golden traces plus I/O-free transition/projection/parsing cores, explicit effect ports, facade compatibility, and independent review")
           (release . "v0.99.90 (terminal; intermediate v0.99.89)"))
   #hasheq((id . MA-07) (status . open) (owner . "GSD projections and persistence")
           (target-waves . ("v0.99.89/W0" "v0.99.89/W2" "v0.99.90/W1" "v0.99.90/W2" "v0.99.90/W5"))
           (evidence . ("docs/reports/GSD-RESPONSIBILITY-EFFECT-INVENTORY-v0.99.87.md" ".planning drift history"))
           (closure-proof . "Pure projection plan and logically atomic application survive crash injection without invented DONE or skipped waves")
           (release . "v0.99.90"))
   #hasheq((id . MA-08) (status . open) (owner . "GSD execution adapters")
           (target-waves . ("v0.99.90/W0-W5"))
           (evidence . ("docs/reports/GSD-RESPONSIBILITY-EFFECT-INVENTORY-v0.99.87.md" "3bf783c2"))
           (closure-proof . "Filesystem/git/process/event effects use domain ports and deterministic fakes; retries are idempotent and terminal outcomes explicit")
           (release . "v0.99.90"))
   #hasheq((id . MA-09) (status . partial) (owner . "LLM provider adapters")
           (target-waves . ("v0.99.87/W3" "v0.99.91/W0" "v0.99.91/W1-B" "v0.99.91/W2-B" "v0.99.91/W3-B" "v0.99.91/W4-B"))
           (evidence . ("docs/reports/PROVIDER-DUPLICATION-PARITY-MATRIX-v0.99.87.md" "tests/test-provider-parity-matrix.rkt" "d18c6898"))
           (closure-proof . "Path B contract matrix, differential fixtures, ownership guards, capability parity, and terminal no-abstraction decision")
           (release . "v0.99.91"))
   #hasheq((id . MA-10) (status . open) (owner . "Runtime session lifecycle")
           (target-waves . ("v0.99.93/W0-W5"))
           (evidence . ("docs/reports/ARCHITECTURE-BASELINE-v0.99.87.md" ".planning/REASSessment-maintainability-post-refactoring.md"))
           (closure-proof . "Trace-equivalent pure extraction measurably improves locality/testability, or evidence-backed rejection closes the candidate")
           (release . "v0.99.93"))
   #hasheq((id . MA-11) (status . guarded) (owner . "Agent iteration boundary")
           (target-waves . ("v0.99.87/W0" "v0.99.93/W4" "v0.99.93/W5"))
           (evidence . ("274de500" "tests/test-arch-fitness.rkt" ".planning/REPORT-agent-iteration-working-set-boundary-cleanup.md"))
           (closure-proof . "Zero agent/iteration to Runtime implementation imports remains green through final series release")
           (release . "v0.99.87 closure baseline; guarded through v0.99.93"))
   #hasheq((id . MA-12) (status . guarded) (owner . "Runtime session state ownership")
           (target-waves . ("v0.99.87/W0" "v0.99.93/W2" "v0.99.93/W4" "v0.99.93/W5"))
           (evidence . ("0bbed34c" "tests/test-arch-parameters.rkt" "tests/test-session-owned-cross-turn-state.rkt"))
           (closure-proof . "Parameter inventory and session-ownership gates prove no hidden cross-turn side channel through final series release")
           (release . "v0.99.87 closure baseline; guarded through v0.99.93"))))
 (milestones .
  (#hasheq((id . v0.99.88) (title . "Extension Host/Runtime Service Boundary") (approved-path . n/a)
           (github-milestone . 875) (github-issues . (9221 9222 9223 9224 9225))
           (broad-gates . (W2 W4))
           (waves .
            (#hasheq((id . W0) (title . "Characterization and re-baselining") (goal . "Characterize extension context, provider registry consumers, lifecycle, dynamic loading, and failure behavior without production changes") (gate . "Focused extension/provider-registry/GSD plus Fast") (acceptance . "Closed session-type claim reverified and all remaining registry consumers classified"))
             #hasheq((id . W1) (title . "Neutral Extension Host Service Protocol") (goal . "Define minimal capability-oriented registry operations and runtime adapter while preserving ctx facade") (gate . "Contract, registry, dynamic-require, Arch, Fast") (acceptance . "Host protocol is narrower than concrete runtime surface and compatibility holds"))
             #hasheq((id . W2) (title . "Isolate Provider Registry Service") (goal . "Remove direct runtime provider-registry import from extensions/context.rkt") (gate . "Arch plus Broad and negative exception probe") (acceptance . "Runtime import and exception removed with differential behavior preserved"))
             #hasheq((id . W3) (title . "Isolate ext-package-manager") (goal . "Move package lifecycle access behind wiring/runtime adapter or host capability") (gate . "Package focused, Security, Arch, Fast") (acceptance . "No package install/filesystem logic moved into util and coupling is removed or narrowly waived"))
             #hasheq((id . W4) (title . "Decide TUI extension exceptions and release") (goal . "Decide three TUI bridges individually and release") (gate . "Broad, Arch, Security, Smoke, Release, independent review") (acceptance . "All five old exceptions closed or newly evidence-decided; none expired")))))
   #hasheq((id . v0.99.89) (title . "GSD Pure Domain Decomposition") (approved-path . n/a)
           (github-milestone . 876) (github-issues . (9226 9227 9228 9229 9230))
           (broad-gates . (W2 W4))
           (waves .
            (#hasheq((id . W0) (title . "Golden Workflow Traces") (goal . "Pin plan/go/success/failure/interruption/retry/replan/resume/close semantics and projections") (gate . "GSD fast/workflow plus Fast") (acceptance . "Deterministic semantic traces cover commands, state, records, projections, and event order"))
             #hasheq((id . W1) (title . "Pure Transition Kernel") (goal . "Extract pure transitions, preconditions, and terminal states") (gate . "Pure-kernel, Arch, Fast") (acceptance . "Kernel has no filesystem, GitHub, runtime, or event-bus imports and facade delegates"))
             #hasheq((id . W2) (title . "Plan/State Projection Kernel") (goal . "Compute complete projection plans purely and apply through an atomic effect shell") (gate . "GSD governance/workflow plus Broad") (acceptance . "Before/after projections remain equivalent and crash probe cannot leave stale partial projections"))
             #hasheq((id . W3) (title . "Command Parsing and Intent Boundary") (goal . "Separate I/O-free parser intent from executor while preserving /go N assertion semantics") (gate . "Parser fitness, command tests, Fast") (acceptance . "Corpus and malformed inputs preserve facade behavior with no skip semantics"))
             #hasheq((id . W4) (title . "Facade Thinning and Release") (goal . "Reduce GSD facades to composition/re-export without public API breakage") (gate . "Broad, Arch, Workflow, Smoke, Release, review") (acceptance . "Pure domains have no I/O imports and Golden Traces are equivalent")))))
   #hasheq((id . v0.99.90) (title . "GSD Execution, Persistence and Campaign Reliability Isolation") (approved-path . n/a)
           (github-milestone . 877) (github-issues . (9231 9232 9233 9234 9235 9236))
           (broad-gates . (W2 W5))
           (waves .
            (#hasheq((id . W0) (title . "Port Inventory and Composition Root") (goal . "Inventory external effects and define small domain ports plus one composition root") (gate . "DI/contracts plus Fast") (acceptance . "At most one cohesive port per external domain with real fakes"))
             #hasheq((id . W1) (title . "Campaign Repository Boundary") (goal . "Encapsulate campaign persistence and migration fail-closed") (gate . "Persistence, Security, Fast") (acceptance . "Schema/fencing/plan/attempt checks and backward-compatible fixtures pass"))
             #hasheq((id . W2) (title . "Atomic Projection Transaction") (goal . "Make campaign record and human projections one logical atomic operation") (gate . "Broad, Governance, failure injection") (acceptance . "Crash at every write recovers idempotently without invented DONE or skipped wave"))
             #hasheq((id . W3) (title . "Wave Executor Isolation") (goal . "Put tool/subagent execution behind explicit outcome executor port") (gate . "Wave executor/orchestrator plus Fast") (acceptance . "Cancellation, timeout, interrupt, pending-tool stop, and exactly-once completion are deterministic"))
             #hasheq((id . W4) (title . "GitHub/Release Side-Effect Adapter") (goal . "Model external board/issue/PR/release effects as idempotent correlated commands") (gate . "Adapter contracts, Security, Workflow, Fast") (acceptance . "Retries create no duplicate effect; dry-run, SHA assertions, and redaction hold"))
             #hasheq((id . W5) (title . "End-to-End Recovery and Release") (goal . "Exercise campaigns across every terminal/restart/crash transition") (gate . "Broad, Arch, Security, Workflow, Smoke, Release, review") (acceptance . "Campaign truth equals projections after every interruption; no duplicate external effect; Golden Traces green")))))
   #hasheq((id . v0.99.91) (title . "Provider Contract and Test Hardening") (approved-path . path-b)
           (github-milestone . 878) (github-issues . (9237 9238 9239 9240 9241))
           (path-rationale . "Path A rejected: fewer than two semantically identical primitives have repeated co-change evidence; only C9 has one notable pair and C9 is blocked by G1")
           (broad-gates . (W2-B W4-B))
           (waves .
            (#hasheq((id . W0) (title . "Provider Contract Golden Matrix") (goal . "Compare equivalent scenarios across four providers with explicit supported/unsupported capability states") (gate . "Provider tests plus Fast") (acceptance . "Normalized chunk/error/telemetry contract matrix is complete without artificial equality"))
             #hasheq((id . W1-B) (title . "Adapter Contract Completion") (goal . "Complete provider-specific contract cases without shared production abstraction") (gate . "Provider contracts plus Fast") (acceptance . "Every provider has explicit expectations for every W0 scenario"))
             #hasheq((id . W2-B) (title . "Differential Stream/Error Fixtures") (goal . "Version redacted provider-specific byte/JSON fixtures for framing, tools, usage, malformed input, and timeout phases") (gate . "Broad plus Security") (acceptance . "Fixture matrix is complete, deterministic, redacted, and versioned"))
             #hasheq((id . W3-B) (title . "Provider Change-Locality Guards") (goal . "Enforce provider protocol parser ownership and neutral generic streaming modules") (gate . "Positive/negative probes, Arch, Fast") (acceptance . "Provider-specific logic cannot leak into shared modules and shared modules cannot absorb protocol details"))
             #hasheq((id . W4-B) (title . "Hardening Reassessment and Release") (goal . "Reassess coverage, defect localization, and change amplification and record terminal no-abstraction decision") (gate . "Broad, Arch, Security, Provider Smoke, Release, review") (acceptance . "Complete contracts, no capability regression, no unsupported base abstraction, terminal MA-09 decision")))))
   #hasheq((id . v0.99.93) (title . "Session Lifecycle Thinning, Reassessment and Series Closure") (approved-path . n/a)
           (github-milestone . 879) (github-issues . (9242 9243 9244 9245 9246 9247))
           (broad-gates . (W2 W5))
           (waves .
            (#hasheq((id . W0) (title . "Lifecycle Trace and Responsibility Map") (goal . "Trace normal/error/cancel/close/retry/compaction paths and classify responsibilities without production change") (gate . "Characterization plus Fast") (acceptance . "Complete event/effect/order map covers all exceptional exits"))
             #hasheq((id . W1) (title . "Pure Prompt Preparation Extraction") (goal . "Extract only pure input/config to preparation-plan transformations") (gate . "Session lifecycle/prompt, Arch, Fast") (acceptance . "Effect order and observable behavior remain unchanged"))
             #hasheq((id . W2) (title . "Context-Build Request/Result Boundary") (goal . "Introduce explicit context-build request/result while preserving runtime and session ownership") (gate . "Broad, rollback, session ownership, context assembly") (acceptance . "Context Assembly stays runtime-owned and cross-turn state stays session-owned"))
             #hasheq((id . W3) (title . "Orchestration Surface Reduction") (goal . "Move only coherent private helpers and optimize change locality rather than LOC") (gate . "Lifecycle, agent-session, iteration DI, Fast") (acceptance . "Composition root stays explicit and locality/test amplification measurably improve"))
             #hasheq((id . W4) (title . "Repository-wide Maintainability Reassessment") (goal . "Repeat baseline and classify findings CLOSED/PARTIAL/OPEN/REJECTED") (gate . "Document/architecture review plus Fast") (acceptance . "Every finding has current reproducible evidence and terminal or follow-up decision"))
             #hasheq((id . W5) (title . "Series Closure and Release") (goal . "Complete traceability, synchronize projections, and publish final series release") (gate . "Broad, Arch, Security, Workflow, Smoke, Release, Manifest/Bundle, Main CI, review") (acceptance . "No open Critical/High without follow-up; zero stale tracking; release artifacts match merge SHA/tag"))))))))
