#hasheq(
 (schema-version . 1)
 (milestone . v0.99.92)
 (wave . W3)
 (baseline . "e13a48e62f105b938f1aef2b44954a395212c092")
 (scope . orchestration-surface-reduction)
 (production-change . #f)
 (decision . rejection)
 (session-lifecycle-metrics .
  #hasheq((loc . 566)
          (provides . 11)
          (fan-in . 9)
          (fan-out . 38)
          (changed-commits . 14)
          (hotspot-score . 7924)
          (co-change
           . (#hasheq((count . 5) (other . agent/iteration/main-loop.rkt))
              #hasheq((count . 5) (other . tests/test-arch-fitness.rkt))
              #hasheq((count . 4) (other . agent/iteration/loop-config.rkt))
              #hasheq((count . 4) (other . tests/helpers/iteration-loop.rkt))
              #hasheq((count . 4) (other . tests/test-agent-iteration-di.rkt))))))
 (candidates .
  (#hasheq((id . busy-error-construction)
           (verdict . reject)
           (lines . 14)
           (params . 1)
           (unique-imports . 0)
           (rationale . "One-parameter raise path of the claim primitive; no coherent module; pre-dynamic-wind ownership boundary (W0-F1).")
           (anchor . "runtime/session/session-lifecycle.rkt:exn:fail:session:busy"))
   #hasheq((id . input-hook-handling)
           (verdict . reject)
           (lines . 14)
           (params . 4)
           (unique-imports . 1)
           (rationale . "Control-flow early return inside the outer dynamic-wind; caller-owned hook/event publication per W0 report.")
           (anchor . "runtime/session/session-lifecycle.rkt:maybe-dispatch-hooks ext-reg 'input"))
   #hasheq((id . rollback-prompt-scope)
           (verdict . defer-to-w4)
           (lines . 27)
           (params . 2)
           (unique-imports . 2)
           (rationale . "Only structurally coherent candidate; requires coordinated oracle regeneration and is in the caller-retained save-back set; W4 #9246 decides.")
           (anchor . "runtime/session/session-prompt-scope.rkt:(define (call-with-session-prompt-scope"))
   #hasheq((id . acknowledgement-tracer)
           (verdict . reject)
           (lines . 16)
           (params . 5)
           (unique-imports . 0)
           (rationale . "One third of the terminal-identity decision (W0-F2); fragmentation without fan-out gain. Renamed terminal-tracer under #9277 canonical terminal; rejection stands.")
           (anchor . "runtime/session/session-lifecycle.rkt:define terminal-tracer"))
   #hasheq((id . cleanup-turn-completed)
           (verdict . reject)
           (lines . 17)
           (params . 2)
           (unique-imports . 0)
           (rationale . "Order-critical safety-net terminal glued to the box protocol; no fan-out gain. Safety-net removed under #9277; canonical producer now unconditional. Rejection stands.")
           (anchor . "runtime/session/session-lifecycle.rkt:(make-event \"turn.completed\""))
   #hasheq((id . emergency-persist)
           (verdict . reject)
           (lines . 9)
           (params . 1)
           (unique-imports . 0)
           (rationale . "One-parameter guarded call to an already-extracted primitive (ensure-persisted!).")
           (anchor . "runtime/session/session-lifecycle.rkt:emergency persist failed"))))
 (terminal-dispositions .
  (#hasheq((id . W3-F2)
           (version . v0.99.93)
           (issue . 9281)
           (disposition . extracted)
           (anchor . "runtime/session/session-prompt-scope.rkt:(define (call-with-session-prompt-scope")
           (evidence . "tests/test-session-prompt-scope.rkt:prompt scope"))))
 (existing-primitives .
  (#hasheq((capability . prompt-compaction-claims) (module . runtime/session/session-mutation.rkt))
   #hasheq((capability . interruption-turn-ownership) (module . runtime/session/session-interruption.rkt))
   #hasheq((capability . persistence) (module . runtime/session/session-persistence.rkt))))
 (findings .
  (#hasheq((id . W3-F1) (severity . low) (owner . runtime-session) (follow-up . "W4 #9246 terminal decision") (summary . "Remaining session-lifecycle complexity is orchestration glue by design; six inline blocks share nearly all imports with the four provided functions, so extraction would add module requires without reducing fan-out (38)."))
   #hasheq((id . W3-F2) (severity . low) (owner . runtime-session) (follow-up . "W4 #9246 terminal decision; implemented by v0.99.93 #9281") (summary . "W3 deferred the coherent rollback prompt-scope wrapper; terminal follow-up #9281 later extracted it with save-back timing preserved.")))))
