#hasheq(
 (schema-version . 1)
 (release . "v0.99.91")
 (finding . MA-09)
 (status . closed)
 (approved-path . path-b)
 (decision . no-shared-production-abstraction)
 (reopen-policy . "Separate dated amendment with two new semantically-identical primitive co-change proofs")
 (forbidden . (provider-base shared-request-parser shared-event-parser protocol-template-flags artificial-provider-equality))
 (entries .
  (#hasheq((id . C1) (disposition . shared-primitive) (evidence . ("tests/test-provider-parity-matrix.rkt:P1" "llm/http-helpers.rkt")))
   #hasheq((id . C2) (disposition . shared-primitive) (evidence . ("tests/test-provider-parity-matrix.rkt:P2" "tests/test-provider-differential-fixtures.rkt")))
   #hasheq((id . C3) (disposition . shared-primitive) (evidence . ("llm/stream.rkt:close-port-after-stream" "tests/test-stream.rkt:close-port-after-stream")))
   #hasheq((id . C4) (disposition . shared-primitive) (evidence . ("tests/test-provider-parity-matrix.rkt:P6" "llm/provider-errors.rkt")))
   #hasheq((id . C5) (disposition . shared-primitive) (evidence . ("tests/test-provider-parity-matrix.rkt:P6" "llm/http-helpers.rkt")))
   #hasheq((id . C6) (disposition . shared-primitive) (evidence . ("tests/test-provider-parity-matrix.rkt:P5" "llm/http-helpers.rkt:translate-stop-reason")))
   #hasheq((id . C7) (disposition . shared-primitive) (evidence . ("tests/test-stream.rkt:accumulate-tool-call-deltas" "llm/stream.rkt:accumulate-tool-call-deltas")))
   #hasheq((id . C8) (disposition . shared-primitive) (evidence . ("tests/test-provider-differential-fixtures.rkt:timeout" "llm/stream.rkt")))
   #hasheq((id . C9) (disposition . retained-local) (evidence . ("tests/test-provider-hardening-terminal-decision.rkt:W4-B4" "docs/reports/PROVIDER-HARDENING-REASSESSMENT-v0.99.91.md:G1")))
   #hasheq((id . C10) (disposition . retained-local) (evidence . ("tests/test-provider-parity-matrix.rkt:P3")))
   #hasheq((id . C11) (disposition . retained-local) (evidence . ("tests/test-provider-hardening-terminal-decision.rkt:W4-B6")))
   #hasheq((id . C12) (disposition . retained-local) (evidence . ("tests/test-provider-parity-matrix.rkt:P6" "llm/azure-openai.rkt:check-azure-status!")))
   #hasheq((id . C13) (disposition . retained-local) (evidence . ("tests/test-provider-hardening-terminal-decision.rkt:W4-B6")))
   #hasheq((id . C14) (disposition . retained-local) (evidence . ("llm/anthropic-helpers.rkt:anthropic-translate-tool" "llm/gemini.rkt:gemini-translate-tool")))
   #hasheq((id . C15) (disposition . retained-local) (evidence . ("tests/test-provider-contract-golden-matrix.rkt:usage" "tests/test-provider-adapter-contract-completion.rkt")))
   #hasheq((id . C16) (disposition . provider-protocol) (evidence . ("tests/test-provider-contract-golden-matrix.rkt" "tests/test-provider-tool-transport.rkt")))
   #hasheq((id . C17) (disposition . provider-protocol) (evidence . ("tests/test-provider-contract-golden-matrix.rkt" "tests/test-provider-differential-fixtures.rkt")))
   #hasheq((id . C18) (disposition . provider-protocol) (evidence . ("tests/test-provider-hardening-terminal-decision.rkt:W4-B3")))
   #hasheq((id . C19) (disposition . provider-protocol) (evidence . ("tests/test-openai-compatible.rkt:openai-normalize-tool")))
   #hasheq((id . C20) (disposition . provider-protocol) (evidence . ("tests/test-gemini.rkt:tool-id")))
   #hasheq((id . C21) (disposition . provider-protocol) (evidence . ("tests/test-anthropic-helpers.rkt:openai-block->anthropic" "tests/test-browser-audit-w4-v0983.rkt:Gemini converts OpenAI image_url")))
   #hasheq((id . C22) (disposition . intentional-duplication) (evidence . ("tests/test-provider-hardening-terminal-decision.rkt:W4-B6" "llm/adapters/eager-stream.rkt")))
   #hasheq((id . C23) (disposition . intentional-duplication) (evidence . ("tests/test-sse-shared-azure.rkt:reasoning_content null" "tests/test-provider-parity-matrix.rkt:P7")))
   #hasheq((id . G1) (disposition . documented-asymmetry) (evidence . ("tests/test-provider-hardening-terminal-decision.rkt:W4-B4")))
   #hasheq((id . G2) (disposition . documented-asymmetry) (evidence . ("tests/test-provider-hardening-terminal-decision.rkt:W4-B5" "llm/openai-compatible.rkt:resolve-request-network-policy-for-model")))
   #hasheq((id . G3) (disposition . documented-asymmetry) (evidence . ("tests/test-provider-hardening-terminal-decision.rkt:W4-B5" "llm/openai-compatible.rkt:openai-wrap-stream-error"))))))
