#hasheq(
 (schema-version . 1)
 (milestone . v0.99.92)
 (wave . W0)
 (baseline . "a4b85569ff0dbe7971c3fec12babdb3fccbdd329")
 (scope . characterization-only)
 (production-change . #f)
 (responsibility-taxonomy . (orchestration pure-preparation persistence eventing fsm wiring))
 (units .
  (#hasheq((id . run-prompt!)
           (owner . "runtime/session/session-lifecycle.rkt:define (run-prompt!")
           (responsibilities . (orchestration eventing fsm))
           (consumers . (sdk tui goal-runner agent-session-facade)))
   #hasheq((id . run-prompt-internal)
           (owner . "runtime/session/session-lifecycle.rkt:define (run-prompt-internal")
           (responsibilities . (orchestration persistence eventing))
           (consumers . (run-prompt!)))
   #hasheq((id . build-session-context-for-prompt)
           (owner . "runtime/session/session-lifecycle.rkt:define (build-session-context-for-prompt")
           (responsibilities . (pure-preparation persistence orchestration))
           (consumers . (run-prompt-internal)))
   #hasheq((id . dispatch-iteration)
           (owner . "runtime/session/session-lifecycle.rkt:define (dispatch-iteration")
           (responsibilities . (orchestration eventing wiring))
           (consumers . (run-prompt-internal)))
   #hasheq((id . run-iteration-loop/v2)
           (owner . "agent/iteration/main-loop.rkt:define (run-iteration-loop/v2")
           (responsibilities . (orchestration fsm))
           (consumers . (dispatch-iteration)))
   #hasheq((id . close-session!)
           (owner . "runtime/agent-session.rkt:define (close-session!")
           (responsibilities . (orchestration persistence eventing fsm wiring))
           (consumers . (sdk tui gui runtime)))
   #hasheq((id . call-with-provider-retry)
           (owner . "runtime/provider-retry.rkt:define (call-with-provider-retry")
           (responsibilities . (orchestration eventing))
           (consumers . (turn-orchestrator)))
   #hasheq((id . with-auto-retry)
           (owner . "runtime/auto-retry.rkt:define (with-auto-retry")
           (responsibilities . (orchestration eventing fsm))
           (consumers . (call-with-provider-retry)))
   #hasheq((id . maybe-compact-context)
           (owner . "runtime/compaction/session-compaction.rkt:define (maybe-compact-context")
           (responsibilities . (orchestration eventing fsm))
           (consumers . (run-prompt-internal interpret-step)))
   #hasheq((id . compact-session-durably!)
           (owner . "runtime/session/session-events.rkt:define (compact-session-durably!")
           (responsibilities . (orchestration persistence eventing fsm wiring))
           (consumers . (session-event-subscribers)))))
 (paths .
  (#hasheq((id . normal)
           (ordered-effects .
            (#hasheq((n . 1) (effect . claim-prompt) (anchor . "runtime/session/session-lifecycle.rkt:try-claim-prompt! sess"))
             #hasheq((n . 2) (effect . begin-prompt-turn) (anchor . "runtime/session/session-lifecycle.rkt:begin-session-turn! sess"))
             #hasheq((n . 3) (effect . turn.started/prompt) (anchor . "runtime/session/session-lifecycle.rkt:(make-event \"turn.started\""))
             #hasheq((n . 4) (effect . input-hook) (anchor . "runtime/session/session-lifecycle.rkt:maybe-dispatch-hooks ext-reg 'input"))
             #hasheq((n . 5) (effect . parameterize-session-state) (anchor . "runtime/session/session-lifecycle.rkt:current-prompt-operation-session sess"))
             #hasheq((n . 6) (effect . append-user-and-build-context) (anchor . "runtime/session/session-lifecycle.rkt:build-session-context-for-prompt sess"))
             #hasheq((n . 7) (effect . maybe-compact) (anchor . "runtime/session/session-lifecycle.rkt:maybe-compact-context sess"))
             #hasheq((n . 8) (effect . context.built) (anchor . "runtime/session/session-lifecycle.rkt:(make-context-event #:session-id sid"))
             #hasheq((n . 9) (effect . ensure-persisted) (anchor . "runtime/session/session-lifecycle.rkt:ensure-persisted!-fn sess"))
             #hasheq((n . 10) (effect . dispatch-iteration) (anchor . "runtime/session/session-lifecycle.rkt:dispatch-iteration sess"))
             #hasheq((n . 11) (effect . rebuild-index) (anchor . "runtime/session/session-lifecycle.rkt:build-index! log-path idx-path"))
             #hasheq((n . 12) (effect . session.updated) (anchor . "runtime/session/session-lifecycle.rkt:\"session.updated\""))
             #hasheq((n . 13) (effect . rollback-save-back) (anchor . "runtime/session/session-lifecycle.rkt:set-lifecycle-state-rollback-st!"))
             #hasheq((n . 14) (effect . finish-and-release) (anchor . "runtime/session/session-lifecycle.rkt:finish-session-turn! sess")))))
   #hasheq((id . error)
           (ordered-effects .
            (#hasheq((n . 1) (effect . provider-or-iteration-raises) (anchor . "runtime/session/session-lifecycle.rkt:[exn:fail?"))
             #hasheq((n . 2) (effect . persist-partial-messages) (anchor . "runtime/session/session-lifecycle.rkt:append-session-entries! sess partial-msgs"))
             #hasheq((n . 3) (effect . runtime.error) (anchor . "runtime/session/session-lifecycle.rkt:\"runtime.error\" payload"))
             #hasheq((n . 4) (effect . turn.completed/error) (anchor . "runtime/session/session-lifecycle.rkt:turn-end-event \"turn.completed\""))
             #hasheq((n . 5) (effect . session.updated/error) (anchor . "runtime/session/session-lifecycle.rkt:lastTurnTermination"))
             #hasheq((n . 6) (effect . rollback-save-back-and-release) (anchor . "runtime/session/session-lifecycle.rkt:release-prompt! sess")))))
   #hasheq((id . cancel)
           (ordered-effects .
            (#hasheq((n . 1) (effect . interrupt.accepted) (anchor . "runtime/session/session-events.rkt:\"interrupt.accepted\""))
             #hasheq((n . 2) (effect . signal-token) (anchor . "runtime/session/session-interruption.rkt:cancel-token! token"))
             #hasheq((n . 3) (effect . cancellation-check-or-stream-cancel) (anchor . "agent/iteration/counters.rkt:define (check-cancellation"))
             #hasheq((n . 4) (effect . stream.turn.completed/cancelled) (anchor . "agent/loop-stream.rkt:make-stream-turn-completed-event"))
             #hasheq((n . 5) (effect . session.updated/cancelled) (anchor . "runtime/session/session-lifecycle.rkt:lastTurnTermination"))
             #hasheq((n . 6) (effect . rotate-token-and-release) (anchor . "runtime/session/session-lifecycle.rkt:finish-session-turn! sess"))
             #hasheq((n . 7) (effect . correlated-turn.cancelled) (anchor . "runtime/session/session-lifecycle.rkt:\"turn.cancelled\"")))))
   #hasheq((id . close)
           (ordered-effects .
            (#hasheq((n . 1) (effect . mark-closed) (anchor . "runtime/agent-session.rkt:guarded-set-closed! sess #t"))
             #hasheq((n . 2) (effect . clear-browser) (anchor . "runtime/agent-session.rkt:current-browser-service #f"))
             #hasheq((n . 3) (effect . ensure-persisted) (anchor . "runtime/agent-session.rkt:ensure-persisted! sess"))
             #hasheq((n . 4) (effect . session.closed) (anchor . "runtime/agent-session.rkt:session-shutdown-event \"session.closed\""))
             #hasheq((n . 5) (effect . shutdown-hook) (anchor . "runtime/agent-session.rkt:'session-shutdown"))
             #hasheq((n . 6) (effect . persist-conclusions) (anchor . "runtime/agent-session.rkt:persist-high-value-conclusions!"))
             #hasheq((n . 7) (effect . mark-inactive) (anchor . "runtime/agent-session.rkt:guarded-set-active! sess #f"))
             #hasheq((n . 8) (effect . stop-subscribers-and-repository) (anchor . "runtime/agent-session.rkt:close-session-repository!")))))
   #hasheq((id . retry)
           (ordered-effects .
            (#hasheq((n . 1) (effect . provider-attempt) (anchor . "runtime/provider-retry.rkt:call-with-provider-retry"))
             #hasheq((n . 2) (effect . classify-and-budget) (anchor . "runtime/auto-retry.rkt:retryable-error?"))
             #hasheq((n . 3) (effect . auto-retry.start) (anchor . "runtime/provider-retry.rkt:make-auto-retry-start-event"))
             #hasheq((n . 4) (effect . backoff) (anchor . "runtime/auto-retry.rkt:sleep"))
             #hasheq((n . 5) (effect . provider-reattempt-same-turn) (anchor . "runtime/provider-retry.rkt:with-auto-retry"))
             #hasheq((n . 6) (effect . success-or-runtime.error) (anchor . "runtime/session/session-lifecycle.rkt:classify-error e")))))
   #hasheq((id . compaction)
           (ordered-effects .
            (#hasheq((n . 1) (effect . threshold-and-claim) (anchor . "runtime/compaction/session-compaction.rkt:try-claim-compaction!"))
             #hasheq((n . 2) (effect . compaction-start-event) (anchor . "runtime/compaction/session-compaction.rkt:\"budget-exceeded\""))
             #hasheq((n . 3) (effect . before-compact-hook) (anchor . "runtime/compaction/session-compaction.rkt:'session-before-compact"))
             #hasheq((n . 4) (effect . compact-history) (anchor . "runtime/compaction/session-compaction.rkt:compact-history"))
             #hasheq((n . 5) (effect . compaction.completed) (anchor . "runtime/compaction/session-compaction.rkt:\"compaction.completed\""))
             #hasheq((n . 6) (effect . release-and-cooldown) (anchor . "runtime/compaction/session-compaction.rkt:release-compaction!"))
             #hasheq((n . 7) (effect . manual-durable-alternative) (anchor . "runtime/session/session-events.rkt:define (compact-session-durably!")))))))
 (exceptional-exits .
  (#hasheq((id . closed-session-guard) (phase . before-claim) (cleanup . none) (terminal . none) (classification . IN_SCOPE) (anchor . "runtime/session/session-lifecycle.rkt:unless (agent-session-active? sess"))
   #hasheq((id . prompt-contention) (phase . claim) (cleanup . none) (terminal . runtime.error) (classification . IN_SCOPE) (anchor . "runtime/session/session-lifecycle.rkt:exn:fail:session:busy"))
   #hasheq((id . begin-turn-failure) (phase . before-dynamic-wind) (cleanup . ownership-at-risk) (terminal . none) (classification . DEFERRED) (anchor . "runtime/session/session-lifecycle.rkt:define active-turn-id"))
   #hasheq((id . outer-turn-start-failure) (phase . before-dynamic-wind) (cleanup . ownership-at-risk) (terminal . none) (classification . DEFERRED) (anchor . "runtime/session/session-lifecycle.rkt:(make-event \"turn.started\""))
   #hasheq((id . input-hook-failure) (phase . outer-dynamic-wind) (cleanup . release+cleanup-terminal+emergency-persist) (terminal . turn.completed/cleanup) (classification . IN_SCOPE) (anchor . "runtime/session/session-lifecycle.rkt:maybe-dispatch-hooks ext-reg 'input"))
   #hasheq((id . context-or-user-persist-failure) (phase . outer+rollback-dynamic-wind) (cleanup . rollback-save-back+release+cleanup-terminal) (terminal . turn.completed/cleanup) (classification . IN_SCOPE) (anchor . "runtime/session/session-lifecycle.rkt:buffer-or-append!-fn sess user-msg"))
   #hasheq((id . compaction-failure) (phase . outer+rollback-dynamic-wind) (cleanup . compaction-release+rollback-save-back+prompt-release) (terminal . turn.completed/cleanup) (classification . IN_SCOPE) (anchor . "runtime/compaction/session-compaction.rkt:dynamic-wind"))
   #hasheq((id . model-select-or-tracer-start-failure) (phase . outside-dispatch-handler) (cleanup . rollback-save-back+prompt-release) (terminal . turn.completed/cleanup) (classification . DEFERRED) (anchor . "runtime/session/session-lifecycle.rkt:start-trace-logger! tracer"))
   #hasheq((id . provider-or-iteration-failure) (phase . dispatch-handler) (cleanup . partial-persist+trace-stop+outer-release) (terminal . turn.completed/error) (classification . IN_SCOPE) (anchor . "runtime/session/session-lifecycle.rkt:with-handlers"))
   #hasheq((id . dispatch-error-handler-failure) (phase . dispatch-handler) (cleanup . outer-cleanup-best-effort) (terminal . possibly-cleanup) (classification . DEFERRED) (anchor . "runtime/session/session-lifecycle.rkt:emit-session-event! bus sid \"runtime.error\""))
   #hasheq((id . index-rebuild-failure) (phase . after-model-terminal) (cleanup . rollback-save-back+outer-release) (terminal . turn.completed/cleanup) (classification . DEFERRED) (anchor . "runtime/session/session-lifecycle.rkt:guarded-set-index! sess (build-index!"))
   #hasheq((id . rollback-save-back-failure) (phase . rollback-after-thunk) (cleanup . outer-release) (terminal . none-after-normal-result) (classification . DEFERRED) (anchor . "runtime/session/session-lifecycle.rkt:set-lifecycle-state-rollback-st!"))
   #hasheq((id . finish-turn-failure) (phase . outer-cleanup) (cleanup . aborts-following-cleanup) (terminal . none) (classification . DEFERRED) (anchor . "runtime/session/session-lifecycle.rkt:finish-session-turn! sess"))
   #hasheq((id . release-prompt-failure) (phase . outer-cleanup) (cleanup . aborts-following-cleanup) (terminal . none) (classification . DEFERRED) (anchor . "runtime/session/session-lifecycle.rkt:release-prompt! sess"))
   #hasheq((id . break-or-kill) (phase . non-exn-fail) (cleanup . dynamic-wind-only) (terminal . cleanup-if-reached) (classification . DEFERRED) (anchor . "runtime/session/session-lifecycle.rkt:[exn:fail?"))
   #hasheq((id . close-during-active-prompt) (phase . concurrent-close) (cleanup . uncoordinated) (terminal . session.closed+later-prompt-events) (classification . SEPARATE_MILESTONE) (anchor . "runtime/agent-session.rkt:when (session-active? sess"))
   #hasheq((id . repeated-close) (phase . close) (cleanup . cleanup-repeats) (terminal . warning) (classification . DEFERRED) (anchor . "runtime/agent-session.rkt:already-closed session"))
   #hasheq((id . retry-exhausted-with-partial) (phase . retry-error) (cleanup . partial-persist) (terminal . runtime.error) (classification . DEFERRED) (anchor . "runtime/provider-retry.rkt:exn:fail:stream-error"))
   #hasheq((id . manual-compaction-failure) (phase . asynchronous-event) (cleanup . release+trace-stop) (terminal . session.compact.failed) (classification . IN_SCOPE) (anchor . "runtime/session/session-events.rkt:\"session.compact.failed\""))))
 (parameter-scopes .
  (#hasheq((parameter . current-prompt-operation-session) (enter . before-run-prompt-internal) (save-back . none) (unwind . automatic) (anchor . "runtime/session/session-lifecycle.rkt:current-prompt-operation-session sess"))
   #hasheq((parameter . current-rollback-state) (enter . from-session-lifecycle-state) (save-back . rollback-dynamic-wind-after) (unwind . after-save-back) (anchor . "runtime/session/session-lifecycle.rkt:current-rollback-state"))))
 (findings .
  (#hasheq((id . W0-F1) (classification . DEFERRED) (summary . "Prompt ownership is claimed before outer dynamic-wind protection."))
   #hasheq((id . W0-F2) (classification . DEFERRED) (summary . "Normal/error/correlated cancellation use different terminal identities and events."))
   #hasheq((id . W0-F3) (classification . SEPARATE_MILESTONE) (summary . "Close does not coordinate with an active prompt."))
   #hasheq((id . W0-F4) (classification . DEFERRED) (summary . "Automatic compaction completion/cooldown runs even after block or error cleanup."))
   #hasheq((id . W0-F5) (classification . DEFERRED) (summary . "Retry sleep is not cancellation-aware and partial wrapping can hide retry metadata.")))))
