#hasheq(
 (schema-version . 2)
 (milestone . v0.99.92)
 (wave . W0)
 (baseline . "a4b85569ff0dbe7971c3fec12babdb3fccbdd329")
 (scope . characterization-only)
 (production-change . #f)
 (responsibility-taxonomy . (orchestration pure-preparation persistence eventing fsm wiring))
 (units .
  (#hasheq((id . run-prompt!) (owner . "runtime/session/session-lifecycle.rkt:(define (run-prompt!") (responsibilities . (orchestration eventing fsm)))
   #hasheq((id . run-prompt-internal) (owner . "runtime/session/session-lifecycle.rkt:(define (run-prompt-internal") (responsibilities . (orchestration persistence eventing)))
   #hasheq((id . build-session-context-for-prompt) (owner . "runtime/session/session-lifecycle.rkt:(define (build-session-context-for-prompt") (responsibilities . (pure-preparation persistence orchestration)))
   #hasheq((id . dispatch-iteration) (owner . "runtime/session/session-lifecycle.rkt:(define (dispatch-iteration") (responsibilities . (orchestration eventing wiring)))
   #hasheq((id . run-iteration-loop/v2) (owner . "agent/iteration/main-loop.rkt:(define (run-iteration-loop/v2") (responsibilities . (orchestration fsm)))
   #hasheq((id . close-session!) (owner . "runtime/agent-session.rkt:(define (close-session!") (responsibilities . (orchestration persistence eventing fsm wiring)))
   #hasheq((id . call-with-provider-retry) (owner . "runtime/provider-retry.rkt:(define (call-with-provider-retry") (responsibilities . (orchestration eventing)))
   #hasheq((id . with-auto-retry) (owner . "runtime/auto-retry.rkt:(define (with-auto-retry") (responsibilities . (orchestration eventing fsm)))
   #hasheq((id . maybe-compact-context) (owner . "runtime/compaction/session-compaction.rkt:(define (maybe-compact-context sess") (responsibilities . (orchestration eventing fsm)))
   #hasheq((id . compact-session-durably!) (owner . "runtime/session/session-events.rkt:(define (compact-session-durably!") (responsibilities . (orchestration persistence eventing fsm wiring)))))
 (consumer-edges .
  (#hasheq((id . sdk-run) (from . interfaces/sdk-core) (to . run-prompt!) (kind . direct) (anchor . "interfaces/sdk-core.rkt:session:run-prompt! sess prompt"))
   #hasheq((id . goal-run) (from . tui/commands/goal-bridge) (to . run-prompt!) (kind . direct) (anchor . "tui/commands/goal-bridge.rkt:run-prompt! (unbox sess-box) prompt"))
   #hasheq((id . tui-campaign) (from . tui/tui-init) (to . run-prompt!) (kind . direct) (anchor . "tui/tui-init.rkt:run-prompt! campaign-sess prompt"))
   #hasheq((id . tui-normal) (from . tui/tui-init) (to . run-prompt!) (kind . direct) (anchor . "tui/tui-init.rkt:run-prompt! sess prompt"))
   #hasheq((id . cli-runners) (from . wiring/run-interactive) (to . run-prompt!) (kind . direct) (anchor . "wiring/run-interactive.rkt:run-prompt! sess prompt"))
   #hasheq((id . rpc-prompt) (from . wiring/run-json-rpc) (to . run-prompt!) (kind . direct) (anchor . "wiring/run-json-rpc.rkt:run-prompt! sess text"))
   #hasheq((id . rpc-default-prompt) (from . wiring/run-json-rpc) (to . run-prompt!) (kind . direct) (anchor . "wiring/run-json-rpc.rkt:run-prompt! default-sess msg"))
   #hasheq((id . gui-campaign) (from . gui/slash-commands) (to . run-prompt!) (kind . direct) (anchor . "gui/slash-commands.rkt:run-prompt! campaign-session prompt"))
   #hasheq((id . gui-submit) (from . gui/slash-commands) (to . run-prompt!) (kind . direct) (anchor . "gui/slash-commands.rkt:run-prompt! sess (hash-ref payload 'submit)"))
   #hasheq((id . gui-new-session) (from . gui/slash-commands) (to . run-prompt!) (kind . direct) (anchor . "gui/slash-commands.rkt:run-prompt! sess (hash-ref payload 'new-session)"))
   #hasheq((id . gui-input) (from . gui/main) (to . run-prompt!) (kind . direct) (anchor . "gui/main.rkt:run-prompt! sess val"))
   #hasheq((id . prompt-internal) (from . run-prompt!) (to . run-prompt-internal) (kind . direct) (anchor . "runtime/session/session-lifecycle.rkt:run-prompt-internal sess"))
   #hasheq((id . prompt-context) (from . run-prompt-internal) (to . build-session-context-for-prompt) (kind . direct) (anchor . "runtime/session/session-lifecycle.rkt:build-session-context-for-prompt sess user-message"))
   #hasheq((id . prompt-dispatch) (from . run-prompt-internal) (to . dispatch-iteration) (kind . direct) (anchor . "runtime/session/session-lifecycle.rkt:dispatch-iteration sess context-after-compact"))
   #hasheq((id . dispatch-loop) (from . dispatch-iteration) (to . run-iteration-loop/v2) (kind . direct) (anchor . "runtime/session/session-lifecycle.rkt:run-iteration-loop/v2"))
   #hasheq((id . rpc-close) (from . wiring/run-json-rpc) (to . close-session!) (kind . direct) (anchor . "wiring/run-json-rpc.rkt:close-session! sess"))
   #hasheq((id . gui-slash-close) (from . gui/slash-commands) (to . close-session!) (kind . direct) (anchor . "gui/slash-commands.rkt:close-session! sess"))
   #hasheq((id . gui-close) (from . gui/main) (to . close-session!) (kind . direct) (anchor . "gui/main.rkt:close-session! sess"))
   #hasheq((id . provider-retry) (from . run-provider-turn) (to . call-with-provider-retry) (kind . direct) (anchor . "runtime/turn-orchestrator.rkt:call-with-provider-retry"))
   #hasheq((id . auto-retry) (from . call-with-provider-retry) (to . with-auto-retry) (kind . direct) (anchor . "runtime/provider-retry.rkt:with-auto-retry"))
   #hasheq((id . policy-retry) (from . with-retry-policy) (to . with-auto-retry) (kind . direct) (anchor . "runtime/auto-retry.rkt:with-auto-retry thunk"))
   #hasheq((id . subagent-retry) (from . run-subagent-loop) (to . with-auto-retry) (kind . direct) (anchor . "tools/builtins/spawn-execution.rkt:with-auto-retry"))
   #hasheq((id . prompt-compaction) (from . run-prompt-internal) (to . maybe-compact-context) (kind . direct) (anchor . "runtime/session/session-lifecycle.rkt:maybe-compact-context sess context-with-system"))
   #hasheq((id . midturn-compaction) (from . compact-context-mid-turn) (to . maybe-compact-context) (kind . direct) (anchor . "runtime/compaction/session-compaction.rkt:maybe-compact-context sess context budget-threshold"))
   #hasheq((id . durable-compaction-event) (from . wire-session-event-handlers!) (to . compact-session-durably!) (kind . direct) (anchor . "runtime/session/session-events.rkt:compact-session-durably! sess #:request-id request-id"))
   #hasheq((id . sdk-compat) (from . interfaces/sdk-compat) (to . interfaces/sdk-core) (kind . transitive) (anchor . "interfaces/sdk-compat.rkt:q:session-send"))
   #hasheq((id . goal-callback) (from . runtime/goal/goal-runner) (to . goal-run) (kind . transitive) (anchor . "runtime/goal/goal-runner.rkt:run-prompt-fn!"))))
 (paths .
  (#hasheq((id . normal-success) (family . normal) (trace .
    (#hasheq((effect . claim) (anchor . "runtime/session/session-lifecycle.rkt:try-claim-prompt! sess"))
     #hasheq((effect . prompt-start) (anchor . "runtime/session/session-lifecycle.rkt:begin-session-turn! sess"))
     #hasheq((effect . input-hook) (anchor . "runtime/session/session-lifecycle.rkt:maybe-dispatch-hooks ext-reg 'input"))
     #hasheq((effect . context) (anchor . "runtime/session/session-lifecycle.rkt:build-session-context-for-prompt sess user-message"))
     #hasheq((effect . compaction) (anchor . "runtime/session/session-lifecycle.rkt:maybe-compact-context sess context-with-system"))
     #hasheq((effect . dispatch) (anchor . "runtime/session/session-lifecycle.rkt:dispatch-iteration sess context-after-compact"))
     #hasheq((effect . index-rebuild) (anchor . "runtime/session/session-lifecycle.rkt:guarded-set-index! sess (build-index!"))
     #hasheq((effect . session-updated) (anchor . "runtime/session/session-lifecycle.rkt:\"session.updated\""))
     #hasheq((effect . rollback-save-back) (anchor . "runtime/session/session-lifecycle.rkt:set-lifecycle-state-rollback-st!"))
     #hasheq((effect . release) (anchor . "runtime/session/session-lifecycle.rkt:release-prompt! sess")))))
   #hasheq((id . handled-error) (family . error) (trace .
    (#hasheq((effect . partial-persist) (anchor . "runtime/session/session-lifecycle.rkt:append-session-entries! sess partial-msgs"))
     #hasheq((effect . runtime-error) (anchor . "runtime/session/session-lifecycle.rkt:emit-session-event! bus sid \"runtime.error\" payload"))
     #hasheq((effect . error-terminal) (anchor . "runtime/session/session-lifecycle.rkt:turn-end-event \"turn.completed\""))
     #hasheq((effect . trace-stop) (anchor . "runtime/session/session-lifecycle.rkt:stop-trace-logger! tracer"))
     #hasheq((effect . index-rebuild) (anchor . "runtime/session/session-lifecycle.rkt:guarded-set-index! sess (build-index!"))
     #hasheq((effect . session-updated) (anchor . "runtime/session/session-lifecycle.rkt:lastTurnTermination"))
     #hasheq((effect . save-back-release) (anchor . "runtime/session/session-lifecycle.rkt:release-prompt! sess")))))
   #hasheq((id . error-then-index-failure) (family . error) (trace .
    (#hasheq((effect . error-terminal) (anchor . "runtime/session/session-lifecycle.rkt:turn-end-event \"turn.completed\""))
     #hasheq((effect . build-index-raises) (anchor . "runtime/session/session-lifecycle.rkt:build-index! log-path idx-path"))
     #hasheq((effect . rollback-save-back) (anchor . "runtime/session/session-lifecycle.rkt:set-lifecycle-state-rollback-st!"))
     #hasheq((effect . release) (anchor . "runtime/session/session-lifecycle.rkt:release-prompt! sess"))
     #hasheq((effect . cleanup-terminal) (anchor . "runtime/session/session-lifecycle.rkt:emit-cleanup-turn-completed?")))))
   #hasheq((id . cancel-pre-iteration) (family . cancel) (trace .
    (#hasheq((effect . interrupt-accepted) (anchor . "runtime/session/session-events.rkt:\"interrupt.accepted\""))
     #hasheq((effect . token-signal) (anchor . "runtime/session/session-interruption.rkt:cancel-token! token"))
     #hasheq((effect . cancellation-check) (anchor . "agent/iteration/counters.rkt:(define (check-cancellation"))
     #hasheq((effect . uncorrelated-turn-cancelled) (anchor . "agent/iteration/counters.rkt:turn-cancelled-event \"turn.cancelled\""))
     #hasheq((effect . index-rebuild-session-updated) (anchor . "runtime/session/session-lifecycle.rkt:lastTurnTermination"))
     #hasheq((effect . rotate-release) (anchor . "runtime/session/session-interruption.rkt:make-cancellation-token"))
     #hasheq((effect . correlated-turn-cancelled) (anchor . "runtime/session/session-lifecycle.rkt:\"turn.cancelled\"")))))
   #hasheq((id . cancel-midstream) (family . cancel) (trace .
    (#hasheq((effect . chunk-processed) (anchor . "agent/stream-runner.rkt:when (stream-chunk-done? chunk"))
     #hasheq((effect . token-observed) (anchor . "agent/stream-runner.rkt:cancellation-token-cancelled?"))
     #hasheq((effect . stream-cancelled) (anchor . "agent/stream-runner.rkt:make-stream-turn-cancelled-event"))
     #hasheq((effect . stream-completed-cancelled) (anchor . "agent/loop-stream.rkt:make-stream-turn-completed-event"))
     #hasheq((effect . session-updated) (anchor . "runtime/session/session-lifecycle.rkt:lastTurnTermination"))
     #hasheq((effect . correlated-turn-cancelled) (anchor . "runtime/session/session-lifecycle.rkt:\"turn.cancelled\"")))))
   #hasheq((id . close-normal) (family . close) (trace .
    (#hasheq((effect . mark-closed) (anchor . "runtime/agent-session.rkt:guarded-set-closed! sess #t"))
     #hasheq((effect . persist) (anchor . "runtime/agent-session.rkt:ensure-persisted! sess"))
     #hasheq((effect . session-closed) (anchor . "runtime/agent-session.rkt:session-shutdown-event \"session.closed\""))
     #hasheq((effect . shutdown-hook) (anchor . "runtime/agent-session.rkt:'session-shutdown"))
     #hasheq((effect . conclusions) (anchor . "runtime/agent-session.rkt:persist-high-value-conclusions!"))
     #hasheq((effect . inactive) (anchor . "runtime/agent-session.rkt:guarded-set-active! sess #f"))
     #hasheq((effect . repository-close) (anchor . "runtime/agent-session.rkt:close-session-repository!")))))
   #hasheq((id . close-repeated) (family . close) (trace .
    (#hasheq((effect . warning) (anchor . "runtime/agent-session.rkt:already-closed session"))
     #hasheq((effect . void-not-return) (anchor . "runtime/agent-session.rkt:(void)"))
     #hasheq((effect . mark-closed-again) (anchor . "runtime/agent-session.rkt:guarded-set-closed! sess #t"))
     #hasheq((effect . repeat-cleanup-groups) (anchor . "runtime/agent-session.rkt:Cleanup steps"))
     #hasheq((effect . repository-close-again) (anchor . "runtime/agent-session.rkt:close-session-repository!")))))
   #hasheq((id . close-active-prompt) (family . close) (trace .
    (#hasheq((effect . no-prompt-claim-check) (anchor . "runtime/agent-session.rkt:(define (close-session! sess)"))
     #hasheq((effect . close-while-active) (anchor . "runtime/agent-session.rkt:when (session-active? sess"))
     #hasheq((effect . repository-close) (anchor . "runtime/agent-session.rkt:close-session-repository!"))
     #hasheq((effect . prompt-index-rebuild-can-follow) (anchor . "runtime/session/session-lifecycle.rkt:guarded-set-index! sess (build-index!"))
     #hasheq((effect . prompt-session-updated-can-follow) (anchor . "runtime/session/session-lifecycle.rkt:\"session.updated\"")))))
   #hasheq((id . retry-success) (family . retry) (trace .
    (#hasheq((effect . failed-attempt) (anchor . "runtime/provider-retry.rkt:wrapped-attempt"))
     #hasheq((effect . retry-decision) (anchor . "runtime/auto-retry.rkt:retryable-error? e"))
     #hasheq((effect . retry-event) (anchor . "runtime/provider-retry.rkt:make-auto-retry-start-event"))
     #hasheq((effect . sleep) (anchor . "runtime/auto-retry.rkt:sleep (/ next-delay 1000.0)"))
     #hasheq((effect . reattempt) (anchor . "runtime/auto-retry.rkt:loop (add1 attempt)"))
     #hasheq((effect . success-health-reset) (anchor . "runtime/provider-retry.rkt:record-success! health")))))
   #hasheq((id . retry-exhausted) (family . retry) (trace .
    (#hasheq((effect . budget-denies) (anchor . "runtime/auto-retry.rkt:< current-type-count type-budget"))
     #hasheq((effect . retry-exhausted-raise) (anchor . "runtime/auto-retry.rkt:retry-exhausted (format"))
     #hasheq((effect . retry-metadata) (anchor . "runtime/session/session-lifecycle.rkt:retries-attempted"))
     #hasheq((effect . runtime-error) (anchor . "runtime/session/session-lifecycle.rkt:emit-session-event! bus sid \"runtime.error\" payload"))
     #hasheq((effect . error-path) (anchor . "runtime/session/session-lifecycle.rkt:make-loop-result context-with-system 'error")))))
   #hasheq((id . retry-exhausted-partial) (family . retry) (trace .
    (#hasheq((effect . exhaustion) (anchor . "runtime/auto-retry.rkt:retry-exhausted (format"))
     #hasheq((effect . partial-wrap) (anchor . "runtime/provider-retry.rkt:exn:fail:stream-error"))
     #hasheq((effect . partial-persist) (anchor . "runtime/session/session-lifecycle.rkt:append-session-entries! sess partial-msgs"))
     #hasheq((effect . metadata-hidden) (anchor . "runtime/session/session-lifecycle.rkt:if (retry-exhausted? e)")))))
   #hasheq((id . retry-held-circuit) (family . retry) (trace .
    (#hasheq((effect . held-detected) (anchor . "runtime/auto-retry.rkt:held-request? e"))
     #hasheq((effect . circuit-callback) (anchor . "runtime/auto-retry.rkt:on-circuit-break"))
     #hasheq((effect . circuit-event) (anchor . "runtime/provider-retry.rkt:\"circuit-break.tripped\""))
     #hasheq((effect . no-retry) (anchor . "runtime/auto-retry.rkt:not (held-request? exn)")))))
   #hasheq((id . retry-progressive-circuit) (family . retry) (trace .
    (#hasheq((effect . stall-count) (anchor . "runtime/auto-retry.rkt:consecutive-stalls"))
     #hasheq((effect . threshold) (anchor . "runtime/auto-retry.rkt:stall-max-consecutive"))
     #hasheq((effect . circuit-event) (anchor . "runtime/provider-retry.rkt:\"circuit-break.tripped\""))
     #hasheq((effect . exhaustion) (anchor . "runtime/auto-retry.rkt:retry-exhausted (format")))))
   #hasheq((id . retry-health-gate) (family . retry) (trace .
    (#hasheq((effect . record-failure) (anchor . "runtime/provider-retry.rkt:record-failure! health"))
     #hasheq((effect . health-check) (anchor . "runtime/provider-retry.rkt:provider-healthy?"))
     #hasheq((effect . health-event) (anchor . "runtime/provider-retry.rkt:\"provider.health-gate\""))
     #hasheq((effect . deny) (anchor . "runtime/provider-retry.rkt:#f")))))
   #hasheq((id . retry-adaptive) (family . retry) (trace .
    (#hasheq((effect . retry-event) (anchor . "runtime/provider-retry.rkt:make-auto-retry-start-event"))
     #hasheq((effect . adapt) (anchor . "runtime/provider-retry.rkt:adapt-provider-request"))
     #hasheq((effect . adaptive-event) (anchor . "runtime/provider-retry.rkt:\"provider.adaptive-retry\""))
     #hasheq((effect . reattempt) (anchor . "runtime/auto-retry.rkt:loop (add1 attempt)")))))
   #hasheq((id . retry-partial-recovery) (family . retry) (trace .
    (#hasheq((effect . capture-partial) (anchor . "runtime/provider-retry.rkt:partial-text-box"))
     #hasheq((effect . threshold) (anchor . "runtime/provider-retry.rkt:partial-min-chars"))
     #hasheq((effect . continuation-context) (anchor . "runtime/provider-retry.rkt:make-text-part continuation-text"))
     #hasheq((effect . recovery-event) (anchor . "runtime/provider-retry.rkt:\"provider.partial-recovery\"")))))
   #hasheq((id . compact-auto-success) (family . compaction) (trace .
    (#hasheq((effect . claim) (anchor . "runtime/compaction/session-compaction.rkt:try-claim-compaction!"))
     #hasheq((effect . start-event) (anchor . "runtime/compaction/session-compaction.rkt:\"budget-exceeded\""))
     #hasheq((effect . hook) (anchor . "runtime/compaction/session-compaction.rkt:'session-before-compact"))
     #hasheq((effect . compact) (anchor . "runtime/compaction/session-compaction.rkt:compact-history"))
     #hasheq((effect . completed) (anchor . "runtime/compaction/session-compaction.rkt:\"compaction.completed\""))
     #hasheq((effect . release) (anchor . "runtime/compaction/session-compaction.rkt:release-compaction!")))))
   #hasheq((id . compact-auto-hook-block) (family . compaction) (trace .
    (#hasheq((effect . claim) (anchor . "runtime/compaction/session-compaction.rkt:try-claim-compaction!"))
     #hasheq((effect . hook-block) (anchor . "runtime/compaction/session-compaction.rkt:hook-result-action compact-hook-res"))
     #hasheq((effect . original-context) (anchor . "runtime/compaction/session-compaction.rkt:context-with-system"))
     #hasheq((effect . release-cooldown-complete) (anchor . "runtime/compaction/session-compaction.rkt:\"compaction-complete\"")))))
   #hasheq((id . compact-auto-start-failure) (family . compaction) (trace .
    (#hasheq((effect . claim) (anchor . "runtime/compaction/session-compaction.rkt:try-claim-compaction!"))
     #hasheq((effect . start-publication-raises) (anchor . "runtime/compaction/session-compaction.rkt:emit-typed-event!"))
     #hasheq((effect . before-dynamic-wind) (anchor . "runtime/compaction/session-compaction.rkt:dynamic-wind"))
     #hasheq((effect . ownership-leaks) (anchor . "runtime/compaction/session-compaction.rkt:release-compaction!")))))
   #hasheq((id . compact-midturn) (family . compaction) (trace .
    (#hasheq((effect . soft-limit-branch) (anchor . "runtime/iteration/step-executor.rkt:stop-soft-limit"))
     #hasheq((effect . over-budget-event) (anchor . "runtime/iteration/retry-policy.rkt:\"context.mid-turn-over-budget\""))
     #hasheq((effect . compact-midturn) (anchor . "runtime/iteration/step-executor.rkt:compact-context-mid-turn"))
     #hasheq((effect . recurse) (anchor . "runtime/iteration/step-executor.rkt:directive-recurse ctx-after-budget")))))
   #hasheq((id . compact-manual-completed) (family . compaction) (trace .
    (#hasheq((effect . claim) (anchor . "runtime/session/session-events.rkt:try-claim-compaction! sess"))
     #hasheq((effect . tracer) (anchor . "runtime/session/session-events.rkt:make-trace-logger"))
     #hasheq((effect . started) (anchor . "runtime/session/session-events.rkt:\"session.compact.started\""))
     #hasheq((effect . persist-summary) (anchor . "runtime/session/session-events.rkt:compact-proc"))
     #hasheq((effect . rebuild-index) (anchor . "runtime/session/session-events.rkt:build-index! log-path"))
     #hasheq((effect . completed) (anchor . "runtime/session/session-events.rkt:\"session.compact.completed\""))
     #hasheq((effect . release-stop) (anchor . "runtime/session/session-events.rkt:release-compaction! sess")))))
   #hasheq((id . compact-manual-nothing) (family . compaction) (trace .
    (#hasheq((effect . claim-start) (anchor . "runtime/session/session-events.rkt:\"session.compact.started\""))
     #hasheq((effect . history-check) (anchor . "runtime/session/session-events.rkt:null? history"))
     #hasheq((effect . nothing-terminal) (anchor . "runtime/session/session-events.rkt:\"session.compact.nothing-to-compact\""))
     #hasheq((effect . release-stop) (anchor . "runtime/session/session-events.rkt:release-compaction! sess")))))
   #hasheq((id . compact-manual-failed) (family . compaction) (trace .
    (#hasheq((effect . handler) (anchor . "runtime/session/session-events.rkt:[exn:fail?"))
     #hasheq((effect . failed-event) (anchor . "runtime/session/session-events.rkt:\"session.compact.failed\""))
     #hasheq((effect . release) (anchor . "runtime/session/session-events.rkt:release-compaction! sess"))
     #hasheq((effect . trace-stop) (anchor . "runtime/session/session-events.rkt:stop-compact-tracer! tracer")))))
   #hasheq((id . compact-manual-tracer-failure) (family . compaction) (trace .
    (#hasheq((effect . claim) (anchor . "runtime/session/session-events.rkt:try-claim-compaction! sess"))
     #hasheq((effect . tracer-construction-raises) (anchor . "runtime/session/session-events.rkt:make-trace-logger"))
     #hasheq((effect . before-handler) (anchor . "runtime/session/session-events.rkt:with-handlers"))
     #hasheq((effect . ownership-leaks) (anchor . "runtime/session/session-events.rkt:release-compaction! sess")))))
   #hasheq((id . compact-manual-contention) (family . compaction) (trace .
    (#hasheq((effect . claim-denied) (anchor . "runtime/session/session-events.rkt:define claimed? (try-claim-compaction! sess)"))
     #hasheq((effect . already-running) (anchor . "runtime/session/session-events.rkt:\"session.compact.already-running\""))
     #hasheq((effect . return) (anchor . "runtime/session/session-events.rkt:'already-running")))))
   #hasheq((id . hook-input-block) (family . normal) (trace .
    (#hasheq((effect . input-hook) (anchor . "runtime/session/session-lifecycle.rkt:hook-result-action input-hook-res"))
     #hasheq((effect . input-blocked) (anchor . "runtime/session/session-lifecycle.rkt:\"input.blocked\""))
     #hasheq((effect . completed-result) (anchor . "runtime/session/session-lifecycle.rkt:\"input-blocked\""))
     #hasheq((effect . cleanup-terminal) (anchor . "runtime/session/session-lifecycle.rkt:emit-cleanup-turn-completed?")))))
   #hasheq((id . hook-before-agent-block) (family . normal) (trace .
    (#hasheq((effect . hook) (anchor . "agent/iteration/main-loop.rkt:'before-agent-start"))
     #hasheq((effect . agent-blocked) (anchor . "agent/iteration/main-loop.rkt:\"agent.blocked\""))
     #hasheq((effect . completed-result) (anchor . "agent/iteration/main-loop.rkt:\"agent.blocked\"")))))
   #hasheq((id . hook-turn-start-block) (family . normal) (trace .
    (#hasheq((effect . hook) (anchor . "agent/iteration/loop-phases.rkt:'turn-start"))
     #hasheq((effect . turn-blocked) (anchor . "agent/iteration/main-loop.rkt:\"turn.blocked\""))
     #hasheq((effect . completed-result) (anchor . "agent/iteration/main-loop.rkt:turn blocked at iteration")))))
   #hasheq((id . hook-model-request-block) (family . normal) (trace .
    (#hasheq((effect . hook) (anchor . "agent/loop.rkt:'model-request-pre"))
     #hasheq((effect . blocked-event) (anchor . "agent/loop.rkt:make-model-request-blocked-event"))
     #hasheq((effect . turn-terminal) (anchor . "agent/loop.rkt:make-turn-end-event")))))
   #hasheq((id . hook-message-start-block) (family . normal) (trace .
    (#hasheq((effect . hook) (anchor . "agent/loop-dispatch.rkt:'message-start"))
     #hasheq((effect . blocked-event) (anchor . "agent/loop-dispatch.rkt:make-message-blocked-event"))
     #hasheq((effect . turn-terminal) (anchor . "agent/loop-dispatch.rkt:make-turn-end-event")))))
   #hasheq((id . hook-message-end-block) (family . normal) (trace .
    (#hasheq((effect . hook) (anchor . "agent/loop-stream.rkt:'message-end"))
     #hasheq((effect . stream-terminal) (anchor . "agent/loop-stream.rkt:make-stream-turn-completed-event"))
     #hasheq((effect . hook-blocked) (anchor . "agent/loop-stream.rkt:'hook-blocked")))))))
 (exceptional-exits .
  (#hasheq((id . closed-guard) (classification . IN_SCOPE) (severity . low) (owner . runtime-session) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/session/session-lifecycle.rkt:unless (agent-session-active? sess"))
   #hasheq((id . busy-event-failure) (classification . DEFERRED) (severity . medium) (owner . runtime-session) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/session/session-lifecycle.rkt:Prompt already running"))
   #hasheq((id . begin-turn-failure) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W1 #9243 preserve; W4 #9246 decide") (anchor . "runtime/session/session-lifecycle.rkt:define active-turn-id"))
   #hasheq((id . outer-start-failure) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W1 #9243 preserve; W4 #9246 decide") (anchor . "runtime/session/session-lifecycle.rkt:(make-event \"turn.started\""))
   #hasheq((id . input-hook-failure) (classification . IN_SCOPE) (severity . medium) (owner . runtime-session) (follow-up . "W1 #9243 equivalence oracle") (anchor . "runtime/session/session-lifecycle.rkt:maybe-dispatch-hooks ext-reg 'input"))
   #hasheq((id . input-hook-block) (classification . IN_SCOPE) (severity . low) (owner . runtime-session) (follow-up . "W1 #9243 equivalence oracle") (anchor . "runtime/session/session-lifecycle.rkt:\"input.blocked\""))
   #hasheq((id . context-persistence-failure) (classification . IN_SCOPE) (severity . high) (owner . runtime-session) (follow-up . "W1 #9243 equivalence oracle") (anchor . "runtime/session/session-lifecycle.rkt:buffer-or-append!-fn sess user-msg"))
   #hasheq((id . context-event-failure) (classification . DEFERRED) (severity . medium) (owner . runtime-session) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/session/session-lifecycle.rkt:make-context-event"))
   #hasheq((id . model-select-failure) (classification . DEFERRED) (severity . medium) (owner . runtime-session) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/session/session-lifecycle.rkt:'model-select"))
   #hasheq((id . tracer-construction-failure) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/session/session-lifecycle.rkt:make-trace-logger bus session-dir"))
   #hasheq((id . tracer-start-failure) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/session/session-lifecycle.rkt:start-trace-logger! tracer"))
   #hasheq((id . provider-generator-failure) (classification . DEFERRED) (severity . medium) (owner . agent-stream) (follow-up . "W4 #9246 terminal reassessment") (anchor . "agent/stream-runner.rkt:provider-stream"))
   #hasheq((id . dispatch-handler-failure) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/session/session-lifecycle.rkt:emit-session-event! bus sid \"runtime.error\" payload"))
   #hasheq((id . normal-tracer-stop-failure) (classification . DEFERRED) (severity . medium) (owner . runtime-session) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/session/session-lifecycle.rkt:Stop trace logger on normal completion"))
   #hasheq((id . index-rebuild-failure) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W2 #9244 boundary equivalence") (anchor . "runtime/session/session-lifecycle.rkt:guarded-set-index! sess (build-index!"))
   #hasheq((id . session-updated-failure) (classification . DEFERRED) (severity . medium) (owner . runtime-session) (follow-up . "W2 #9244 boundary equivalence") (anchor . "runtime/session/session-lifecycle.rkt:\"session.updated\""))
   #hasheq((id . rollback-save-back-failure) (classification . DEFERRED) (severity . high) (owner . runtime-session-state) (follow-up . "W2 #9244 ownership gate") (anchor . "runtime/session/session-lifecycle.rkt:set-lifecycle-state-rollback-st!"))
   #hasheq((id . finish-turn-failure) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/session/session-lifecycle.rkt:finish-session-turn! sess"))
   #hasheq((id . release-prompt-failure) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/session/session-lifecycle.rkt:release-prompt! sess"))
   #hasheq((id . acknowledgement-tracer-failure) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/session/session-lifecycle.rkt:acknowledgement-tracer"))
   #hasheq((id . cleanup-terminal-failure) (classification . IN_SCOPE) (severity . low) (owner . runtime-session) (follow-up . "W1 #9243 equivalence oracle") (anchor . "runtime/session/session-lifecycle.rkt:cleanup turn.completed failed"))
   #hasheq((id . emergency-persist-failure) (classification . IN_SCOPE) (severity . medium) (owner . runtime-session) (follow-up . "W1 #9243 equivalence oracle") (anchor . "runtime/session/session-lifecycle.rkt:emergency persist failed"))
   #hasheq((id . interrupt-accepted-publication-failure) (classification . DEFERRED) (severity . high) (owner . runtime-interruption) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/session/session-events.rkt:\"interrupt.accepted\""))
   #hasheq((id . interrupt-signal-failure) (classification . DEFERRED) (severity . high) (owner . runtime-interruption) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/session/session-events.rkt:signal-session-interrupt!"))
   #hasheq((id . retry-callback-failure) (classification . DEFERRED) (severity . medium) (owner . runtime-retry) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/provider-retry.rkt:on-retry"))
   #hasheq((id . retry-sleep-break) (classification . DEFERRED) (severity . medium) (owner . runtime-retry) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/auto-retry.rkt:sleep (/ next-delay 1000.0)"))
   #hasheq((id . retry-partial-metadata-loss) (classification . DEFERRED) (severity . medium) (owner . runtime-retry) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/provider-retry.rkt:exn:fail:stream-error"))
   #hasheq((id . auto-compaction-start-event-failure) (classification . DEFERRED) (severity . high) (owner . runtime-compaction) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/compaction/session-compaction.rkt:\"budget-exceeded\""))
   #hasheq((id . auto-compaction-hook-block) (classification . IN_SCOPE) (severity . low) (owner . runtime-compaction) (follow-up . "W1 #9243 preserve ordering") (anchor . "runtime/compaction/session-compaction.rkt:hook-result-action compact-hook-res"))
   #hasheq((id . auto-compaction-body-failure) (classification . DEFERRED) (severity . medium) (owner . runtime-compaction) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/compaction/session-compaction.rkt:compact-history"))
   #hasheq((id . auto-compaction-cleanup-failure) (classification . DEFERRED) (severity . high) (owner . runtime-compaction) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/compaction/session-compaction.rkt:release-compaction!"))
   #hasheq((id . manual-compaction-contention-event-failure) (classification . DEFERRED) (severity . medium) (owner . runtime-compaction) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/session/session-events.rkt:\"session.compact.already-running\""))
   #hasheq((id . manual-compaction-tracer-construction-failure) (classification . DEFERRED) (severity . high) (owner . runtime-compaction) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/session/session-events.rkt:make-trace-logger"))
   #hasheq((id . manual-compaction-failed-event-failure) (classification . DEFERRED) (severity . high) (owner . runtime-compaction) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/session/session-events.rkt:\"session.compact.failed\""))
   #hasheq((id . repeated-close) (classification . DEFERRED) (severity . medium) (owner . runtime-session) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/agent-session.rkt:already-closed session"))
   #hasheq((id . active-prompt-close) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W4 #9246 assign separate concurrency milestone") (anchor . "runtime/agent-session.rkt:when (session-active? sess"))
   #hasheq((id . close-cleanup-group-failure) (classification . IN_SCOPE) (severity . medium) (owner . runtime-session) (follow-up . "W3 #9245 locality assessment") (anchor . "runtime/agent-session.rkt:Cleanup steps"))
   #hasheq((id . non-exn-break-kill) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W4 #9246 terminal reassessment") (anchor . "runtime/session/session-lifecycle.rkt:[exn:fail?"))))
 (parameter-scopes .
  (#hasheq((id . current-prompt-operation-session) (enter . before-run-prompt-internal) (save-back . none) (unwind . automatic) (anchor . "runtime/session/session-lifecycle.rkt:current-prompt-operation-session sess"))
   #hasheq((id . current-rollback-state) (enter . from-session-lifecycle-state) (save-back . rollback-dynamic-wind-after-before-parameter-unwind) (unwind . after-save-back) (anchor . "runtime/session/session-lifecycle.rkt:set-lifecycle-state-rollback-st!"))))
 (behavioral-evidence .
  (#hasheq((id . normal-error-close) (anchor . "tests/test-agent-session-basic.rkt:run-prompt"))
   #hasheq((id . cancellation) (anchor . "tests/test-agent-session-cancellation.rkt:cancellation"))
   #hasheq((id . correlated-interrupt) (anchor . "tests/test-interrupt-lifecycle.rkt:interrupt.accepted"))
   #hasheq((id . close-guards) (anchor . "tests/test-session-lifecycle-guards.rkt:close"))
   #hasheq((id . close-cleanup) (anchor . "tests/test-session-cleanup.rkt:close-session!"))
   #hasheq((id . manual-compaction) (anchor . "tests/test-session-compaction-lifecycle.rkt:session.compact"))
   #hasheq((id . auto-compaction-hook) (anchor . "tests/test-hooks-complete.rkt:session-before-compact"))
   #hasheq((id . retry-prompt) (anchor . "tests/test-retry-prompt-persistence.rkt:last-user-prompt"))))
 (findings .
  (#hasheq((id . W0-F1) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W1 #9243 preserve; W4 #9246 terminal decision") (summary . "Prompt ownership is claimed before outer dynamic-wind protection."))
   #hasheq((id . W0-F2) (classification . DEFERRED) (severity . medium) (owner . runtime-session) (follow-up . "W1 #9243 preserve; W4 #9246 terminal decision") (summary . "Normal, error and correlated cancellation use different terminal identities/events."))
   #hasheq((id . W0-F3) (classification . DEFERRED) (severity . high) (owner . runtime-session) (follow-up . "W4 #9246 assign separate concurrency milestone") (summary . "Close does not coordinate with an active prompt or repository writer."))
   #hasheq((id . W0-F4) (classification . DEFERRED) (severity . medium) (owner . runtime-compaction) (follow-up . "W3 #9245 locality assessment; W4 #9246 decision") (summary . "Automatic compaction completion/cooldown runs after hook block or body error, while start-event failure leaks ownership."))
   #hasheq((id . W0-F5) (classification . DEFERRED) (severity . medium) (owner . runtime-retry) (follow-up . "W4 #9246 terminal decision") (summary . "Retry sleep is not cancellation-aware and partial wrapping can hide retry metadata.")))))
