#lang racket/base

;; scripts/analyze-coverage.rkt --- Static test-coverage analysis
;;
;; Scans target Racket source modules, identifies top-level `define` forms
;; (functions, values, parameters, structs), finds test files that require
;; the module, and counts how many definitions are referenced in tests.
;;
;; Usage:
;;   racket scripts/analyze-coverage.rkt <module-path> [module-path ...]
;;
;; Outputs Markdown to stdout.

(require racket/string
         racket/list
         racket/file
         racket/path
         racket/match
         racket/port)

;; ---------------------------------------------------------------------------
;; Helpers
;; ---------------------------------------------------------------------------

(define (file->lines path)
  (with-handlers ([exn:fail? (lambda (_) (list))])
    (port->lines (open-input-file path))))

(define (file->string path)
  (with-handlers ([exn:fail? (lambda (_) "")])
    (port->string (open-input-file path))))

;; ---------------------------------------------------------------------------
;; Extract top-level definitions from source
;; ---------------------------------------------------------------------------

(define (extract-definitions lines)
  "Return list of top-level defined names (define, struct)."
  (define def-pat #px"^\\(define\\s+(?:\\s*\\(\\s*)?([a-zA-Z][-a-zA-Z0-9?*+!]+)")
  (define struct-pat #px"^\\(struct\\s+\\(?\\s*([a-zA-Z][-a-zA-Z0-9?*+!]+)")

  (define (first-name line)
    (or (let ([m (regexp-match def-pat line)]) (and m (cadr m)))
        (let ([m (regexp-match struct-pat line)]) (and m (cadr m)))
        #f))

  (define names
    (for/list ([line (in-list lines)]
               #:when (and (not (regexp-match #px"^\\(provide" line))
                           (not (regexp-match #px"^\\(require" line))
                           (not (regexp-match #px"^\\s*;" line)))
               [n (in-value (first-name line))]
               #:when n)
      n))
  (reverse (remove-duplicates (reverse names) string=?)))

;; ---------------------------------------------------------------------------
;; Find test files that require the module
;; ---------------------------------------------------------------------------

(define (find-test-files module-path)
  "Return list of test file paths that require the given module."
  (define path-no-ext (string-replace module-path ".rkt" ""))
  (define patterns
    (list (format "../~a" module-path)
          (format "../../~a" module-path)
          (format "../~a" path-no-ext)
          (format "../../~a" path-no-ext)))
  (with-handlers ([exn:fail? (lambda (_) (list))])
    (for/list ([f (in-directory "tests")]
               #:when (and (file-exists? f)
                           (string-suffix? (path->string f) ".rkt")
                           (not (string-contains? (path->string f) "/compiled/")))
               [content (in-value (file->string f))]
               #:when (ormap (lambda (p) (string-contains? content p)) patterns))
      (path->string (find-relative-path (current-directory) f)))))

;; ---------------------------------------------------------------------------
;; Count tested definitions
;; ---------------------------------------------------------------------------

(define (count-tested defs test-files)
  "Return (values total tested tested-names untested-names)."
  (define combined (apply string-append (map file->string test-files)))
  (define-values (tested untested) (partition (lambda (n) (string-contains? combined n)) defs))
  (values (length defs) (length tested) tested untested))

;; ---------------------------------------------------------------------------
;; Heuristic module classifier
;; ---------------------------------------------------------------------------

(define (classify-module content)
  (cond
    [(string-contains? content "emit-typed-event!") (values "effectful" "Emits typed events")]
    [(string-contains? content "emit-session-event!") (values "effectful" "Emits session events")]
    [(string-contains? content "subprocess") (values "effectful" "Uses subprocess")]
    [else (values "pure" "Pure function module")]))

;; ---------------------------------------------------------------------------
;; Report generation
;; ---------------------------------------------------------------------------

(define (generate-report module-paths)
  (printf "# Test Coverage Report\n\n")
  (printf "Generated by `scripts/analyze-coverage.rkt`.\n\n")
  (printf "| Module | Type | Total Defs | Tested Defs | Coverage |\n")
  (printf "|--------|------|-----------:|------------:|--------:|\n")

  (define results
    (for/list ([mp (in-list module-paths)])
      (define src (file->string mp))
      (define lines (file->lines mp))
      (define defs (extract-definitions lines))
      (define-values (mod-type mod-desc) (classify-module src))
      (define test-files (find-test-files mp))
      (define-values (total tested tested-names untested-names) (count-tested defs test-files))
      (define pct
        (if (= total 0)
            100.0
            (/ (round (* (/ tested total) 1000.0)) 10.0)))
      (printf "| `~a` | ~a | ~a | ~a | ~a%% |\n" mp mod-type total tested pct)
      (list mp mod-type mod-desc defs total tested tested-names untested-names pct test-files)))

  (printf "\n")

  ;; Detail per module
  (for ([r (in-list results)])
    (match-define (list mp
                        mod-type
                        mod-desc
                        defs
                        total
                        tested
                        tested-names
                        untested-names
                        pct
                        test-files)
      r)
    (printf "---\n\n")
    (printf "## Module: `~a`\n\n" mp)
    (printf "- **Classification**: ~a (~a)\n" mod-type mod-desc)
    (printf "- **Coverage**: ~a%% (~a/~a definitions tested)\n" pct tested total)
    (if (pair? test-files)
        (begin
          (printf "- **Test files**:\n")
          (for ([tf (in-list test-files)])
            (printf "  - `~a`\n" tf)))
        (printf "- **No test files found** --- module has no test coverage.\n"))
    (printf "\n### Definitions\n\n| Name | Tested? |\n|------|--------:|\n")
    (for ([d (in-list defs)])
      (printf "| `~a` | ~a |\n" d (if (member d tested-names string=?) "Yes" "No")))
    (when (pair? untested-names)
      (printf "\n### Untested Definitions\n\n")
      (for ([d (in-list untested-names)])
        (printf "- `~a`\n" d))))

  ;; Summary
  (printf "\n---\n\n")
  (printf "## Summary\n\n")
  (define below
    (filter values
            (for/list ([r (in-list results)])
              (match-define (list mp _ _ _ _ _ _ _ pct _) r)
              (and (< pct 60.0) mp))))
  (if (pair? below)
      (begin
        (printf "### Modules below 60%% coverage threshold\n\n")
        (for ([mp (in-list below)])
          (printf "- `~a`\n" mp))
        (printf "\n"))
      (printf "All modules meet the 60%% coverage threshold.\n\n"))

  ;; CI note
  (printf "### CI Integration\n\n")
  (printf "Current CI (`.github/workflows/ci.yml`) does **not** include a coverage step.\n")
  (printf "To add: run this script and gate on <60%% modules.\n\n")

  (void))

;; ---------------------------------------------------------------------------
;; Entry
;; ---------------------------------------------------------------------------

(define (main args)
  (cond
    [(null? args)
     (displayln "Usage: racket scripts/analyze-coverage.rkt <module-path> ...")
     (exit 1)]
    [else (generate-report args)]))

(main (vector->list (current-command-line-arguments)))
