#lang racket/base

;; agent/event-structs.rkt -- facade re-exporting all event struct definitions
;;
;; ARCH-05: Decomposed into focused sub-modules:
;;   - event-structs/base.rkt            -- typed-event base struct
;;   - event-structs/turn-events.rkt     -- turn start/end events
;;   - event-structs/message-events.rkt  -- message lifecycle events
;;   - event-structs/tool-events.rkt     -- tool execution + per-tool events
;;   - event-structs/provider-events.rkt -- provider/LLM events
;;   - event-structs/session-events.rkt  -- session/input/model/agent/context events
;;   - event-structs/iteration-events.rkt -- auto-retry/compaction/injection events
;;   - event-structs/hook-events.rkt     -- hook interception events
;;   - event-structs/stream-events.rkt   -- streaming events
;;
;; This file re-exports everything for backward compatibility.
;; W11 (v0.72.6): Replaced wildcard re-exports with explicit identifier lists
;; to prevent accidental export leakage from sub-module changes.
;;
;; v0.30.6 status: 30+ typed event structs across 9 sub-modules.
;;
;; v0.96.1: Event API classification:
;;   PUBLIC (extension-facing, stability commitment):
;;     typed-event, context-event, injection-event, turn-start-event
;;     These are consumed by extensions/, gui/, tui/ and changing their
;;     field names or removing accessors is a BREAKING CHANGE.
;;   INTERNAL (runtime-internal, no stability commitment):
;;     All other events. Consumers are in agent/, runtime/, llm/, tools/.
;;     Field names may change between minor versions.

(require "event-structs/base.rkt"
         "event-structs/turn-events.rkt"
         "event-structs/message-events.rkt"
         "event-structs/tool-events.rkt"
         "event-structs/provider-events.rkt"
         "event-structs/session-events.rkt"
         "event-structs/iteration-events.rkt"
         "event-structs/hook-events.rkt"
         "event-structs/stream-events.rkt"
         ;; F10: browser events re-exported from facade
         (only-in "../browser/events.rkt"
                  browser-session-opened-event
                  browser-session-opened-event?
                  make-browser-session-opened-event
                  browser-session-opened-event-type
                  browser-session-opened-event-fields
                  browser-session-closed-event
                  browser-session-closed-event?
                  make-browser-session-closed-event
                  browser-session-closed-event-type
                  browser-session-closed-event-fields
                  browser-action-started-event
                  browser-action-started-event?
                  make-browser-action-started-event
                  browser-action-started-event-type
                  browser-action-started-event-fields
                  browser-action-completed-event
                  browser-action-completed-event?
                  make-browser-action-completed-event
                  browser-action-completed-event-type
                  browser-action-completed-event-fields
                  browser-action-failed-event
                  browser-action-failed-event?
                  make-browser-action-failed-event
                  browser-action-failed-event-type
                  browser-action-failed-event-fields
                  browser-page-loaded-event
                  browser-page-loaded-event?
                  make-browser-page-loaded-event
                  browser-page-loaded-event-type
                  browser-page-loaded-event-fields
                  browser-policy-blocked-event
                  browser-policy-blocked-event?
                  make-browser-policy-blocked-event
                  browser-policy-blocked-event-type
                  browser-policy-blocked-event-fields
                  browser-sidecar-started-event
                  browser-sidecar-started-event?
                  make-browser-sidecar-started-event
                  browser-sidecar-started-event-type
                  browser-sidecar-started-event-fields
                  browser-sidecar-stopped-event
                  browser-sidecar-stopped-event?
                  make-browser-sidecar-stopped-event
                  browser-sidecar-stopped-event-type
                  browser-sidecar-stopped-event-fields
                  browser-screenshot-captured-event
                  browser-screenshot-captured-event?
                  make-browser-screenshot-captured-event
                  browser-screenshot-captured-event-type
                  browser-screenshot-captured-event-fields))

;; From event-structs/base.rkt
;; PUBLIC API — stable for extensions
;; Explicit re-exports from event-structs/base.rkt — do NOT use all-from-out (ADR-0028)
(provide typed-event
         typed-event?
         typed-event-type
         typed-event-timestamp
         typed-event-session-id
         typed-event-turn-id
         ;; Explicit re-exports from event-structs/turn-events.rkt — do NOT use all-from-out (ADR-0028)
         turn-start-event
         turn-start-event?
         turn-start-event-model
         turn-start-event-provider
         make-turn-start-event
         turn-start-event-type
         turn-start-event-fields
         turn-end-event
         turn-end-event?
         turn-end-event-reason
         turn-end-event-duration-ms
         make-turn-end-event
         turn-end-event-type
         turn-end-event-fields
         ;; Explicit re-exports from event-structs/message-events.rkt — do NOT use all-from-out (ADR-0028)
         message-start-event
         message-start-event?
         message-start-event-role
         message-start-event-model
         make-message-start-event
         message-start-event-type
         message-start-event-fields
         message-update-event
         message-update-event?
         message-update-event-content
         message-update-event-delta
         make-message-update-event
         message-update-event-type
         message-update-event-fields
         message-end-event
         message-end-event?
         message-end-event-role
         message-end-event-content-length
         make-message-end-event
         message-end-event-type
         message-end-event-fields
         ;; Explicit re-exports from event-structs/tool-events.rkt — do NOT use all-from-out (ADR-0028)
         tool-execution-start-event
         tool-execution-start-event?
         tool-execution-start-event-tool-name
         tool-execution-start-event-tool-call-id
         make-tool-execution-start-event
         tool-execution-start-event-type
         tool-execution-start-event-fields
         tool-execution-update-event
         tool-execution-update-event?
         tool-execution-update-event-tool-name
         tool-execution-update-event-progress
         make-tool-execution-update-event
         tool-execution-update-event-type
         tool-execution-update-event-fields
         tool-execution-end-event
         tool-execution-end-event?
         tool-execution-end-event-tool-name
         tool-execution-end-event-duration-ms
         tool-execution-end-event-result-summary
         tool-execution-end-event-result-error
         make-tool-execution-end-event
         tool-execution-end-event-type
         tool-execution-end-event-fields
         tool-call-event
         tool-call-event?
         tool-call-event-tool-name
         tool-call-event-arguments
         tool-call-event-tool-call-id
         make-tool-call-event
         tool-call-event-type
         tool-call-event-fields
         tool-result-event
         tool-result-event?
         tool-result-event-tool-call-id
         tool-result-event-content
         tool-result-event-is-error?
         make-tool-result-event
         tool-result-event-type
         tool-result-event-fields
         struct:bash-tool-call-event
         bash-tool-call-event
         bash-tool-call-event?
         bash-tool-call-event-command
         bash-tool-call-event-timeout
         bash-tool-call-event-cwd
         make-bash-tool-call-event
         bash-tool-call-event-fields
         struct:edit-tool-call-event
         edit-tool-call-event
         edit-tool-call-event?
         edit-tool-call-event-path
         edit-tool-call-event-edits
         make-edit-tool-call-event
         edit-tool-call-event-fields
         struct:write-tool-call-event
         write-tool-call-event
         write-tool-call-event?
         write-tool-call-event-path
         write-tool-call-event-content
         make-write-tool-call-event
         write-tool-call-event-fields
         struct:read-tool-call-event
         read-tool-call-event
         read-tool-call-event?
         read-tool-call-event-path
         read-tool-call-event-offset
         read-tool-call-event-limit
         make-read-tool-call-event
         read-tool-call-event-fields
         struct:grep-tool-call-event
         grep-tool-call-event
         grep-tool-call-event?
         grep-tool-call-event-pattern
         grep-tool-call-event-path
         grep-tool-call-event-glob
         make-grep-tool-call-event
         grep-tool-call-event-fields
         struct:find-tool-call-event
         find-tool-call-event
         find-tool-call-event?
         find-tool-call-event-pattern
         find-tool-call-event-path
         make-find-tool-call-event
         find-tool-call-event-fields
         struct:custom-tool-call-event
         custom-tool-call-event
         custom-tool-call-event?
         make-custom-tool-call-event
         custom-tool-call-event-fields
         ;; Explicit re-exports from event-structs/provider-events.rkt — do NOT use all-from-out (ADR-0028)
         provider-request-event
         provider-request-event?
         provider-request-event-model
         provider-request-event-provider
         make-provider-request-event
         provider-request-event-type
         provider-request-event-fields
         provider-response-event
         provider-response-event?
         provider-response-event-model
         provider-response-event-provider
         provider-response-event-latency-ms
         make-provider-response-event
         provider-response-event-type
         provider-response-event-fields
         model-stream-delta-event
         model-stream-delta-event?
         model-stream-delta-event-delta
         model-stream-delta-event-model
         make-model-stream-delta-event
         model-stream-delta-event-type
         model-stream-delta-event-fields
         model-stream-thinking-event
         model-stream-thinking-event?
         model-stream-thinking-event-thinking
         model-stream-thinking-event-model
         make-model-stream-thinking-event
         model-stream-thinking-event-type
         model-stream-thinking-event-fields
         model-stream-completed-event
         model-stream-completed-event?
         model-stream-completed-event-model
         model-stream-completed-event-provider
         make-model-stream-completed-event
         model-stream-completed-event-type
         model-stream-completed-event-fields
         ;; Explicit re-exports from event-structs/session-events.rkt — do NOT use all-from-out (ADR-0028)
         session-start-event
         session-start-event?
         session-start-event-model
         make-session-start-event
         session-start-event-type
         session-start-event-fields
         session-shutdown-event
         session-shutdown-event?
         session-shutdown-event-reason
         make-session-shutdown-event
         session-shutdown-event-type
         session-shutdown-event-fields
         input-event
         input-event?
         input-event-input-type
         input-event-content
         make-input-event
         input-event-type
         input-event-fields
         model-select-event
         model-select-event?
         model-select-event-model
         model-select-event-provider
         make-model-select-event
         model-select-event-type
         model-select-event-fields
         agent-start-event
         agent-start-event?
         agent-start-event-model
         make-agent-start-event
         agent-start-event-type
         agent-start-event-fields
         agent-end-event
         agent-end-event?
         agent-end-event-reason
         agent-end-event-duration-ms
         make-agent-end-event
         agent-end-event-type
         agent-end-event-fields
         context-event
         context-event?
         context-event-token-count
         context-event-window-size
         make-context-event
         context-event-type
         context-event-fields
         context-assembled-event
         context-assembled-event?
         context-assembled-event-iteration
         context-assembled-event-total-messages
         context-assembled-event-assembled-messages
         context-assembled-event-token-count
         context-assembled-event-working-set-entries
         context-assembled-event-working-set-tokens
         make-context-assembled-event
         context-assembled-event-type
         context-assembled-event-fields
         context-blocked-event
         context-blocked-event?
         context-blocked-event-reason
         make-context-blocked-event
         context-blocked-event-type
         context-blocked-event-fields
         working-set-injected-event
         working-set-injected-event?
         working-set-injected-event-entries
         working-set-injected-event-tokens
         make-working-set-injected-event
         working-set-injected-event-type
         working-set-injected-event-fields
         context-assembly-detail-event
         context-assembly-detail-event?
         context-assembly-detail-event-total-messages
         context-assembly-detail-event-tier-a-count
         context-assembly-detail-event-tier-b-count
         context-assembly-detail-event-tier-c-count
         context-assembly-detail-event-excluded-count
         context-assembly-detail-event-excluded-ids
         context-assembly-detail-event-summary-length
         context-assembly-detail-event-gsd-pinned-count
         context-assembly-detail-event-ws-entry-count
         context-assembly-detail-event-ws-tokens
         context-assembly-detail-event-cache-hit-p
         make-context-assembly-detail-event
         context-assembly-detail-event-type
         context-assembly-detail-event-fields
         goal-start-event
         goal-start-event?
         goal-start-event-goal-text
         goal-start-event-max-turns
         goal-start-event-checks
         make-goal-start-event
         goal-start-event-type
         goal-start-event-fields
         goal-turn-start-event
         goal-turn-start-event?
         goal-turn-start-event-turn-number
         goal-turn-start-event-goal-text
         make-goal-turn-start-event
         goal-turn-start-event-type
         goal-turn-start-event-fields
         goal-evaluated-event
         goal-evaluated-event?
         goal-evaluated-event-achieved?
         goal-evaluated-event-reason
         goal-evaluated-event-turn-number
         goal-evaluated-event-token-cost
         make-goal-evaluated-event
         goal-evaluated-event-type
         goal-evaluated-event-fields
         goal-check-event
         goal-check-event?
         goal-check-event-label
         goal-check-event-exit-code
         goal-check-event-timed-out?
         goal-check-event-stdout
         goal-check-event-stderr
         make-goal-check-event
         goal-check-event-type
         goal-check-event-fields
         goal-achieved-event
         goal-achieved-event?
         goal-achieved-event-goal-text
         goal-achieved-event-turns-used
         goal-achieved-event-total-token-cost
         make-goal-achieved-event
         goal-achieved-event-type
         goal-achieved-event-fields
         goal-failed-event
         goal-failed-event?
         goal-failed-event-goal-text
         goal-failed-event-reason
         goal-failed-event-turns-used
         make-goal-failed-event
         goal-failed-event-type
         goal-failed-event-fields
         ;; Explicit re-exports from event-structs/iteration-events.rkt — do NOT use all-from-out (ADR-0028)
         auto-retry-event
         auto-retry-event?
         auto-retry-event-attempt
         auto-retry-event-max-attempts
         auto-retry-event-error-type
         make-auto-retry-event
         auto-retry-event-type
         auto-retry-event-fields
         auto-retry-start-event
         auto-retry-start-event?
         auto-retry-start-event-attempt
         auto-retry-start-event-max-retries
         auto-retry-start-event-delay-ms
         auto-retry-start-event-error
         auto-retry-start-event-error-type
         make-auto-retry-start-event
         auto-retry-start-event-type
         auto-retry-start-event-fields
         compaction-event
         compaction-event?
         compaction-event-reason
         compaction-event-tokens-before
         compaction-event-tokens-after
         make-compaction-event
         compaction-event-type
         compaction-event-fields
         injection-event
         injection-event?
         injection-event-source
         injection-event-content-type
         injection-event-content-length
         injection-event-message
         make-injection-event
         injection-event-type
         injection-event-fields
         iteration-decision-event
         iteration-decision-event?
         iteration-decision-event-iteration
         iteration-decision-event-termination
         iteration-decision-event-consecutive-tools
         iteration-decision-event-max-iterations
         iteration-decision-event-max-iterations-hard
         make-iteration-decision-event
         iteration-decision-event-type
         iteration-decision-event-fields
         ;; Explicit re-exports from event-structs/hook-events.rkt — do NOT use all-from-out (ADR-0028)
         model-request-blocked-event
         model-request-blocked-event?
         model-request-blocked-event-reason
         make-model-request-blocked-event
         model-request-blocked-event-type
         model-request-blocked-event-fields
         message-blocked-event
         message-blocked-event?
         message-blocked-event-hook
         message-blocked-event-reason
         make-message-blocked-event
         message-blocked-event-type
         message-blocked-event-fields
         turn-cancelled-event
         turn-cancelled-event?
         turn-cancelled-event-reason
         turn-cancelled-event-iteration
         make-turn-cancelled-event
         turn-cancelled-event-type
         turn-cancelled-event-fields
         assistant-message-completed-event
         assistant-message-completed-event?
         assistant-message-completed-event-content-length
         make-assistant-message-completed-event
         assistant-message-completed-event-type
         assistant-message-completed-event-fields
         ;; Explicit re-exports from event-structs/stream-events.rkt — do NOT use all-from-out (ADR-0028)
         stream-completed-event
         stream-completed-event?
         stream-completed-event-usage
         stream-completed-event-finish_reason
         stream-completed-event-truncated?
         make-stream-completed-event
         stream-completed-event-type
         stream-completed-event-fields
         stream-delta-event
         stream-delta-event?
         stream-delta-event-delta
         make-stream-delta-event
         stream-delta-event-type
         stream-delta-event-fields
         stream-tool-call-delta-event
         stream-tool-call-delta-event?
         stream-tool-call-delta-event-delta-tool-call
         make-stream-tool-call-delta-event
         stream-tool-call-delta-event-type
         stream-tool-call-delta-event-fields
         stream-thinking-event
         stream-thinking-event?
         stream-thinking-event-delta
         make-stream-thinking-event
         stream-thinking-event-type
         stream-thinking-event-fields
         stream-message-start-event
         stream-message-start-event?
         stream-message-start-event-message-id
         make-stream-message-start-event
         stream-message-start-event-type
         stream-message-start-event-fields
         stream-message-delta-event
         stream-message-delta-event?
         stream-message-delta-event-text
         stream-message-delta-event-message-id
         make-stream-message-delta-event
         stream-message-delta-event-type
         stream-message-delta-event-fields
         stream-message-end-event
         stream-message-end-event?
         stream-message-end-event-message-id
         stream-message-end-event-usage
         make-stream-message-end-event
         stream-message-end-event-type
         stream-message-end-event-fields
         stream-turn-completed-event
         stream-turn-completed-event?
         stream-turn-completed-event-termination
         stream-turn-completed-event-turn-id-str
         stream-turn-completed-event-reason
         make-stream-turn-completed-event
         stream-turn-completed-event-type
         stream-turn-completed-event-fields
         stream-turn-cancelled-event
         stream-turn-cancelled-event?
         stream-turn-cancelled-event-reason
         make-stream-turn-cancelled-event
         stream-turn-cancelled-event-type
         stream-turn-cancelled-event-fields
         stream-tool-call-started-event
         stream-tool-call-started-event?
         stream-tool-call-started-event-id
         stream-tool-call-started-event-name
         stream-tool-call-started-event-arguments
         make-stream-tool-call-started-event
         stream-tool-call-started-event-type
         stream-tool-call-started-event-fields
         stream-assistant-msg-completed-event
         stream-assistant-msg-completed-event?
         stream-assistant-msg-completed-event-message-id
         stream-assistant-msg-completed-event-content
         make-stream-assistant-msg-completed-event
         stream-assistant-msg-completed-event-type
         stream-assistant-msg-completed-event-fields
         ;; Browser events
         browser-session-opened-event
         browser-session-opened-event?
         make-browser-session-opened-event
         browser-session-opened-event-type
         browser-session-opened-event-fields
         browser-session-closed-event
         browser-session-closed-event?
         make-browser-session-closed-event
         browser-session-closed-event-type
         browser-session-closed-event-fields)
