#hash((status . "current")
      (milestone . 840)
      (wave . "W0")
      (issue . 8786)
      (branch . "feature/wave-8786")
      (implementation-sha . "e12e800585631596151215f6f67835ea5c725aa2")
      (content-digest . "d0ce9a4c4bd565353213cff2a187422461ad9e431e94e0f9f25e700737b4090e")
      (red-first . #hash((command . "racket -e '(require \"scripts/run-tests/classify.rkt\") (define all (collect-test-files (quote workflows))) (define s0 (shard-files all 0 2)) (define s1 (shard-files all 1 2)) (printf \"~a ~a ~a\" (length all) (length s0) (length s1))'")
                         (failure . "28 files, need 14+14 split")))
      (focused-tests . #hash((command . "racket -e '(require \"scripts/run-tests/classify.rkt\") ...'")
                             (result . "passed")
                             (tests . 3)
                             (description . "shard split correctness, union equality, overlap check")))
      (format-compile . #hash((result . "passed")
                              (command . "rm -rf compiled/; raco make main.rkt")))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 23)
                    (warnings . 1)
                    (warning-detail . "release-readiness (non-blocking, pre-existing)")))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1044)
                    (tests . 15314)
                    (ci-verified . #t)))
      (review-artifact . "docs/reports/gsd-wave-reviews/ci-accel-p2-w0.rktd")
      (remaining-items . ())
      (planning-sync . "current"))