#hash((status . "current")
      (milestone . 839)
      (wave . "W0")
      (issue . 8780)
      (branch . "feature/ci-accel-w0-shard-support")
      (implementation-sha . "57b2a7677f10aa73d1742c83811c874d6285c8cf")
      (content-digest . "7f089dfb979f3b604031244fe7bfac7cbd45e20cedc78b18018aef49c698446e")
      (red-first . #hash((command . "raco test tests/test-run-tests-shard.rkt")
                         (failure . "shard-files, platform-file?, and platform suite did not exist")))
      (focused-tests . #hash((command . "raco test tests/test-run-tests-shard.rkt tests/test-run-tests-arg-validation.rkt tests/test-run-tests-profiles.rkt tests/test-run-tests-script.rkt")
                             (result . "passed")
                             (tests . 38)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i; rm -rf compiled/; raco make main.rkt")))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 23)
                    (warnings . 1)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1039)
                    (tests . 15314)))
      (review-artifact . "docs/reports/gsd-wave-reviews/ci-accel-w0.rktd")
      (remaining-items . ())
      (planning-sync . "current"))
