#hash((status . "current")
      (milestone . 839)
      (wave . "W1")
      (issue . 8781)
      (branch . "feature/ci-accel-w1-workflow-restructure")
      (implementation-sha . "96d76d22f0f0c50ba756e38005bc270484361ce9")
      (content-digest . "d46c956ba05b7c78874044527dd92c782ebd16d064df29c3eb03e1b8d7b04b18")
      (red-first . #hash((command . "python3 -c 'import yaml; yaml.safe_load(open(\".github/workflows/ci.yml\"))'")
                         (failure . "no shard support, no platform suite, inter-wave-gate redundant")))
      (focused-tests . #hash((command . "raco test tests/test-run-tests-shard.rkt")
                             (result . "passed")
                             (tests . 15)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i; rm -rf compiled/; raco make main.rkt")))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 23)
                    (warnings . 1)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1039)
                    (tests . 15314)))
      (review-artifact . "docs/reports/gsd-wave-reviews/ci-accel-w1.rktd")
      (remaining-items . ())
      (planning-sync . "current"))
