#hash((status . "current")
      (milestone . 840)
      (wave . "W1")
      (issue . 8788)
      (branch . "feature/wave-8788")
      (implementation-sha . "a68cd8f73ae4a0078cc4a49e55b5b322056a565e")
      (content-digest . "c15ba1b3572b61bf6a72e2e63c98b9f3455167abad6d3492d386103c46375eeb")
      (red-first . #hash((command . "python3 -c 'import yaml; ...'")
                         (failure . "lint-alignment present as separate job, gsd-governance runs on PRs")))
      (focused-tests . #hash((command . "python3 -c 'import yaml; d=yaml.safe_load(open(\".github/workflows/ci.yml\")); ...'")
                             (result . "passed")
                             (tests . 3)
                             (description . "lint-alignment absent, gsd-governance push-only, lint has alignment step")))
      (format-compile . #hash((result . "passed")
                              (command . "raco make main.rkt")))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 23)
                    (warnings . 1)
                    (warning-detail . "release-readiness (non-blocking, pre-existing)")))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1044)
                    (tests . 15314)
                    (ci-verified . #t)))
      (review-artifact . "docs/reports/gsd-wave-reviews/ci-accel-p2-w1.rktd")
      (remaining-items . ())
      (planning-sync . "current"))