#hasheq(
  (branch . "binding/fb67e0429ed1-w7")
  (content-digest . "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")
  (delivery-head-sha . "435d59031c77c0fa421da60b8cc42b7e7a75bbf3")
  (delivery-pr . 9755)
  (fast . #hasheq(
    (command . "racket scripts/run-tests.rkt --suite fast, 12 jobs, profile=local, at the merge head 0cf48cb0 (the binding publication changes no source, so this measures the delivered code)")
    (details . "1209 files, 1209 passed, 0 failed, 0 timeouts; 17996 tests, 17996 passed, 0 failed; 26m36.852s, exit 0. The progress-dot count in the log is 1209, matching the file count, and the RUN-SUMMARY runner-version is 1.00.31, matching util/version.rkt. The independent binding reviewer verified this from the captured log rather than re-running the 27-minute suite, and recorded that substitution in its NOT-RUN register instead of reporting a re-run it did not perform.")
    (result . "passed")
    (run-summary . "RUN-SUMMARY runner-version=1.00.31 suite=fast profile=local shard=none execution-mode=subprocess file-count=1209 pass=1209 fail=0 timeout=0 skip=0 wall-clock-seconds=1596.852 metadata-completeness=explicit:1180/heuristic:0/missing:29")
  ))
  (focused-tests . #hasheq(
    (command . "racket scripts/run-tests.rkt on each of the four files the W7 repairs touch (test-worker-security.rkt, test-runner-base-dir-resolution.rkt, test-wave-integrity-adversarial.rkt, test-release-entry-current.rkt), and on the release-surface set (test-version.rkt, test-lint-release-readiness.rkt, test-lint-release-notes.rkt, test-release-workflow-contract.rkt)")
    (details . "At the merge head 0cf48cb0, and re-run independently by the binding reviewer in this same worktree with the same results: the four files give 38 + 4 + 8 + 5 = 55 tests, 0 failed, each with runner exit 0; the release-surface set gives 4 files and 109 tests, 0 failed, exit 0. Counts are read from the runner's own \"Tests: N total, N passed, 0 failed\" line rather than inferred from an exit code, because a bare exit code is exactly the vacuous green this wave exists to police. The project runner is authoritative here; bare raco test is not, because it can exit 0 without running anything in a module+main file.")
    (result . "passed")
  ))
  (format-compile . #hasheq(
    (command . "raco make over each .rkt file changed between base 50bdf7334a9161e9e930b40be0870c52a498a0b9 and the merge head, then raco fmt per file compared against the file on disk - the same canonicality test scripts/pre-commit.rkt check-fmt-canonical performs. The binding publication itself changes no source.")
    (details . "29 changed .rkt files at the merge head: 29 compiled with raco make, 29 canonical, 0 not-canonical, 0 fmt-error. The independent binding reviewer re-derived the count of 29 from git and spot-checked five files end to end (util/version.rkt, test-worker-security.rkt, test-wave-integrity-adversarial.rkt, test-runner-base-dir-resolution.rkt, test-milestone-gate.rkt), all compiling and canonical, and recorded in its NOT-RUN register that the other 24 were not individually re-run and rest on this measurement. The count here is the observed one and the spot-check scope is stated rather than implied.")
    (result . "passed")
  ))
  (implementation-sha . "0cf48cb0018c08329179f83fd9c626e65dfc8589")
  (issue . 9730)
  (lint . #hasheq(
    (command . "racket scripts/lint-all.rkt, check-version-expectations.rkt, metrics.rkt --lint, sync-readme-status.rkt --check, and verify-artifact-provenance.rkt at the default root and with --current-wave v1.00.31-w7 and --current-wave v1.00.31-w6")
    (details . "At the merge head 0cf48cb0: lint-all 23 passed, 0 failed, 2 non-blocking warnings (arch; release-readiness is the branch-gated gate recorded as deferred in release-preflight.json, not a failure). Version-expectation lint PASSED over 1511 test files with 0 hard-coded \"1.00.31\" literals. All 5 static metrics match README.md; the README Status block is in sync with the CHANGELOG. Artifact provenance ok with 952 notes at the default root, 950 for --current-wave v1.00.31-w7 and 951 for --current-wave v1.00.31-w6. Every one of these was re-run independently by the binding reviewer in this worktree and every number reproduced exactly.")
    (result . "passed")
  ))
  (merge-sha . "0cf48cb0018c08329179f83fd9c626e65dfc8589")
  (merged-at . "2026-09-27T07:24:43Z")
  (milestone . 896)
  (notes . "This is the campaign-binding validation record for W7, written on the merge head 0cf48cb0018c08329179f83fd9c626e65dfc8589 on a fresh-main worktree. Every number in the five gate-evidence fields above was measured at that head in that worktree and re-run independently by the binding reviewer; where the reviewer substituted log verification or a sample for a full re-run, this record says so rather than implying a re-run that did not happen. The independent binding review's round 1 returned CHANGES-REQUESTED on exactly one point - the remaining-items owner was still a PENDING sentinel, which the strict gate rejects - and that field is finalized here. No other field was changed in response to it.")
  (plan-id . "fb67e0429ed155a4b4e3f31afe3ef3ca7748ee891c06247b11e5e2a86cfebd75")
  (planning-sync . "current")
  (red-first . #hasheq(
    (command . "The BUG-0009 version-expectation sweep, at the W7 content head and re-verified by the independent binding review: a scratch worktree with the version bumped to 1.00.31 and the 15 swept test files reverted to base, then racket scripts/check-version-expectations.rkt run with that scratch tree as cwd. The lint resolves util/version.rkt relative to the cwd, so running the script by absolute path from another tree reports the wrong tree and yields a false PASS. Second red-first: tests/test-worker-security.rkt with the W2 checks restored to their pre-fix form, run through racket scripts/run-tests.rkt.")
    (failure . "First, with util/version.rkt at 1.00.31 and the pre-derivation test content, the version-expectation lint exits 1 with \"FAIL: 56 hard-coded version literal(s) \\\"1.00.31\\\" in tests/ (derive from q-version instead)\" across 15 test files, each of which would have gone green forever and silently pinned a stale expectation after the next bump. Second, the W2 check defect was an invisible failure rather than a red one: the same breakage read \"Tests: 33 total, 33 passed\" with exit 0 before the fix and \"Tests: 38 total, 35 passed, 3 failed\" after the W2 checks were wired into run-tests, which is the worse of the two defects because it is a green light built on a detector that cannot fail. Both captures are retained at artifacts/wave-delivery-integrity/v1.00.31-w7/raw/red-first-version-expectations.txt and raw/red-first-worker-security-w2.txt, and the independent binding reviewer read both and quoted the failing assertions from them.")
  ))
  (remaining-items . (
    #hasheq(
      (classification . "deferred-noncritical")
      (label . "deferred-by-design: post-merge-release-gate")
      (owner . "coordinator (post-merge release step)")
      (rationale . "lint-release-readiness --strict is branch-gated: it requires the release commit to be on main and requires .gate-evidence for the fast, tui, arch and workflows suites naming the release SHA and version. It therefore runs on clean main after this wave merges and before the annotated v1.00.31 tag is pushed, together with the full CI-strict tag-publish preflight. It has never been locally passed in this campaign and is recorded here as outstanding by design rather than reported as passing; the changelog says six of seven gates pass rather than all of them. This binding publication does not satisfy it and does not claim to.")
    )
    #hasheq(
      (classification . "noncritical")
      (label . "environmental-not-a-regression")
      (owner . "campaign backlog (local environment)")
      (rationale . "tests/test-browser-playwright-sidecar.rkt fails on this host because the playwright npm module does not resolve for the available node. It fails identically on main, the file is untouched by this wave, and the ci profile skips it. Recorded as a known local gap rather than a pass. Installing the module, or declaring the browser requirement for the local profile, is a follow-up rather than a change made during a release bake.")
    )
    #hasheq(
      (classification . "noncritical")
      (label . "follow-up-not-blocking")
      (owner . "campaign backlog (runner contract audit)")
      (rationale . "The runner treats a test file as failed purely on its exit code. W7 fixed the one file that defeated that contract (test-worker-security.rkt, whose W2 checks could not fail), and its red-first capture shows why the general property matters: a test file that swallows its own failures while exiting 0 reads as green. The general property is a property of rackunit structure rather than of this wave, and no other test file installs a custom current-check-handler. Worth a dedicated audit; not introduced or widened here.")
    )
    #hasheq(
      (classification . "noncritical")
      (label . "outstanding-coordinator-owned")
      (owner . "coordinator (hosted latency sample)")
      (rationale . "The v1.00.30 W4 frozen doc asks for the PR latency regime fingerprint for the guarded compiled-root pilot. The merge SHA is recorded (cc25b3663362d032b9a23a9d22f9dd5edbe637d8); the fingerprint needs a hosted latency sample on that exact head and is recorded as outstanding rather than estimated or back-filled. It is not a binding-completion gate.")
    )
  ))
  (required-pr-checks . ("lint" "lint-quality" "security" "release-dry-run" "workflows (0)" "workflows (1)" "workflows-aggregate" "smoke (ubuntu-latest)" "test (0)" "test (1)" "test (2)" "test-aggregate" "test-platform"))
  (review-artifact . "docs/reports/gsd-wave-reviews/fb67e0429ed155a4b4e3f31afe3ef3ca7748ee891c06247b11e5e2a86cfebd75-w7.rktd")
  (status . "current")
  (wave . "W7")
  (wave-branch . "campaign/v1.00.31-w7")
)
