#hash((status . "current")
      (milestone . 842)
      (wave . "W07")
      (issue . 8854)
      (implementation-sha . "6bdcfe3a7e225344322963d1f17235963ba21058")
      (content-digest . "af7c58089fe8b91ce88efed9cc68ce4afada0be239285c5bfa5d7168a210b19e")
      (branch . "v09955-w7-tooling-docs")
      (red-first . #hash((command . "raco test tests/test-milestone-gate.rkt tests/test-abstraction-audit.rkt")
                         (failure . "none — existing tests passed from clean state")))
      (focused-tests . #hash((result . "passed")
                             (count . 173)
                             (suites . "milestone (93), abstraction audit (80)")))
      (format-compile . #hash((result . "passed") (detail . "raco fmt -i + raco make main.rkt + raco make on all split scripts")))
      (lint . #hash((result . "passed") (detail . "23 passed, 1 non-blocking warning")))
      (fast . #hash((result . "passed") (detail . "smoke suite 289/289 passed in 71.0s")))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.55-w7.rktd")
      (before-after . #hash((CI-1 . #hash((before . "848L (abstraction-audit.rkt)")
                                          (after . "75L coordinator + 493L analysis + 314L report")))
                             (CI-2 . #hash((before . "816L (milestone-gate.rkt)")
                                          (after . "493L coordinator + 96L gate-evidence + 261L gate-claims")))
                             (D-1 . #hash((before . "158L (overview.md)")
                                          (after . "445L expanded overview")))))
      (remaining-items . ())
      (planning-sync . "current"))
