#hash((status . "current")
      (milestone . 845)
      (wave . "W03")
      (issue . 8875)
      (implementation-sha . "c35048530c10c298be724c28309800be696b87c3")
      (content-digest . "387f5fb12c87ce8303aeebd19b52da4d91cc0b1b120d625becd3c6b7bf0ad7e4")
      (branch . "v09958-w3-scripts-tui")
      (red-first . #hash((command . "raco test tests/test-abstraction-audit.rkt tests/test-run-tests-shard.rkt") (failure . "none — refactor preserves API surface via all-from-out re-exports")))
      (fast . #hash((result . "passed") (detail . "run-tests-shard (15), abstraction-audit (80), tui-terminal (44), clipboard (34)")))
      (focused-tests . #hash((result . "passed") (count . 173) (suites . "run-tests-shard (15), abstraction-audit (80), tui-terminal (44), clipboard (34)")))
      (format-compile . #hash((result . "passed") (detail . "raco fmt -i + raco make main.rkt")))
      (lint . #hash((result . "passed") (detail . "23 passed, 1 warning")))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.58-w3.rktd")
      (findings . #hash((P3-CL . #hash((status . "complete") (action . "extract-module") (detail . "classify-metadata.rkt (139L) + classify-filters.rkt (290L); classify.rkt facade (185L)")))
                         (P3-AN . #hash((status . "complete") (action . "refactor") (detail . "data-driven compute-summary; 493L->449L")))
                         (P3-TUI . #hash((status . "complete") (action . "dead-code-removal") (detail . "compute-layout-legacy, clipboard-copy wrapper, string-prefix? shadow")))
                         (P3-CH . #hash((status . "deferred") (action . "skip") (detail . "tight coupling to 20+ imports; risk outweighs P3 benefit")))
                         (P3-P . #hash((status . "deferred") (action . "skip") (detail . "10+ test consumers; removal cascade risk")))))
      (before-after . #hash((classify . #hash((before . "565L monolith") (after . "185L facade + 139L metadata + 290L filters")))
                             (abstraction-analysis . #hash((before . "493L") (after . "449L")))))
      (remaining-items . (#hash((id . "P3-CH") (classification . "deferred-noncritical") (owner . "post-v0.99.58") (rationale . "command-handlers.rkt /go helpers tightly coupled to 20+ imports; extraction risk outweighs P3 benefit. Tracked for future decomposition."))
                         #hash((id . "P3-P") (classification . "deferred-noncritical") (owner . "post-v0.99.58") (rationale . "protocol-types.rkt facade has 10+ test consumers; removal would cascade across test suite. Tracked for coordinated removal."))))
      (planning-sync . "current"))
