#hash((status . "current")
      (milestone . 837)
      (wave . "W6")
      (issue . 8736)
      (branch . "feature/v09951-w6-production-explorer")
      (implementation-sha . "7e0a91abea4b087774c589a31ca77d3ca205aae2")
      (content-digest . "9e9db010dc2e84d4b52e19e883f3744b0f5dca2ce5af0c4f5074a7d8e7261bed")
      (red-first . #hash((command . "raco test tests/test-tmux-explore-production-provenance.rkt")
                         (failure . "MAS verifier used mas.spawn-approval-decided (not production); provider confirmed by negative inference not positive identity; release-audit looked for non-existent release.authorization.refused event")))
      (focused-tests . #hash((command . "raco test tests/test-tmux-explore-production-provenance.rkt tests/test-tmux-explore-verifiers.rkt tests/test-tmux-explore-evidence.rkt tests/test-tmux-explore-executor.rkt tests/test-tmux-tui-explore.rkt tests/test-tmux-real-provider-docs.rkt tests/test-trace-logger.rkt")
                             (result . "passed")
                             (tests . 62)))
      (smoke . #hash((command . "racket scripts/run-tests.rkt --suite smoke --profile local")
                     (result . "passed")
                     (files . 19)
                     (tests . 289)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i changed Racket files; clean compiled directories; raco make main.rkt")))
      (architecture . #hash((command . "racket scripts/run-tests.rkt --suite arch --profile local")
                            (result . "passed")
                            (files . 14)
                            (tests . 182)))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 21)
                    (warnings . 2)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1036)
                    (tests . 15301)))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.51-w6.rktd")
      (remaining-items . ("Real-provider acceptance campaign: all nine scenarios must PASS at exact PR-head SHA before merge (credential-bearing run)"))
      (planning-sync . "current"))
