#hash((status . "current")
      (milestone . 844)
      (wave . "W01")
      (issue . 8867)
      (implementation-sha . "92c05dc6c72e16ddacc396a703c4ebec2c6b6e44")
      (content-digest . "d723499d46e0fd69c9fc8df1b2c87593b7355d6d317e9a394ca2c0ab90c4f34f")
      (branch . "v09957-w1-security-cli")
      (red-first . #hash((command . "raco test tests/test-cli-flags.rkt tests/test-subprocess.rkt") (failure . "none")))
      (focused-tests . #hash((result . "passed") (count . 111) (suites . "cli-flags (9), subprocess (29), settings (73)")))
      (format-compile . #hash((result . "passed") (detail . "raco fmt -i + raco make main.rkt")))
      (lint . #hash((result . "passed") (detail . "23 passed, 1 non-blocking (release-readiness)")))
      (fast . #hash((result . "passed") (detail . "smoke 289/289")))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.57-w1.rktd")
      (findings . #hash((S-1 . #hash((status . "complete") (action . "parameter-added") (detail . "current-secret-scrub-patterns replaces defaults when non-empty; wired through settings")))
                         (I-3 . #hash((status . "complete") (action . "split") (detail . "cli/args.rkt 634L -> 50L facade; 4 sub-modules created")))))
      (before-after . #hash((I-3 . #hash((before . "cli/args.rkt 634L monolithic") (after . "50L facade + 4 sub-modules (679L total)")))))
      (remaining-items . ())
      (planning-sync . "current"))
