#hash((status . "current")
      (milestone . 837)
      (wave . "W0")
      (issue . 8730)
      (branch . "feature/v09951-w0-gsd-merge-enforcement")
      (implementation-sha . "7d927ae60f7e79731fa1de06745521a86e9a8fcf")
      (content-digest . "9bbced853aa6b116abc0620295035c9f277ea06b30c29a63ef74aeeaf3db0ae9")
      (red-first . #hash((command . "raco test tests/test-claim-verifier.rkt tests/test-milestone-close-gate.rkt tests/test-milestone-gate.rkt; raco test tests/test-gsd-governance-workflow.rkt")
                         (failure . "Seven fail-open assertions reproduced empty claim/issue/gate acceptance and missing/pending/failed required-job success; governance fixture and workflow check also failed before implementation.")))
      (focused-tests . #hash((command . "raco test tests/test-gsd-governance-workflow.rkt tests/test-claim-verifier.rkt tests/test-milestone-close-gate.rkt tests/test-milestone-gate.rkt tests/test-release-audit-truth.rkt")
                             (result . "passed")
                             (tests . 204)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i changed-racket-files; rm -rf compiled/ scripts/compiled tests/compiled; raco make main.rkt scripts/gsd-wave-gate.rkt")))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 22)
                    (warnings . 1)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1021)
                    (tests . 15159)))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.51-w0.rktd")
      (remaining-items . ())
      (planning-sync . "current"))
