#hash((status . "current")
      (milestone . 837)
      (wave . "W2")
      (issue . 8732)
      (branch . "feature/v09951-w2-session-containment-redaction")
      (implementation-sha . "1fda2abd03338028a7b6b71a8439bc4b077635dc")
      (content-digest . "25a4cec41d7a7f90e47efcbd330f266234ffb940bbd8062532efc42261cb2bd1")
      (red-first . #hash((command . "raco test tests/test-session-id-containment.rkt tests/test-trace-logger-containment.rkt tests/test-w2-credential-redaction.rkt tests/test-provider-config-redaction.rkt tests/test-explorer-redaction-boundaries.rkt")
                         (failure . "Traversal and artifact links reached ID-derived filesystem paths; pending sidecars and async trace publication followed replaceable links; capability-secret, OAuth text keys, q-settings, provider configs, and nested explorer evidence exposed raw credentials.")))
      (focused-tests . #hash((command . "raco test W2 containment/redaction/OAuth/provider/RPC/trace/explorer/settings/session focused files")
                             (result . "passed")
                             (tests . 330)
                             (post-review-regression-tests . 106)))
      (security . #hash((command . "racket scripts/run-tests.rkt --suite security --profile local")
                        (result . "passed")
                        (files . 54)
                        (tests . 641)))
      (smoke . #hash((command . "racket scripts/run-tests.rkt --suite smoke --profile local")
                     (result . "passed")
                     (files . 19)
                     (tests . 289)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i changed Racket files; rm -rf compiled/ && raco make main.rkt")))
      (architecture . #hash((command . "racket scripts/run-tests.rkt --suite arch --profile local")
                            (result . "passed")
                            (files . 13)
                            (tests . 180)
                            (oversized-modules . 0)
                            (boundary-violations . 0)))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 22)
                    (warnings . 1)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1029)
                    (tests . 15245)))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.51-w2.rktd")
      (remaining-items . ())
      (planning-sync . "current"))
