#hash((status . "current")
      (milestone . 838)
      (wave . "W0")
      (issue . 8764)
      (branch . "repair/v09952-w0-projection-truth")
      (implementation-sha . "e8fcc0aec7194781ebb75af1d236deb886489398")
      (content-digest . "f26f4b23b919e729bf182f24ae77d901461b7fd095aecb7c241724c6e664718f")
      (red-first . #hash((command . "post-merge truth check: inspect docs/reports/gsd-milestones/v0.99.52.json after PR #8776 merge")
                         (failure . "W0 remained in-progress after its issue/board closure, reproducing the planning contradiction this wave must make impossible")))
      (focused-tests . #hash((command . "raco test tests/test-gsd-milestone-truth.rkt")
                             (result . "passed")
                             (tests . 26)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i and raco make tests/test-gsd-milestone-truth.rkt")))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 22)
                    (warnings . 2)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1039)
                    (tests . 15372)))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.52-w0.rktd")
      (remaining-items . (#hash((classification . "deferred-noncritical")
                                (owner . "#8775")
                                (rationale . "Parallel test-settings file-load assertion intermittently fails, then focused and complete superseding runs pass; tracked for deterministic test-isolation repair before milestone closure."))))
      (planning-sync . "current"))
