#hash((status . "current")
      (milestone . 843)
      (wave . "W01")
      (issue . 8858)
      (implementation-sha . "70c4a7382fbad7ce35aa7e8e1578ced8277ff051")
      (content-digest . "6fe3fe7ac35abf18e46a224dabc0de3b34ca4cdb4d65074661835858483ea541")
      (branch . "v09956-w1-provider-scheduler")
      (red-first . #hash((command . "raco test tests/test-anthropic.rkt tests/test-scheduler.rkt") (failure . "none")))
      (focused-tests . #hash((result . "passed") (count . 295) (suites . "anthropic (133), scheduler (162)")))
      (format-compile . #hash((result . "passed") (detail . "raco fmt -i + raco make main.rkt")))
      (lint . #hash((result . "passed") (detail . "23 passed, 1 non-blocking")))
      (fast . #hash((result . "passed") (detail . "smoke 289/289")))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.56-w1.rktd")
      (before-after . #hash((L-1 . #hash((before . "inline in anthropic.rkt") (after . "llm/adapters/eager-stream.rkt")))
                             (T-2 . #hash((before . "548L") (after . "221L + 139L + 289L")))))
      (remaining-items . ())
      (planning-sync . "current"))
