#hash((status . "current")
      (milestone . 843)
      (wave . "W00")
      (issue . 8857)
      (implementation-sha . "2e714b8066ea0f778c0a67ebba9613acadf9480b")
      (content-digest . "a40a82596021953d3131e7b83f265d061d7c643dbea4da06a26d5d9d4939aabe")
      (branch . "v09956-w0-session-loop")
      (red-first . #hash((command . "raco test tests/test-sessions.rkt tests/test-contract-tightening.rkt")
                         (failure . "none — existing tests passed from clean state")))
      (focused-tests . #hash((result . "passed")
                             (count . 191)
                             (suites . "sessions (29), session-index (45), session-store (60), session-tree-nav (30), contract-tightening (27)")))
      (format-compile . #hash((result . "passed") (detail . "raco fmt -i + raco make main.rkt")))
      (lint . #hash((result . "passed") (detail . "23 passed, 1 non-blocking warning")))
      (fast . #hash((result . "passed") (detail . "smoke suite 289/289 passed in 68.8s")))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.56-w0.rktd")
      (before-after . #hash((R-6 . #hash((before . "hash-set!/hash-update!/hash-remove! in mutations.rkt")
                                          (after . "all immutable: hash-set/hash-update/hash-remove returning new index")))
                             (A-6 . #hash((before . "phase-pre-hook/phase-msg-hook do I/O, return '() effects")
                                          (after . "phases return pure payload + effect:dispatch-hook; I/O in callers")))))
      (remaining-items . ())
      (planning-sync . "current"))
