#hash((status . "current")
      (milestone . 838)
      (wave . "W1")
      (issue . 8765)
      (branch . "feature/v09952-w1-digest-bound-approval")
      (implementation-sha . "3dbd624c283be04358ca5aa0b37829c5fb709ced")
      (content-digest . "3f7f35d0f22b8c4f4959371bc591bf3a5c2e9b6531d1664c99215ef7585563a4")
      (content-digest-command . "git diff --binary origin/main...2f0f74ab42ef561ac2cbcf8e2ea4006418855d90 -- . ':(exclude)docs/reports/gsd-wave-evidence/**' ':(exclude)docs/reports/gsd-wave-reviews/**' ':(exclude)docs/reports/gsd-wave-validation/**' | sha256sum (exact CI gsd-governance computation; identical at attestation head since records are excluded)")
      (red-first . #hash((command . "raco test tests/test-spawn-approval.rkt tests/test-spawn-subagents-approval.rkt tests/test-approval-broker.rkt tests/test-legacy-approval-api.rkt (initial red run)")
                         (failure . "Dangerous channel-less single/batch spawn approved silently (fail-open headless default); uncorrelated boolean decisions; public set-headless-approval-mode!; omitted capabilities defaulted dangerous; no digest binding registration->presentation->decision->grant->execution.")))
      (focused-tests . #hash((command . "raco test tests/test-approval-broker.rkt tests/test-approval-channel.rkt tests/test-approval-channel-teardown.rkt tests/test-approval-correlation.rkt tests/test-approval-overlay-lifecycle.rkt tests/test-hitl-approval-integration.rkt tests/test-spawn-approval.rkt tests/test-spawn-subagents-approval.rkt tests/test-spawn-execution-plan.rkt tests/test-legacy-approval-api.rkt tests/test-tui-approval-reducer.rkt tests/test-tui-approval-keyhandler.rkt tests/test-spawn-subagent-integration.rkt tests/test-workflow-executor.rkt")
                             (result . "passed")
                             (tests . 115)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i and raco make on all changed .rkt files; pre-commit staged lint PASS")))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 23)
                    (warnings . 1)))
      (security-suite . #hash((result . "passed")
                              (command . "racket scripts/run-tests.rkt --suite security")
                              (files . 58)
                              (tests . 639)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1043)
                    (tests . 15362)))
      (ci-repair . #hash((cause . "metrics-sync/metrics-lint/prose failed on first PR head 1c6edd3c: metrics enumerate via git ls-files, so the 4 new test modules were untracked when README was synced; pre-commit hook also reformatted 7 staged files after commit-object creation (net -46 lines).")
                         (repair-commit . "8d88d8852ec7c8a938cf89314e277b6f2de7e77d")
                         (invariant-comment-commit . "3dbd624c283be04358ca5aa0b37829c5fb709ced")))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.52-w1.rktd")
      (remaining-items . (#hash((classification . "deferred-noncritical")
                                (owner . "#8775")
                                (rationale . "Parallel test-settings file-load isolation flake remains tracked for deterministic repair before milestone closure; does not block W1."))))
      (real-provider . "not-used (prohibited until W1 security and W6 credential-defense prerequisites merge and validate)")
      (planning-sync . "current"))
