#hash((status . "current")
      (milestone . 837)
      (wave . "W5")
      (issue . 8735)
      (branch . "feature/v09951-w5-compact-correlation")
      (implementation-sha . "9134f0ebe46aa0bd8d8bbe67f0518067d5cfd522")
      (content-digest . "c07e32d23c84cc207f17802ebd91ab675004611da5aa3a18b09292767df23468")
      (red-first . #hash((command . "raco test tests/test-compact-correlation-isolation.rkt")
                         (failure . "compact.requested subscriber did not filter by target session; session A reacted to session B's request; TUI did not track pending compact request-id; terminal events cleared status without correlation.")))
      (focused-tests . #hash((command . "raco test test-compact-correlation-isolation test-compaction-command test-session-compaction-lifecycle test-compaction-guard test-agent-session-context test-tmux-explore-verifiers tui/test-state workflows/session/test-session-compact test-tmux-tui-commands")
                             (result . "passed")
                             (tests . 237)))
      (security . #hash((command . "racket scripts/run-tests.rkt --suite security --profile local")
                        (result . "passed")
                        (files . 55)
                        (tests . 651)))
      (workflows . #hash((command . "racket scripts/run-tests.rkt --suite workflows --profile local")
                         (result . "passed")
                         (files . 28)
                         (tests . 146)))
      (smoke . #hash((command . "racket scripts/run-tests.rkt --suite smoke --profile local")
                     (result . "passed")
                     (files . 19)
                     (tests . 289)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i changed Racket files; clean compiled directories; raco make main.rkt")))
      (architecture . #hash((command . "racket scripts/run-tests.rkt --suite arch --profile local")
                            (result . "passed")
                            (files . 14)
                            (tests . 182)
                            (oversized-modules . 0)
                            (boundary-violations . 0)))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 21)
                    (warnings . 2)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1034)
                    (tests . 15287)))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.51-w5.rktd")
      (remaining-items . ())
      (planning-sync . "current"))
