#hash((status . "current")
      (milestone . 838)
      (wave . "W0")
      (issue . 8764)
      (branch . "feature/v09952-w0-governance-truth")
      (implementation-sha . "5dd8b1ee83a33aa83a2ed7959341bb46f8fe0238")
      (content-digest . "887ea18bb4f0f2db0bf141be2888cc996ea02b0148a570b982b29ce739952fcf")
      (red-first . #hash((command . "baseline replay at origin/main 7b169a7f: copy only new W0 tests into detached worktree; run Python finalizer and three Racket governance test commands")
                         (failure . "all four commands exited 1 before W0 production changes; raw logs retained under .planning/v0.99.52-w0/red-baseline-*.log")))
      (focused-tests . #hash((command . "python3 -m unittest discover -s scripts/github -p 'test_*.py'; raco test tests/test-gsd-governance-workflow.rkt tests/test-gsd-milestone-truth.rkt tests/test-milestone-close-gate.rkt")
                             (result . "passed")
                             (tests . 121)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i and raco make for all six changed Racket source/test files; raco make main.rkt")))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 22)
                    (warnings . 2)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1039)
                    (tests . 15372)))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.52-w0.rktd")
      (remaining-items . (#hash((classification . "deferred-noncritical")
                                (owner . "#8775")
                                (rationale . "Parallel test-settings file-load assertion intermittently fails, then focused and complete superseding runs pass; tracked for deterministic test-isolation repair before milestone closure."))))
      (planning-sync . "current"))
