#hash((status . "current")
      (milestone . 845)
      (wave . "W02")
      (issue . 8874)
      (implementation-sha . "2ce9b125253be8eb496df352e5314ca013395759")
      (content-digest . "f599300c1baaa3a341cd1c2dc90cb66016162d7c302f33926bb4a90862773e93")
      (branch . "v09958-w2-runtime-decomp")
      (red-first . #hash((command . "racket -e decode-mouse-message test") (failure . "4-field raw returned #f before fix")))
      (fast . #hash((result . "passed") (detail . "mouse-bridge (15), sessions (37), session-lifecycle+manager (37), goal-state+conclusion (82), compaction-command+correlation (4)")))
      (focused-tests . #hash((result . "passed") (count . 175) (suites . "mouse-bridge (15), sessions (37), session-lifecycle+manager (37), goal-state+conclusion (82), compaction (4)")))
      (format-compile . #hash((result . "passed") (detail . "raco fmt -i + raco make main.rkt")))
      (lint . #hash((result . "passed") (detail . "23 passed, 1 warning")))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.58-w2.rktd")
      (findings . #hash((P1-BK . #hash((status . "complete") (action . "extract-module") (detail . "runtime/session-index/bookmarks.rkt (160L) extracted; mutations.rkt re-exports")))
                         (P1-ST . #hash((status . "complete") (action . "extract-module") (detail . "runtime/session/session-store-goal-task.rkt (158L) via parameter injection")))
                         (P2-FT . #hash((status . "complete") (action . "extract-module") (detail . "runtime/compaction/file-tracker.rkt (82L) pure functions")))
                         (P2-M . #hash((status . "complete") (action . "bugfix") (detail . "decode-mouse-message handles 4-field raw + 7-field decoded; 4 new tests")))))
      (before-after . #hash((mutations . #hash((before . "415L monolithic") (after . "266L + bookmarks.rkt 160L")))
                             (session-store . #hash((before . "554L") (after . "490L + session-store-goal-task.rkt 158L")))
                             (compactor . #hash((before . "406L") (after . "355L + file-tracker.rkt 82L")))))
      (remaining-items . ())
      (planning-sync . "current"))
