#hash((status . "current")
      (milestone . 837)
      (wave . "W8")
      (issue . 8738)
      (branch . "feature/v09951-w8-release-81")
      (implementation-sha . "5fb22542be5081eb8515a4ece74aa81033f12b8b")
      (content-digest . "efce34421470bb94c73c741be1ca6aefc7108a930ecbefc68c1ba7b90936ddef")
      (red-first . #hash((command . "racket scripts/lint-release-notes.rkt --check")
                         (failure . "release-notes lint missing required sections for 0.99.51")))
      (focused-tests . #hash((command . "raco test tests/test-version.rkt")
                             (result . "passed")
                             (tests . 4)))
      (version-bump . #hash((from . "0.99.50")
                            (to . "0.99.51")
                            (surfaces-synced . 29)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i; rm -rf compiled/; raco make main.rkt")))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 22)
                    (warnings . 2)))
      (smoke . #hash((command . "racket scripts/run-tests.rkt --suite smoke --profile local")
                     (result . "passed")
                     (files . 19)
                     (tests . 289)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1038)
                    (tests . 15314)))
      (architecture . #hash((result . "passed")
                            (command . "racket scripts/run-tests.rkt --suite arch")
                            (files . 14)
                            (tests . 182)))
      (workflows . #hash((result . "passed")
                         (command . "racket scripts/run-tests.rkt --suite workflows")
                         (files . 28)
                         (tests . 146)))
      (release-dry-run . #hash((result . "passed")
                               (checks . 5)))
      (release-notes-lint . #hash((result . "passed")
                                  (version . "0.99.51")))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.51-w8.rktd")
      (remaining-items . ())
      (planning-sync . "current"))
