#hash((status . "current")
      (milestone . 837)
      (wave . "W1")
      (issue . 8731)
      (branch . "feature/v09951-w1-atomic-batch-hitl")
      (implementation-sha . "5c0695479310373e956e9e5aa0c6a1b443baf433")
      (content-digest . "28f6162912599150b729bec9a3cfab29953f51026c36e08863270fd8365ee507")
      (red-first . #hash((command . "raco test tests/test-spawn-subagent-helpers.rkt tests/test-approval-channel-teardown.rkt; independent diff review")
                         (failure . "Explicit empty authority became unrestricted; delegated any was accepted; legacy waiters did not wake; interactive teardown became permissive; reviewer also found effective model absent from approved batch snapshot.")))
      (focused-tests . #hash((command . "raco test approval/channel/overlay/TUI/spawn/batch/workflow focused files")
                             (result . "passed")
                             (tests . 230)
                             (post-refactor-regression-tests . 159)))
      (security . #hash((command . "racket scripts/run-tests.rkt --suite security")
                        (result . "passed")
                        (files . 48)
                        (tests . 617)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i changed-racket-files; rm -rf compiled trees; raco make main.rkt")))
      (architecture . #hash((result . "passed")
                            (oversized-modules . 0)
                            (boundary-violations . 0)))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 22)
                    (warnings . 1)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1023)
                    (tests . 15220)))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.51-w1.rktd")
      (remaining-items . ())
      (planning-sync . "current"))
