#hash((status . "current")
      (milestone . 837)
      (wave . "W3")
      (issue . 8733)
      (branch . "feature/v09951-w3-provider-transport-terminal-outcomes")
      (implementation-sha . "6984b7277bb1e4865eee7aef7f79feb8591c3c56")
      (content-digest . "05ba710e977275ed07135dcc11a03d2114cbbb0ce6e8a83a82437df1608a57f2")
      (red-first . #hash((command . "raco test tests/test-provider-tool-transport.rkt tests/test-spawn-subagent-terminal-outcomes.rkt tests/test-spawn-subagents-batch.rkt tests/test-scheduler.rkt tests/test-workflow-executor.rkt")
                         (failure . "Canonical adapter tool-call spellings produced no request two; bridge emitted nested underscore forms; max-turn/cancel/failure were successful or untyped; turns-used was configured maximum; batch counted timeout as success and leaked raw details; scheduler ran later tools after cancellation; workflow reversed parallel siblings; Gemini omitted stable native IDs; summarized tool results and assistant merges lost correlation.")))
      (focused-tests . #hash((command . "raco test provider transport/architecture, terminal, batch, scheduler, workflow, Gemini, context assembly/overflow")
                             (result . "passed")
                             (tests . 255)))
      (security . #hash((command . "racket scripts/run-tests.rkt --suite security --profile local")
                        (result . "passed")
                        (files . 55)
                        (tests . 651)
                        (supersedes . "One earlier parallel run hit transient tcp-listen errno=98 in test-remote-ipc-resilience; focused 12/12 and complete superseding security runs passed.")))
      (workflows . #hash((command . "racket scripts/run-tests.rkt --suite workflows --profile local")
                         (result . "passed")
                         (files . 28)
                         (tests . 146)))
      (smoke . #hash((command . "racket scripts/run-tests.rkt --suite smoke --profile local")
                     (result . "passed")
                     (files . 19)
                     (tests . 289)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i changed Racket files; clean compiled directories; raco make main.rkt")))
      (architecture . #hash((command . "racket scripts/run-tests.rkt --suite arch --profile local")
                            (result . "passed")
                            (files . 14)
                            (tests . 182)
                            (oversized-modules . 0)
                            (boundary-violations . 0)))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 21)
                    (warnings . 2)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1031)
                    (tests . 15273)))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.51-w3.rktd")
      (remaining-items . ())
      (planning-sync . "current"))
