#hash((status . "current")
      (milestone . 837)
      (wave . "W7")
      (issue . 8737)
      (branch . "feature/v09951-w7-release-gate-hardening")
      (implementation-sha . "489b42d16e85e9bd85a324a497eef2412fa9fc37")
      (content-digest . "746c78cc55abb4973dfd76883b0b8b2b63521311241de6bd3447aeee2122de8e")
      (red-first . #hash((command . "raco test tests/test-gate-evidence-hardening.rkt tests/test-uploaded-manifest-verification.rkt")
                         (failure . "gate evidence verification did not check SHA, failed count, timed_out count; no uploaded manifest field verification; release-notes lint not integrated")))
      (focused-tests . #hash((command . "raco test tests/test-gate-evidence-hardening.rkt tests/test-uploaded-manifest-verification.rkt tests/test-run-tests-gate-evidence.rkt tests/test-lint-release-readiness.rkt tests/test-release-manifest-traceability.rkt tests/test-release-workflow-contract.rkt tests/test-release-audit-truth.rkt tests/test-release-repair.rkt tests/test-milestone-gate.rkt tests/test-milestone-close-gate.rkt tests/test-lint-release-notes.rkt")
                             (result . "passed")
                             (tests . 334)))
      (smoke . #hash((command . "racket scripts/run-tests.rkt --suite smoke --profile local")
                     (result . "passed")
                     (files . 19)
                     (tests . 289)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i changed Racket files; clean compiled directories; raco make main.rkt")))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 21)
                    (warnings . 3)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1038)
                    (tests . 15309)))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.51-w7.rktd")
      (remaining-items . ())
      (planning-sync . "current"))
