#hash((branch . "feature/v09952-w9-pipeline")
 (content-digest . "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")
 (fast . #hash((command . "racket scripts/run-tests.rkt --suite fast") (files . 1049) (result . "passed") (tests . 15426)))
 (focused-tests . #hash((command . "raco test tests/test-release-workflow-contract.rkt tests/test-release-repair.rkt tests/test-w9-ci-workflow-verification.rkt") (result . "passed") (tests . 82)))
 (format-compile . #hash((command . "raco fmt -i and raco make on changed files") (result . "passed")))
 (implementation-sha . "aeaa524e985c45db1402f2af0a4d4f9217ee9839")
 (issue . 8773)
 (lint . #hash((blocking-checks . 0) (command . "git commit hook lint") (result . "passed") (warnings . 1)))
 (milestone . 838)
 (planning-sync . "current")
 (red-first . #hash((command . "test-release-workflow-contract.rkt tests covering DAG order") (failure . "release.yml had separate build/smoke jobs; restructured to release-core.yml")))
 (remaining-items . ())
 (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.52-w9.rktd")
 (status . "current")
 (wave . "W9"))
