#hash((status . "current")
      (milestone . 837)
      (wave . "W4")
      (issue . 8734)
      (branch . "feature/v09951-w4-resume-parity-session-truth")
      (implementation-sha . "e13ba09642048e2f864f5c64269d02d228d025b7")
      (content-digest . "a29e98fa1339cf4aede51eb4c47594b3f269810d4952a1f706bb49bff8260f81")
      (red-first . #hash((command . "raco test tests/test-resume-parity.rkt tests/test-session-metadata-truth.rkt")
                         (failure . "open-or-resume-session did not exist; read-session-metadata read non-existent top-level model key returning always unknown; tool-call-count used wrong content part type lookup; SDK session-info lacked session-dir and start-time.")))
      (focused-tests . #hash((command . "raco test resume-parity, session-metadata, sessions, sdk, main, cli, cli-args, agent-session, rpc-mode, tui-session-resume")
                             (result . "passed")
                             (tests . 374)))
      (security . #hash((command . "racket scripts/run-tests.rkt --suite security --profile local")
                        (result . "passed")
                        (files . 55)
                        (tests . 651)))
      (workflows . #hash((command . "racket scripts/run-tests.rkt --suite workflows --profile local")
                         (result . "passed")
                         (files . 28)
                         (tests . 146)))
      (smoke . #hash((command . "racket scripts/run-tests.rkt --suite smoke --profile local")
                     (result . "passed")
                     (files . 19)
                     (tests . 289)))
      (format-compile . #hash((result . "passed")
                              (command . "raco fmt -i changed Racket files; clean compiled directories; raco make main.rkt")))
      (architecture . #hash((command . "racket scripts/run-tests.rkt --suite arch --profile local")
                            (result . "passed")
                            (files . 14)
                            (tests . 182)
                            (oversized-modules . 0)
                            (boundary-violations . 0)))
      (lint . #hash((result . "passed")
                    (command . "racket scripts/lint-all.rkt")
                    (blocking-checks . 21)
                    (warnings . 2)))
      (fast . #hash((result . "passed")
                    (command . "racket scripts/run-tests.rkt --suite fast")
                    (files . 1033)
                    (tests . 15283)))
      (review-artifact . "docs/reports/gsd-wave-reviews/v0.99.51-w4.rktd")
      (remaining-items . ())
      (planning-sync . "current"))
