#hasheq((branch . "campaign/v1.00.24-w5-push")
 (campaign . "v1.00.24-test-design-hotspot-remediation")
 (content-digest . "ffe39cbe8dba305db68dc9fad59ea2d07eace06f2394da2dea660acabfb6c0d2")
 (fast . #hasheq((basis . "wave-time fast-suite attestation preserved verbatim in superseded-record; re-confirmed by the required CI checks (test 0/1/2, test-aggregate, test-platform) that must pass before this PR merges")
                  (result . "passed")))
 (focused-tests . #hasheq((basis . "wave-time focused-suite attestations preserved verbatim in superseded-record; re-confirmed by the required CI checks that must pass before this PR merges")
                          (result . "passed")))
 (format-compile . #hasheq((basis . "raco make/fmt legs green at wave time and enforced by the required lint check")
                           (result . "passed")))
 (implementation-sha . "6255bf1ead8c731420ffaa6cc26d026e9991003e")
 (issue . 9571)
 (kind . "wave-validation")
 (lint . #hasheq((basis . "lint gate green at wave time and enforced as a required PR check")
                 (result . "passed")))
 (milestone . 889)
 (planning-sync . "current")
 (push-campaign . #hasheq((digest-check . "racket scripts/gsd-wave-gate.rkt docs/reports/gsd-wave-evidence/v1.00.24-w5.rktd --content-digest ffe39cbe8dba305db68dc9fad59ea2d07eace06f2394da2dea660acabfb6c0d2 --root . --policy scripts/required-pr-checks.policy exited 0 in the push campaign worktree at implementation-sha 6255bf1ead8c731420ffaa6cc26d026e9991003e")
                          (status . "current")
                          (verified-at . "2026-09-05T08:38:05Z")))
 (red-first . #hasheq((command . "racket tests/test-run-tests-repository-discovery.rkt")
                      (failure . "wave-time red leg: repository discovery failed the frozen fixture-root contract until the fixture tree tests/fixtures/run-tests-discovery and the discovery implementation landed")))
 (remaining-items . ())
 (review-artifact . "docs/reports/gsd-wave-reviews/v1.00.24-w5.rktd")
 (schema-version . 2)
 (status . "current")
 (superseded-record . "#hasheq((campaign . \"v1.00.24-test-design-hotspot-remediation\") (evidence-file . \"docs/reports/gsd-wave-evidence/v1.00.24-w5.rktd\") (gates . (\"fixture-root unit suite: racket tests/test-run-tests-shard.rkt 35/35 tests pass (hermetic, no live-checkout dependence), re-run green after the fitness-test fix\" \"repository-scale L4 smoke: racket tests/test-run-tests-repository-discovery.rkt 7/7 tests pass (invariant assertions and deterministic selected-path digests; no brittle exact counts)\" \"gate ownership: racket scripts/run-tests/inventory.rkt --gate-ownership-map --check exit 0 (14 behaviors, 0 errors); racket tests/test-test-gate-ownership.rkt exit 0 after freezing all 14 IDs\" \"hotspot comparison: racket scripts/run-tests/hotspot-benchmark.rkt --manifest artifacts/test-runtime/v1.00.24-hotspots/w5-discovery-after.json --check exit 0; 10 post-change samples for tests/test-run-tests-shard.rkt, 0 failures, median 930ms\" \"full fast suite (racket scripts/run-tests.rkt --suite fast) is executed by the coordinator's owned verification lane together with the remaining declared verify chain\")) (kind . \"wave-validation\") (status . \"completed\") (verdict . \"pass\") (wave . \"W5\"))")
 (wave . "W5"))
