(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W7")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.25-w7.rktd")
(implementation-sha . "ce4a3c82334e3c32b601e8934205a69dc66fcf9a")
(branch . "main")
(validation-result . pass)
(checks . ((release-entry-tests . "racket tests/test-release-entry-current.rkt — 5/5 green at implementation-sha (changelog milestone reference, version agreement across util/version.rkt, info.rkt, README badge, activation-report state binding)")
           (sums-binding . "sha256sum -c in artifacts/ci-baseline/v1.00.25-c1 and -c2 — both clean; the activation report quotes these checksums verbatim and the prepared-env report checksum a5f7129dd2efdf233422d4ca639dfdfc7e64049360e2192ab3b6d850fc040a7c matches the actual file byte-for-byte")
           (digest-binding . "non-artifact digest c3f5f098d1c978f46e567e0a1179fd6cbc208694e196963610c7205b80894781 reproduces at implementation-sha ce4a3c82334e3c32b601e8934205a69dc66fcf9a over util/version.rkt info.rkt tests/test-release-entry-current.rkt tests/test-ci-cohort-report.rkt tests/test-prepared-env-report.rkt tests/test-run-tests-profiles.rkt")
           (preflight-components . "at implementation-sha: racket scripts/metrics.rkt --lint, racket scripts/lint-release-notes.rkt --check, racket scripts/release-dry-run.rkt, and racket scripts/lint-release-readiness.rkt --strict --context tag-publish all green; the coordinator's owned lane re-runs the full declared verify command including the fast/security/arch suites")
           (file-contract . "all nine declared wave files exist; the three rktd records are record-only additions outside the digest inputs")))
(record-only . "this validation adds no code and touches no digest input")
