#hasheq((schema-version . 2)
        (milestone . 895)
        (wave . "W2")
        (issue . 9688)
        (validation . "local green on exact wave content")
        (branch . "campaign/v1.00.30-w2")
        (head . "81e0d4cedd990e273b547fa30fc96968aed6aa3d")
        (verify-command . "raco test tests/test-ci-eager-compilation.rkt tests/test-ci-workflow-diagnostics.rkt tests/test-prepared-env-report.rkt && racket scripts/check-deps.rkt && racket scripts/run-tests.rkt --suite fast && racket scripts/metrics.rkt --lint")
        (local-result . "pass")
        (fmt-and-compile . "all changed Racket sources formatted with raco fmt -i and compiled with raco make before verification chain")
        (fixtures-deterministic . #t)
        (no-secrets . #t)
        (coordinator-owned-verification . #hash((r0 . "pending") (per-wave-guard . "pending") (r1-cohort . "pending - >=3 comparable heads, exact final head; PASS=containment only")))
        (hold-conditions . "missing remote evidence means HOLD; never complete while cohort open or delivery pending"))
