(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W1")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.25-w1.rktd")
(implementation-sha . "63b2aa6f")
(validator . "W1 delivery verification lane (format, affected tests, manifest check, secrets/metrics lints)")
(validation-verdict . "pass")
(checks . ((tdd-tests . "tests/test-ci-cohort-report.rkt: 61/61 green after the W1 decision-schema extension (per-configuration p50/p95 linear interpolation, reliability counts, inventory-equality verdicts, explicit promote/hold verdict per lane, LPT fallback with named reason)")
           (manifest-check . "racket scripts/run-tests/cohort-report.rkt --manifest artifacts/ci-baseline/v1.00.25-c1/cohort.json --out-json artifacts/ci-baseline/v1.00.25-c1/report.json --out-md artifacts/ci-baseline/v1.00.25-c1/report.md --check exits 0: all 20 SHAs x 4 configurations inventory-digests equal to the required-lane fast/batch/fifo inventory for the same SHA")
           (decision-file-present . "artifacts/ci-baseline/v1.00.25-c1/decision.md exists with per-lane verdicts, numbers, exact gate text, and reviewer")
           (artifact-checksums . "artifacts/ci-baseline/v1.00.25-c1/SHA256SUMS regenerated over cohort.json, README.md, report.json, report.md, decision.md")
           (evidence-digest . "non-artifact-content-digest 265a2dcb... reproduces from README.md, scripts/run-tests/cohort-report.rkt, tests/test-ci-cohort-report.rkt at HEAD 63b2aa6f")
           (exactly-one-evidence-record . "docs/reports/gsd-wave-evidence/v1.00.25-w1.rktd contains exactly one wave-evidence record")
           (focused-suite . "racket scripts/run-tests.rkt --suite fast is owned by the coordinator verification lane and was not launched in-session")))
(honesty-check . "no fabricated run IDs, no revised targets, no dropped SHAs, no forced cohort closure; the hold decision is the only verdict the recorded evidence supports")
