#hasheq((branch . "campaign/v1.00.24-w4-push")
 (campaign . "v1.00.24-test-design-hotspot-remediation")
 (content-digest . "66f9f7d0a2f6104057b00008dc295e222661d063eb89d8e1cc33b5ab424299e9")
 (fast . #hasheq((basis . "wave-time fast-suite attestation preserved verbatim in superseded-record; re-confirmed by the required CI checks (test 0/1/2, test-aggregate, test-platform) that must pass before this PR merges")
                  (result . "passed")))
 (focused-tests . #hasheq((basis . "wave-time focused-suite attestations preserved verbatim in superseded-record; re-confirmed by the required CI checks that must pass before this PR merges")
                          (result . "passed")))
 (format-compile . #hasheq((basis . "raco make/fmt legs green at wave time and enforced by the required lint check")
                           (result . "passed")))
 (implementation-sha . "67904113ae7c5418fe4ea8789fde044f98c2bcae")
 (issue . 9570)
 (kind . "wave-validation")
 (lint . #hasheq((basis . "lint gate green at wave time and enforced as a required PR check")
                 (result . "passed")))
 (milestone . 889)
 (planning-sync . "current")
 (push-campaign . #hasheq((digest-check . "racket scripts/gsd-wave-gate.rkt docs/reports/gsd-wave-evidence/v1.00.24-w4.rktd --content-digest 66f9f7d0a2f6104057b00008dc295e222661d063eb89d8e1cc33b5ab424299e9 --root . --policy scripts/required-pr-checks.policy exited 0 in the push campaign worktree at implementation-sha 67904113ae7c5418fe4ea8789fde044f98c2bcae")
                          (status . "current")
                          (verified-at . "2026-09-05T07:26:51Z")))
 (red-first . #hasheq((command . "racket tests/test-gsd-system-adapters-timeout.rkt")
                      (failure . "wave-time red leg recorded at commit 1034106f: run-campaign-wave accepted unbounded deadlines until the mandatory-deadline follow-up; the seam regression test failed before the fix landed")))
 (remaining-items . ())
 (review-artifact . "docs/reports/gsd-wave-reviews/v1.00.24-w4.rktd")
 (schema-version . 2)
 (status . "current")
 (superseded-record . "#hasheq((campaign . \"v1.00.24-test-design-hotspot-remediation\") (evidence-file . \"docs/reports/gsd-wave-evidence/v1.00.24-w4.rktd\") (gates . (\"focused timeout suites: tests/test-gsd-system-adapters-timeout.rkt 8/8 tests pass, tests/test-gsd-wave-executor-isolation.rkt 19/19 tests pass (green before and after the ledger/inventory updates and the mandatory-deadline follow-up commit 1034106f)\" \"bounded L4 canary: tests/test-gsd-wave-timeout-canary.rkt 2/2 tests pass, 2.2-2.4s total (cap 12s), re-run green after ledger update\" \"gate ownership: racket scripts/run-tests/inventory.rkt --gate-ownership-map --check exit 0 (12 behaviors, 0 errors)\" \"hotspot comparison: racket scripts/run-tests/hotspot-benchmark.rkt --manifest artifacts/test-runtime/v1.00.24-hotspots/w4-gsd-timeout-after.json --check exit 0; >=10 post-change samples per family (avg 441ms timeout suite, 619ms executor isolation)\" \"full fast suite (racket scripts/run-tests.rkt --suite fast) is executed by the coordinator's owned verification lane together with the remaining declared verify chain\")) (kind . \"wave-validation\") (status . \"completed\") (verdict . \"pass\") (wave . \"W4\"))")
 (wave . "W4"))
