(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.26")
(wave . "W6")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.26-w6.rktd")
(implementation-sha . "aa7ec8e2fbdf99b5af67af314078935f93ac089f")
(branch . "campaign/v1.00.26-w6")
(validation-result . pass)
(checks
  (cohort-tests . "racket tests/test-ci-cohort-report.rkt — 74 success(es) 0 failure(s) 0 error(s) at implementation-sha (pr-elapsed mode pins: first-check-start to last-required-check-completion semantics, exactly-20 unique SHAs required, duplicates/re-runs recorded not dropped, linear-interpolated percentiles, report --check regeneration, verdict text recorded verbatim)")
  (tooling-suites . "racket tests/test-runner-*.rkt focused subsets — 9 success(es) and 20 success(es) 0 failures 0 errors on the two touched-suite groups; no unrelated suite regressed in the fast checks run during the wave")
  (report-regeneration . "racket scripts/run-tests/cohort-report.rkt --manifest artifacts/ci-topology/v1.00.26-c2/cohort.json --out-json artifacts/ci-topology/v1.00.26-c2/report.json --out-md artifacts/ci-topology/v1.00.26-c2/report.md --check — PASS (regenerated statistics match the committed report byte-for-byte in the checked fields)")
  (sums-binding . "sha256sum -c artifacts/ci-topology/v1.00.26-c2/SHA256SUMS — OK; all four artifacts match byte-for-byte (verified standalone after generation)")
  (digest-binding . "non-artifact digest 83310bdb5562538519c7805c8dc2b4ef3e771fafd9228f03c68db50c3c3f27c2 reproduces with the recorded command at implementation-sha aa7ec8e2fbdf99b5af67af314078935f93ac089f over scripts/run-tests/cohort-report.rkt tests/test-ci-cohort-report.rkt")
  (branch-guard . "current branch is campaign/v1.00.26-w6, not main — passes; delivery goes through the protected-main PR")
  (decision-file . "test -f artifacts/ci-topology/v1.00.26-c2/decision.md — present; records target-unachieved with observed p50/p95, the named next lever, and an explicit no-target-revision clause")
  (rktd-parse . "all three W6 rktd records read back as balanced Racket data (read loop clean, no unexpected parens)")
  (file-contract . "all ten declared wave targets accounted for: cohort.json + report.json + report.md + decision.md + SHA256SUMS checksummed in artifacts/ci-topology/v1.00.26-c2/, the pr-elapsed extension in scripts/run-tests/cohort-report.rkt, the extended tests in tests/test-ci-cohort-report.rkt, and the three record-only rktd files under docs/reports/gsd-wave-{evidence,reviews,validation}/; delivery lands via the campaign PR on campaign/v1.00.26-w6 with the squash-merge and post-merge gate confirmation owned by the runtime coordinator")
  (rollback-rehearsal-dry-run . "documented sequence (not executed against live protection): no workflow or lane behavior changed, so there is nothing to roll back functionally; reverting the two digest-input files and deleting the artifacts directory + rktd trio restores the exact pre-wave tree; a checksum or report mismatch is caught by sha256sum -c / report --check failing closed"))
(record-only . "this validation adds no code and touches no digest input")
