#hasheq((status . "current")
 (milestone . 894)
 (wave . "W11")
 (issue . 9650)
 (branch . "campaign/v1.00.29-w11")
 (implementation-sha . "df58a7c53f365aab34076bf5bf603f7871a0df6d")
 (content-digest . "06ebb39bf8f5f95147b3a572391e4efe573e34534b6fc245751cb78f841b4d78")
 (red-first . #hasheq((command . "racket tests/test-release-entry-current.rkt (before the release entry and version surfaces existed on the bake branch)") (failure . "5 failures: info.rkt version must match the canonical version (actual 1.00.28 expected 1.00.29); CHANGELOG must carry a release heading for the canonical version; release entry must carry the Released line and milestone reference; release-language lint passes; entry names activated and not-activated states")))
 (focused-tests . #hasheq((result . "passed")))
 (format-compile . #hasheq((result . "passed")))
 (lint . #hasheq((result . "passed")))
 (fast . #hasheq((result . "passed")))
 (review-artifact . "docs/reports/gsd-wave-reviews/v1.00.29-w11.rktd")
 (remaining-items . ())
 (planning-sync . "current")
 (gate-results . "lint-release-notes --check: PASSED CHANGELOG.md version 1.00.29; release-dry-run: 6/6; metrics --lint: All 5 static metrics match README.md; sync-readme-status --check: OK; check-version-expectations: PASSED 0 hard-coded literals; lint-doc-freshness: PASSED; frozen chain cold purge exact tree: RUN-SUMMARY runner-version=1.00.29 file-count=1190 pass=1190 fail=0 wall-clock-seconds=1242.197 + metrics 5/5; bake-fallout suites green: deterministic-clock 10/10, milestone-gate, edit-guidance-doc, lint-doc-freshness, run-tests-profiles, release-entry-current 5/5")
 (counting-note . "check-version-expectations scans 1488 .rkt test files vs the README metric 1489 (all-files census basis)")
 (review-history . "Round 1 (kimi-coding) REQUEST_CHANGES: B1 dismissed with evidence (actual linter green on exact tree); B2 stale chain evidence valid and fixed (real RUN-SUMMARY quoted); B3 dangling binding citation valid and fixed (origin/main merged). Round 2 re-verified the bake-artifact delta at the final content head. Two working-tree revert incidents during the bake (BUG-0038 stale-TUI class) mitigated by immediate commits."))
