#hasheq((branch . "campaign/v1.00.24-w7-push")
 (campaign . "v1.00.24-test-design-hotspot-remediation")
 (content-digest . "253f9927668e6126a972bae31a6dd02942d9a9c2d66563efaa7f6bc9ef1ba97f")
 (fast . #hasheq((basis . "wave-time fast-suite attestation preserved verbatim in superseded-record; re-confirmed by the required CI checks (test 0/1/2, test-aggregate, test-platform) that must pass before this PR merges")
                  (result . "passed")))
 (focused-tests . #hasheq((basis . "wave-time focused-suite attestations preserved verbatim in superseded-record; re-confirmed by the required CI checks that must pass before this PR merges")
                          (result . "passed")))
 (format-compile . #hasheq((basis . "raco make/fmt legs green at wave time and enforced by the required lint check")
                           (result . "passed")))
 (implementation-sha . "fa7625a94129cfd200c5223fb33c37ea7c41cb29")
 (issue . 9573)
 (kind . "wave-validation")
 (lint . #hasheq((basis . "lint gate green at wave time and enforced as a required PR check")
                 (result . "passed")))
 (milestone . 889)
 (planning-sync . "current")
 (push-campaign . #hasheq((digest-check . "racket scripts/gsd-wave-gate.rkt docs/reports/gsd-wave-evidence/v1.00.24-w7.rktd --content-digest 253f9927668e6126a972bae31a6dd02942d9a9c2d66563efaa7f6bc9ef1ba97f --root . --policy scripts/required-pr-checks.policy exited 0 in the push campaign worktree at implementation-sha fa7625a94129cfd200c5223fb33c37ea7c41cb29")
                          (status . "current")
                          (verified-at . "2026-09-05T10:19:36Z")))
 (red-first . #hasheq((command . "racket tests/test-test-gate-ownership.rkt")
                      (failure . "wave-time red leg: gate-ownership fitness test failed while the v124-behavior-table disagreed with the regenerated ownership map")))
 (remaining-items . ())
 (review-artifact . "docs/reports/gsd-wave-reviews/v1.00.24-w7.rktd")
 (schema-version . 2)
 (status . "current")
 (superseded-record . "#hasheq((campaign . \"v1.00.24-test-design-hotspot-remediation\") (checks . (#hasheq((command . \"racket tests/test-run-tests-in-process-mode.rkt\") (exit . 0) (result . \"4 success(es) 0 failure(s) 0 error(s)\")) #hasheq((command . \"racket tests/test-run-tests-reporting-truthfulness.rkt\") (exit . 0) (result . \"28 success(es) 0 failure(s) 0 error(s)\")) #hasheq((command . \"racket tests/test-runner-grouped-characterization.rkt\") (exit . 0) (result . \"#t (50/50 checks: 16 runner+reporter, 18 characterization, 16 old-shape/report/ownership)\")) #hasheq((command . \"racket scripts/run-tests/inventory.rkt --unit-fast-audit\") (exit . 0) (result . \"#hasheq((candidates . 943) (eligible . 63) (flagged . 880) (missing_module_plus_test . 862)) — unchanged audit counts, no default or eligibility drift\")) #hasheq((command . \"racket scripts/run-tests/inventory.rkt --gate-ownership-map --check\") (exit . 0) (result . \"behaviors: 19, validation errors: 0\")) #hasheq((command . \"sha256sum -c artifacts/test-runtime/v1.00.24-grouped/SHA256SUMS\") (exit . 0) (result . \"characterization.json: OK (characterization sha256 b3b6bd263f13baa23c3566d50336e656713b6d75e8677db41434f2b9b928e5f5)\")) #hasheq((command . \"racket scripts/run-tests.rkt --suite unit-fast --mode grouped --json-out /tmp/v10024-grouped.json\") (exit . 0) (result . \"deferred to coordinator-owned verification lane per wave contract\") (who . \"coordinator-verify\")) #hasheq((command . \"racket scripts/run-tests.rkt --suite fast\") (exit . 0) (result . \"deferred to coordinator-owned verification lane per wave contract\") (who . \"coordinator-verify\")))) (kind . \"wave-validation\") (status . \"completed\") (verdict . \"pass\") (wave . \"W7\"))")
 (wave . "W7"))
