(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.26")
(wave . "W1")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.26-w1.rktd")
(implementation-sha . "efe6adb465563b25b635f146dfca66c9a3a83cc8")
(branch . "campaign/v1.00.26-w1")
(validation-result . pass)
(checks . ((milestone-gate . "racket tests/test-milestone-gate.rkt — exit 0 at implementation-sha (extended pins: lightweight lint steps, lint-quality job present and required)")
           (w9-integration-tests . "racket tests/test-w9-ci-workflow-verification.rkt — 18 success(es) 0 failure(s) 0 error(s) at implementation-sha (live ci-required-jobs evaluation: lint + lint-quality required; lint stays required throughout the split; policy contains both names; heavyweight steps absent from lint's section and present in lint-quality's)")
           (runtime-contract-tests . "racket tests/test-ci-runtime-contract.rkt — 31 success(es) 0 failure(s) 0 error(s) at implementation-sha (required-set == policy equality, aggregate needs edges intact, per-job timing shape, same-SHA before/after pairing with anchor_sha == head_sha == c6ee39e4…)")
           (sums-binding . "sha256sum -c artifacts/ci-topology/v1.00.26-w1/SHA256SUMS — OK; dag-checkpoint.json matches byte-for-byte")
           (digest-binding . "non-artifact digest 3da8e5265f39df1127aa1bc17dd456b9b29d02f57fa34fc69d355aacc1a2c7e2 reproduces with the recorded command at implementation-sha efe6adb465563b25b635f146dfca66c9a3a83cc8 over .github/workflows/ci.yml scripts/required-pr-checks.policy scripts/gsd-gates/gate-claims.rkt tests/test-milestone-gate.rkt tests/test-ci-runtime-contract.rkt tests/test-w9-ci-workflow-verification.rkt")
           (branch-guard . "test \"$(git branch --show-current)\" != \"main\" — passes; work is on campaign/v1.00.26-w1, delivery goes through the protected-main PR")
           (rollback-rehearsal-dry-run . "documented sequence (not executed against live protection): (1) remove the lint-quality branch-protection requirement first — lint stays required, main never enters a state where a required check is missing; (2) then restore workflow/policy (revert the split) — check-name lint still exists and reports, so no never-reporting window opens; (3) invariant: a half-reverted state (workflow reverted but policy still requiring lint-quality, or vice versa) is a release blocker — the required-set drift alarm fails with both sides named before any push could hide it")
           (file-contract . "all ten declared wave targets exist: ci.yml split, policy adds lint-quality, three test files extended, dag-checkpoint.json + SHA256SUMS checksummed, and the three rktd records are record-only additions outside the digest inputs; delivery lands via the campaign PR on campaign/v1.00.26-w1 with the squash-merge, the post-merge lint-quality-on-main verification, and the protection change owned by the runtime coordinator")))
(record-only . "this validation adds no code and touches no digest input")
