(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W3")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.25-w3.rktd")
(implementation-sha . "cbded764")
(validator . "W3 delivery verification lane (focused scheduler contracts, guard tests, fast suite owned by the coordinator)")
(validation-verdict . "pass")
(checks . ((activation-semantics . "tests/test-runner-scheduler-characterization.rkt: ordering default stays unset while the hold stands (parse-ordering #f with FAST_SHARD_ORDERING unset/set-to-lpt/set-to-fifo; runner default ordering fifo; vocabulary unchanged); manual --ordering override selects the requested ordering; --ordering seam exits 0 and an invalid value exits 2 with a named diagnostic; ci.yml contains no --ordering flag and no FAST_SHARD_ORDERING token")
           (freshness-contracts . "missing evidence, stale evidence (older than the declared default-max-age-seconds), malformed evidence (invalid-shape), and wrong-inventory evidence (do-not-overlap) each fall back to fifo with a DISTINCT named reason and recorded snapshot status/checksum - no silent fallback path exists")
           (determinism-contracts . "two consecutive ordering decisions serialize identically; two consecutive orderings are byte-identical; two consecutive shard-plan generations on the same inputs are structurally and byte identical (canonical recursive key-sorted rendering); real consecutive --shard-plan report runs over the committed durations fixture produced byte-identical output, sha256 08e418bb... on both runs")
           (untouched-contracts . "tests/test-run-tests-profiles.rkt 7/7 and tests/test-runner-work-queue.rkt 11/11 stay green unchanged: same selection, retry, timeout/serial partition, strictness, result ordering, and JSON shape; the characterization suite itself grew from 7 to 17 tests, all green")
           (exactly-one-evidence-record . "docs/reports/gsd-wave-evidence/v1.00.25-w3.rktd contains exactly one wave-evidence record")
           (no-production-change . "the wave diff touches only the extended guard-test file and the three W3 report files; .github/workflows/ci.yml, scripts/run-tests/profiles.rkt, and the runner sources are untouched (git status confirms zero dirty lines in ci.yml)")))
(honesty-check . "no activation, no invented run metrics, no revised targets; the hold record plus real determinism digests is the only deliverable the W1 dependency evidence supports")
