(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W6")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.25-w6.rktd")
(implementation-sha . "56d3f689bfd9e2ea0bbdba6a9557021b5541b2e5")
(branch . "main")
(validation-result . pass)
(checks . ((report-tests . "racket tests/test-ci-cohort-report.rkt — 18/18 green including the C2-specific mode-distinction assertions")
           (manifest-check . "racket scripts/run-tests/cohort-report.rkt --manifest artifacts/ci-baseline/v1.00.25-c2/cohort.json --out-json artifacts/ci-baseline/v1.00.25-c2/report.json --out-md artifacts/ci-baseline/v1.00.25-c2/report.md --check — PASS")
           (decision-file . "test -f artifacts/ci-baseline/v1.00.25-c2/decision.md — PASS; decision.md records target unachieved with observed p50 253.5 s / p95 276.0 s and names the next lever")
           (sums-binding . "SHA256SUMS over cohort.json, report.json, report.md, decision.md verifies clean (sha256sum -c) and is enforced by --check")
           (digest-binding . "non-artifact digest b7f8b341adc8cc3491e32f686b9422b5c4a41a1a7d58c9c72896c06ca0f8c5be reproduces at implementation-sha 56d3f689bfd9e2ea0bbdba6a9557021b5541b2e5 over scripts/run-tests/cohort-report.rkt and tests/test-ci-cohort-report.rkt")
           (file-contract . "all nine declared wave files exist; the three rktd records are record-only additions outside the digest inputs")))
(record-only . "this validation adds no code and touches no digest input")
