(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.26")
(wave . "W4")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.26-w4.rktd")
(implementation-sha . "9dc73a9d79bb47569ad1dd337e2f818f48ce01f4")
(branch . "campaign/v1.00.26-w4")
(validation-result . pass)
(checks . ((runtime-contract-tests . "racket tests/test-ci-runtime-contract.rkt — 38 success(es) 0 failure(s) 0 error(s) at implementation-sha (workflow shards keep the product-default scheduler: ci.yml sets TEST_RUNNER_SCHEDULER nowhere, matched via the env-assignment regexp TEST_RUNNER_SCHEDULER[ \\t]*:; TEST_RUNNER_SCHEDULER=batch still forces batch everywhere; unset still defaults to the product default; scheduler choice does not alter selection, verdicts, JSON shape, or result order; shard-measurement.json exists, is checksum-bound, schema-bound, records n=5 batch / n=2 queue with verdict-target-met=false and decision.outcome=hold)")
           (work-queue-tests . "racket tests/test-runner-work-queue.rkt — 11 success(es) 0 failure(s) 0 error(s); file byte-unchanged by this wave, validating the plan's conditional-extension clause")
           (scheduler-characterization-tests . "racket tests/test-runner-scheduler-characterization.rkt — 18 success(es) 0 failure(s) 0 error(s)")
           (sums-binding . "sha256sum -c artifacts/ci-topology/v1.00.26-w4/SHA256SUMS — OK; shard-measurement.json matches byte-for-byte (verified in-suite and standalone)")
           (digest-binding . "non-artifact digest 2a5cab88cef83b48d7e6df4b7852df59fb2c72c75e789be693b9f0be13ce5f2f reproduces with the recorded command at implementation-sha 9dc73a9d79bb47569ad1dd337e2f818f48ce01f4 over .github/workflows/ci.yml tests/test-ci-runtime-contract.rkt")
           (branch-guard . "test \"$(git branch --show-current)\" != \"main\" — passes; work is on campaign/v1.00.26-w4, delivery goes through the protected-main PR")
           (format-lint . "raco fmt -i applied to tests/test-ci-runtime-contract.rkt after the pre-commit quick-lint flagged the hand-touched pin; the staged file then passed the hook and the commit landed")
           (metrics-sync . "README's generated metrics table was synced earlier on the branch (70bc6f9c) after the W4 test extensions moved the counts; the evidence trio and the final pin flip add record-only files outside the counted surfaces — metrics re-sync re-run before the final commit to guard the CI lint-quality equality check")
           (rollback-rehearsal-dry-run . "documented sequence (not executed against live protection): the delivered workflow scheduler behavior is byte-identical to the pre-wave batch default, so there is nothing to roll back functionally; reverting the decision comment and the test pin restores the exact pre-wave tree; the env seam removal is itself the rollback of the trial — unsetting TEST_RUNNER_SCHEDULER restores the product default everywhere; a checkpoint/SHA256SUMS mismatch is caught by sha256sum -c failing closed")
           (file-contract . "all eight declared wave targets accounted for: ci.yml carries the hold decision comment and no scheduler env, test-ci-runtime-contract.rkt extended with the hold contract, test-runner-work-queue.rkt unchanged by documented necessity, shard-measurement.json + SHA256SUMS present and checksum-bound, and the three rktd records are record-only additions outside the digest inputs; delivery lands via the campaign PR on campaign/v1.00.26-w4 with the squash-merge and post-merge gate confirmation owned by the runtime coordinator")))
(record-only . "this validation adds no code and touches no digest input")
