(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W2")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.25-w2.rktd")
(implementation-sha . "3bd71b73")
(validator . "W2 delivery verification lane (focused scheduler contracts, guard tests, fast suite owned by the coordinator)")
(validation-verdict . "pass")
(checks . ((scheduler-default . "tests/test-run-tests-profiles.rkt: 7/7 - parse-args returns batch with TEST_RUNNER_SCHEDULER unset, set to queue, and set to batch; manual --scheduler queue/batch override still selects the requested scheduler")
           (workflow-contract . "tests/test-scheduler-shadow-workflow.rkt: 10/10 - ci.yml contains no TEST_RUNNER_SCHEDULER token and no --scheduler flag; the required fast shard keeps STRICT_TEST_RUNNER=1 ... --suite fast --jobs 4 verbatim; the lever remains available via the shadow workflow only")
           (characterization-contracts . "tests/test-runner-scheduler-characterization.rkt 7/7 and tests/test-runner-work-queue.rkt 11/11 stay green unchanged: same selection, timeout/serial partition, strictness, result ordering, and JSON shape")
           (exactly-one-evidence-record . "docs/reports/gsd-wave-evidence/v1.00.25-w2.rktd contains exactly one wave-evidence record")
           (no-production-change . "the wave diff touches only the two guard-test files and the three W2 report files; ci.yml and scripts/run-tests/profiles.rkt are untouched")
           (evidence-digest . "non-artifact-content-digest 7cd33e2d... reproduces from tests/test-run-tests-profiles.rkt and tests/test-scheduler-shadow-workflow.rkt at HEAD 3bd71b73 with the recorded command")
           (focused-suite . "racket scripts/run-tests.rkt --suite fast is owned by the coordinator verification lane and was not launched in-session")))
(honesty-check . "no activation, no invented run metrics, no revised targets; the hold record is the only deliverable the W1 dependency evidence supports")
