#hash((status . "current") (milestone . 888) (wave . "W6") (issue . 9547) (branch . "campaign/v1.00.23-w6-c0-close")
      (implementation-sha . "81a0a1e559a7888206070fb0b84ea90826e703f1") (content-digest . "b4d64b4d48de86a545989f5b279c42055d5b8ef0aec70494e13a28b75a31f2bd")
      (red-first . #hash((command . "racket scripts/run-tests/cohort-report.rkt --manifest artifacts/ci-baseline/v1.00.23-c0/cohort.json --out-json artifacts/ci-baseline/v1.00.23-c0/report.json --out-md artifacts/ci-baseline/v1.00.23-c0/report.md --check") (failure . "The former empty manifest was rejected as silently truncated; the closed 20-SHA manifest now regenerates successfully.")))
      (focused-tests . #hash((result . "passed") (count . 69) (suites . "scheduler-order (21), shadow-workflow (8), cohort-report (40)")))
      (format-compile . #hash((result . "passed") (detail . "schema-2 evidence and cohort artifacts parse successfully")))
      (lint . #hash((result . "passed") (detail . "pre-commit and CI lint checks passed")))
      (fast . #hash((result . "passed") (detail . "canonical CI fast artifacts pass; local full-fast run timed out")))
      (review-artifact . "docs/reports/gsd-wave-reviews/v1.00.23-w6.rktd") (remaining-items . ()) (planning-sync . "current"))
