;; Wave validation: v1.00.28 W2 — Fixture amplification reduction with pristine-copy experiment
;; Record-only companion to gsd-wave-evidence/v1.00.28-w2.rktd.
(
(wave . "v1.00.28-w2")
(validated-sha . "8c003200dc39fe275a2a0dd93862cb03c8f4e958")
(checks
  (branch . "campaign/v1.00.28-w2 checked out (not main); base origin/main 04637d83 (v1.00.27 tip); prior-attempt checkpoints 4ecee83a/a55af211/8df65621/15e0b14f/75f26c89 present, this attempt added 8c003200 (verify-command compatibility: SHA256SUMS path form + metrics sync + scratch cleanup) and writes this trio at return")
  (checksums . "sha256sum -c artifacts/test-runtime/v1.00.28-w2/SHA256SUMS from the q root → fixture-census.json OK, git-fixture-experiment.json OK, stress-evidence.json OK (manifest uses exactly the q-root-relative paths the declared Verify command exercises)")
  (focused-suites . "the four touched test files ran individually at the validated SHA: test-pristine-git-fixture 7/7/0, test-gsd-delivery-verifier 25/25/0, test-gsd-campaign-repository 33/33/0, test-gsd-wave-worktree 10/10/0 — all exit 0; the chained Verify command (including the fast suite and the branch check) is coordinator-owned and runs at return")
  (experiment-evidence . "git-fixture-experiment.json carries ≥10 successful samples per arm (14/14), interleaved A/B through the shared constructor, 2 uncounted warmups, medians for construct/first-use/total; stress-evidence.json carries 12/12 concurrent instances per strategy with a byte-identical pristine baseline snapshot (16 files / 1574 bytes before and after); SHA256SUMS pins all three JSON artifacts")
  (gate . "activation gate evaluated and recorded truthfully in TEST-FIXTURE-AMPLIFICATION-v1.00.28.md: isolation ✅, stress ✅, median improvement ❌ (pristine-copy ~3.7x slower than clone), no behavior changes ✅, one-edit rollback ✅ — the failing row means NOT activated; the constructor default is the legacy clone strategy and the hold is stated in the report and both artifact-bearing records")
  (rollback . "one edit: the shared constructor's strategy parameter (back to clone), and the legacy-contract test in tests/test-pristine-git-fixture.rkt pins that contract so the rollback path cannot silently rot")
  (lints . "racket scripts/metrics.rkt --sync-all → synced (test-line metric updated for the wave's test additions); --lint → all 5 static metrics match README.md; racket scripts/lint-format.rkt → 0 errors, 0 warnings over 2386 .rkt files after deleting the attempt's tmp/ scratch probes per the BUG-0026 contract")
  (declared-files . "all twelve declared wave files exist at HEAD: the two new test files, the three edited consuming suites, the three checksummed JSON artifacts + SHA256SUMS, the amplification report, and the gsd-wave-{evidence,reviews,validation}/v1.00.28-w2.rktd trio")
  (no-security-delta . "no execute-* check, isolation root, worker-security contract, gate semantics, or scheduler variable modified; the wave is test-side construction strategy plus artifacts/reports only"))
(prior-failure-addressed . "attempt-1 ended in a provider/network infrastructure failure, not a logic failure; all wave content (safety suite, pristine builder, constructor switch, census, experiment, stress, report, 10 checkpoints) was already on this branch, so this attempt resumed instead of restarting and closed the three gaps the infra stop left: (1) the declared Verify command could not have consumed SHA256SUMS in artifact-relative form — rewritten q-root-relative and re-verified 3/3 OK; (2) the test additions had never been metrics-synced — --sync-all run with lint green; (3) the attempt's tmp/ scratch probes broke the pre-commit format lint and blocked checkpointing — deleted per BUG-0026, lint 0 errors, checkpoint 8c003200 landed; the missing evidence trio is written this attempt")
(result . "all wave-scoped checks green at validated-sha 8c003200 with the truthful activation HOLD preserved (legacy clone default, one-edit rollback contract-tested); the declared Verify command is coordinator-owned and runs at return"))
