(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.26")
(wave . "W0")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.26-w0.rktd")
(implementation-sha . "7219aee72a99e214e6908dd2b9f5a97e6cb0078f")
(branch . "campaign/v1.00.26-w0")
(validation-result . pass)
(checks . ((contract-characterization-tests . "racket tests/test-ci-runtime-contract.rkt — 27 success(es) 0 failure(s) 0 error(s) at implementation-sha (policy-equality pin, twelve required checks, aggregate needs edges, fast-env not-required, fail-closed missing-check failures, snapshot checksum 6e0eee763b696c772482e3f4c3c060d95d96546c690394b2aa5f85139eb41a25)")
           (w9-integration-tests . "racket tests/test-w9-ci-workflow-verification.rkt — exit 0 at implementation-sha (second-layer literal re-pin of the same graph and fail-closed semantics)")
           (sums-binding . "sha256sum -c artifacts/ci-topology/v1.00.26-w0/SHA256SUMS — OK; graph-snapshot.json matches byte-for-byte")
           (digest-binding . "non-artifact digest ddf6f085435b4d96c4b3b18df96ccdf3ce5e002eaa37b22f786224d79dc518b2 reproduces with the recorded command at implementation-sha 7219aee72a99e214e6908dd2b9f5a97e6cb0078f over tests/test-ci-runtime-contract.rkt tests/test-w9-ci-workflow-verification.rkt")
           (policy-anchor-unmodified . "git diff origin/main..HEAD -- scripts/required-pr-checks.policy is empty — the policy is pinned read-only by tests, never edited by this wave")
           (file-contract . "all eight declared wave targets exist: both test files extended, policy anchor untouched, graph-snapshot.json + SHA256SUMS checksummed, and the three rktd records are record-only additions outside the digest inputs; delivery lands via PR #9607 on campaign/v1.00.26-w0 with the squash-merge and merge-SHA binding owned by the runtime coordinator")))
(record-only . "this validation adds no code and touches no digest input")
