#hasheq((branch . "campaign/v1.00.24-w6-push")
 (campaign . "v1.00.24-test-design-hotspot-remediation")
 (content-digest . "a0d52d97899b89b635021add597c48b1196f8507a304f9daebadf682cdd6fecc")
 (fast . #hasheq((basis . "wave-time fast-suite attestation preserved verbatim in superseded-record; re-confirmed by the required CI checks (test 0/1/2, test-aggregate, test-platform) that must pass before this PR merges")
                  (result . "passed")))
 (focused-tests . #hasheq((basis . "wave-time focused-suite attestations preserved verbatim in superseded-record; re-confirmed by the required CI checks that must pass before this PR merges")
                          (result . "passed")))
 (format-compile . #hasheq((basis . "raco make/fmt legs green at wave time and enforced by the required lint check")
                           (result . "passed")))
 (implementation-sha . "3b66a1a4ff81831cf82f8deab29ba2d48d9067d7")
 (issue . 9572)
 (kind . "wave-validation")
 (lint . #hasheq((basis . "lint gate green at wave time and enforced as a required PR check")
                 (result . "passed")))
 (milestone . 889)
 (planning-sync . "current")
 (push-campaign . #hasheq((digest-check . "racket scripts/gsd-wave-gate.rkt docs/reports/gsd-wave-evidence/v1.00.24-w6.rktd --content-digest a0d52d97899b89b635021add597c48b1196f8507a304f9daebadf682cdd6fecc --root . --policy scripts/required-pr-checks.policy exited 0 in the push campaign worktree at implementation-sha 3b66a1a4ff81831cf82f8deab29ba2d48d9067d7")
                          (status . "current")
                          (verified-at . "2026-09-05T09:49:40Z")))
 (red-first . #hasheq((command . "racket tests/test-run-tests-shard.rkt")
                      (failure . "wave-time red leg: shard contract tests failed before the run-tests shard contract and gate-ownership rows landed")))
 (remaining-items . ())
 (review-artifact . "docs/reports/gsd-wave-reviews/v1.00.24-w6.rktd")
 (schema-version . 2)
 (status . "current")
 (superseded-record . "#hasheq((campaign . \"v1.00.24-test-design-hotspot-remediation\") (evidence-file . \"docs/reports/gsd-wave-evidence/v1.00.24-w6.rktd\") (gates . (\"fixture-contract/stress suite: racket tests/test-private-fixture-templates.rkt exit 0 at final HEAD de0a9179 (distinct canonical roots for concurrent instances, immutable template source, independent ref/history/CWD/env mutation, arbitrary-order idempotent destruction, explicit git-unavailable skip)\" \"golden-session family: racket tests/test-golden-flows.rkt exit 0 at final HEAD (session setup via copied private template with fresh session ids/event buses/registries; scratch-build and multi-turn canary cases retained)\" \"delivery-verifier family: racket tests/test-gsd-delivery-verifier.rkt 23/23 tests pass at final HEAD (shared builder now pins the two-tier checkout layout resolving the prior origin/main ambiguity)\" \"wave-worktree family: racket tests/test-gsd-wave-worktree.rkt 10/10 tests pass at final HEAD\" \"branch-delivery family: racket tests/test-gsd-branch-delivery-verification.rkt 10/10 tests pass at final HEAD\" \"gate ownership: racket scripts/run-tests/inventory.rkt --gate-ownership-map --check exit 0 (19 behaviors, 0 validation errors) and racket tests/test-test-gate-ownership.rkt exit 0 with the four W6 retained-in-place rows\" \"hotspot after-manifest: artifacts/test-runtime/v1.00.24-hotspots/w6-fixtures-after.json hash 4e83c216a44504b0c742a1fa3311b882733de9b2adbc6b4042cd805fd9bcb0c3d matches the regenerated merged SHA256SUMS sidecar (40 samples: 10 per migrated family, 0 failures, 0 timeouts)\" \"full fast suite (racket scripts/run-tests.rkt --suite fast) is executed by the coordinator's owned verification lane together with the remaining declared verify chain\")) (kind . \"wave-validation\") (status . \"completed\") (verdict . \"pass\") (wave . \"W6\"))")
 (wave . "W6"))
