(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.26")
(wave . "W7")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.26-w7.rktd")
(implementation-sha . "61be1eef26e2048d5d1860b02a1bc1686094faae")
(branch . "campaign/v1.00.26-w7")
(validation-result . pass)
(checks . ((digest-binding . "non-artifact digest 6d14078a6b9e5ad719e8c41d01fce9fc1a8997374348c911f9af964f744262a8 reproduces with the recorded command at implementation-sha 61be1eef26e2048d5d1860b02a1bc1686094faae over CHANGELOG.md README.md util/version.rkt docs/reports/CI-TOPOLOGY-v1.00.26.md tests/test-w3-telemetry-relocation.rkt tests/test-w9-ci-workflow-verification.rkt (re-verified after the trio commit)")
           (topology-artifact-bindings . "per-report digests re-verified standalone: v1.00.26-w0 graph-snapshot OK, v1.00.26-w1/w2/w3 dag-checkpoints OK, v1.00.26-w4 shard-measurement OK (5/5); artifacts/ci-topology/v1.00.26-c2/SHA256SUMS verified OK (4/4: cohort.json report.json report.md decision.md)")
           (w9-integration-tests . "racket tests/test-w9-ci-workflow-verification.rkt — 18 success(es) 0 failure(s) 0 error(s) at the release-surface tree (re-run after the BUG-0009 de-literalization of its version-derived paths)")
           (w3-contract-tests . "racket tests/test-w3-telemetry-relocation.rkt green at the release-surface tree with version-derived literals after the BUG-0009 de-literalization")
           (release-notes-lint . "racket scripts/lint-release-notes.rkt --check — PASSED: CHANGELOG.md version 1.00.26")
           (metrics-lint . "racket scripts/metrics.rkt --lint — All 5 static metrics match README.md")
           (readiness-partial . "racket scripts/lint-release-readiness.rkt --strict --context tag-publish on the campaign branch: version sync PASS, changelog entry PASS, clean tree PASS, conflict-marker PASS; the on-main check FAILs by construction on a campaign branch (tag-publish context expects a tag checkout or main — coordinator-owned at the merge state) and the gate-evidence checks require fresh .gate-evidence recordings at the final HEAD, re-recorded post-commit as the last implementation action")
           (file-contract . "all eight declared wave targets accounted for: CHANGELOG.md release entry, README.md metrics/status sync, util/version.rkt at 1.00.26, docs/reports/CI-TOPOLOGY-v1.00.26.md new at HEAD, artifacts/ci-topology/v1.00.26-c2/SHA256SUMS verified, and the three v1.00.26-w7.rktd records are record-only additions outside the digest inputs; delivery lands via the campaign PR with squash-merge, tag, publish, and post-release protection re-audit owned by the runtime coordinator")))
(record-only . "this validation adds no code and touches no digest input")
