(kind . "wave-validation")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W4")
(validated-artifact . "docs/reports/gsd-wave-evidence/v1.00.25-w4.rktd")
(implementation-sha . "0897fa6d7eb9bf57b397a624dee2fdfd91270ed2")
(validator . "W4 delivery verification lane (format, affected tests, manifest check, secrets/metrics lints)")
(validation-verdict . "pass")
(checks . ((tdd-tests . "tests/test-run-tests-profiles.rkt: 9/9 green re-run at implementation-sha 0897fa6d (and at attempt-2 HEAD), including the two W4 hold pins (security required lane stays on batch with byte-pinned suite command; TEST_RUNNER_SCHEDULER=batch still forces batch everywhere) and the tests-first ordering check counting the W4 test-cases in the delivery commit")
           (cross-check . "racket tests/test-scheduler-shadow-workflow.rkt: 10/10 green re-run at 0897fa6d, including its global ci.yml pin that no lane may reference the scheduler repository variable — confirming the W4 comment-only ci.yml change introduced no scheduler lever")
           (ci-yml-comment-only . "the ci.yml delta between 63b2aa6f and 351e8548 is the 7-line W4 hold notice above the security job, and ci.yml is byte-identical from 351e8548 through 0897fa6d; no job, step, environment, secret, sandbox, or command token changed")
           (exactly-one-evidence-record . "docs/reports/gsd-wave-evidence/v1.00.25-w4.rktd contains exactly one wave-evidence record")
           (evidence-digest . "non-artifact-content-digest fc006543... reproduces from .github/workflows/ci.yml and tests/test-run-tests-profiles.rkt at implementation-sha 0897fa6d with the reproduction command recorded in the evidence record; attempt-1's 2ef2e29c... pin was stale after the canonical-fmt checkpoint and failed delivery verification, which is repaired by this rebind")
           (focused-suite . "racket scripts/run-tests.rkt --suite security and --suite fast are owned by the coordinator verification lane and were not launched in-session; the two contract test files were run focused instead")))
(honesty-check . "no fabricated samples, no revised targets, no invented run IDs; hold is the only verdict the recorded evidence supports, and the record says plainly that the security gate was not evaluable rather than estimating a p50 from absent data")
