#hasheq((campaign . "v1.00.24-test-design-hotspot-remediation")
        (kind . "wave-validation")
        (wave . "W8")
        (branch . "main")
        (implementation-sha . "c28430fba6e418d346cd183d82c7262abcaab3e0")
        (content-digest-command . "git diff --binary d37b474b..c28430fb -- . (excluding gsd-wave-evidence/reviews/validation) | sha256sum")
        (checks . (#hasheq((command . "racket scripts/run-tests/hotspot-benchmark.rkt --manifest artifacts/test-runtime/v1.00.24-hotspots/w3-gsd-timeout-after.json --check")
                           (exit . 0)
                           (result . "regenerated manifest matches --check expectations: hotspot family w3-gsd-timeout reproducible (command/source/sample count/config+inventory digests/before-after medians recorded, verdict unchanged)"))
                  #hasheq((command . "sha256sum -c SHA256SUMS (in artifacts/test-runtime/v1.00.24-hotspots/)")
                          (exit . 0)
                          (result . "6/6 entries OK: w1-cwd-after, w2-retry-after, w3-gsd-timeout-after, w4-gsd-timeout-after, w5-discovery-after, w6-fixtures-after — all comparison manifests byte-identical to published checksums"))
                  #hasheq((command . "racket scripts/run-tests/inventory.rkt --gate-ownership-map --check")
                          (exit . 0)
                          (result . "behaviors: 19, validation errors: 0 — zero orphan behavior IDs, zero duplicate IDs, zero missing destinations; non-ledger inventory unchanged; source-membership changes all paired with valid destinations (GSD-WAVE-WORKTREE-PRIVATE-TEMPLATE: fast->fast owner test-design; GSD-BRANCH-DELIVERY-PRIVATE-TEMPLATE: fast->fast owner test-design)"))))
        (evidence-state . "single integrated wave-evidence record at docs/reports/gsd-wave-evidence/v1.00.24-w8.rktd; bake table in docs/reports/TEST-DESIGN-HOTSPOT-BAKE-v1.00.24.md shows per-family command, source, sample count, digests, before/after median/p95, failures/timeouts, destination, verdict; incomparable/missed rows labeled honestly")
        (queue-lpt-status . "queue run only as compatibility drill with canonical batch defaults preserved; queue/LPT not activated; grouped broad activation and the 2x claim withheld")
        (release-truth . "step 7 (protected-main PR merge, annotated v1.00.24 tag, public release verification) remains coordinator-owned; this record attests implementation-side checks only")
        (timestamp . "2026-07-24T12:00:00Z"))
