(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W7")
(wave-title . "Integrated bake, evidence closure, and v1.00.25 release")
(status . "ready-for-merge")
(implementation-sha . "ce4a3c82334e3c32b601e8934205a69dc66fcf9a")
(dependency-sha . "56d3f689bfd9e2ea0bbdba6a9557021b5541b2e5")
(branch . "main")
(attempt-history . ((attempt-1 . "ended in a provider/network infrastructure stop before completion (no logic failure recorded by the runtime); the wave was preserved (attempt not consumed) and resumed from the committed checkpoints on main — the version bump, release-language sync, release-entry contract test, and README metrics sync from the prior attempt were kept and extended, not redone")))
(non-artifact-content-digest . "c3f5f098d1c978f46e567e0a1179fd6cbc208694e196963610c7205b80894781")
(non-artifact-digest-inputs . "util/version.rkt info.rkt tests/test-release-entry-current.rkt tests/test-ci-cohort-report.rkt tests/test-prepared-env-report.rkt tests/test-run-tests-profiles.rkt (paths relative to repo root; reproduce with: cd q && for f in util/version.rkt info.rkt tests/test-release-entry-current.rkt tests/test-ci-cohort-report.rkt tests/test-prepared-env-report.rkt tests/test-run-tests-profiles.rkt; do git show ce4a3c82334e3c32b601e8934205a69dc66fcf9a:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum)")
(measurement . ((gate-text . "Roadmap v1.00.25 §6 W7: bake the v1.00.25 release — integrated fast/security/arch gates, provisioned broad gates, strict release preflight, release language naming every activated and non-activated state explicitly, and durable evidence closure; the release-entry tests bind changelog, version surfaces, and the activation report; tag creation and public release publication are the runtime coordinator's owned post-verify flow and are not claimed as done inside this record.")
                (gate-evaluable . #t)
                (gate-verdict . pass)
                (gate-verdict-label . "in-repo bake and evidence closure green at implementation-sha; publication reserved to the owned verification lane")
                (release-entry-tests . "tests/test-release-entry-current.rkt — 5/5 green: CHANGELOG references the milestone, util/version.rkt (1.00.25) agrees with info.rkt and the README version badge, and the activation report's per-lane states are bound")
                (activation-states . ((fast-queue . "not activated — C1 overall-verdict hold (0 attempts / 0 samples on all three queue configurations); W2 hold record + C1 decision 67638641fd644a02bda41a4f27bf56281f01df9cfe8850f6303d29fb0c437fea")
                                      (fast-lpt . "not activated — C1 fast-LPT hold (0 attempts / 0 samples, no predicted improvement); W3 hold record + C1 decision")
                                      (security-queue . "not activated — W4 decision w4-security-queue-v1 verdict hold (security lane keeps pinned single --suite security run)")
                                      (prepared-environment . "not activated — decision reserved; W5 evidence integrated and passing (15/15 verified restores, rate 1.0 >= 95%, zero fallbacks)")
                                      (grouped-tier-overlap . "not activated — withheld, out of v1.00.25 scope by plan (reserved to v1.00.26/v1.00.27)")
                                      (performance-claim . "not made — C1 and C2 decisions record honest holds / target unachieved; no 2x claim anywhere"))
                (evidence-closure . "the activation report's evidence index quotes every checksum verbatim from the delivered SHA256SUMS manifests; all eight C1/C2 checksums and the prepared-env report checksum re-verified byte-for-byte with sha256sum -c and direct sha256sum at implementation-sha"))))
(decision . ((release-readiness . "the strict preflight is designed to run at the coordinator's owned verification lane with --context tag-publish (tag uniqueness check skipped by design because the tag may be created at publication time); all in-repo preflight components are green at implementation-sha and the coordinator's verify command re-runs the exact declaration")
             (rollback . "release rollback is the standard upstream flow; nothing inside the milestone requires a code rollback because no scheduler lever was activated — main already is the rollback state")))
(delivery . ((tdd-tests-first . #t)
             (contract-tests . "tests/test-release-entry-current.rkt written first in the prior attempt and pinned by checkpoint 0fcbc3de, then de-hardcoded to derive report filenames from q-version in ce4a3c82; it binds CHANGELOG <-> util/version.rkt <-> info.rkt <-> README badge <-> activation report states")
             (focused-suite-command . "racket tests/test-release-entry-current.rkt && racket scripts/metrics.rkt --lint && racket scripts/lint-release-notes.rkt --check && racket scripts/release-dry-run.rkt && racket scripts/lint-release-readiness.rkt --strict --context tag-publish")
             (artifacts . ((changelog . "CHANGELOG.md v1.00.25 entry naming every lane state and binding the activation report")
                           (activation-report . "docs/reports/TEST-SCHEDULER-ACTIVATION-v1.00.25.md (per-lane states, every claim checksum-bound)")
                           (sums-c1 . "artifacts/ci-baseline/v1.00.25-c1/SHA256SUMS (final; sha256sum -c clean)")
                           (sums-c2 . "artifacts/ci-baseline/v1.00.25-c2/SHA256SUMS (final; sha256sum -c clean)")
                           (version . "util/version.rkt and info.rkt at 1.00.25; README badge version-1.00.25")))
             (honesty . ((evidence-provenance . "every activation-report claim quotes a delivered SHA256SUMS checksum verbatim and all were re-verified byte-for-byte at implementation-sha; the non-artifact digest is computed over the exact non-doc files W7 touched at ce4a3c82334e3c32b601e8934205a69dc66fcf9a with the reproduction command recorded above")
                         (state-honesty . "the report names all four non-activated lanes with named reasons plus the withheld grouped-mode scope and the unmade 2x claim; no lane is softened to activated and no performance claim is implied")
                         (publication-honesty . "this record does not claim the annotated tag or the public release; tag creation and publication run in the coordinator's owned verification lane after merge, per the runtime contract")
                         (digest-provenance . "digest c3f5f098d1c978f46e567e0a1179fd6cbc208694e196963610c7205b80894781 reproduces at implementation-sha ce4a3c82334e3c32b601e8934205a69dc66fcf9a; the record-only commits that add these rktd files touch no digest input")))))
(note . "W7 closes the v1.00.25 campaign in-repo: the release language (CHANGELOG + activation report) names every activated and non-activated state explicitly with verbatim checksums, the version surfaces agree, the release-entry contract test is green, and the C1/C2 baseline sums verify clean. The tag and public release are deliberately not created here — they belong to the coordinator-owned post-verify publication flow, and the strict readiness lint is invoked with --context tag-publish accordingly.")
(review-artifact . "docs/reports/gsd-wave-reviews/v1.00.25-w7.rktd")
(validation-artifact . "docs/reports/gsd-wave-validation/v1.00.25-w7.rktd")
