(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.26")
(wave . "W7")
(wave-title . "Bake, rollback-rehearsal evidence closure, and the v1.00.26 release")
(status . "ready-for-merge")
(implementation-sha . "61be1eef26e2048d5d1860b02a1bc1686094faae")
(branch . "campaign/v1.00.26-w7")
(dependency-state . "branched from origin/main after W0-W6 delivered with durable topology evidence: the required-check graph is characterized and pinned (W0), the atomic lint split is live and protected (W1), fast-env overlaps lint-quality (W2), shard-plan-report left the mergeable path (W3), the scheduler and worker-scale holds are recorded with observed numbers (W4/W5), and the honest target-unachieved C2 verdict is bound byte-for-byte (W6)")
(attempt-history
  (attempt-1 . "FAILED delivery verification: the wave's implementation surfaces (topology report, release-surface doc sync, prepared-env evidence binding) were written into the working tree but never committed to the delivery branch, and the evidence trio was never created — the coordinator's changed-target-files check had nothing at HEAD to verify")
  (attempt-2 . "resume after attempt-1: audited the leftover working tree, classified every pre-staged/unstaged change as in-scope W7 surfaces, committed the topology report and prepared-env evidence binding (8231db41), committed the release-surface doc/version sync with the BUG-0009 de-literalization of the W3/W9 tests (61be1eef), created the evidence trio, and re-verified every checksum binding standalone — the declared target files now all exist at HEAD on campaign/v1.00.26-w7"))
(non-artifact-content-digest . "6d14078a6b9e5ad719e8c41d01fce9fc1a8997374348c911f9af964f744262a8")
(non-artifact-digest-inputs . "CHANGELOG.md README.md util/version.rkt docs/reports/CI-TOPOLOGY-v1.00.26.md tests/test-w3-telemetry-relocation.rkt tests/test-w9-ci-workflow-verification.rkt (paths relative to repo root; reproduce with: cd q && for f in CHANGELOG.md README.md util/version.rkt docs/reports/CI-TOPOLOGY-v1.00.26.md tests/test-w3-telemetry-relocation.rkt tests/test-w9-ci-workflow-verification.rkt; do git show 61be1eef26e2048d5d1860b02a1bc1686094faae:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum; the wave-evidence trio itself is deliberately NOT a digest input — it is record-only, and the topology artifacts are instead bound byte-for-byte by the per-wave SHA256SUMS files)")
(measurement
  (gate-text . "Roadmap v1.00.26 section 7 W7: bake v1.00.26 from a clean clone at the exact merge SHA; all required checks remain protected; the rehearsed DAG rollback evidence is retained and verified; integrated gates pass; the release publishes with honest language about what changed and what was held; every required check is verified still required after the release.")
  (gate-evaluable . #t)
  (gate-verdict . "ready-for-merge — bake surfaces complete and checksum-bound; release publish and post-release protection re-audit are coordinator-owned steps that complete at the merge SHA")
  (topology-report . "docs/reports/CI-TOPOLOGY-v1.00.26.md: per-wave change table (W0-W7), DAG timing checkpoints with same-SHA provenance at c6ee39e4, the three honest holds with observed numbers, the rehearsed rollback in fail-safe order (remove the lint-quality protection requirement first, restore workflow/policy state second, lint required throughout), and the checksummed dry-run evidence — every digest in the report re-verified OK standalone against the live artifacts this attempt")
  (holds-honesty . "no speedup claim for any held lever; the only measured critical-path improvements claimed are the W1 lint split (~65 s at same SHA) and the W3 telemetry relocation (289 s earlier); the W6 miss (p50 935 s vs 588 s, p95 957.5 s vs 735 s) is reported as target unachieved with no target revision")
  (release-surfaces . "CHANGELOG.md carries the dated v1.00.26 entry naming every topology change, every hold, and the rollback rehearsal; README metrics/status rows synced (test lines 263061 after the W3/W9 test de-literalization); util/version.rkt already at 1.00.26 from the W0 characterization; the README status language names the W4/W5/W6 holds explicitly"))
(decision
  (outcome . "bake delivered; release publish proceeds at the coordinator-verified merge SHA")
  (no-target-revision . "the W6 elapsed thresholds stand; the holds from W4/W5 are restated with their observed numbers and are not relitigated in the release language")
  (rollback . "the rehearsed rollback is documented in the topology report with its checksummed dry-run evidence (per-wave SHA256SUMS plus the integrated C2 binding, all re-verified OK); the ordering constraint — protection requirement removed first, workflow/policy restored second, lint required throughout — is preserved in every surface that mentions the procedure")
  (post-release-audit . "the required-check set re-audit against scripts/required-pr-checks.policy is declared in the topology report and gated on the coordinator's tag-publish step; the readiness lint runs with --context tag-publish in this wave's focused checks so the pre-publish state fails closed"))
(delivery
  (tdd-tests-first . #t)
  (contract-tests . "tests/test-w9-ci-workflow-verification.rkt pins the W0/W1/W2 topology graph, the lint split, and the W2 DAG checkpoint with version-derived paths (18 success(es) at this HEAD); tests/test-w3-telemetry-relocation.rkt pins the relocation contract with version-derived literals; the BUG-0009 de-literalization means a future version bump fails loudly instead of silently pinning stale literals")
  (focused-suite-command . "racket tests/test-w9-ci-workflow-verification.rkt && racket tests/test-w3-telemetry-relocation.rkt && racket scripts/lint-release-readiness.rkt --strict --context tag-publish && racket scripts/lint-release-notes.rkt --check && racket scripts/metrics.rkt --lint && (cd artifacts/ci-topology/v1.00.26-c2 && sha256sum -c SHA256SUMS) — all green at implementation-sha; the coordinator owns the full fast/security/arch/dry-run gate at the merge SHA")
  (artifacts
    (topology-report . "docs/reports/CI-TOPOLOGY-v1.00.26.md (per-wave record, checkpoints, holds, rollback rehearsal, checksummed evidence)")
    (sha256sums . "artifacts/ci-topology/v1.00.26-c2/SHA256SUMS (final C2 binding; verified OK standalone)")
    (prepared-env-evidence . "artifacts/ci-topology/v1.00.26-prepared-env/SHA256SUMS + report.json (129 restore records bound from the W5 campaign evidence)")
    (evidence-trio . "docs/reports/gsd-wave-{evidence,reviews,validation}/v1.00.26-w7.rktd (record-only)"))
  (pr-plan . "single PR from campaign/v1.00.26-w7 to main carrying the topology report, release surfaces, prepared-env evidence binding, de-literalized tests, and this evidence trio; squash-merge, annotated tag at the merge SHA, protected-environment release publish, and the post-release required-check re-audit are coordinator-owned"))
(record-only . "the evidence trio adds no code and touches no artifact bytes; digest inputs were final at 61be1eef")
