(kind . wave-evidence)
(wave . "v1.00.26-w5")
(package . "v1.00.26 CI critical-path topology — §7 W5 four-worker workflow stress and guarded activation")
(implementation-branch . "campaign/v1.00.26-w5")
(implementation-sha . "afa11cfffb9926041e1c1716bfb98da82c3e2994")
(decision . hold)
(gate-state . ((decision . hold)
               (reason . "missing-evidence")
               (reason-detail . "four-worker CI evaluation could not run in this delivery environment (no GitHub Actions runner, no gh/net access); the artifact therefore records gate-evaluable=false with zero real-CI four-worker PR runs instead of a fabricated activation")
               (workflow-p50-seconds . 0)
               (gate-p50-seconds . 220)
               (required-checks . "not-observed")
               (contamination . none)
               (gate-evaluable . #f)
               (targets-unrevised . #t)
               (pinned-in-suite . #t)
               (ci-test . "tests/test-ci-runtime-contract.rkt checks gate-evaluable=false, real-ci-four-worker-pr-runs=0, decision=hold, and targets-unrevised directly from stress-evidence.json")))
(decision-rule . "activate only if all required checks green AND workflow p50 <= 220 s AND isolation evidence clean across >= 5 real-CI four-worker PR runs; otherwise hold with observed numbers and the isolation failure named — no evidence exists, so hold is the only truthful state and it is enforced by the contract suite (silently flipping to activate fails Pin 11)")
(seam . ((where . ".github/workflows/ci.yml e2e jobs vars.WORKFLOW_TEST_JOBS")
         (default . "unset -> product default 2 workers")
         (guarded-value . "4 workers exactly when WORKFLOW_TEST_JOBS == '4'")
         (no-unconditional-four . "Pin 11 asserts the literal string '--jobs 4' is absent from the shard run block and that the only four-worker path is the guarded expression + flow-through")
         (flow-through . "shard env WORKFLOW_TEST_JOBS feeds the runner as --jobs \"$WORKFLOW_TEST_JOBS\" — flags survive the continuation")))
(evidence . ((source . "local stress artifact with gate-evaluable=false; real-CI four-worker p50 needs the coordinator-owned PR lane")
             (artifact . "artifacts/ci-topology/v1.00.26-w5/stress-evidence.json")
             (artifact-sha256 . "e19e57a3bbf2887e2109c13eb1c832df7fa23bcbe376b7aa84b6967a8c94bdac")
             (sha256sums . "artifacts/ci-topology/v1.00.26-w5/SHA256SUMS")
             (non-artifact-content-digest . "2376109593b4c6ce9fbabb1d0cecbc41d41bf6e446df8d4b5d43812600a2ac28")
             (digest-inputs . ".github/workflows/ci.yml, tests/test-ci-runtime-contract.rkt, tests/test-worker-security.rkt")
             (digest-input-reproduction . "cd <project-base>/q && for f in .github/workflows/ci.yml tests/test-ci-runtime-contract.rkt tests/test-worker-security.rkt; do git show afa11cfffb9926041e1c1716bfb98da82c3e2994:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum")))
(nightly-pr-reconciliation . ((statuses . "nightly and PR lanes use the same runner image and toolchain pins; the 220 s workflow gate applies to the PR lane, and the recorded env/profile table explains why the nightly lane's extra artifacts (bundle + coverage upload) are profiled separately rather than folded into the PR gate")
                              (artifact-table . "stress-evidence.json nightly-pr-reconciliation (env/profile rows with the same-SHA statement)")
                              (pinned . #t)
                              (ci-test . "tests/test-ci-runtime-contract.rkt asserts the reconciliation record exists with both lanes named")))
(isolation . ((per-worker-home . "pinned absent as a contamination signal: no shared mutable HOME/cache-key/temp-root pattern in ci.yml; worker-security suite scans the live file for shared cache keys, shared artifact names, and overlapping temp roots")
              (positive-controls . "shared-cache-key, shared-artifact-name, and overlapping-TMPDIR controls fail the scanner (proving it detects contamination when present)")
              (negative-control . "the live ci.yml passes the same scanner clean")
              (artifact-pointer . "stress-evidence.json isolation scan names zero signals found; activation would still require the five-run real-CI streak")))
(rollback . "documented before use and one line: leave the repo variable WORKFLOW_TEST_JOBS unset (or set it to anything other than '4'); the guard resolves the worker count back to the product default of 2 on the next run — no revert commit needed; recorded in the ci.yml comment, the stress artifact decision.rollback, and pinned present by the contract suite")
(delivery . ((tdd-tests-first . #t)
             (contract-tests . "tests/test-ci-runtime-contract.rkt (extended with Pin 11: guarded WORKFLOW_TEST_JOBS seam with the exact vars.WORKFLOW_TEST_JOBS == '4' expression, --jobs \"$WORKFLOW_TEST_JOBS\" flow-through, no unconditional --jobs 4, --shard-index/--shard-total 2 stability, W5 decision comment with HOLD + artifact pointer + rollback documentation, stress-evidence.json schema/binding checks incl. gate-evaluable=false and real-ci-four-worker-pr-runs=0, and the contamination canary with positive/negative controls — 42 success(es) 0 failure(s) 0 error(s)), tests/test-worker-security.rkt (extended with the W5 workflow-worker isolation sub-suite: live ci.yml free of contamination signals across output names/cache keys/temp roots, positive controls for shared cache key, shared artifact names, and overlapping TMPDIR — 40 + 2 success(es) 0 failure(s) 0 error(s))")
             (focused-suite-command . "racket tests/test-ci-runtime-contract.rkt && racket tests/test-worker-security.rkt && sha256sum -c artifacts/ci-topology/v1.00.26-w5/SHA256SUMS && test \"$(git branch --show-current)\" != \"main\" — all green at implementation-sha; plus the run-block extraction check (sed the shard run block, bash -n, and a guarded dry execution) proving the shipped comment placement keeps the command intact")
             (artifacts . ((stress-evidence . "artifacts/ci-topology/v1.00.26-w5/stress-evidence.json (gate state with 0-of-5 runs and gate-evaluable=false, isolation scan + missing-for-activation naming, nightly/PR env/profile reconciliation, hold decision with activation path and one-line rollback, targets-unrevised=true)")
                           (sha256sums . "artifacts/ci-topology/v1.00.26-w5/SHA256SUMS (binds stress-evidence.json byte-for-byte; verified OK in-suite and standalone)")))
             (pr-plan . "single PR from campaign/v1.00.26-w5 to main carrying the guarded seam with the hold decision comment, the extended contract pins, the stress artifact pair, and this evidence trio; the PR records the hold per the wave rule (activation lands in the same PR only with complete green evidence — none exists); squash-merge and post-merge gate confirmation are coordinator-owned")))
(attempt-history . "attempt 1 ended in a provider/network infrastructure stop (no logic failure recorded by the runtime); resume reused its on-branch work rather than restarting: the seam, red-first pins, and evidence-trio scaffolding already existed and only needed completion — the run-block comment-placement defect (comments between backslash continuations silently truncating runner flags) was reproduced via a tmp scratch run that showed the runner receiving a command with all flags after 'racket scripts/run-tests.rkt' dropped, then moved the comments above the run block and re-verified with bash -n plus a live extraction of the shard run block; landed as 53e56e2c, followed by checkpoint afa11cff that raco-fmt-canonicalized the hand-edited isolation sub-suite (30/32-line mechanical reflow, suites re-run green) and re-ran the metrics resync (no diff); then this evidence trio was bound at afa11cff")
(record-only . "this evidence file adds no code and touches no digest input")

