(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W4")
(wave-title . "Decide and activate the security queue from the same C1 evidence")
(status . "ready-for-merge")
(implementation-sha . "0897fa6d7eb9bf57b397a624dee2fdfd91270ed2")
(dependency-sha . "63b2aa6f")
(branch . "main")
(attempt-history . ((attempt-1 . "FAILED delivery verification: the non-artifact digest was bound at 351e8548, but the follow-up canonical-fmt checkpoint 0897fa6d changed tests/test-run-tests-profiles.rkt, so digest 2ef2e29c... no longer described the delivered files")
                    (attempt-2 . "digest rebound over the same two non-artifact files at implementation-sha 0897fa6d; the record-only repair commits touch no digest input")))
(non-artifact-content-digest . "fc00654358ebbd3afd88499cd00d5177b8b9052c7b8d087670772998efea5050")
(non-artifact-digest-inputs . ".github/workflows/ci.yml tests/test-run-tests-profiles.rkt (paths relative to repo root; reproduce with: cd q && for f in .github/workflows/ci.yml tests/test-run-tests-profiles.rkt; do git show 0897fa6d7eb9bf57b397a624dee2fdfd91270ed2:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum)")
(decision . ((decision-version . "w4-security-queue-v1")
             (lane . "security-queue")
             (verdict . "hold")
             (gate-text . "Roadmap v1.00.25 §6 W4: security queue p50 <= 240 s with permission, isolation, and sandbox semantics completely unchanged, and no reliability regression versus paired batch. A missed or unevaluable gate produces hold, never a revised target.")
             (gate-evaluable . #f)
             (observed . ((paired-samples . 0)
                          (security-queue-p50-s . "not measurable (no samples)")
                          (paired-batch-baseline . "no security/batch cohort leg exists; the only captured baseline leg is fast/batch/fifo (20 samples, p50 228.5815 s, p95 235.9965 s), which is a fast-lane baseline, not a security-lane one")))
             (w1-basis . "W1 wave-evidence record decision block: (security-queue . hold) with security/queue/fifo at 0 recorded attempts across all 20 eligible SHAs; cohort status stays started")
             (next-lever . "close cohort C1's security/queue/fifo shadow leg with real scheduled-run evidence (re-validate run IDs against the GitHub API as in W1's offline re-validation), then re-run the reviewed security-gate decision in a future wave/decision record")
             (activation . none)
             (ci-yml-change . "comment-only W4 hold notice above the security job; no scheduler token and no command change")
             (rollback-command . "not applicable (nothing was activated); had a promotion ever landed, rollback is: remove the TEST_RUNNER_SCHEDULER lever from the lane and rerun")))
(delivery . ((tdd-tests-first . #t)
             (contract-tests . "tests/test-run-tests-profiles.rkt W4 hold pins: (1) the required security lane's workflow block carries no scheduler token and its single --suite security run command is pinned verbatim, so permission/isolation/sandbox semantics cannot change without a deliberate pin relaxation; (2) TEST_RUNNER_SCHEDULER=batch still forces batch everywhere; (3) no ci.yml lane resolves a scheduler from the repository variable")
             (focused-suite-command . "racket tests/test-run-tests-profiles.rkt && racket tests/test-scheduler-shadow-workflow.rkt")
             (scheduler-neutrality . "nothing was activated, so no security test, environment isolation, HOME sandbox, worker allowlist, or verdict path changed; the only ci.yml delta is the W4 comment block, and the byte-pinned suite command plus the scheduler-token guards prove the execution semantics are identical to batch")
             (honesty . "hold recorded from genuinely absent paired evidence: the security shadow leg has zero attempts in artifacts/ci-baseline/v1.00.25-c1/cohort.json and no security/batch paired baseline exists; no numbers were invented and no target was revised")))
(honesty . ((evidence-provenance . "all observed numbers are quoted from the W1 wave-evidence record and artifacts/ci-baseline/v1.00.25-c1/decision.md; this wave captured no new cohort attempts")
            (digest-provenance . "digest fc006543... is computed over the two current non-artifact files (.github/workflows/ci.yml, tests/test-run-tests-profiles.rkt) at implementation-sha 0897fa6d (the canonical-fmt checkpoint that is the final content state of both inputs) with the exact reproduction command recorded above; attempt-1 digest 2ef2e29c... was computed at 351e8548 before the fmt checkpoint landed and was stale at delivery time")))
(note . "W4 records the roadmap-consistent hold for the security queue: the C1 evidence cannot evaluate the security gate (zero paired samples), the lane stays on the CLI batch default, permission/isolation/sandbox semantics are untouched by construction (comment-only ci.yml change with byte-pinned suite command), and the next lever is closing the C1 security shadow leg with real run evidence.")
(review-artifact . "docs/reports/gsd-wave-reviews/v1.00.25-w4.rktd")
(validation-artifact . "docs/reports/gsd-wave-validation/v1.00.25-w4.rktd")
