;; Wave evidence: v1.00.27 W5 — Final C3 cohort and independent verification
;; Record-only companion to gsd-wave-reviews/v1.00.27-w5.rktd
;; and gsd-wave-validation/v1.00.27-w5.rktd.
(
(wave . "v1.00.27-w5")
(ticket . "#9593")
(implementation-sha . "d5f9afbab1de65558a91e92dbab3d19c83cda5d1")
(delivery . "branch campaign/v1.00.27-w5; squash-merge PR owned by the coordinator binds this trio to the merge SHA")
(scope . "scripts/run-tests/cohort-report.rkt (final-claim verdict mode), tests/test-ci-cohort-report.rkt (extended), artifacts/ci-baseline/v1.00.27-c3/{cohort.json,report.json,report.md,decision.md,independent-verification.md,SHA256SUMS}, docs/reports/gsd-wave-evidence|reviews|validation/v1.00.27-w5.rktd")
(tooling-digests
  ("scripts/run-tests/cohort-report.rkt" . "938a57d20ff46b5a9ee2b047b6eea42391f2d45eac03ae5242e02021615c61bc")
  ("tests/test-ci-cohort-report.rkt" . "582bed50380dd27fa2a466a2237656f6bd8a926d1f24aec27e63e6cf44e2e702"))
(what-was-done
  (final-claim-mode "cohort-report.rkt gained the final-claim verdict mode: every roadmap §8 row (fast p50/p95, PR CI p50/p95, security runner p50, workflows runner p50, prepared-env verified restores) is evaluated against the FIXED thresholds (fast ≤115/≤135 s, PR CI ≤588/≤735 s, security ≤240 s, workflows ≤220 s, prepared-env ≥95%) with its coupled guards (inventory-accounted, reliability-non-regression, semantic-gate-equivalence, four-worker-isolation-proof, failure-truth, shared-state-permission-isolation, prepared-env-no-bypass); a row missing guard evidence is recorded unverified, never pass; reasons and verdicts are tool-computed, never hand-written; percentiles are exact-quantile linear interpolation at rank q*(n-1)")
  (hash-key-duality "guard identifiers arriving from JSON arrays are strings while the gate table keys by symbol; the mode normalizes guard ids so string-keyed lookups resolve, and threshold comparisons use equal? so JSON numbers match exactly — both covered by tests (checkpoint 3161494e), plus symbol-normalized guard ids and JSON-null prepared-env acceptance for pre-cutover SHAs (checkpoint 5608b89f)")
  (cohort "artifacts/ci-baseline/v1.00.27-c3/cohort.json accumulates the C3 cohort on real merged PRs: 20 unique eligible head SHAs (expected 20, none dropped), 21 attempts (one SHA retried once) with 21 successes / 0 failures / 0 reruns / 0 cancels, 12 lane-run-failed exclusions disjoint from the included set, per-SHA per-attempt raw timing samples (fast-execution, end-to-end PR elapsed, security runner, workflows runner), per-SHA inventory digests, prepared-env record outcomes (24 records over the cutover window: 24 verified, 0 fallback, rate 100.0), and the recorded C2 reliability baseline (checkpoint 59eb0e3f)")
  (report "report.json/report.md regenerated deterministically from cohort.json by the final-claim mode: six of seven rows miss their fixed targets (fast-p50 267.5 s vs ≤115, fast-p95 285.95 s vs ≤135, pr-ci-p50 1043.5 s vs ≤588, pr-ci-p95 1175.65 s vs ≤735, security-runner-p50 685.5 s vs ≤240, workflows-runner-p50 695.5 s vs ≤220 — all 'target not achieved'), prepared-env-verified-restores passes (100.0% ≥ 95.0%); all seven rows carry their guard evidence; targets never revised; --check byte-stable over the committed report (checkpoint d5f9afba)")
  (decision "decision.md records the tool-computed verdict 'target not achieved' with observed numbers per row, the no-rollback queue disposition (timing miss alone, zero reliability regression versus C2), and named next levers (fast-lane critical path, PR-CI gate topology, security/workflows suite sharding) for separate reviewed decisions; the verified verdict remains withholdable until every row passes with its guard")
  (independent-verification "independent-verification.md is a second-channel review by an agent process independent of the implementing executor: it re-derived all 7 row observed values from the raw per-SHA samples with the same q*(n-1) interpolation, re-derived all verdicts against the fixed thresholds, recounted SHA uniqueness (20/20), attempt reliability (21/21/0/0/0), prepared-env records (24/24 verified, pre-cutover nulls correctly excluded), and resolved every guard reference to an existing file — per-row agree on all seven rows; overall AGREE with 'target not achieved'; its channel limitation (no shell access for sha256sum in that channel) is disclosed in the record and later covered by this channel's sha256sum -c")
  (checksums "SHA256SUMS pins all five final artifacts (cohort.json, report.json, report.md, decision.md, independent-verification.md); the wave-evidence record above binds the non-artifact tooling content digests (cohort-report.rkt, test-ci-cohort-report.rkt) so the verdict-producing code is pinned alongside the data"))
(focused-results
  (test-ci-cohort-report . "racket tests/test-ci-cohort-report.rkt → 74+9+20+24 success(es) 0 failure(s) 0 error(s), exit 0 (final-claim gate rows, guard duality, unverified-never-pass, exact quantiles)")
  (regeneration-check . "racket scripts/run-tests/cohort-report.rkt --manifest artifacts/ci-baseline/v1.00.27-c3/cohort.json --out-json ... --out-md ... --check → CHECK PASS: match, exit 0 (byte-stable regeneration)")
  (checksums . "sha256sum -c artifacts/ci-baseline/v1.00.27-c3/SHA256SUMS → all five artifacts OK")
  (branch . "campaign/v1.00.27-w5 checked out; not main"))
(prior-failure-addressed . "the previous wave attempt ended in a provider/network infrastructure failure, not a logic failure; this attempt resumed the committed branch work (five tooling/cohort checkpoints already present), did not restart exploration, and completed the previously missing declared targets: SHA256SUMS written and verified, decision.md and independent-verification.md committed, and this evidence/review/validation trio written so every declared wave file exists at HEAD on the delivery branch")
(security-semantics . "untouched: no execute-* check, isolation root, worker-security contract, or gate semantics was modified; the cohort measures the existing integrated topology (fast/queue/lpt, four workers, prepared-env cutover) read-only, and the final-claim mode only evaluates recorded data")
(result . "C3 is closed on 20 unique merged-PR head SHAs with every §8 row explicitly tool-verdicted against fixed targets and guards (six 'target not achieved', one 'pass'), independent verification signed with per-row agree, artifacts checksummed, and the final-claim tooling delivered with green tests; the verdict W6 publishes or withholds is 'target not achieved'"))
