(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.26")
(wave . "W0")
(wave-title . "Characterize the CI required-check graph and fail-closed invariants")
(status . "ready-for-merge")
(implementation-sha . "7219aee72a99e214e6908dd2b9f5a97e6cb0078f")
(dependency-sha . "ba3fe3e01e23369f147bb85b654668646b5335d3")
(branch . "campaign/v1.00.26-w0")
(dependency-state . "v1.00.25 released (merge ba3fe3e0 is origin/main); recorded queue/LPT/security activations held — W0 starts from the pinned topology, not the withheld levers")
(attempt-history . ((attempt-1 . "ended in a provider/network infrastructure stop before completion (no logic failure recorded by the runtime); the wave was preserved (attempt not consumed) and resumed from the committed state on campaign/v1.00.26-w0 — the characterization tests, snapshot, and checksums from the prior attempt were kept and extended, not redone")))
(non-artifact-content-digest . "ddf6f085435b4d96c4b3b18df96ccdf3ce5e002eaa37b22f786224d79dc518b2")
(non-artifact-digest-inputs . "tests/test-ci-runtime-contract.rkt tests/test-w9-ci-workflow-verification.rkt (paths relative to repo root; reproduce with: cd q && for f in tests/test-ci-runtime-contract.rkt tests/test-w9-ci-workflow-verification.rkt; do git show 7219aee72a99e214e6908dd2b9f5a97e6cb0078f:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum)")
(measurement . ((gate-text . "Roadmap v1.00.26 §7 W0: pin the CURRENT required-check graph as executable, fail-closed characterization — job names, needs edges, branch-protection requirements, and the aggregate-check invariants (workflows-aggregate, test-aggregate) — and prove the PR-delivery contract by landing this characterization through the campaign's first protected-main PR.")
                (gate-evaluable . #t)
                (gate-verdict . pass)
                (gate-verdict-label . "characterization green at implementation-sha; PR #9607 merge is the runtime coordinator's owned flow and is not claimed as done inside this record")
                (required-check-pinning . "tests/test-ci-runtime-contract.rkt — 27/27 green: the required-check set equals scripts/required-pr-checks.policy contents (policy file read-only anchor, not modified); lint, security, release-dry-run, test (0), test (1), test (2), test-aggregate, test-platform, workflows (0), workflows (1), and workflows-aggregate are all required; every aggregate job needs exactly its shard jobs (workflows-aggregate <- workflows (0), workflows (1); test-aggregate <- test (0), test (1), test (2)); fast-env is asserted NOT required; the gate function fails closed — a missing required check fails, never passes")
                (snapshot-binding . "artifacts/ci-topology/v1.00.26-w0/graph-snapshot.json holds the live required-check graph fetched via the GitHub API (branch protection + workflow job metadata) plus the same-SHA DAG timing baseline (19 jobs, per-job started/completed timestamps for one PR's run of the current topology — documentation-grade shape baseline for W1–W3, not a cohort); sha256sum -c artifacts/ci-topology/v1.00.26-w0/SHA256SUMS is clean and the test pins the snapshot checksum 6e0eee763b696c772482e3f4c3c060d95d96546c690394b2aa5f85139eb41a25")
                (drift-alarm . "policy-vs-snapshot comparison in the test fails with an explicit message naming both sides (pinned policy list vs snapshot list) so any topology drift after W0 is a named, localized failure, never a silent pass")))
(decision . ((characterization-only . "this wave changes no workflow, no policy file, and no gate code — it pins current reality so later waves can name their own deltas against a checksummed baseline")
             (fail-closed-invariant . "the required-check gate is asserted to treat absence of any required check as failure; tests exercise the missing-check path explicitly")
             (rollback . "pure test+artifact addition; rollback is reverting the two test files and the artifacts directory — main's behavior is untouched by this wave")))
(delivery . ((tdd-tests-first . #t)
             (contract-tests . "characterization tests written first (checkpoint-committed with red->green cycle), extended tests/test-ci-runtime-contract.rkt (27 tests) and tests/test-w9-ci-workflow-verification.rkt; the policy anchor scripts/required-pr-checks.policy is pinned read-only by tests, not edited")
             (focused-suite-command . "racket tests/test-ci-runtime-contract.rkt && racket tests/test-w9-ci-workflow-verification.rkt && sha256sum -c artifacts/ci-topology/v1.00.26-w0/SHA256SUMS")
             (artifacts . ((graph-snapshot . "artifacts/ci-topology/v1.00.26-w0/graph-snapshot.json (live required-check graph + 19-job DAG timing baseline)")
                           (sums . "artifacts/ci-topology/v1.00.26-w0/SHA256SUMS (final; sha256sum -c clean)")
                           (policy-anchor . "scripts/required-pr-checks.policy (unmodified; required set source of truth pinned by tests)")
                           (pr . "campaign/v1.00.26-w0 PR #9607 — first protected-main PR of the campaign, branch cut from origin/main ba3fe3e0")))
             (honesty . ((evidence-provenance . "the snapshot checksum is quoted verbatim from the delivered SHA256SUMS manifest and re-verified with sha256sum -c at implementation-sha 7219aee7; the non-artifact digest reproduces over the two test files with the recorded command")
                         (timing-baseline-honesty . "the DAG timing baseline is one PR's job start/end times at one point in time — recorded as a shape reference for W1–W3 comparisons, explicitly not a statistical cohort")
                         (merge-honesty . "this record does not claim the squash-merge or its SHA; the coordinator owns post-verify merge binding, and the required-checks PR itself is the delivery vehicle being characterized — the same graph this wave pins is the gate this PR must pass")
                         (digest-provenance . "digest ddf6f085435b4d96c4b3b18df96ccdf3ce5e002eaa37b22f786224d79dc518b2 reproduces at implementation-sha 7219aee72a99e214e6908dd2b9f5a97e6cb0078f; the record-only commits that add these rktd files touch no digest input")))))
(note . "W0 pins the CI required-check graph as tests plus a checksummed live snapshot with a same-SHA DAG timing baseline; the fail-closed invariant (missing required check fails the gate) is executable, and the wave lands through PR #9607 — the campaign's first protected-main PR — proving the delivery contract the remaining waves will reuse.")
(review-artifact . "docs/reports/gsd-wave-reviews/v1.00.26-w0.rktd")
(validation-artifact . "docs/reports/gsd-wave-validation/v1.00.26-w0.rktd")
