(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W2")
(wave-title . "Activate queue scheduling for fast lanes only")
(issue . 9590)
(status . "closed-hold-recorded")
(implementation-sha . "3bd71b73")
(dependency-sha . "63b2aa6f")
(branch . "main")
(non-artifact-content-digest . "7cd33e2dc8f4fb1f030566db279eedb15367c4d441dbb91d34c07112f2aaa590")
(non-artifact-digest-inputs . "tests/test-run-tests-profiles.rkt tests/test-scheduler-shadow-workflow.rkt (paths relative to repo root; sha256 each file, sort the hex digests, newline-join, sha256 the joined text; reproduce with: cd q && for f in tests/test-run-tests-profiles.rkt tests/test-scheduler-shadow-workflow.rkt; do git show HEAD:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum)")
(activation . ((dependency-verdict . "hold (W1 decision block: fast-queue . hold; overall-verdict . hold)")
               (wave-outcome . "the wave's own dependency clause applies: a hold keeps this wave closed and records the hold instead of activating")
               (repository-variable-changed . #f)
               (required-lane-lever-present . #f)
               (cli-default-scheduler . "batch (scripts/run-tests/cli.rkt parse-args; unchanged and pinned)")
               (manual-override-preserved . "--scheduler queue and --scheduler batch remain valid for shadow configurations (pinned)")
               (activation-command-not-executed . "gh api repos/coinerd/q/actions/variables/TEST_RUNNER_SCHEDULER -X PUT -f value=queue (NOT executed: the W1 dependency gate returned hold)")
               (rollback-command . "gh api -X DELETE repos/coinerd/q/actions/variables/TEST_RUNNER_SCHEDULER (one command; current state: the variable was never set, so main already IS the rollback state)")))
(delivery . ((tdd-tests-first . #t)
             (schema-tests . "tests/test-run-tests-profiles.rkt tests/test-scheduler-shadow-workflow.rkt")
             (guard-tests . "hold pins: (1) ci.yml carries no TEST_RUNNER_SCHEDULER token and no --scheduler flag; (2) the required fast shard keeps the STRICT_TEST_RUNNER=1 ... --suite fast --jobs 4 command line verbatim; (3) parse-args returns batch with TEST_RUNNER_SCHEDULER unset, set to queue, and set to batch; (4) manual --scheduler queue/batch override still selects the requested scheduler; any silent future activation breaks a pin")
             (focused-suite-command . "racket tests/test-run-tests-profiles.rkt && racket tests/test-scheduler-shadow-workflow.rkt && racket tests/test-runner-scheduler-characterization.rkt && racket tests/test-runner-work-queue.rkt")
             (focused-suite-result . "7/7, 10/10, 7/7, 11/11 - all green")
             (broad-gate . "racket scripts/run-tests.rkt --suite fast (owned by the coordinator verification lane, launched after wave return)")
             (honesty . "no fabricated data: the activation-evidence items the roadmap asks for (variable change SHA, first required-CI run on the new default, its p50/p95) are explicitly NOT produced because the dependency gate returned hold; recording invented numbers would repeat the exact failure the roadmap forbids - a missed gate produces hold, never a revised target")))
(honesty . ((activation-evidence . "the roadmap asks for the variable change SHA, the first required-CI run on the new default, and its p50/p95; none exist and none were fabricated - the W1 dependency verdict is hold for all three lanes, so the activation branch of W2 is not executed and the wave closes by recording the hold")
            (verdict-equivalence . "scheduler choice cannot alter any verdict on this branch because the required lane still runs the batch default end to end; selection, timeout/serial partition, strictness, result ordering, and JSON shape are unchanged by construction, and the scheduler characterization and work-queue contracts stay green byte-for-byte unchanged")
            (digest-provenance . "digest 7cd33e2d... is computed over the two guard-test files at HEAD 3bd71b73 with the exact reproduction command recorded above")))
(note . "W2 records the honest hold: the W1 decision closed cohort C1 with overall-verdict hold (fast-queue, fast-LPT, security-queue all hold; zero shadow attempts), and the W2 dependency clause keeps the wave closed and records the hold instead of activating. ci.yml is untouched; batch remains the live default; the guard tests make any silent activation a red CI run.")
(related-artifact-reports . "none produced: no cohort artifact belongs to W2; W1's C1 artifacts under artifacts/ci-baseline/v1.00.25-c1/ remain authoritative")
(review-artifact . "docs/reports/gsd-wave-reviews/v1.00.25-w2.rktd")
(validation-artifact . "docs/reports/gsd-wave-validation/v1.00.25-w2.rktd")
(campaign . ((name . "v1.00.25")
             (issue . 9590)
             (prior-attempt . "attempt 1 failed delivery verification; this attempt re-derived the dependency verdict from W1's recorded decision block and executed the wave's own hold clause with guard tests instead of repeating the activation attempt")))
