(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W1")
(wave-title . "Close cohort C1 and decide queue/LPT promotions")
(status . "ready-for-merge")
(implementation-sha . "63b2aa6f")
(dependency-sha . "e6d78f36")
(branch . "main")
(non-artifact-content-digest . "265a2dcbd135b3064171ac91bf26390092ba3463dbe29ee27095b04c84ff68b5")
(non-artifact-digest-inputs . "README.md scripts/run-tests/cohort-report.rkt tests/test-ci-cohort-report.rkt (paths relative to repo root; sha256 each file, sort the hex digests, newline-join, sha256 the joined text; reproduce with: cd q && for f in <those three paths>; do git show HEAD:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum)")
(artifact-directory . "artifacts/ci-baseline/v1.00.25-c1")
(artifact-sha256sums-file . "artifacts/ci-baseline/v1.00.25-c1/SHA256SUMS")
(cohort . ((cohort-id . "v1.00.25-c1")
           (cohort-status . "started")
           (eligible-sha-count . 20)
           (configurations . ("fast/batch/fifo" "fast/queue/fifo" "fast/queue/lpt" "security/queue/fifo"))
           (baseline-leg . "fast/batch/fifo: 20 samples, p50 228.5815 s, p95 235.9965 s, 0 failed/cancelled/rerun attempts (real captured evidence)")
           (shadow-legs . "fast/queue/fifo, fast/queue/lpt, security/queue/fifo: 0 recorded attempts across all 20 SHAs")))
(decision . ((decision-version . "w1-decision-v1")
             (overall-verdict . "hold")
             (fast-queue . "hold")
             (fast-LPT . "hold")
             (security-queue . "hold")
             (gate-text . "Initial fast threshold: queue fast execution p50 ≤ 130.0 s and p95 ≤ 145.0 s with no reliability regression versus the paired batch baseline on the same SHAs (roadmap v1.00.25 §6, W1). A missed gate produces hold, never a revised target.")
             (targets-revised . #f)
             (shas-dropped . 0)
             (record . "artifacts/ci-baseline/v1.00.25-c1/decision.md")))
(delivery . ((tdd-tests-first . #t)
             (schema-tests . "tests/test-ci-cohort-report.rkt")
             (manifest-check-command . "racket scripts/run-tests/cohort-report.rkt --manifest artifacts/ci-baseline/v1.00.25-c1/cohort.json --out-json artifacts/ci-baseline/v1.00.25-c1/report.json --out-md artifacts/ci-baseline/v1.00.25-c1/report.md --check")
             (focused-suite-command . "racket scripts/run-tests.rkt --suite fast")
             (honesty . "no fabricated data: shadow legs genuinely have zero attempts in cohort.json; baseline numbers are real captured C0 evidence; the cohort is NOT force-closed because the tooling's own validation refuses closed status with empty legs, and closing on zero shadow samples would fabricate a promotion basis")))
(honesty . ((run-ids . "per the W0 evidence record, all per-SHA attempts in cohort.json carry manifest-recorded placeholder run IDs and no GitHub-hosted shadow runs exist in the delivery environment; W1 re-validated this offline: the three shadow legs still have zero attempts, so no run ID could be replaced with real scheduled-run evidence and the cohort cannot be honestly closed")
            (w1-obligation . "the W0 obligation to re-validate every run ID against the GitHub API was re-checked in this wave; it remains unsatisfiable offline and is carried forward with the open cohort")
            (digest-provenance . "digest 265a2dcb... is computed over the three current non-artifact files (README.md, scripts/run-tests/cohort-report.rkt, tests/test-ci-cohort-report.rkt) at HEAD 63b2aa6f with the exact reproduction command recorded above")))
(note . "W1 records the honest hold decision for all three lanes: zero shadow attempts cannot satisfy the paired gates, the cohort stays started, no target was revised, no SHA was dropped, and decision.md documents numbers, exact gate text, and the reviewer.")
(related-artifact-reports . "docs/reports/gsd-artifact-reports/v1.00.25-c1.md")
(review-artifact . "docs/reports/gsd-wave-reviews/v1.00.25-w1.rktd")
(validation-artifact . "docs/reports/gsd-wave-validation/v1.00.25-w1.rktd")
(campaign . ((name . "v1.00.25")
             (issue . 9589)
             (prior-attempt . "attempt 1 ended in a provider/network infrastructure failure after committing the TDD decision-schema checkpoint cffc1050; attempt 2 resumed from that checkpoint (plus the uncommitted report regeneration) rather than restarting"))))
