(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W6")
(wave-title . "Post-promotion activation cohort C2")
(status . "ready-for-merge")
(implementation-sha . "56d3f689bfd9e2ea0bbdba6a9557021b5541b2e5")
(dependency-sha . "1ccf8dd94480ee91e09bd2fac34a8817be743255")
(branch . "main")
(attempt-history . ((attempt-1 . "ended in an infrastructure stop before completion (no failure reason recorded by the runtime); the wave was preserved (attempt not consumed) and resumed from the committed checkpoints on main")))
(non-artifact-content-digest . "b7f8b341adc8cc3491e32f686b9422b5c4a41a1a7d58c9c72896c06ca0f8c5be")
(non-artifact-digest-inputs . "scripts/run-tests/cohort-report.rkt tests/test-ci-cohort-report.rkt (paths relative to repo root; reproduce with: cd q && for f in scripts/run-tests/cohort-report.rkt tests/test-ci-cohort-report.rkt; do git show 56d3f689bfd9e2ea0bbdba6a9557021b5541b2e5:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum)")
(measurement . ((gate-text . "Roadmap v1.00.25 §6 W6: post-promotion out-of-sample cohort C2 over 20 NEW eligible PR head SHAs on the promoted defaults; fast execution target p50 <= 115 s and p95 <= 135 s; a miss records target unachieved and names the next lever; targets are never revised inside this wave or this milestone.")
                (gate-evaluable . #t)
                (gate-verdict . fail)
                (gate-verdict-label . "target unachieved")
                (threshold-p50-seconds . 115)
                (threshold-p95-seconds . 135)
                (observed-p50-seconds . 253.5)
                (observed-p95-seconds . 276.0)
                (observed-min-max-seconds . (214.0 . 277.0))
                (cohort . ((cohort-id . "v1.00.25-c2")
                           (mode . post-promotion)
                           (paired-shadow . #f)
                           (defaults . "promoted defaults on main (W2-W4 activations: hash-joining shards + fast-lane queue promotion, unified static-fast and corpus-cached-rules plans, planned-light path)")
                           (sample-size . 20)
                           (new-unique-shas . 20)
                           (lane . "required ci.yml lane itself (test shards on the PR head), not a shadow lane")
                           (window . ((start-utc . "2026-09-04")
                                      (end-utc . "2026-09-06")
                                      (first-sha . "5739881dc53a")
                                      (first-run-id . 33867684782)
                                      (last-sha . "879d6321a47b")
                                      (last-run-id . 34001252123)))
                           (reliability . ((total-attempts . 20) (successes . 20) (failures . 0) (cancelled . 0) (reruns . 0) (shas-dropped . 0)))
                           (exclusions . "8 ineligible SHAs observed during selection are recorded in cohort.json exclusions with named reasons (e.g. lane-run-failed with the failing run link); none were dropped silently")
                           (recipe . "per SHA: take the final successful required-lane run of the PR head, keep its successful test-results-fast shards, and record the maximum shard wall_clock_seconds as that SHA's sample; p50/p95 computed with linear interpolation over the 20 samples"))))
(decision . ((target-status . "target unachieved")
             (achieved . #f)
             (observed . "p50 253.5 s (target <= 115 s), p95 276.0 s (target <= 135 s)")
             (next-lever . "shard-count/parallelism tuning of the fast suite: the per-SHA sample is the slowest test-results-fast shard (max 277.0 s), so the named lever is raising FAST_SHARD_COUNT beyond 3 with shard rebalancing to shrink the per-shard critical path, pursued as a separate reviewed decision record")
             (rollback . "no queue rollback is implied by a timing miss alone, per the wave contract; targets are not revised inside this wave or this milestone")))
(delivery . ((tdd-tests-first . #t)
             (contract-tests . "tests/test-ci-cohort-report.rkt (18 tests) extended first with C2-specific assertions: (1) cohort mode vocabulary post-promotion|paired-shadow is pinned in cohort.json and echoed in report.json so every number names which mode produced it; (2) post-promotion cohorts must reference the promoted defaults and must not duplicate a shadow/paired cohort's sample provenance; (3) reliability counters (attempts, successes, failures, cancelled, reruns) must sum per-SHA without dropping SHAs; (4) exclusions require named reasons; (5) --check enforces SHA256SUMS binding over the artifact set")
             (focused-suite-command . "racket tests/test-ci-cohort-report.rkt && racket scripts/run-tests/cohort-report.rkt --manifest artifacts/ci-baseline/v1.00.25-c2/cohort.json --out-json artifacts/ci-baseline/v1.00.25-c2/report.json --out-md artifacts/ci-baseline/v1.00.25-c2/report.md --check")
             (artifacts . ((cohort . "artifacts/ci-baseline/v1.00.25-c2/cohort.json (sha256 edb8dda3ed9be345701955f095210e099aa10554803ffcd8b832f1f3a0b5cee5)")
                           (report-json . "artifacts/ci-baseline/v1.00.25-c2/report.json (sha256 02481e3651b07712ed1b8249e4e6ded83dce363279fde771cbf674ce43b81f74)")
                           (report-md . "artifacts/ci-baseline/v1.00.25-c2/report.md (sha256 5098e37e6ed3b71f4bc5175441079a9461518f0a59fcf15e01e54fcb3d504d50)")
                           (decision . "artifacts/ci-baseline/v1.00.25-c2/decision.md (sha256 572eaea038ce6af80b7ab03d38f0dec484770691f6e1b231b00b8283b70db5eb)")
                           (sums . "artifacts/ci-baseline/v1.00.25-c2/SHA256SUMS (bound by --check)")))
             (honesty . ((evidence-provenance . "all 20 samples come from the required ci.yml lane (not a shadow) on 20 new unique PR head SHAs, first eligible after the W2-W4 activations were stable, with the reliability ledger recording failed/cancelled/rerun attempts and 8 named exclusions; no SHA was dropped and no number is invented")
                         (target-honesty . "the roadmap fast-execution target is missed by a wide margin (p50 253.5 s vs <= 115 s; p95 276.0 s vs <= 135 s); decision.md records target unachieved with the observed numbers and names the next lever instead of revising the target")
                         (digest-provenance . "digest b7f8b341... is computed over the two current non-artifact files at implementation-sha 56d3f689bfd9e2ea0bbdba6a9557021b5541b2e5 with the exact reproduction command recorded above; the record-only commits that add these rktd files touch no digest input")))))
(note . "W6 measures the promoted defaults out of sample: cohort C2 spans 20 new eligible PR head SHAs on the required lane under the activated W2-W4 defaults, ingested with full reliability bookkeeping. The observed fast-execution p50 is 253.5 s and p95 276.0 s, so the roadmap target (p50 <= 115 s, p95 <= 135 s) is honestly recorded as target unachieved; the named next lever (shard-count/parallelism tuning of the fast suite) is reserved for a separate reviewed decision, and no queue rollback is implied by the timing miss alone.")
(review-artifact . "docs/reports/gsd-wave-reviews/v1.00.25-w6.rktd")
(validation-artifact . "docs/reports/gsd-wave-validation/v1.00.25-w6.rktd")
