(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W5")
(wave-title . "Prepared-environment evidence integration and warm observation")
(status . "ready-for-merge")
(implementation-sha . "1ccf8dd94480ee91e09bd2fac34a8817be743255")
(dependency-sha . "0897fa6d7eb9bf57b397a624dee2fdfd91270ed2")
(branch . "main")
(attempt-history . ((attempt-1 . "ended in provider/network infrastructure failure before completion; the wave was preserved (attempt not consumed) and resumed from the committed checkpoints on main")))
(non-artifact-content-digest . "c696dc7971dddf44457ca4fbd2508a1e3e62769fcc926d23df453495fa6f297b")
(non-artifact-digest-inputs . "scripts/ci/prepared-env-report.rkt tests/test-prepared-env-report.rkt .github/workflows/ci.yml (paths relative to repo root; reproduce with: cd q && for f in scripts/ci/prepared-env-report.rkt tests/test-prepared-env-report.rkt .github/workflows/ci.yml; do git show 1ccf8dd94480ee91e09bd2fac34a8817be743255:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum)")
(measurement . ((gate-text . "Roadmap v1.00.25 §6 W5: honest measurement — >= 95% verified restores or named fallback causes, and the v1.00.11 baseline / v1.00.16 setup+execution metrics remeasured on the current tree without copying historical numbers.")
                (gate-evaluable . #t)
                (gate-verdict . pass)
                (verified-restore-rate . 1.0)
                (threshold-percent . 95)
                (counts . ((verified . 15) (rebuilt . 0) (fallback . 0) (unknown . 0)))
                (fallback-causes . none)
                (warm-window . ((start-utc . "2026-09-05T10:42:45Z")
                                (end-utc . "2026-09-06T00:25:41Z")
                                (record-count . 15)
                                (restore-ms-range . (338 . 635))
                                (basis . "backfilled from GitHub Actions run logs of ci.yml test shards on main under the activated defaults (batch scheduler, prepared-environment auto); state and restore durations extracted from Q_PREPARED_ENV_* telemetry lines, wall clocks from the jobs API")))
                (fresh-measurements . ((label . "fresh measurements on the current tree")
                                       (sample-count . 5)
                                       (setup-plus-execution-seconds . (257.59 263.618 249.578 252.587 275.619))
                                       (run-ids . (33961390069 33963502719 33991560045 33998236198 34001252123))
                                       (recipe . "critical path = slowest test-results-fast shard wall_clock_seconds (suite fast, 3 shards x 4 workers, FAST_SHARD_COUNT=3); setup component = that shard's prepared-environment restore_ms; both reported and summed as setup-plus-execution-seconds; missing telemetry stays unknown")
                                       (historical-note . "the v1.00.11 baseline 488.0 s and the v1.00.16 setup+execution 627.0 s are recorded history only; this report contains exclusively fresh measurements on the current tree with the same commands and profiles, never the historical numbers")))))
(decision . ((activation . none)
             (reserved . "this wave decides no activation; the prepared-environment promotion decision is explicitly reserved for a later reviewed decision record")
             (ci-yml-change . "report artifact wiring only: the prepared-env-report job aggregates restore outcomes, runs the manifest --check gate, and uploads prepared-env-report-<run_id>.json as a workflow artifact; no install/relink semantics and no loud-fallback behavior changed")))
(delivery . ((tdd-tests-first . #t)
             (contract-tests . "tests/test-prepared-env-report.rkt (16 tests): (1) schema requires per-restore outcomes limited to verified | rebuilt | fallback; (2) fallback outcomes require named causes; (3) missing restore duration / cache-key / SHA context serializes as unknown, never zero; (4) verified-restore-rate = verified / (verified+rebuilt+fallback) with unknown excluded; (5) >= 95% gate passes at 1.0 and fails below threshold listing every distinct cause; (6) fresh-measurement section rejects copied historical numbers and labels current values fresh; (7) --check enforces SHA256SUMS binding")
             (focused-suite-command . "racket tests/test-prepared-env-report.rkt && racket scripts/ci/prepared-env-report.rkt --manifest artifacts/ci-baseline/v1.00.25-prepared-env/report.json --check")
             (artifacts . ((report . "artifacts/ci-baseline/v1.00.25-prepared-env/report.json (sha256 a5f7129dd2efdf233422d4ca639dfdfc7e64049360e2192ab3b6d850fc040a7c)")
                           (sums . "artifacts/ci-baseline/v1.00.25-prepared-env/SHA256SUMS (bound by --check)")))
             (honesty . ((evidence-provenance . "all 15 restore outcomes are backfilled from real GitHub Actions run logs of ci.yml on main; no number is invented, missing data is unknown, and the zero fallback count reflects genuinely zero fallback observations in the window")
                         (measurement-provenance . "the 5 setup+execution samples are fresh measurements on the current tree at the recorded run ids; the 488.0 s and 627.0 s historical figures are cited only inside the historical-note as history")
                         (digest-provenance . "digest c696dc79... is computed over the three current non-artifact files at implementation-sha 1ccf8dd94480ee91e09bd2fac34a8817be743255 with the exact reproduction command recorded above; the record-only commits that add these rktd files touch no digest input")))))
(note . "W5 makes prepared-environment restore evidence durable and machine-checked: the report schema pins per-restore outcomes, named fallback causes, durations, cache keys, and SHA context; the ci.yml prepared-env-report job aggregates real warm-observation outcomes and gates on the >= 95% verified-restore rate; the warm window on activated defaults shows 15/15 verified restores (rate 1.0, no fallback causes); the historical setup+execution comparison points are remeasured as fresh samples and the activation decision itself is reserved for a later reviewed decision.")
(review-artifact . "docs/reports/gsd-wave-reviews/v1.00.25-w5.rktd")
(validation-artifact . "docs/reports/gsd-wave-validation/v1.00.25-w5.rktd")
