;; Wave evidence: v1.00.28 W7 — Work-mass remeasurement and second-pass decision
;; Record-only companion to gsd-wave-reviews/v1.00.28-w7.rktd
;; and gsd-wave-validation/v1.00.28-w7.rktd.
(
(wave . "v1.00.28-w7")
(ticket . "#9595")
(implementation-sha . "a3c6d8c38bce1211fdee72d5d14aeb0ea50283b7")
(delivery . "branch campaign/v1.00.28-w7 from fresh origin/main; squash-merge PR is owned by the coordinator; this trio is bound to the merge SHA at merge time")
(base . "origin/main 04637d835d33f887a29846a2f3c1855146151985; the branch carries W1-W6 campaign content already checkpointed on this branch's history")
(scope . "artifacts/test-runtime/v1.00.28-w7/{fast-runtime-census.json,comparison.json,removed-since-baseline.json,SHA256SUMS} (new, checksummed), docs/reports/TEST-WORK-MASS-v1.00.28.md (section 17 appended; W0 baseline rows untouched), docs/reports/gsd-wave-{evidence,reviews,validation}/v1.00.28-w7.rktd (this trio), scripts/run-tests/runtime-census.rkt (fd-leak fix in the --refresh-sums writer), scripts/run-tests/sha256.rkt (GNU-coreutils-compatible digest lines), tests/test-runtime-census.rkt (checksum-line regression coverage), tests/test-work-mass-comparison.rkt + scripts/run-tests/work-mass-comparison.rkt (inventory-equality comparison tool)")
(what-was-done
  (identical-method . "post-remediation census re-run with the identical W0 method: same runner, 3 samples, jobs=1 serial timing, same sample floor; compiled/ purged before the run so the census measures the checked-out sources (BUG-0065 lesson); artifacts SHA-256 checksummed")
  (comparison-tool . "scripts/run-tests/work-mass-comparison.rkt regenerates comparison.json from the W0 baseline and the W7 post census; it asserts inventory equality between the two censuses (a file present at W0 but silently absent at W7 is a red error, new files get explicit added rows) and computes all percentages against the stored medians; removed-since-baseline.json records the 2 legitimate removals explicitly")
  (comparison-rows . "fast work mass 980,465 -> 927,785 ms (-52,680 ms, -5.37 %); top 1/10/25/50/100 contribution rows: 39,208 -> 38,582 (-1.60 %), 147,403 -> 146,171 (-0.84 %), 234,054 -> 230,191 (-1.65 %), 313,225 -> 299,820 (-4.28 %), 403,953 -> 382,883 (-5.22 %); bucket counts < 250 ms 37 -> 75, 250 ms-1 s 951 -> 948, 1-2 s 117 -> 89, 2-5 s 45 -> 41, 5-10 s 14 -> 12, > 10 s 7 -> 8; the four runtime counters (process launches, git launches, fixture constructions, requested real sleep) stay 'unknown' on both sides on purpose: instrumenting them mid-series would break W0-vs-W7 comparability, and the W0 static wait-pattern proxy stands (1,609 matches/706 files at W0 vs 1,630/710 at W7, no material movement)")
  (verdict . "intermediate guide applied: -5.37 % is < 10 % so the verdict is INSUFFICIENT; recorded in section 17.2 as an intermediate result that does not replace or relax the fixed final gate")
  (next-bottleneck . "work mass did not improve materially, so the named next lever is another targeted test-design pass on the remaining hotspot mass (section 17.3): top-10 files barely moved at 146,171 ms (15.7 % of post mass), candidates in order tests/test-runner-scheduler-characterization.rkt (38,582 ms, largest single file), the top-10 block, and the eight > 10 s files (128,186 ms); scheduling/sharding/worker-count changes are explicitly NOT the accepted next step because more workers would only hide an unchanged workload")
  (inventory-equality . "2 W0 files absent at W7 are explicit removals (tests/test-browser-audit-w1-v0984.rkt, tests/test-browser-audit-w2-v0983.rkt, old-campaign residue, listed in removed-since-baseline.json); 5 W7-only files (4 new campaign tests plus tests/test-deterministic-clock.rkt as a collection-failure row) carry explicit added rows; no silent drops in either direction"))
(focused-results
  (census-check . "racket scripts/run-tests/runtime-census.rkt --check artifacts/test-runtime/v1.00.28-w7/fast-runtime-census.json -> PASS, recomputed medians match the stored census")
  (comparison-tests . "racket tests/test-work-mass-comparison.rkt -> all contract checks passed, exit 0")
  (census-tests . "racket tests/test-runtime-census.rkt -> green, exit 0 (includes the new checksum-line regression coverage)")
  (checksums . "sha256sum -c artifacts/test-runtime/v1.00.28-w7/SHA256SUMS -> census, comparison, removals manifest OK; W0 baseline dir sums still OK")
  (report-integrity . "grep W7 docs/reports/TEST-WORK-MASS-v1.00.28.md hits section 17; W0 baseline rows (980,465 ms totals, section 4/5/7/11) verified unmodified")
  (verify-lane . "the declared Verify command is coordinator-owned and runs at return; its components were exercised individually on this branch (census --check green, both test suites green, sha256sum -c OK, W7 grep hit, branch campaign/v1.00.28-w7 != main)"))
(security-semantics . "untouched: no execute-* check, isolation root, worker-security contract, gate semantics, or scheduler variable was modified; the wave changes measurement tooling and artifacts only, and the runner fd-leak fix is scoped to the census --refresh-sums writer")
(result . "post census passes --check with the identical method, every W0 comparison row is reported with percentages, the explicit verdict INSUFFICIENT and the named next bottleneck (targeted test-design pass, not scheduling) are recorded in section 17, W0 baseline rows were never rewritten, and census + comparison + removals manifest are checksummed and trio-bound"))
