(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.26")
(wave . "W6")
(wave-title . "End-to-end PR C2 cohort (20 unique merged PRs) on the integrated W1-W5 topology — honest verdict: target unachieved, next lever named")
(status . "ready-for-merge")
(implementation-sha . "aa7ec8e2fbdf99b5af67af314078935f93ac089f")
(branch . "campaign/v1.00.26-w6")
(dependency-state . "branched from origin/main after W1-W5 integrated on the protected mainline (lint split, LPT ordering, security queue, prepared-env warm restore, and the W5 batch-vs-queue hold are all live on main); the wave extended only the pr-elapsed tooling surfaces declared in the plan")
(attempt-history
  (attempt-1 . "TDD red first (pr-elapsed-mode tests written before the mode existed), then the PR-elapsed mode was implemented in scripts/run-tests/cohort-report.rkt, the real 20-PR cohort was ingested through the standard exclusions/reruns tooling, the report was generated and checked (--check PASS), and the honest verdict was recorded — one continuous attempt, no provider stops")
  (attempt-2 . "resume after attempt-1 FAILED delivery verification: the verify lane's `racket scripts/run-tests.rkt --suite fast` segment hit two latent red CI-contract suites (tests/test-run-tests-profiles.rkt, tests/test-scheduler-shadow-workflow.rkt — their comment-filter used #rx\"^\\\\s*#\" where \\\\s is not a valid #rx class, so the filter never matched and comment lines leaked into assertions; the attempt-1 focused chain never executed those two suites). Fix commit a14b60f4 rewrites the ci.yml comment in place (byte-identical var-expansion semantics) and moves the filter to #px so leading-whitespace comments actually match; both suites now green alongside the six other workflow/cohort suites. Non-artifact digest inputs untouched: HEAD digest recomputed = 83310bdb…c3c3f27c2, identical to the implementation-sha binding; SHA256SUMS re-verified 4/4 OK; report --check PASS with byte-identical regeneration; cohort tests 74/9/20 green at HEAD"))
(non-artifact-content-digest . "83310bdb5562538519c7805c8dc2b4ef3e771fafd9228f03c68db50c3c3f27c2")
(non-artifact-digest-inputs . "scripts/run-tests/cohort-report.rkt tests/test-ci-cohort-report.rkt (paths relative to repo root; reproduce with: cd q && for f in scripts/run-tests/cohort-report.rkt tests/test-ci-cohort-report.rkt; do git show aa7ec8e2fbdf99b5af67af314078935f93ac089f:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum; the cohort/report/decision artifacts are deliberately NOT digest inputs — they are checksummed byte-for-byte by artifacts/ci-topology/v1.00.26-c2/SHA256SUMS instead, and the rktd trio is record-only)")
(measurement
  (gate-text . "Roadmap v1.00.26 section 7 W6: end-to-end PR elapsed no more than 588 s p50 / 735 s p95 on 20 unique merged PR head SHAs, measured from first required-check start to last required-check completion (mergeable-PR wall time, queue wait not counted alone); duplicates and re-runs recorded, never dropped; a miss records target-unachieved with observed numbers and the named next lever; targets are never revised inside this milestone.")
  (gate-evaluable . #t)
  (gate-verdict . "target unachieved")
  (cohort-provenance . "20 unique merged PR head SHAs ingested via scripts/run-tests/cohort-report.rkt --pr-elapsed from artifacts/ci-topology/v1.00.26-c2/cohort.json (cohort.json binds every SHA to its per-check start/completion timestamps; expected-size 20, cohort-size 20, unique-SHA assertion green)")
  (observed . "p50 = 935 s (target 588 s; miss by 347 s), p95 = 957.5 s (target 735 s; miss by 222.5 s), linear-interpolated percentiles per the TDD clause")
  (exclusions-reruns-honesty . "exclusion-count 0; failures/cancellations recorded in the manifest counts rather than dropped (total-fail / total-timeout / zero-test-shas fields present); no SHA was silently dropped to make the numbers look better")
  (tooling . "PR-elapsed mode added to scripts/run-tests/cohort-report.rkt this wave (first-check-start to last-required-check-completion, per-SHA and aggregate inventory, queue-telemetry kept separate from the gate so queue wait is visible but not double-counted); tests/test-ci-cohort-report.rkt extended with the failing-first pr-elapsed pins — 74/9/20 all green at implementation-sha"))
(decision
  (outcome . "target unachieved")
  (no-target-revision . "the 588 s p50 / 735 s p95 thresholds stand exactly as fixed in the roadmap package; this cohort records the honest miss with observed numbers and does not move the goalposts")
  (next-lever . "reuse prepared-environment warm caches at PR-head first-check start (mount the W5-verified warm-restore image into the fast/security lanes setup step) to close the pre-first-check and setup share of the wall clock; tracked as the v1.00.27 CI-topology lever, re-measured against this same unchanged pr-elapsed C2 gate")
  (rollback . "no behavior change on main-ancestry code paths: the delivered state only adds the pr-elapsed mode, its tests, and the record-only cohort artifacts; reverting the two digest inputs and the artifacts directory restores the exact pre-wave tree; a checksum mismatch is caught by sha256sum -c failing closed"))
(delivery
  (tdd-tests-first . #t)
  (contract-tests . "tests/test-ci-cohort-report.rkt extended with the failing-first pr-elapsed pins then the gate-honesty contract: exactly-20 unique SHAs required, duplicates/re-runs recorded not dropped, linear-interpolated percentiles, gate text recorded verbatim with verdict target-unachieved; 74 success(es) 0 failure(s) 0 error(s); tooling suites 9/20 green — all green at implementation-sha")
  (focused-suite-command . "racket tests/test-ci-cohort-report.rkt && racket scripts/run-tests/cohort-report.rkt --manifest artifacts/ci-topology/v1.00.26-c2/cohort.json --out-json artifacts/ci-topology/v1.00.26-c2/report.json --out-md artifacts/ci-topology/v1.00.26-c2/report.md --check && sha256sum -c artifacts/ci-topology/v1.00.26-c2/SHA256SUMS && test -f artifacts/ci-topology/v1.00.26-c2/decision.md && current branch is not main — all green at implementation-sha")
  (artifacts
    (cohort . "artifacts/ci-topology/v1.00.26-c2/cohort.json (20 unique SHAs, per-check timing evidence, exclusions/reruns recorded)")
    (report . "artifacts/ci-topology/v1.00.26-c2/report.json + report.md (schema-bound statistics, pr-elapsed-gate p50/p95 with observed-vs-target)")
    (decision . "artifacts/ci-topology/v1.00.26-c2/decision.md (target unachieved, next lever named, no revision)")
    (sha256sums . "artifacts/ci-topology/v1.00.26-c2/SHA256SUMS (binds cohort.json, report.json, report.md, decision.md byte-for-byte; verified OK standalone)"))
  (pr-plan . "single PR from campaign/v1.00.26-w6 to main carrying the pr-elapsed tooling, its tests, and the cohort artifacts + evidence trio; squash-merge and post-merge gate confirmation are coordinator-owned; the cohort wave issue stays open until the C2 cohort closes per the working-directory contract"))
(record-only . "this evidence file adds no code beyond the two digest-input files and touches no artifact bytes")
