(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W3")
(wave-title . "Activate within-shard LPT ordering when C1 proved it")
(issue . 9591)
(status . "closed-hold-recorded")
(implementation-sha . "cbded764")
(dependency-sha . "b631e9c2")
(branch . "main")
(non-artifact-content-digest . "c9b648eb416d50f80696598155ce793ab9f7847adca91465b12f935c12105f61")
(non-artifact-digest-inputs . "tests/test-runner-scheduler-characterization.rkt (path relative to repo root; sha256 of the file at implementation-sha cbded764; reproduce with: cd q && git show cbded764:tests/test-runner-scheduler-characterization.rkt | sha256sum)")
(activation . ((dependency-verdict . "hold (W1 decision block: fast-LPT . hold, no predicted improvement over round-robin; overall-verdict . hold)")
               (wave-outcome . "the wave's own dependency clause applies: a hold keeps this wave closed and records the hold instead of activating within-shard LPT ordering")
               (ordering-lever-changed . #f)
               (ci-ordering-lever-present . #f)
               (cli-default-ordering . "unset (parse-args never reads FAST_SHARD_ORDERING; the runner applies fifo as the default ordering, pinned)")
               (manual-override-preserved . "--ordering fifo and --ordering lpt remain valid; an invalid value exits 2 with a named --ordering diagnostic (pinned)")
               (activation-command-not-executed . "add FAST_SHARD_ORDERING=lpt (or --ordering lpt) to the fast shard steps in .github/workflows/ci.yml (NOT executed: the W1 dependency gate returned hold for fast-LPT)")
               (rollback-command . "delete the FAST_SHARD_ORDERING repository variable / remove --ordering from the fast shard steps (one edit; current state: the lever was never added, so main already IS the rollback state)")))
(delivery . ((tdd-tests-first . #t)
             (schema-tests . "tests/test-runner-scheduler-characterization.rkt")
             (guard-tests . "eight W3 pins added under 'W3 (#9591)': (1) ordering default stays unset while the hold stands - parse-ordering returns #f with FAST_SHARD_ORDERING unset, set to lpt, and set to fifo; the runner default ordering stays fifo; the ordering vocabulary is unchanged; (2) manual --ordering fifo/lpt override still selects the requested ordering; (3) --ordering CLI seam accepted with exit 0, invalid value exits 2 with a named diagnostic; (4) ci.yml carries no --ordering flag and no FAST_SHARD_ORDERING token; (5) missing evidence falls back to fifo with a named reason and snapshot-status missing; (6) stale evidence (mtime older than the declared max age) falls back to fifo with the named max-accepted-age reason; (7) malformed evidence falls back to fifo with the named invalid-shape reason; (8) wrong-inventory evidence falls back to fifo with the named do-not-overlap reason; any silent activation or silent fallback breaks a pin")
             (freshness-contracts . "the freshness threshold is the existing declared default-max-age-seconds constant; stale/malformed/wrong-inventory/missing each produce a DISTINCT named status and fallback reason, and the applied decision records the evidence checksum")
             (determinism-contracts . "two consecutive ordering decisions serialize identically (ordering-record->jsexpr), two consecutive orderings are byte-identical, and two consecutive shard-plan generations are structurally and byte identical (canonical-plan-bytes: recursive key-sorted canonical rendering, independent of hash iteration order)")
             (lpt-when-usable . "with fresh, well-formed, inventory-compatible evidence, lpt mode orders longest-duration first and breaks duration ties deterministically on path (byte length, then lexicographic) - proven against tests/fixtures/shard-plan-durations.json-shaped snapshots")
             (focused-suite-command . "racket tests/test-runner-scheduler-characterization.rkt && racket tests/test-run-tests-profiles.rkt && racket tests/test-runner-work-queue.rkt")
             (focused-suite-result . "17/17, 7/7, 11/11 - all green (raco fmt applied; green after formatting)")
             (broad-gate . "racket scripts/run-tests.rkt --suite fast (owned by the coordinator verification lane, launched after wave return)")
             (plan-determinism-evidence . "two consecutive racket scripts/run-tests.rkt <fast characterization + profiles> --shard-plan report --durations tests/fixtures/shard-plan-durations.json --jobs 4 --suite fast runs produced byte-identical output, sha256 08e418bbe13082e9c776b0835ae3f67cb92eaa4aba8765631af496499f375279 on both runs")
             (honesty . "no fabricated data: the roadmap's activation-evidence items (ordering variable SHA, before/after shard-plan digests from an activated run, first required runs with the new ordering) are explicitly NOT produced because the W1 dependency gate returned hold for fast-LPT; a missed gate produces hold, never a revised target. The before/after digest slot is filled honestly with the consecutive-generation digest above, which proves the determinism contract the wave asks for without claiming activation.")))
(honesty . ((activation-evidence . "the roadmap asks for the ordering variable SHA, before/after shard-plan digests, and the first required runs with the new ordering; none of these exist because there is no activation - ci.yml is untouched, FAST_SHARD_ORDERING was never set, and no required run used lpt ordering; recording invented numbers would repeat the exact failure the roadmap forbids")
            (verdict-equivalence . "with no ordering lever reachable from the required lane, fast shards run fifo end to end: selection, retry, timeout/serial partition, strictness, and result ordering are unchanged by construction, and the scheduler characterization, profiles, and work-queue contracts stay green")
            (paired-cohort . "W1's C1 cohort was paired out-of-sample (fast/queue/lpt vs fast/queue/fifo) and closed with fast-LPT . hold (no predicted improvement over round-robin); per the wave goal, no extra pre-activation cohort is needed - the paired evidence is already the input, and its verdict is hold")
            (digest-provenance . "digest c9b648eb... is computed over the extended guard-test file at implementation-sha cbded764 with the exact reproduction command recorded above")))
(note . "W3 records the honest hold: the W1 decision closed cohort C1 with overall-verdict hold and fast-LPT . hold (no predicted improvement over round-robin), and the W3 dependency clause keeps the wave closed and records the hold instead of flipping the ordering lever for the required fast shards. ci.yml is untouched; the runner default ordering stays fifo; the guard tests make any silent activation - and any silent fifo fallback - a red run. The ordering machinery itself stays fully contract-tested (named fallbacks, freshness threshold, deterministic tie-breaking, byte-identical plan generations), so a future promoting wave can flip the lever with this suite as its safety net.")
(related-artifact-reports . "tests/fixtures/shard-plan-durations.json is the committed duration source used for the shard-plan determinism digests; W1's C1 artifacts remain authoritative for the hold verdict")
(review-artifact . "docs/reports/gsd-wave-reviews/v1.00.25-w3.rktd")
(validation-artifact . "docs/reports/gsd-wave-validation/v1.00.25-w3.rktd")
(campaign . ((name . "v1.00.25")
             (issue . 9591)
             (prior-attempt . "attempt 1 failed delivery verification; this attempt re-derived the dependency verdict from W1's recorded decision block (fast-LPT . hold), executed the wave's own hold clause with eight guard pins plus real consecutive-generation plan determinism digests instead of an activation attempt, and extended the characterization suite rather than the profiles suite (profiles already pinned the batch/queue state from W2 and needed no ordering change)"))))
