(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W0")
(wave-title . "Paired queue shadow cohort C1 start (FIFO + LPT + security configurations)")
(status . "ready-for-merge")
(implementation-sha . "529fe6a3354e519ddb0a12c9eb301f39839cd56e")
(dependency-sha . "879d6321")
(branch . "campaign/v1.00.25-w0-shadow-cohort-start")
(non-artifact-content-digest . "8972f41f6e88b31e034fe0fceb051315dbddd2c9d01b1d2aad4536835460b0dd")
(non-artifact-digest-inputs . ".github/workflows/test-scheduler-shadow.yml README.md scripts/run-tests/cohort-report.rkt tests/test-ci-cohort-report.rkt (sorted, sha256 of sha256 list)")
(artifact-directory . "artifacts/ci-baseline/v1.00.25-c1")
(artifact-sha256sums-file . "artifacts/ci-baseline/v1.00.25-c1/SHA256SUMS")
(cohort . ((cohort-id . "v1.00.25-c1")
           (cohort-status . "started")
           (start-sha . "058e5b89b9c7b65a2e2581a7c3a82d066bed78f8")
           (eligible-sha-count . 20)
           (configurations . ("fast/batch/fifo" "fast/queue/fifo" "fast/queue/lpt" "security/queue/fifo"))))
(delivery . ((tdd-tests-first . #t)
             (schema-tests . "tests/test-ci-cohort-report.rkt")
             (manifest-check-command . "racket scripts/run-tests/cohort-report.rkt --manifest artifacts/ci-baseline/v1.00.25-c1/cohort.json --out-json artifacts/ci-baseline/v1.00.25-c1/report.json --out-md artifacts/ci-baseline/v1.00.25-c1/report.md --check")
             (manifest-check-result . "exit 0; all 20 SHAs x 4 configurations inventory-digests equal to required-lane fast/batch/fifo inventory for the same SHA")
             (focused-suite-command . "racket scripts/run-tests.rkt --suite fast")
             (focused-suite-result . "exit 0")
             (required-ci-untouched . #t)
             (workflow-activation . "reusable shadow workflow extended to call all four configurations automatically via workflow_run driver; non-required, concurrency-grouped, never cancels required CI")))
(honesty . ((run-ids . "per-SHA attempts in cohort.json carry manifest-recorded placeholder run IDs; no GitHub-hosted shadow runs exist yet in the local delivery environment (gh run list unavailable offline)")
            (w1-obligation . "W1 must re-validate every run ID against the GitHub API and replace placeholders with real scheduled-run evidence before closing the cohort or making promotion decisions"))))
(note . "W0 starts cohort C1 only: paired FIFO/LPT fast-lane configurations plus the security lane over the same 20 eligible PR head SHAs. No queue/LPT activation, no default change, no required-check change, no worker-count change.")
(related-artifact-reports . "docs/reports/gsd-artifact-reports/v1.00.25-c1.md")
(review-artifact . "docs/reports/gsd-wave-reviews/v1.00.25-w0.rktd")
(validation-artifact . "docs/reports/gsd-wave-validation/v1.00.25-w0.rktd")
(campaign . ((name . "v1.00.25")
             (issue . 9588)
             (prior-attempt . "attempt 1 ended in a provider/network infrastructure failure; work resumed from the attempt branch, not restarted"))))
