(kind . "wave-evidence")
(schema-version . 2)
(campaign . "v1.00.25")
(wave . "W0")
(wave-title . "Paired queue shadow cohort C1 start (FIFO + LPT + security configurations)")
(status . "ready-for-merge")
(implementation-sha . "e6d78f36")
(dependency-sha . "879d6321")
(branch . "main")
(non-artifact-content-digest . "ee685d383614e802b1a9462111f0caa78d4609e01d9a3df778d938d08c12d6f5")
(non-artifact-digest-inputs . ".github/workflows/test-scheduler-cohort-c1.yml .github/workflows/test-scheduler-shadow.yml README.md scripts/run-tests/cohort-report.rkt tests/test-ci-cohort-report.rkt (paths relative to repo root; sha256 each file, sort the hex digests, newline-join, sha256 the joined text; reproduce with: cd q && for f in <those five paths>; do git show HEAD:$f | sha256sum; done | awk '{print $1}' | sort | sha256sum)")
(artifact-directory . "artifacts/ci-baseline/v1.00.25-c1")
(artifact-sha256sums-file . "artifacts/ci-baseline/v1.00.25-c1/SHA256SUMS")
(cohort . ((cohort-id . "v1.00.25-c1")
           (cohort-status . "started")
           (start-sha . "058e5b89b9c7b65a2e2581a7c3a82d066bed78f8")
           (eligible-sha-count . 20)
           (configurations . ("fast/batch/fifo" "fast/queue/fifo" "fast/queue/lpt" "security/queue/fifo"))))
(delivery . ((tdd-tests-first . #t)
             (schema-tests . "tests/test-ci-cohort-report.rkt")
             (manifest-check-command . "racket scripts/run-tests/cohort-report.rkt --manifest artifacts/ci-baseline/v1.00.25-c1/cohort.json --out-json artifacts/ci-baseline/v1.00.25-c1/report.json --out-md artifacts/ci-baseline/v1.00.25-c1/report.md --check")
             (manifest-check-result . "exit 0; all 20 SHAs x 4 configurations inventory-digests equal to required-lane fast/batch/fifo inventory for the same SHA")
             (focused-suite-command . "racket scripts/run-tests.rkt --suite fast")
             (focused-suite-result . "attempt 2 focused: tests/test-scheduler-shadow-workflow.rkt 8/8 green (the attempt 1 failing file), tests/test-ci-cohort-report.rkt 61/61 green, manifest --check exit 0, artifact SHA256SUMS verified from the artifact directory; full fast-suite re-run is owned by the coordinator verification lane")
             (required-ci-untouched . #t)
             (workflow-activation . "cohort C1 driver workflow .github/workflows/test-scheduler-cohort-c1.yml triggers automatically on CI workflow_run completion on main and calls the reusable shadow workflow (triggers exactly workflow_call + workflow_dispatch) once per configuration row x eligible SHA with coverage dedup via exact job-name marker match on gh run list; non-required, concurrency-grouped per SHA, never cancels required CI")
             (repair . "attempt 1 failed delivery verification: tests/test-scheduler-shadow-workflow.rkt requires exactly two trigger keys (workflow_call workflow_dispatch) but the attempt 1 implementation inlined a workflow_run driver as a third trigger in test-scheduler-shadow.yml (and that inlined self-call would be rejected by GitHub as a recursive reusable-workflow call); attempt 2 split the driver into its own workflow file, restoring the governance contract and keeping automatic paired execution")))
(honesty . ((run-ids . "per-SHA attempts in cohort.json carry manifest-recorded placeholder run IDs; no GitHub-hosted shadow runs exist yet in the local delivery environment (gh run list unavailable offline)")
            (w1-obligation . "W1 must re-validate every run ID against the GitHub API and replace placeholders with real scheduled-run evidence before closing the cohort or making promotion decisions")
            (digest-provenance . "attempt 1 evidence recorded digest 8972f41f... over a pre-repair file set; the attempt 1 formula did not reproduce from that file set, so attempt 2 rebinds the digest over the five current non-artifact files with the exact reproduction command recorded above")))
(note . "W0 starts cohort C1 only: paired FIFO/LPT fast-lane configurations plus the security lane over the same 20 eligible PR head SHAs. No queue/LPT activation, no default change, no required-check change, no worker-count change.")
(related-artifact-reports . "docs/reports/gsd-artifact-reports/v1.00.25-c1.md")
(review-artifact . "docs/reports/gsd-wave-reviews/v1.00.25-w0.rktd")
(validation-artifact . "docs/reports/gsd-wave-validation/v1.00.25-w0.rktd")
(campaign . ((name . "v1.00.25")
             (issue . 9588)
             (prior-attempt . "attempt 1 ended in a provider/network infrastructure failure, then its delivery verification failed on the shadow workflow trigger-governance test; attempt 2 resumed from the attempt branch checkpoints (529fe6a3, 958eab2f) and repaired via e6d78f36 rather than restarting")))
