;; Wave evidence: v1.00.28 W2 — Fixture amplification reduction with pristine-copy experiment
;; Record-only companion to gsd-wave-reviews/v1.00.28-w2.rktd
;; and gsd-wave-validation/v1.00.28-w2.rktd.
(
(wave . "v1.00.28-w2")
(ticket . "#9590")
(implementation-sha . "8c003200dc39fe275a2a0dd93862cb03c8f4e958")
(delivery . "branch campaign/v1.00.28-w2 from fresh origin/main 04637d83 (v1.00.27 tip); the squash-merge PR and evidence binding to the merge SHA are coordinator-owned at merge time")
(scope . "tests/helpers/pristine-git-fixture.rkt and tests/test-pristine-git-fixture.rkt (new); tests/test-gsd-delivery-verifier.rkt, tests/test-gsd-campaign-repository.rkt, tests/test-gsd-wave-worktree.rkt (consume the pristine fixture behind the strategy-agnostic constructor contract); artifacts/test-runtime/v1.00.28-w2/{fixture-census,git-fixture-experiment,stress-evidence}.json + SHA256SUMS; docs/reports/TEST-FIXTURE-AMPLIFICATION-v1.00.28.md; docs/reports/gsd-wave-{evidence,reviews,validation}/v1.00.28-w2.rktd (this trio)")
(what-was-done
  (safety-suite-first . "tests/test-pristine-git-fixture.rkt written red before the builder existed: byte-level isolation under concurrent create/destroy, no hardlinks, no objects/info/alternates entry, no shared object store, no shared mutable refs, no inherited hooks, repository-local user.name/user.email per instance, per-test instances start from the immutable pristine baseline and a scenario delta never mutates the baseline, plus the legacy-contract test that keeps the one-edit rollback honest; green at 7/7 (checkpoints 4ecee83a, 8df65621)")
  (pristine-baseline . "tests/helpers/pristine-git-fixture.rkt builds the immutable pristine baseline once per process (hook-free seeding, runtime-path dispatch, top-level env neutralization) and hands out cheap isolated per-test copies; the shared constructor make-private-git-fixture! takes a strategy parameter so the consuming suites do not know which construction path they use")
  (constructor-switch . "test-gsd-delivery-verifier, test-gsd-campaign-repository, and test-gsd-wave-worktree consume the constructor behind the same contract (checkpoint a55af211); no behavioral change: 25/25, 33/33, 10/10 at the branch head, identical to pre-wave counts")
  (census . "the W0 env-gated construction counter was wired into the git and session fixture constructors (checkpoint 15e0b14f); per-family counts in fixture-census.json show the amplification concentrates in test-gsd-delivery-verifier (21 repositories per run, the same dv-base shape rebuilt 19 times); branch/commit counts per construction are recorded as null with the reason (not counter-instrumented)")
  (experiment . "git-fixture-experiment.json: interleaved A/B through the shared constructor, sample = construct + git rev-parse --verify HEAD first-use assert + cleanup, 2 uncounted warmups then 14 successful samples per arm, identical method both arms; legacy git clone --no-local median 38.77 ms construct / 43.51 ms total vs pristine-copy 143.95 ms / 148.52 ms — the pristine copy is ~3.7x slower to construct on this machine, refuting the hypothesis")
  (stress . "stress-evidence.json: 12 concurrent instances per strategy all pass, pristine baseline byte-integrity snapshot identical before and after (16 files / 1574 bytes)")
  (hold . "activation gate applied truthfully: isolation and stress pass, no behavior changes in the consuming suites, rollback is one edit and contract-tested — but the median-improvement criterion fails in the wrong direction (3.7x slower), so the pristine-copy strategy is NOT activated as the construction default; the legacy clone path remains the default and the truthful hold is recorded in TEST-FIXTURE-AMPLIFICATION-v1.00.28.md and the evidence JSONs (checkpoint 75f26c89)")
  (verify-compat . "this attempt made the branch verify-command-compatible: SHA256SUMS rewritten with q-root-relative paths so the declared 'sha256sum -c artifacts/test-runtime/v1.00.28-w2/SHA256SUMS' from the q root verifies (3/3 OK), racket scripts/metrics.rkt --sync-all re-synced README after the test additions (lint: all 5 static metrics match), and the attempt's tmp/ scratch probes that broke the pre-commit format lint were deleted per the BUG-0026 scratch-file contract (format lint now 0 errors over 2386 files); checkpoint 8c003200"))
(focused-results
  (pristine-safety . "racket tests/test-pristine-git-fixture.rkt → 7/7, exit 0")
  (delivery-verifier . "racket tests/test-gsd-delivery-verifier.rkt → 25/25, exit 0")
  (campaign-repository . "racket tests/test-gsd-campaign-repository.rkt → 33/33, exit 0")
  (wave-worktree . "racket tests/test-gsd-wave-worktree.rkt → 10/10, exit 0")
  (checksums . "sha256sum -c artifacts/test-runtime/v1.00.28-w2/SHA256SUMS (from q root) → fixture-census.json OK, git-fixture-experiment.json OK, stress-evidence.json OK")
  (metrics . "racket scripts/metrics.rkt --sync-all → synced; --lint → all 5 static metrics match README.md")
  (format-lint . "racket scripts/lint-format.rkt → 0 errors, 0 warnings, 2386 files, PASSED"))
(security-semantics . "untouched: no execute-* check, isolation root, worker-security contract, gate semantics, or scheduler variable was modified; the wave changes only how test Git fixtures are constructed (and does not even switch the default), all inside test/ plus artifact and report files")
(result . "fixture amplification is measured and reported, the sanctioned Git-fixture experiment has checksummed 14-sample-per-arm interleaved evidence, the activation gate was applied honestly and the pristine-copy strategy is NOT activated (recorded hold, legacy clone default retained), rollback stays one constructor-parameter edit and is contract-tested, and every declared wave file exists at the implementation head 8c003200; the merge/PR flow is coordinator-owned"))
