;; GSD Wave Evidence — v1.00.29 W9: dup-04 removal (proof-bundle reuse wiring)
;; Branch: campaign/v1.00.29-w9 (worktree /tmp/q-w9); base 9112e1ec (fresh main)
;; Date: 2026-09-12

(evidence
 (wave v1.00.29-w9)
 (implementation-sha bcceaaf7)
 (branch campaign/v1.00.29-w9)
 (base 9112e1ec)
 (ticket "campaign v1.00.29 W9 (milestone #894): DUPLICATE-PROOF-REDUCTION — remove the dup-04 platform duplicate execution via q.proof-bundle/1 reuse")
 (commits
  ((sha b33b8100)
   (scope "scripts/proof-bundle/consume.rkt CLI adapter: write (canonical q.proof-bundle/1 assembly from claim/context JSON + scalar producer args) and consume (validate-proof-bundle-file + q.reuse-decision/1 record; exit 0 reusable / 3 not-reusable / 4 invalid — never 0 on anything else)"))
  ((sha cbaa7917)
   (scope "ci.yml test-platform: green-suite-only 'Produce proof bundle' step (real digest recipes over named inputs, recorded in the claim's digest_sources annotations) + proof-bundle-platform upload (upload-artifact@v7, retention 14d); consume.rkt producer-section fix caught by the fail-closed completeness gate during an end-to-end dry run of the exact step body; README metrics resync"))
  ((sha bbbf0731)
   (scope "consume.rkt hardening from dry runs: json-safe serialization (write-json rejects symbol values) and request normalization to the validator's exact in-memory vocabulary (expected-artifacts keys are DATA strings; subject-binding/claim-gate-class enums translated string->symbol)"))
  ((sha 73213bc0)
   (scope "full-regression.yml test-platform (macos) lane: 'Resolve + consume proof bundle' step (gh run list --workflow ci.yml --commit GITHUB_SHA, guarded; gh run download proof-bundle-platform, guarded; jq-built ~22-key consumer request from the producer bundle; consume.rkt consume), suite step gated on bundle_ok != 'true', decision artifact always uploaded (§11.3), producer evidence adoption keeps the summarize lane contract intact; no exit masking anywhere"))
  ((sha 60275387)
   (scope "tests/test-proof-bundle-consume.rkt: §9 threat model at the consumer boundary (a)-(g) + adapter contracts + W9 workflow-contract pins; consume.rkt usage guards now abort with exit 2; README resync"))
  ((sha 08eea480)
   (scope "artifacts/proof-graph/v1.00.29-w9/removals.json (content-addressed dup-04 entry) + SHA256SUMS; README resync"))
  ((sha 1146da6d)
   (scope "docs/reports/DUPLICATE-PROOF-REDUCTION-v1.00.29.md: §4.7 before/after ratio 31.6% -> 4.51% (same-window, W0 inputs only), §11.2 mass accounting (zero distinct removals), §11.3 fallback ledger, §11.6 rollback drill with actual commands + output"))
  ((sha bcceaaf7)
   (scope "tier-ownership matrix resync for the new test family (1387 families; --check PASS) — W3/W5 precedent"))
  ((sha "this-commit")
   (scope "wave evidence trio")))
 (deliverables
  ((file scripts/proof-bundle/consume.rkt)
   (detail "CLI adapter over the untouched W5 writer/validator: write assembles + finalizes the bundle (producer completeness gate fail-closed) and prints the content-addressed bundle_id; consume runs validate-proof-bundle-file and writes the §11.3 record; deterministic for byte-identical inputs (created_at must be supplied by the caller, never invented); deps racket/base + json/contract/date/file/string only; no network/threads/sleeps"))
  ((file .github/workflows/ci.yml)
   (detail "test-platform ONLY: after the (still unconditional) suite step, produce the bundle from artifacts-run/claim.json (claim claim:platform-cross-version:macos-fast-suite, run context from GITHUB_* env, tree via git rev-parse HEAD^{tree}, workflow revision = the same commit's ci.yml blob SHA) and upload proof-bundle-platform (bundle + claim) with retention-days 14; W4 purge wiring and W6 identity steps byte-identical; the producer step runs only on a green suite so a failed run can never yield a reusable bundle"))
  ((file .github/workflows/full-regression.yml)
   (detail "test-platform (macos-14) lane: preceding Resolve + consume proof bundle step builds the full consumer request with jq from the downloaded bundle (expected commit/tree = GITHUB_SHA/its tree, workflow revision = same commit's ci.yml blob SHA, environment/policy/selection/artifact expectations copied from the producer), runs consume.rkt consume; bundle_ok=true (exit 0) is the ONLY skip condition and adopts the producer's test-results-platform as lane evidence so the summarize stage keeps its evidence contract; ANY other outcome records a named fallback cause and runs the suite; release.yml untouched"))
  ((file tests/test-proof-bundle-consume.rkt)
   (detail "21 checks: write determinism/completeness/usage; §9 (a) tampered bundle -> 4, (b) stale commit -> 3, (c) expired retention -> 3, (d) wrong claim -> 3, (e) unauthorized consumer + release mode -> 3, (f) valid -> 0 with complete q.reuse-decision/1 record (consumer-id, decision, bundle_id, reason, zero-tests-run, normal-proof-executed, decided-at/request-current-time), (g) missing bundle -> 4; never-exit-0-on-unexpected; request-vocabulary normalization; workflow pins (suite unconditional in ci.yml, bundle_ok fallback retained in full-regression.yml, same-commit resolution, no exit masking, release.yml clean, W0 dup-04 accounting input)"))
  ((file artifacts/proof-graph/v1.00.29-w9/removals.json)
   (detail "one removal entry (dup-04, exact_duplicate) with all required fields incl. content-addressed sha256 over the canonical JSON with the sha256 field empty (bundle-writer FIPS 180-4); SHA256SUMS consistent (sha256sum -c OK)"))
  ((file docs/reports/DUPLICATE-PROOF-REDUCTION-v1.00.29.md)
   (detail "§4.7 before/after duplicate-proof ratio on W0's recorded numbers only (6065s/19188s = 31.6% before; 866s/19188s = 4.51% after; delta 27.1pp; 85.7% of observed avoidable mass removed; re-verification ratio 2 -> 1 for the platform claim), §11.2 mass accounting table (zero distinct_environment/distinct_semantic/observational removals), §11.3 fallback ledger, §11.6 rollback drill with actual commands and output"))
  ((file artifacts/tier-ownership/v1.00.28-w0/ownership-matrix.json)
   (detail "resynced for the new test family (1387 families, 7 areas, 0 gaps; --check PASS); recorded as a required deviation per the W3/W5 precedent")))
 (wiring-decision
  ((case "consumer's minimum-retention-until is set to current-time (not now+14d): the producer retains 14d from bundle creation, so a later-dated consumer minimum would always trip retention-shortfall and reuse could never activate; the equality still enforces that expired evidence is rejected via retention-expired")
   (why "the consumer's honest requirement is 'the evidence must still be retained now'; step 13 semantics preserved, no validator change")
   (case2 "the consumer copies environment/policy/selection/artifact expectations from the downloaded producer bundle: the pre-decided design (W0 dup-04 'same selection/env/strictness') plus fail-closed equality either way; a future platform-accurate split needs a positive §4.4 compatibility proof and is out of scope")
   (why2 "the validator pins the equality regardless of where the expectation text comes from; the request is the consumer's own file, built per run")))
 (residual
  "tests/test-interfaces-tui.rkt fails in this sandbox (selection-text P1 check at tests/test-interfaces-tui.rkt:906; TTY-sensitive) in fast shard 5. Proven pre-existing on the untouched base: the identical failure reproduces in a throwaway worktree at base 9112e1ec with none of this wave's changes (racket tests/test-interfaces-tui.rkt -> same check, same line). Same family is already on the W3/W5 record. Recorded, not coerced; this wave's diff cannot affect it.")
 (issues-referenced ("campaign v1.00.29 W9")))
